/**
 * Export an SBA Year Plan as a Word checklist: overall progress, then each
 * term/skill group as a table of its required ECZ tasks with the marks and the
 * current status (Planned / Administered / Marked). The printable record an
 * HOD signs off when checking SBA coverage.
 */

import { saveBlob } from '../../utils/saveBlob.js'
import { sanitizeXmlText } from '../../utils/xmlText.js'
import {
  AlignmentType,
  BorderStyle,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from 'docx'
import { attributionSection } from '../../utils/docxAttribution.js'
import { SBA_TASK_STATUSES } from '../../utils/sbaPlanner.js'

const STATUS_LABEL = Object.fromEntries(SBA_TASK_STATUSES.map((s) => [s.value, s.label]))
const STATUS_FILL = { not_started: 'FFFFFF', planned: 'FEF3C7', administered: 'E0F2FE', marked: 'DCFCE7' }

const BORDER = {
  top:    { style: BorderStyle.SINGLE, size: 4, color: '999999' },
  bottom: { style: BorderStyle.SINGLE, size: 4, color: '999999' },
  left:   { style: BorderStyle.SINGLE, size: 4, color: '999999' },
  right:  { style: BorderStyle.SINGLE, size: 4, color: '999999' },
}

function text(str, opts = {}) { return new TextRun({ text: sanitizeXmlText(str), ...opts }) }
function para(runs, opts = {}) { return new Paragraph({ children: Array.isArray(runs) ? runs : [runs], ...opts }) }
function cell(content, { shading, width } = {}) {
  return new TableCell({
    children: Array.isArray(content) ? content : [content],
    borders: BORDER,
    width: width ? { size: width, type: WidthType.PERCENTAGE } : undefined,
    ...(shading ? { shading: { fill: shading } } : {}),
  })
}

function groupTable(group, statuses) {
  const head = new TableRow({
    tableHeader: true,
    children: [
      cell(para(text('Task', { bold: true, size: 16 })), { width: 64, shading: 'E2E8F0' }),
      cell(para(text('Marks', { bold: true, size: 16 })), { width: 14, shading: 'E2E8F0' }),
      cell(para(text('Status', { bold: true, size: 16 })), { width: 22, shading: 'E2E8F0' }),
    ],
  })
  const rows = group.columns.map((c) => {
    const st = statuses[c.key] || 'not_started'
    return new TableRow({
      children: [
        cell(para(text(c.label, { size: 16 })), { width: 64 }),
        cell(para(text(`/${c.max}`, { size: 16 })), { width: 14 }),
        cell(para(text(STATUS_LABEL[st] || 'Not started', { size: 16 })), { width: 22, shading: STATUS_FILL[st] }),
      ],
    })
  })
  return new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: [head, ...rows] })
}

export function buildSbaPlannerDocument(plan, header = {}, opts = {}) {
  const { groups = [], summary = {}, total = 0 } = plan
  const statuses = plan.statuses || {}
  const children = []

  children.push(new Paragraph({
    children: [text(`${header.subjectLabel || ''} — ${header.gradeLabel || ''} SBA Year Plan`, { bold: true, size: 28 })],
    heading: HeadingLevel.HEADING_1,
    alignment: AlignmentType.CENTER,
    spacing: { after: 80 },
  }))
  const sub = [header.school, header.className, header.year].filter(Boolean).join(' · ')
  if (sub) children.push(para(text(sub, { size: 18, color: '555555' }), { alignment: AlignmentType.CENTER, spacing: { after: 120 } }))

  children.push(para([
    text('Progress: ', { bold: true, size: 18 }),
    text(`${summary.done || 0} of ${summary.total || 0} tasks marked (${summary.percentComplete || 0}%). `, { size: 18 }),
    text(`Maximum ${total} marks for this grade → converted to 10%.`, { italics: true, size: 16, color: '6b7280' }),
  ], { spacing: { after: 160 } }))

  groups.forEach((g) => {
    children.push(new Paragraph({
      children: [
        text(g.group, { bold: true, size: 22, color: '0e2a32' }),
        text(`   ${g.summary?.done || 0}/${g.summary?.total || 0} marked`, { size: 16, color: '6b7280' }),
      ],
      spacing: { before: 180, after: 60 },
      border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: 'cccccc' } },
    }))
    children.push(groupTable(g, statuses))
  })

  return new Document({
    creator: 'zedexams.com',
    title: 'SBA Year Plan',
    description: 'Generated by ZedExams Teacher Tools',
    styles: { default: { document: { run: { font: 'Calibri', size: 18 } } } },
    sections: [{ ...attributionSection(opts), children }],
  })
}

export async function downloadSbaPlannerDocx(plan, header = {}, filename = 'sba-year-plan.docx', opts = {}) {
  const doc = buildSbaPlannerDocument(plan, header, opts)
  const blob = await Packer.toBlob(doc)
  await saveBlob(blob, filename)
}
