/**
 * Export an SBA Mark Tracker as a landscape Word schedule: one row per pupil,
 * one column per official ECZ task (grouped by term/skill), the raw total and
 * the converted 10%-per-grade SBA mark. This is the record schools must retain
 * for verification and the figure entered on the ECZ OMES portal.
 */

import { saveBlob } from '../../utils/saveBlob.js'
import { sanitizeXmlText } from '../../utils/xmlText.js'
import {
  AlignmentType,
  BorderStyle,
  Document,
  HeadingLevel,
  PageOrientation,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from 'docx'
import { attributionSection } from '../../utils/docxAttribution.js'
import { convertSbaMark } from '../../config/sba.js'

const BORDER = {
  top:    { style: BorderStyle.SINGLE, size: 4, color: '999999' },
  bottom: { style: BorderStyle.SINGLE, size: 4, color: '999999' },
  left:   { style: BorderStyle.SINGLE, size: 4, color: '999999' },
  right:  { style: BorderStyle.SINGLE, size: 4, color: '999999' },
}

function text(str, opts = {}) {
  return new TextRun({ text: sanitizeXmlText(str), ...opts })
}
function para(runs, opts = {}) {
  return new Paragraph({ children: Array.isArray(runs) ? runs : [runs], ...opts })
}
function cell(content, { shading, width } = {}) {
  return new TableCell({
    children: Array.isArray(content) ? content : [content],
    borders: BORDER,
    width: width ? { size: width, type: WidthType.PERCENTAGE } : undefined,
    ...(shading ? { shading: { fill: shading } } : {}),
  })
}

export function buildSbaTrackerDocument(artifact, opts = {}) {
  const { header = {}, columns = [], pupils = [], total = 0 } = artifact
  const children = []

  children.push(new Paragraph({
    children: [text(`${header.subjectLabel || ''} — ${header.gradeLabel || ''} SBA Mark Schedule`, { bold: true, size: 28 })],
    heading: HeadingLevel.HEADING_1,
    alignment: AlignmentType.CENTER,
    spacing: { after: 80 },
  }))
  const sub = [header.school, header.className, header.year].filter(Boolean).join(' · ')
  if (sub) {
    children.push(para(text(sub, { size: 18, color: '555555' }), { alignment: AlignmentType.CENTER, spacing: { after: 160 } }))
  }
  children.push(para(text(
    `School Based Assessment (ECZ). Maximum for ${header.gradeLabel || 'this grade'} = ${total} marks → converted to 10%. ` +
    'Final mark entered on the ECZ portal in Grade 7 = G5 + G6 + G7.',
    { italics: true, size: 16, color: '6b7280' },
  ), { spacing: { after: 160 } }))

  const headRow = new TableRow({
    tableHeader: true,
    children: [
      cell(para(text('SN', { bold: true, size: 14 })), { shading: 'E2E8F0' }),
      cell(para(text("Pupil's name", { bold: true, size: 14 })), { shading: 'E2E8F0' }),
      ...columns.map((c) => cell(
        para(text(`${c.label} /${c.max}`, { bold: true, size: 12 })), { shading: 'EEF2F7' },
      )),
      cell(para(text(`Total /${total}`, { bold: true, size: 14 })), { shading: 'E2E8F0' }),
      cell(para(text('SBA /10', { bold: true, size: 14 })), { shading: 'DCFCE7' }),
    ],
  })

  const bodyRows = pupils.map((p, i) => {
    const marks = p.marks || {}
    const raw = columns.reduce((s, c) => s + (Number(marks[c.key]) || 0), 0)
    const converted = convertSbaMark(raw, total).rounded
    return new TableRow({
      children: [
        cell(para(text(String(i + 1), { size: 14 }))),
        cell(para(text(p.name || '', { size: 16 }))),
        ...columns.map((c) => cell(
          para(text(marks[c.key] != null ? String(marks[c.key]) : '', { size: 14 }), { alignment: AlignmentType.CENTER }),
        )),
        cell(para(text(String(raw), { bold: true, size: 16 }), { alignment: AlignmentType.CENTER })),
        cell(para(text(String(converted), { bold: true, size: 16 }), { alignment: AlignmentType.CENTER }), { shading: 'F0FDF4' }),
      ],
    })
  })

  children.push(new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [headRow, ...bodyRows],
  }))

  return new Document({
    creator: 'zedexams.com',
    title: 'SBA Mark Schedule',
    description: 'Generated by ZedExams Teacher Tools',
    styles: { default: { document: { run: { font: 'Calibri', size: 18 } } } },
    sections: [{
      ...attributionSection(opts),
      properties: { page: { size: { orientation: PageOrientation.LANDSCAPE } } },
      children,
    }],
  })
}

export async function downloadSbaTrackerDocx(artifact, filename = 'sba-mark-schedule.docx', opts = {}) {
  const doc = buildSbaTrackerDocument(artifact, opts)
  const blob = await Packer.toBlob(doc)
  await saveBlob(blob, filename)
}
