/**
 * Pure helpers for the same-origin download-echo endpoint, with NO firebase
 * requires — so a plain `node` test can exercise them without the functions/
 * deps installed (CI installs only the root deps).
 *
 * The endpoint exists because some browsers (DuckDuckGo, in-app WebViews, older
 * Android) drop the filename for an in-page blob: download — the name has to
 * arrive on an HTTP response header. We echo the just-generated bytes back from
 * zedexams.com with a Content-Disposition that carries the real name, so the
 * download manager names the file correctly AND it reads as coming from our own
 * domain (not firebasestorage.googleapis.com).
 */

const querystring = require("querystring");

// Content types we are willing to label the echo with. Anything else is served
// as a generic binary attachment. Combined with X-Content-Type-Options: nosniff
// and Content-Disposition: attachment, this keeps the endpoint from being usable
// to reflect inline-rendered (e.g. HTML) content.
const SAFE_TYPES = new Set([
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/msword",
  "application/pdf",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "text/csv",
]);

function sanitizeType(type) {
  const t = String(type || "").toLowerCase().split(";")[0].trim();
  return SAFE_TYPES.has(t) ? t : "application/octet-stream";
}

/**
 * RFC 6266 Content-Disposition with an ASCII fallback plus the UTF-8 form, so
 * the filename survives non-ASCII names on every browser.
 */
function contentDispositionFor(name) {
  const n = String(name || "download");
  const ascii = n.replace(/[^\x20-\x7E]/g, "_").replace(/["\\]/g, "");
  return `attachment; filename="${ascii}"; filename*=UTF-8''${encodeURIComponent(n)}`;
}

/**
 * Pull the base64 payload out of an `application/x-www-form-urlencoded` body of
 * the shape `data=<urlencoded-base64>`. Returns the raw base64 string, or null
 * when absent/malformed.
 */
function parseEchoData(rawBody) {
  const parsed = querystring.parse(String(rawBody || ""));
  const data = parsed.data;
  return typeof data === "string" && data ? data : null;
}

module.exports = {
  SAFE_TYPES,
  sanitizeType,
  contentDispositionFor,
  parseEchoData,
};
