// The spec's reference case: Grade 4 Science, 4.1.1 The Respiratory System,
// written in the point form the §3.1 budgets ask the generator for.
export const REFERENCE_PLAN = {
  generalCompetences: ['Communication', 'Analytical Thinking', 'Creativity and Innovation', 'Collaboration', 'Critical Thinking'],
  specificCompetence: '4.1.1.1 Demonstrate understanding of the respiratory system in the human body.',
  lessonGoal: 'Identify the main parts of the respiratory system and describe how air moves into and out of the lungs.',
  rationale: 'Learners study the nose, trachea, bronchi and lungs to understand breathing and care for respiratory health (Asthma, TB, Bronchitis). Lesson 1 of 4.',
  priorKnowledge: 'Learners know humans breathe but have not yet studied the organs involved.',
  references: ['Zambia CDC Grade 4 Integrated Science Syllabus, Topic 4.1 p.18', 'Grade 4 Integrated Science Teaching Module, Topic 4.1.1 p.24'],
  learningEnvironment: {
    natural: 'Not applicable for this lesson.',
    artificial: 'Classroom with chalkboard, chalk, exercise books and shared textbooks.',
    technological: 'Not applicable for this lesson.',
  },
  materials: ['Chalkboard and chalk', 'Exercise books and pencils', 'Shared textbooks', 'Hand-drawn chart of the respiratory system'],
  expectedStandard: 'Understanding of the respiratory system demonstrated satisfactorily.',
  stages: [
    { name: 'INTRODUCTION', duration: '5 min',
      teacher: 'Learners place a hand on the chest and breathe deeply; ask what happens inside the body.\nState the lesson goal.',
      pupils: 'Breathe, feel chest movement, share observations.',
      assessment: 'State that air enters the body when breathing.' },
    { name: 'LESSON DEVELOPMENT — Parts of the System', duration: '12 min',
      teacher: 'Draw and label nose, trachea, bronchi and lungs on the chalkboard.\nExplain each part’s function in simple terms.\nPairs study the textbook diagram.',
      pupils: 'Study diagrams in pairs; identify and name each part.',
      assessment: 'Name at least three parts of the system.' },
    { name: 'LESSON DEVELOPMENT — Path of Air', duration: '8 min',
      teacher: 'Draw arrows: nose → trachea → bronchi → lungs and back.\nAsk which gas goes in and which comes out (oxygen in, carbon dioxide out).\nIntroduce Asthma and TB briefly.',
      pupils: 'Trace the path of air; answer questions; discuss in pairs.',
      assessment: 'Describe the path of air; name one respiratory disease.' },
    { name: 'EXERCISE / ASSESSMENT', duration: '10 min',
      teacher: 'Learners draw and label the system; write one sentence on how air moves.\nCirculate and give corrective feedback.',
      pupils: 'Draw, label and write in exercise books.',
      assessment: 'Diagram with three or more parts labelled correctly.' },
    { name: 'HOMEWORK', duration: '2 min',
      teacher: 'Ask an adult about breathing problems (e.g. Asthma); write two sentences.',
      pupils: 'Record the task in exercise books.',
      assessment: 'Task written correctly.' },
    { name: 'CONCLUSION', duration: '3 min',
      teacher: 'Point to each part; learners name it and its function.\nAsk why respiratory health matters.',
      pupils: 'Name parts; suggest healthy habits.',
      assessment: 'Name all four parts; give one health reason.' },
  ],
  remedialWork: 'Re-teach labelling with a partially completed chalkboard diagram for learners who struggled.',
  extensionActivity: 'Advanced learners write a short paragraph on Asthma and two ways of preventing respiratory diseases.',
}

export const REFERENCE_META = {
  format: 'classic',
  school: 'Jemareen Academy',
  teacherName: 'Mahenga Mwelwa',
  grade: 'Grade 4',
  subject: 'Science',
  topic: '4.1 The Human Body',
  subtopic: '4.1.1 The Respiratory System',
  date: '2026-07-30',
  duration: 40,
  compactMeta: true,
  learningEnvironments: ['Artificial'],
}
