/**
 * Class Timetable studio — /teacher/generate/class-timetable
 *
 * Pure client-side tool (no AI call, no usage meter). The teacher picks the
 * CURRICULUM first (2023 CBC, 2013 OBC, adapted, custom), then the grade —
 * the central curriculum configuration (src/utils/curriculumFramework.js)
 * supplies the official subjects, weekly allocations, option groups
 * (Expressive Arts OR Home Economics, language provisions) and block
 * preferences. The schedule itself is stored as explicit BLOCKS (singles +
 * double periods + school activities — src/utils/timetableBlocks.js) and
 * generated by the block-aware auto-fill in src/utils/classTimetable.js.
 *
 * TWO PHASES (2026-08 restructure):
 *   Phase 1 — a 3-step setup wizard (Class → School day → Subjects) with a
 *   single sticky-footer CTA that, in generate mode, folds the old
 *   "Generate curriculum timetable" + "Auto-fill timetable" buttons into
 *   one "Auto-fill & open the week" action.
 *   Phase 2 — the full-screen grid workspace (timetable/TimetableWorkspace):
 *   slim sticky top bar, tap-to-place subject palette, and drawers for Day
 *   times / Subjects / conflicts / layout / preview.
 * Progress is remembered per timetable (localStorage) so a returning
 * teacher lands straight in the workspace; "Edit setup" goes back.
 *
 * This component keeps owning ALL state and handlers — the components
 * under ./timetable/ are presentational and receive props.
 *
 * Outputs the official timetable grid on screen and as DOCX / XLSX / PDF,
 * and saves to the teacher's library. Drafts autosave (universal draft
 * manager) so a half-built week survives a refresh; undo/redo covers the
 * current editing session.
 */

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Grid3x3, AlertTriangle } from 'lucide-react'
import { useAuth } from '../../../contexts/AuthContext'
import {
  DAYS_OF_WEEK,
  DEFAULT_DAYS,
  DEFAULT_TIMING,
  DEFAULT_DISPLAY_PREFERENCES,
  getSchoolDayTemplate,
  buildPeriods,
  lessonPeriods as lessonRowsOf,
  curriculumSubjectsForGrade,
  newSubject,
  recommendedLessonPeriods,
  distributePeriodsPerDay,
  weeklyCapacity,
  autoFillBlocks,
  validateTimetableBlocks,
  resolveAllocationReadiness,
  totalAllocated,
  buildTimetableArtifact,
  dayEndTime,
  timeToMinutes,
  templatesForDayType,
  resolveCapacityFit,
  withCalendarOverride,
  removeCalendarOverride,
} from '../../../utils/classTimetable'
import {
  DEFAULT_CURRICULUM_ID,
  getCurriculum,
  resolveTimetableCurriculum,
  gradeStructureModeFor,
} from '../../../utils/curriculumFramework'
import {
  gradeStructureFor,
  isGradeInCurriculum,
} from '../../../config/teacherTaxonomy'
import {
  BLOCK_TYPES,
  segmentsOf,
  blockAt,
  slotsToBlocks,
  setCellBlock,
  setBlockDetails,
  joinBlocks,
  splitBlock,
  toggleBlockLock,
  suggestJoins,
} from '../../../utils/timetableBlocks'
import {
  normaliseTimetableForConflictCheck,
  findCrossTimetableConflicts,
  changedSiblingsSince,
  blockingConflicts,
} from '../../../utils/timetableConflictEngine'
import { loadSiblingTimetables } from '../../../utils/siblingTimetables'
import TimetableConflictPanel from './TimetableConflictPanel'
import BlockDetailsModal from './BlockDetailsModal'
import { useTeachingProfile } from '../../../features/teacherSettings/lib/useTeachingProfile'
import { buildTimetableGridModel, subjectTintMap } from '../../../utils/timetableGridModel'
import { saveClassTimetableGeneration, isFreePlanTeacher } from '../../../utils/teacherLibraryService'
import { useLibraryAutoSave } from '../../../hooks/useLibraryAutoSave'
import { downloadClassTimetableDocx } from '../../../utils/classTimetableToDocx'
import { downloadClassTimetableXlsx } from '../../../utils/classTimetableToXlsx'
import { buildDownloadName } from '../../../utils/downloadFilename'
import { downloadClassTimetablePdf } from '../../../utils/classTimetableToPdf'
import {
  normalizeTimingBreaks,
  normalizeDaySchedulesBreaks,
} from '../../../utils/durationOptions'
import ClassTimetableView from '../views/ClassTimetableView'
import StudioPageHeader from '../StudioPageHeader'
import SeoHelmet from '../../seo/SeoHelmet'
import ConfirmDialog from '../../ui/ConfirmDialog'
import Chip from '../../ui/Chip'
import { useToast } from '../../ui/Toast'
import { useDraftManager } from '../../../hooks/draft/useDraftManager'
import { classTimetableDescriptor } from '../../../hooks/draft/descriptors/handBuilt'
import { usePlatformSettings } from '../../../contexts/PlatformSettingsContext'
import DraftRecoveryPrompt from '../../draft/DraftRecoveryPrompt'
import { buildRequestKey, toDisplayMessage } from '../../../utils/requestControl.js'
import { deduplicatedRequest } from '../../../utils/requestDeduplication.js'
import { useAbortableRequest } from '../../../hooks/useAbortableRequest.js'
import TimetableSetupWizard from './timetable/TimetableSetupWizard'
import WizardStepClass from './timetable/WizardStepClass'
import WizardStepSchoolDay from './timetable/WizardStepSchoolDay'
import SubjectsPanel from './timetable/SubjectsPanel'
import TimetableLayoutPanel from './timetable/TimetableLayoutPanel'
import TimetableWorkspace from './timetable/TimetableWorkspace'
import WorkspaceDrawer from './timetable/WorkspaceDrawer'

const DEFAULT_ACTIVITIES = ['Remedial work', 'Library', 'Clubs']
const HISTORY_LIMIT = 60

/** Where the setup-vs-workspace progress for one timetable is remembered. */
function phaseStorageKey(uid, generationId) {
  return `zx:tt-phase:${uid || 'anon'}:${generationId || 'new'}`
}

function readPhasePref(uid, generationId) {
  try {
    return JSON.parse(window.localStorage.getItem(phaseStorageKey(uid, generationId)) || 'null')
  } catch {
    return null
  }
}

/** The grade/form options for the selected curriculum, grouped by stage — the
 * SAME per-curriculum structure Teaching Assignments uses (CBC: ECE, Lower
 * Primary 1–3, Upper Primary 4–6, Secondary Forms 1–4; OBC: its own 1–7 / 8–12
 * layout). There is deliberately NO separate Class-Timetable grade list. */
function gradeStagesFor(curriculumId) {
  return gradeStructureFor(gradeStructureModeFor(curriculumId)).stages
}

/**
 * Seed the studio's subject list for a curriculum + grade. There is NO generic
 * or hard-coded fallback: a curriculum that prescribes an official allocation
 * (CBC 2023 / adapted) is seeded ONLY from the framework — a grade with no
 * prescribed table (CBC Grade 7 / secondary, or an empty grade) returns [] so
 * the studio surfaces the "curriculum timetable data unavailable" diagnostic
 * instead of guessing. Curricula with no catalogued table (OBC 2013 / custom)
 * fall back to the manual subject list the teacher edits by hand.
 */
function seedSubjects(grade, curriculumId, selectedOptions) {
  if (!grade) return []
  const curriculum = getCurriculum(curriculumId)
  if (curriculum?.hasAllocations) {
    return resolveTimetableCurriculum({ curriculumId, grade, selectedOptions })
      ? curriculumSubjectsForGrade(grade, curriculumId, selectedOptions)
      : []
  }
  return curriculumSubjectsForGrade(grade, curriculumId, selectedOptions)
}

/** Lesson periods/day that fit the curriculum's weekly load for a grade, or
 * the studio default when there is no prescribed allocation. */
function lessonPeriodsForGrade(grade, days, curriculumId) {
  const fw = resolveTimetableCurriculum({ curriculumId, grade })
  return fw ? recommendedLessonPeriods(fw.totalPeriods, days) : DEFAULT_TIMING.lessonPeriods
}

export default function ClassTimetableStudio() {
  const { currentUser, userProfile, isAdmin } = useAuth()
  const toast = useToast()
  const uid = currentUser?.uid

  const initialGrade = 'G5'
  const [curriculumId, setCurriculumId] = useState(DEFAULT_CURRICULUM_ID)
  const [selectedOptions, setSelectedOptions] = useState({})
  const [header, setHeader] = useState(() => ({
    school: userProfile?.school || userProfile?.schoolName || '',
    grade: initialGrade,
    className: '',
    term: '',
    year: String(new Date().getFullYear()),
    teacherName: userProfile?.displayName || userProfile?.fullName || '',
    preparedBy: '',
    approvedBy: '',
  }))
  const [days, setDays] = useState(DEFAULT_DAYS)
  const [timing, setTiming] = useState(() => ({
    startTime: DEFAULT_TIMING.startTime,
    endTime: DEFAULT_TIMING.endTime,
    fitToEndTime: DEFAULT_TIMING.fitToEndTime,
    periodMinutes: DEFAULT_TIMING.periodMinutes,
    // Right-size the grid to the framework's weekly load for the starting grade.
    lessonPeriods: lessonPeriodsForGrade(initialGrade, DEFAULT_DAYS, DEFAULT_CURRICULUM_ID),
    breaks: DEFAULT_TIMING.breaks.map((b) => ({ ...b, enabled: true })),
  }))
  const [dayTemplate, setDayTemplate] = useState('full-day-break-lunch')
  const [subjects, setSubjects] = useState(() => seedSubjects(initialGrade, DEFAULT_CURRICULUM_ID, {}))
  // Week mode: 'exact' = Mode A (per-day lesson counts sum to the curriculum
  // total); 'activities' = Mode B (full grid, spare slots become labelled
  // school activities); 'flat' = no special handling (manual curricula).
  const [weekMode, setWeekMode] = useState('activities')
  const [dayCounts, setDayCounts] = useState({}) // Mode A per-day lesson counts
  const [activities, setActivities] = useState(DEFAULT_ACTIVITIES)
  const [displayPreferences, setDisplayPreferences] = useState(DEFAULT_DISPLAY_PREFERENCES)
  // Day-specific school structures: a day with no entry here shares the school
  // day above. A day WITH an entry has its own Full/Half/Custom structure — a
  // REGULAR weekly pattern (e.g. Friday always knocks off at 12:30), saved
  // with this timetable. { [day]: { dayType, templateId, timing } }
  const [daySchedules, setDaySchedules] = useState({})
  const [editingDayStructureFor, setEditingDayStructureFor] = useState(null)
  // School Calendar overrides: an OCCASIONAL, date-specific change (e.g. one
  // Friday shortened for a staff meeting) that never touches daySchedules
  // above. { date, dayType, timing, reason }[]
  const [calendarOverrides, setCalendarOverrides] = useState([])
  const [newOverrideDate, setNewOverrideDate] = useState('')
  const [newOverrideDayType, setNewOverrideDayType] = useState('half')
  const [newOverrideReason, setNewOverrideReason] = useState('')

  // Phase model: the 3-step setup wizard vs the grid workspace. Progress is
  // remembered per timetable so a returning teacher lands in the workspace.
  const [phase, setPhase] = useState(() => (
    readPhasePref(currentUser?.uid, null)?.phase === 'workspace' ? 'workspace' : 'wizard'
  ))
  const [wizardStep, setWizardStep] = useState(() => {
    const s = readPhasePref(currentUser?.uid, null)?.wizardStep
    return Number.isInteger(s) ? Math.min(2, Math.max(0, s)) : 0
  })
  // How the week starts: generate from curriculum / upload existing / blank.
  const [entryMode, setEntryMode] = useState('generate')
  const [showRecoveryPreview, setShowRecoveryPreview] = useState(false)

  // The schedule itself: explicit blocks (source of truth) + undo history.
  const [blocks, setBlocksRaw] = useState([])
  const historyRef = useRef({ past: [], future: [] })
  const setBlocks = (next, { history = true } = {}) => {
    setBlocksRaw((prev) => {
      const value = typeof next === 'function' ? next(prev) : next
      if (history && value !== prev) {
        historyRef.current.past.push(prev)
        if (historyRef.current.past.length > HISTORY_LIMIT) historyRef.current.past.shift()
        historyRef.current.future = []
      }
      return value
    })
  }
  const undo = () => {
    setBlocksRaw((prev) => {
      const past = historyRef.current.past
      if (!past.length) return prev
      historyRef.current.future.push(prev)
      return past.pop()
    })
  }
  const redo = () => {
    setBlocksRaw((prev) => {
      const future = historyRef.current.future
      if (!future.length) return prev
      historyRef.current.past.push(prev)
      return future.pop()
    })
  }

  const [generationId, setGenerationId] = useState(null)
  const [saving, setSaving] = useState(false)
  const [dirtySinceSave, setDirtySinceSave] = useState(false)
  const [confirmClear, setConfirmClear] = useState(false)

  /* ── Cross-timetable conflict checking ── */
  const navigate = useNavigate()
  const { assignments } = useTeachingProfile()
  const [siblings, setSiblings] = useState([])
  const [siblingStatus, setSiblingStatus] = useState('idle') // idle|loading|ready|error
  const [siblingError, setSiblingError] = useState('')
  const [lastCheckedAt, setLastCheckedAt] = useState(null)
  const [staleSiblings, setStaleSiblings] = useState([])
  const [selectedConflict, setSelectedConflict] = useState(null)
  const [detailsBlockId, setDetailsBlockId] = useState(null)
  const [finalChecking, setFinalChecking] = useState(false)
  const [offline, setOffline] = useState(typeof navigator !== 'undefined' && navigator.onLine === false)
  useEffect(() => {
    const on = () => setOffline(false)
    const off = () => setOffline(true)
    window.addEventListener('online', on)
    window.addEventListener('offline', off)
    return () => { window.removeEventListener('online', on); window.removeEventListener('offline', off) }
  }, [])
  const [confirmRemoveDouble, setConfirmRemoveDouble] = useState(null) // blockId
  const [confirmRemoveSubject, setConfirmRemoveSubject] = useState(null) // subject id
  // Pending curriculum/grade/option switch — changing any of these reseeds
  // subjects, so we ask first when the teacher has lessons placed.
  const [pendingSwitch, setPendingSwitch] = useState(null) // { kind, value, groupId? }
  // A recovered draft whose curriculum/grade/subjects don't reconcile against
  // the current catalog — surfaced as "Needs review" instead of silently
  // generating from stale values.
  const [recoveredReview, setRecoveredReview] = useState(null) // { curriculumId, grade, gradeValid, missing[] }
  const [mobileDay, setMobileDay] = useState('all')
  const lastSeedKeyRef = useRef(`${DEFAULT_CURRICULUM_ID}|${initialGrade}`)
  // Skip the mount + draft-restore runs of the dirty-marking effect so a
  // freshly-loaded saved timetable isn't flagged "Update in library".
  const dirtySkipRef = useRef(1)

  const periods = useMemo(() => buildPeriods(timing), [timing])
  const curriculum = useMemo(
    () => resolveTimetableCurriculum({ curriculumId, grade: header.grade, selectedOptions }),
    [curriculumId, header.grade, selectedOptions],
  )
  const curriculumMeta = useMemo(() => getCurriculum(curriculumId), [curriculumId])
  const gradeStages = useMemo(() => gradeStagesFor(curriculumId), [curriculumId])
  // Does this curriculum prescribe an official weekly allocation for the chosen
  // grade, and is the loaded subject list a COMPLETE resolution of it?
  const readiness = useMemo(
    () => resolveAllocationReadiness({ subjects, curriculum }),
    [subjects, curriculum],
  )
  // The curriculum expects an official table (CBC / adapted) but either the
  // grade has none (Grade 7 / secondary) or the loaded allocation is incomplete
  // (e.g. a stale draft that dropped Mathematics and Science → 32 of 42).
  const expectsAllocation = Boolean(curriculumMeta?.hasAllocations)
  const allocationBlocked = expectsAllocation && (!curriculum || !readiness.ready)
  const segments = useMemo(() => segmentsOf(periods), [periods])

  // Mode A per-day lesson counts (only when the teacher chose the exact
  // week) PLUS any day-specific school-day structures — a day with its own
  // structure (see daySchedules state) ignores the Mode A count for that day
  // entirely, since its own timing determines its own lesson count.
  const dayStructure = useMemo(() => {
    const hasDaySchedules = Object.keys(daySchedules).length > 0
    let counts = null
    if (weekMode === 'exact') {
      counts = {}
      for (const day of days) {
        const n = dayCounts[day]
        counts[day] = n == null ? lessonRowsOf(periods).length : n
      }
    }
    if (!counts && !hasDaySchedules) return null
    return {
      ...(counts ? { periodsPerDay: counts } : {}),
      ...(hasDaySchedules ? { daySchedules } : {}),
    }
  }, [weekMode, dayCounts, days, periods, daySchedules])

  const capacity = useMemo(() => weeklyCapacity(periods, days, dayStructure), [periods, days, dayStructure])
  // Can the complete weekly curriculum allocation physically fit the current
  // per-day capacity? Auto-fill/generation are blocked (never silently
  // truncated) when it cannot.
  const capacityFit = useMemo(
    () => resolveCapacityFit({ subjects, days, periods, dayStructure }),
    [subjects, days, periods, dayStructure],
  )

  /* Timing readouts. In fit mode the period length is derived (shown to the
   * teacher); in fixed mode the day end is computed and checked against the
   * teacher's target knock-off time. */
  const derivedPeriodMinutes = useMemo(() => {
    if (!timing.fitToEndTime) return 0
    const lessons = lessonRowsOf(periods)
    if (!lessons.length) return 0
    const total = lessons.reduce((sum, p) => sum + (timeToMinutes(p.end) - timeToMinutes(p.start)), 0)
    return Math.round(total / lessons.length)
  }, [timing.fitToEndTime, periods])
  const computedEnd = useMemo(() => dayEndTime(periods), [periods])
  const knockOffDelta = useMemo(() => {
    if (timing.fitToEndTime || !computedEnd || !timing.endTime) return null
    return timeToMinutes(computedEnd) - timeToMinutes(timing.endTime)
  }, [timing.fitToEndTime, timing.endTime, computedEnd])
  const allocated = useMemo(() => totalAllocated(subjects), [subjects])
  const filled = useMemo(
    () => blocks.reduce((n, b) => n + (b.type === BLOCK_TYPES.CURRICULUM ? b.length : 0), 0),
    [blocks],
  )
  const validation = useMemo(
    () => validateTimetableBlocks({ blocks, subjects, periods, days, dayStructure, curriculum }),
    [blocks, subjects, periods, days, dayStructure, curriculum],
  )

  const artifact = useMemo(() => buildTimetableArtifact({
    header: { ...header, term: header.term === '' ? '' : Number(header.term) },
    days,
    periods,
    blocks,
    dayStructure,
    displayPreferences,
    curriculumId,
    selectedOptions,
    subjectAllocations: subjects,
    calendarOverrides,
  }), [header, days, periods, blocks, dayStructure, displayPreferences, curriculumId, selectedOptions, subjects, calendarOverrides])

  // The editable grid + preview render from the same shared model.
  const gridModel = useMemo(() => buildTimetableGridModel(artifact), [artifact])

  /* Cross-timetable conflicts: the CURRENT in-memory artifact (including
   * unsaved edits) is normalised and compared against the loaded siblings by
   * the pure engine — every block/teacher/room/time edit recalculates
   * locally, with no extra Firestore reads (§ refresh re-queries). */
  const currentNormalised = useMemo(
    () => normaliseTimetableForConflictCheck({ id: generationId || '', output: artifact }),
    [artifact, generationId],
  )
  const conflictResult = useMemo(
    () => findCrossTimetableConflicts({ currentTimetable: currentNormalised, siblingTimetables: siblings }),
    [currentNormalised, siblings],
  )

  // A debounced background probe, a manual "Refresh" click, and the
  // pre-save "Final Check & Save" flow can all call this within moments of
  // each other. `useAbortableRequest` makes only the LATEST call (whichever
  // fired most recently — the strongest signal of current intent) able to
  // update `siblings`/`staleSiblings`/`lastCheckedAt`; an earlier call that
  // resolves after being superseded is dropped instead of clobbering fresher
  // state with an out-of-order response. `deduplicatedRequest` additionally
  // shares one Firestore round-trip when two callers ask for the exact same
  // (uid, timetable, school, year, term) at once — e.g. the debounce firing
  // right as the teacher clicks "Refresh" manually.
  const { run: runSiblingRefresh } = useAbortableRequest({ timeoutMs: 15_000 })
  const refreshConflicts = useCallback(async ({ silent = false } = {}) => {
    if (!uid) return null
    setSiblingStatus('loading')
    setSiblingError('')
    const key = buildRequestKey(
      'timetable-siblings', uid, generationId || '', header.school, header.year, header.term,
    )
    const result = await runSiblingRefresh(({ signal }) => deduplicatedRequest(key, () => loadSiblingTimetables({
      uid,
      timetableId: generationId || '',
      school: header.school,
      year: header.year,
      term: header.term,
    }), { signal, timeoutMs: 15_000 }))

    if (result.status === 'success') {
      const fresh = result.data
      // Stale-data note: which siblings changed since the previous check.
      setStaleSiblings((lastCheckedAt ? changedSiblingsSince(siblings, fresh.siblings) : []))
      setSiblings(fresh.siblings)
      setLastCheckedAt(fresh.checkedAt)
      setSiblingStatus('ready')
      return fresh.siblings
    }
    if (result.status === 'error') {
      console.error('[ClassTimetableStudio] sibling load failed', result.error)
      setSiblingStatus('error')
      setSiblingError(offline ? 'you appear to be offline' : toDisplayMessage(result.error))
      if (!silent) toast.error('Could not load your other timetables for conflict checking.')
      return null
    }
    // 'stale' / 'aborted' — a newer refresh call already superseded this one.
    // Treat it like "couldn't confirm" rather than reusing possibly-outdated
    // data, so a caller like Final Check & Save never saves against a result
    // that isn't actually this call's own.
    return null
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [uid, generationId, header.school, header.year, header.term, siblings, lastCheckedAt, offline, runSiblingRefresh])

  /* Load siblings once the studio knows who's signed in, and re-scope when
   * the school / year / term context changes (debounced — school is typed). */
  const refreshRef = useRef(refreshConflicts)
  refreshRef.current = refreshConflicts
  useEffect(() => {
    if (!uid) return undefined
    const t = setTimeout(() => { refreshRef.current({ silent: true }) }, 900)
    return () => clearTimeout(t)
  }, [uid, header.school, header.year, header.term])

  // Universal Draft Manager: cross-device auto-save + recovery. The library
  // copy (aiGenerations) is saved separately by useLibraryAutoSave below.
  const { featureFlags } = usePlatformSettings().settings
  const draft = useDraftManager({
    studioId: 'class_timetable',
    uid,
    draftId: 'class_timetable-current',
    descriptor: classTimetableDescriptor,
    state: {
      header, days, timing, subjects, generationId, blocks,
      curriculumId, selectedOptions, weekMode, dayCounts, activities,
      displayPreferences, dayTemplate, daySchedules, calendarOverrides,
      slots: artifact.slots, // legacy readers of old drafts
    },
    enabled: Boolean(uid && featureFlags?.universalDrafts !== false),
    onRestore: (p) => {
      // Set the seed key BEFORE setHeader so the reseed effect below sees the
      // restored curriculum+grade as "current" and doesn't wipe the recovered
      // subjects/blocks.
      const restoredCurriculum = p.curriculumId || DEFAULT_CURRICULUM_ID
      const restoredGrade = p.header?.grade || lastSeedKeyRef.current.split('|')[1]
      lastSeedKeyRef.current = `${restoredCurriculum}|${restoredGrade}`
      if (p.curriculumId) setCurriculumId(p.curriculumId)
      if (p.selectedOptions) setSelectedOptions(p.selectedOptions)
      if (p.header) setHeader((h) => ({ ...h, ...p.header }))
      if (Array.isArray(p.days) && p.days.length) setDays(p.days)
      // Coerce any legacy break durations (numeric strings, "20 min" labels)
      // back to integer minutes as the draft loads, so the dropdowns and the
      // grid builder only ever see whole numbers.
      if (p.timing) setTiming((t) => ({ ...t, ...normalizeTimingBreaks(p.timing) }))
      if (Array.isArray(p.subjects) && p.subjects.length) setSubjects(p.subjects)
      if (p.weekMode) setWeekMode(p.weekMode)
      if (p.dayCounts) setDayCounts(p.dayCounts)
      if (Array.isArray(p.activities)) setActivities(p.activities)
      if (p.displayPreferences) setDisplayPreferences((d) => ({ ...d, ...p.displayPreferences }))
      if (p.dayTemplate) setDayTemplate(p.dayTemplate)
      if (p.daySchedules && typeof p.daySchedules === 'object') setDaySchedules(normalizeDaySchedulesBreaks(p.daySchedules))
      if (Array.isArray(p.calendarOverrides)) setCalendarOverrides(p.calendarOverrides)
      let restoredBlocks = []
      if (Array.isArray(p.blocks)) {
        restoredBlocks = p.blocks
        setBlocksRaw(p.blocks)
      } else if (p.slots && typeof p.slots === 'object') {
        // An old draft carries per-cell slots only — migrate to single blocks.
        const restoredPeriods = buildPeriods({ ...timing, ...(p.timing || {}) })
        restoredBlocks = slotsToBlocks(p.slots, restoredPeriods, p.days || days)
        setBlocksRaw(restoredBlocks)
      }
      if (p.generationId !== undefined) setGenerationId(p.generationId)
      dirtySkipRef.current += 1

      // A saved timetable reopened — or a draft with lessons already placed —
      // lands straight in the workspace; a setup-stage draft resumes the wizard.
      if (p.generationId || restoredBlocks.length > 0) setPhase('workspace')
      setShowRecoveryPreview(false)

      // Reconcile the recovered draft against the CURRENT catalog. A stale
      // curriculum/grade (e.g. an old CBC Grade 7, or a Grades 1–4 grouping) or
      // an incomplete subject set must not silently generate — flag it "Needs
      // review" so the teacher confirms before replacing valid selections.
      const restoredMode = gradeStructureModeFor(restoredCurriculum)
      const gradeValid = isGradeInCurriculum(restoredGrade, restoredMode)
      const restoredCurriculumFw = resolveTimetableCurriculum({
        curriculumId: restoredCurriculum, grade: restoredGrade, selectedOptions: p.selectedOptions || {},
      })
      const restoredReadiness = resolveAllocationReadiness({
        subjects: Array.isArray(p.subjects) ? p.subjects : [],
        curriculum: restoredCurriculumFw,
      })
      const stale = !gradeValid
        || (getCurriculum(restoredCurriculum)?.hasAllocations && (!restoredCurriculumFw || !restoredReadiness.ready))
      setRecoveredReview(stale
        ? {
            curriculumId: restoredCurriculum,
            grade: restoredGrade,
            gradeValid,
            missing: restoredReadiness.missing || [],
          }
        : null)
    },
  })

  /* Persist the setup-vs-workspace progress per timetable so the teacher
   * lands where they left off (G2). */
  useEffect(() => {
    try {
      window.localStorage.setItem(
        phaseStorageKey(uid, generationId),
        JSON.stringify({ phase, wizardStep }),
      )
    } catch { /* storage unavailable — progress just isn't remembered */ }
  }, [uid, generationId, phase, wizardStep])

  /* Reseed the subject list — and right-size the grid — from the curriculum
   * when the curriculum or grade changes. Skipped on the initial draft
   * restore (the key matches lastSeedKeyRef there, so a half-built week is
   * never wiped). Option changes do NOT clear the grid — they swap subject
   * allocations and the validation panel flags any stray placements. */
  useEffect(() => {
    const key = `${curriculumId}|${header.grade}`
    if (key === lastSeedKeyRef.current) return
    lastSeedKeyRef.current = key
    setSubjects(seedSubjects(header.grade, curriculumId, selectedOptions))
    setTiming((t) => ({ ...t, lessonPeriods: lessonPeriodsForGrade(header.grade, days, curriculumId) }))
    setDayCounts({})
    setBlocks([], { history: false })
    historyRef.current = { past: [], future: [] }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [curriculumId, header.grade, days])

  /* Option-group changes swap the allocations without touching the grid. */
  useEffect(() => {
    if (!curriculum) return
    setSubjects((list) => {
      const fresh = seedSubjects(header.grade, curriculumId, selectedOptions)
      // Keep any custom subjects/edits the teacher added beyond the framework.
      const freshLabels = new Set(fresh.map((s) => s.label))
      const extras = list.filter((s) => !freshLabels.has(s.label) && !s.optionGroupId && !s.choiceGroup && !s.subjectId)
      return [...fresh, ...extras]
    })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedOptions])

  /* Any data edit marks the library copy stale. */
  useEffect(() => {
    if (dirtySkipRef.current > 0) { dirtySkipRef.current -= 1; return }
    setDirtySinceSave(true)
  }, [header, days, timing, subjects, blocks, curriculumId, selectedOptions, weekMode, dayCounts, activities, displayPreferences, daySchedules, calendarOverrides])

  const setH = (field, value) => setHeader((h) => ({ ...h, [field]: value }))
  const setT = (field, value) => setTiming((t) => ({ ...t, [field]: value }))
  const setPref = (field, value) => setDisplayPreferences((d) => ({ ...d, [field]: value }))

  function toggleDay(day) {
    setDays((list) => list.includes(day)
      ? list.filter((d) => d !== day)
      : DAYS_OF_WEEK.filter((d) => d === day || list.includes(d)))
  }

  /* ── curriculum / grade / option switching (guarded) ── */
  function requestSwitch(kind, value, groupId) {
    if (kind === 'curriculum' && value === curriculumId) return
    if (kind === 'grade' && value === header.grade) return
    if (kind === 'option' && selectedOptions[groupId] === value) return
    if (filled > 0) { setPendingSwitch({ kind, value, groupId }); return }
    applySwitch({ kind, value, groupId })
  }
  function applySwitch({ kind, value, groupId }) {
    if (kind === 'curriculum') {
      setCurriculumId(value)
      // Curriculum is the top of the dependency chain: clear optional-subject
      // choices, and drop a grade that isn't valid in the new curriculum's
      // structure (e.g. an OBC Grade 7 when switching to CBC). The reseed effect
      // then clears the subjects and grid so nothing stale carries over.
      setSelectedOptions({})
      setRecoveredReview(null)
      if (!isGradeInCurriculum(header.grade, gradeStructureModeFor(value))) {
        setH('grade', '')
        toast.info('Grade cleared — it is not offered in this curriculum. Pick a grade to load its subjects.')
      }
    } else if (kind === 'grade') {
      setH('grade', value)
      setRecoveredReview(null)
    } else if (kind === 'option') {
      setSelectedOptions((o) => ({ ...o, [groupId]: value }))
      toast.info('Optional subject changed — re-check the curriculum validation below.')
    }
    setPendingSwitch(null)
  }

  /* ── subjects ── */
  function updateSubject(id, field, value) {
    setSubjects((list) => list.map((s) => (s.id === id ? { ...s, [field]: value } : s)))
  }
  function addSubject() {
    setSubjects((list) => [...list, newSubject(`Subject ${list.length + 1}`)])
  }
  function requestRemoveSubject(id) {
    const s = subjects.find((x) => x.id === id)
    if (!s) return
    if (subjects.length <= 1) return
    // Compulsory curriculum subjects need explicit confirmation — removing
    // one makes the timetable non-compliant.
    if (s.compulsory && s.selected !== false) { setConfirmRemoveSubject(id); return }
    setSubjects((list) => list.filter((x) => x.id !== id))
  }
  function resetSubjectsFromCurriculum() {
    setSubjects(seedSubjects(header.grade, curriculumId, selectedOptions))
    setRecoveredReview(null)
    toast.info('Subjects reset from the curriculum for this grade.')
  }

  /* Spare-slot policy switch (SubjectsPanel) — choosing the exact week
   * distributes the curriculum total across the days. */
  function changeWeekMode(mode) {
    setWeekMode(mode)
    if (mode === 'exact' && curriculum) setDayCounts(distributePeriodsPerDay(curriculum.totalPeriods, days))
  }

  /* ── breaks / timing ── */
  function updateBreak(idx, field, value) {
    setTiming((t) => ({
      ...t,
      breaks: t.breaks.map((b, i) => (i === idx ? { ...b, [field]: value } : b)),
    }))
  }
  function applyDayTemplate(id) {
    setDayTemplate(id)
    const tpl = getSchoolDayTemplate(id)
    if (!tpl?.timing) return
    setTiming((t) => ({
      ...t,
      ...tpl.timing,
      lessonPeriods: t.lessonPeriods, // keep the grade-sized grid
      breaks: tpl.timing.breaks.map((b) => ({ ...b })),
    }))
    toast.info(`${tpl.label} times applied — adjust anything below.`)
  }

  /* ── day-specific school structures (recurring, saved with this week) ── */
  function setDayType(day, dayType) {
    if (dayType === 'custom') {
      setDaySchedules((prev) => ({
        ...prev,
        [day]: {
          dayType: 'custom',
          templateId: null,
          timing: prev[day]?.timing
            ? { ...prev[day].timing, fitToEndTime: true }
            : { ...timing, fitToEndTime: true, breaks: timing.breaks.map((b) => ({ ...b })) },
        },
      }))
      return
    }
    const tpl = templatesForDayType(dayType)[0]
    if (!tpl?.timing) return
    setDaySchedules((prev) => ({
      ...prev,
      [day]: { dayType, templateId: tpl.id, timing: { ...tpl.timing, breaks: tpl.timing.breaks.map((b) => ({ ...b })) } },
    }))
  }
  function applyDayTemplateToDay(day, templateId) {
    const tpl = getSchoolDayTemplate(templateId)
    if (!tpl?.timing) return
    setDaySchedules((prev) => ({
      ...prev,
      [day]: { dayType: tpl.dayType, templateId, timing: { ...tpl.timing, breaks: tpl.timing.breaks.map((b) => ({ ...b })) } },
    }))
  }
  function updateDayTiming(day, field, value) {
    setDaySchedules((prev) => {
      const existing = prev[day]
      if (!existing) return prev
      return { ...prev, [day]: { ...existing, timing: { ...existing.timing, [field]: value } } }
    })
  }
  function updateDayBreak(day, idx, field, value) {
    setDaySchedules((prev) => {
      const existing = prev[day]
      if (!existing) return prev
      return {
        ...prev,
        [day]: {
          ...existing,
          timing: { ...existing.timing, breaks: existing.timing.breaks.map((b, i) => (i === idx ? { ...b, [field]: value } : b)) },
        },
      }
    })
  }
  function clearDaySchedule(day) {
    setDaySchedules((prev) => {
      if (!(day in prev)) return prev
      const next = { ...prev }
      delete next[day]
      return next
    })
    if (editingDayStructureFor === day) setEditingDayStructureFor(null)
  }

  /* ── School Calendar overrides (occasional, date-specific — never the
   * recurring weekly structure above) ── */
  function addCalendarOverride() {
    if (!newOverrideDate) { toast.error('Pick a date first.'); return }
    const tpl = templatesForDayType(newOverrideDayType)[0]
    setCalendarOverrides((prev) => withCalendarOverride(prev, {
      date: newOverrideDate,
      dayType: newOverrideDayType,
      templateId: tpl?.id || null,
      reason: newOverrideReason.trim() || null,
      timing: tpl?.timing ? { ...tpl.timing, breaks: tpl.timing.breaks.map((b) => ({ ...b })) } : { ...timing, fitToEndTime: true },
    }))
    toast.success(`Calendar override added for ${newOverrideDate} — the saved weekly timetable is unchanged.`)
    setNewOverrideDate('')
    setNewOverrideReason('')
  }
  function removeOverride(date) {
    setCalendarOverrides((prev) => removeCalendarOverride(prev, date))
  }

  /* ── grid editing (block-aware) ── */
  function setCell(day, slot, value) {
    const existing = blockAt(blocks, day, slot)
    if (existing && existing.length > 1 && !value) {
      // Deleting part of a double period → ask remove-or-split.
      setConfirmRemoveDouble(existing.blockId)
      return
    }
    if (existing && existing.length > 1 && value && value !== existing.label) {
      // The merged cell represents the whole block — change all of it.
      setBlocks((prev) => prev.map((b) => (b.blockId === existing.blockId ? { ...b, label: value, subjectId: null } : b)))
      return
    }
    if (existing?.locked) { toast.error('This period is locked — unlock it first.'); return }
    setBlocks((prev) => setCellBlock(prev, day, slot, { label: value }))
  }

  function onJoinDown(day, slot) {
    const a = blockAt(blocks, day, slot)
    const b = a ? blockAt(blocks, day, slot + a.length) : null
    if (!a || !b) return
    const res = joinBlocks(blocks, a.blockId, b.blockId, segments)
    if (!res.ok) { toast.error(res.reason); return }
    setBlocks(res.blocks)
    toast.success(`${a.label} is now a double period.`)
  }

  function onSplit(blockId) {
    const res = splitBlock(blocks, blockId)
    if (!res.ok) { toast.error(res.reason); return }
    setBlocks(res.blocks)
  }

  function onToggleLock(blockId) {
    setBlocks((prev) => toggleBlockLock(prev, blockId))
  }

  function onRemoveWholeDouble() {
    if (!confirmRemoveDouble) return
    setBlocks((prev) => prev.filter((b) => b.blockId !== confirmRemoveDouble))
    setConfirmRemoveDouble(null)
  }

  /* ── auto-fill ── */
  // Generation is blocked (never silently truncated) whenever the complete
  // weekly allocation cannot physically fit the per-day capacity — callers
  // may pass the periods/dayStructure they are about to switch to (e.g.
  // onGenerateFromCurriculum resizing the grid) so the check runs against
  // what will actually be auto-filled, not stale state.
  function runAutoFill(subjectList, opts = {}) {
    const effPeriods = opts.periods || periods
    const effStructure = opts.dayStructure !== undefined ? opts.dayStructure : dayStructure
    const effActivities = opts.activities !== undefined ? opts.activities : (weekMode === 'activities' && curriculum ? activities : [])
    const fit = resolveCapacityFit({ subjects: subjectList, days, periods: effPeriods, dayStructure: effStructure })
    if (!fit.fits) {
      toast.error(`This week needs ${fit.required} periods but the current day structures only hold ${fit.capacity} (${fit.shortfall} short) — add lesson periods or change a day's structure first.`)
      return
    }
    const lockedBlocks = blocks.filter((b) => b.locked)
    const result = autoFillBlocks({
      subjects: subjectList,
      days,
      periods: effPeriods,
      dayStructure: effStructure,
      lockedBlocks,
      activities: effActivities,
    })
    setBlocks(result.blocks)
    if (result.unplaced.length) {
      const detail = result.unplaced.map((u) => `${u.label} (${u.missing} short)`).join(', ')
      toast.error(`Not everything fits: ${detail}. ${result.unplaced[0].reason}`)
    } else {
      toast.success('Timetable filled — fine-tune any cell below.')
    }
    if (result.notes.length) toast.info(result.notes[0])
  }

  function onAutoFill() {
    if (!days.length) { toast.error('Pick at least one teaching day first.'); return }
    if (!subjects.length) { toast.error('Add at least one subject first.'); return }
    runAutoFill(subjects)
  }

  /* Build a fresh curriculum-based week: reset subjects to the official
   * allocation, right-size the grid, then run the block-aware auto-fill. */
  function onGenerateFromCurriculum() {
    if (!days.length) { toast.error('Pick at least one teaching day first.'); return }
    // Never generate from an incomplete official allocation — the guard below
    // (and the diagnostic panel) tell the teacher exactly what is missing.
    if (allocationBlocked) {
      const miss = readiness.missing?.[0]?.label
      toast.error(miss
        ? `Generation is unavailable because ${miss} is missing from the ${header.grade || 'grade'} curriculum allocation.`
        : 'No curriculum timetable allocation is available for this curriculum and grade.')
      return
    }
    const fresh = seedSubjects(header.grade, curriculumId, selectedOptions)
    setSubjects(fresh)
    if (curriculum) {
      const rec = recommendedLessonPeriods(curriculum.totalPeriods, days)
      if (rec !== timing.lessonPeriods) {
        const nextTiming = { ...timing, lessonPeriods: rec }
        setTiming(nextTiming)
        const nextPeriods = buildPeriods(nextTiming)
        const hasDaySchedules = Object.keys(daySchedules).length > 0
        const nextCounts = weekMode === 'exact' ? distributePeriodsPerDay(curriculum.totalPeriods, days) : null
        const nextStructure = (nextCounts || hasDaySchedules)
          ? { ...(nextCounts ? { periodsPerDay: nextCounts } : {}), ...(hasDaySchedules ? { daySchedules } : {}) }
          : null
        if (weekMode === 'exact') setDayCounts(nextCounts)
        runAutoFill(fresh, {
          periods: nextPeriods,
          dayStructure: nextStructure,
          activities: weekMode === 'activities' ? activities : [],
        })
        return
      }
      if (weekMode === 'exact') setDayCounts(distributePeriodsPerDay(curriculum.totalPeriods, days))
    }
    runAutoFill(fresh)
  }

  function onClearGrid() {
    setBlocks([])
    setConfirmClear(false)
    toast.info('Grid cleared.')
  }

  /* The wizard's single CTA (G2): generate mode folds the old "Generate
   * curriculum timetable" + "Auto-fill" buttons into one action, then the
   * workspace opens; upload/blank modes just open the week. */
  function finishSetup() {
    if (entryMode === 'generate') onGenerateFromCurriculum()
    setPhase('workspace')
  }

  /* Apply an uploaded/photographed timetable into the editable grid. Subjects
   * reset to the grade's curriculum allocation so the curriculum check can
   * tell the teacher whether the upload matches the requirements. */
  function onUploadExtracted(result) {
    if (!result) return
    if (Array.isArray(result.days) && result.days.length) setDays(result.days)
    // An uploaded grid carries explicit period lengths, not a knock-off time —
    // reproduce it with the fixed-length builder.
    const nextTiming = { ...timing, ...(result.timing || {}), fitToEndTime: false }
    if (result.timing) setTiming(nextTiming)
    setSubjects(seedSubjects(header.grade, curriculumId, selectedOptions))
    const nextPeriods = buildPeriods(nextTiming)
    const migrated = slotsToBlocks(result.slots || {}, nextPeriods, result.days || days)
    setBlocks(migrated)
    // Consecutive repeats read from the upload are candidate doubles — the
    // teacher confirms each one; separated repeats stay separate singles.
    const joinable = suggestJoins(migrated, segmentsOf(nextPeriods))
    if (joinable.length) {
      toast.info(`${joinable.length} adjacent repeated lesson${joinable.length === 1 ? '' : 's'} could be double periods — use the Join button on those cells to confirm.`)
    }
  }

  /* ── conflict actions ── */
  function highlightConflictBlock(blockId) {
    if (!blockId) return
    const cell = document.getElementById(`ttcell-${blockId}`)
    if (cell) cell.scrollIntoView({ behavior: 'smooth', block: 'center' })
  }
  function onSelectConflict(conflict) {
    setSelectedConflict(conflict)
    highlightConflictBlock(conflict?.currentBlock?.blockId)
  }
  function onOpenConflictingTimetable(timetableId) {
    if (!timetableId) return
    if (!siblings.some((s) => s.timetableId === timetableId)) {
      toast.error('Source timetable is no longer available.')
      return
    }
    // The saved-library view renders the sibling with its normal permissions.
    navigate(`/teacher/library/${timetableId}`)
  }
  function onEditBlockDetails(blockId) {
    if (!blockId) return
    setDetailsBlockId(blockId)
    highlightConflictBlock(blockId)
  }
  function onMoveLessonAction(blockId) {
    // No drag-and-drop in this phase: focus the affected cell so the teacher
    // can reassign it with the existing cell editor.
    const block = blocks.find((b) => b.blockId === blockId)
    if (block) {
      highlightConflictBlock(blockId)
      toast.info(`Use the ${block.day} cell to move or clear ${block.label} — the block keeps its links when its details are unchanged.`)
    }
  }
  function onSaveBlockDetails(details) {
    if (!detailsBlockId) return
    setBlocks((prev) => setBlockDetails(prev, detailsBlockId, details))
    toast.success('Block details updated — conflicts recalculated.')
  }

  /* ── persistence + export ── */
  async function onSaveToLibrary({ silent = false, publishState } = {}) {
    if (saving) return
    if (filled === 0) { if (!silent) toast.error('Fill at least one lesson before saving.'); return }
    setSaving(true)
    try {
      const id = await saveClassTimetableGeneration({ uid, existingId: generationId, artifact, publishState })
      setGenerationId(id)
      setDirtySinceSave(false)
      if (!silent) {
        // Draft saves are allowed with conflicts — but never silently.
        const blocking = blockingConflicts(conflictResult.conflicts)
        if (!publishState && blocking.length) {
          toast.info(`Saved with ${blocking.length} unresolved conflict${blocking.length === 1 ? '' : 's'} — see the Timetable conflicts panel.`)
        } else if (publishState === 'final') {
          toast.success('Final timetable saved — no blocking conflicts.')
        } else {
          toast.success(generationId ? 'Library copy updated.' : 'Saved to your library.')
        }
      }
      return id
    } catch (err) {
      console.error('[ClassTimetableStudio] save failed', err)
      if (!silent) toast.error(err?.message || 'Could not save to your library. Please try again.')
      return null
    } finally {
      setSaving(false)
    }
  }

  /* Final check & save: refresh siblings FIRST (never publish on stale
   * data), re-run the engine against the fresh set, and block the final
   * save while error-level conflicts remain. */
  async function onFinalCheckAndSave() {
    if (finalChecking || saving) return
    if (filled === 0) { toast.error('Fill the timetable first.'); return }
    if (offline) {
      toast.error('You are offline. Cross-class conflict results may be outdated — reconnect before a final save.')
      return
    }
    setFinalChecking(true)
    try {
      const freshSiblings = await refreshConflicts()
      if (freshSiblings === null) {
        toast.error('The pre-save conflict check failed — fix the connection and try again.')
        return
      }
      const fresh = findCrossTimetableConflicts({
        currentTimetable: currentNormalised,
        siblingTimetables: freshSiblings,
      })
      const blocking = blockingConflicts(fresh.conflicts)
      if (blocking.length) {
        const changed = changedSiblingsSince(siblings, freshSiblings)
        const changedNote = changed.length
          ? ` ${changed.join(', ')} ${changed.length === 1 ? 'was' : 'were'} updated after your last conflict check.`
          : ''
        toast.error(`Cannot save as final: ${blocking.length} unresolved error-level conflict${blocking.length === 1 ? '' : 's'}.${changedNote} Resolve them in the Timetable conflicts panel.`)
        return
      }
      await onSaveToLibrary({ publishState: 'final' })
    } finally {
      setFinalChecking(false)
    }
  }

  // Auto-save to the library so a hand-built timetable is never lost.
  useLibraryAutoSave({
    enabled: filled > 0,
    dirty: dirtySinceSave,
    saving,
    onSave: () => onSaveToLibrary({ silent: true }),
  })

  function fileBase(ext = 'docx') {
    return buildDownloadName({
      docType: 'Class Timetable',
      grade: header.grade,
      extra: header.className,
      term: header.term,
      year: header.year,
      ext,
    })
  }
  const attribution = isFreePlanTeacher({ userProfile, isAdmin })

  async function onExportDocx() {
    if (filled === 0) { toast.error('Fill the timetable first.'); return }
    try {
      await downloadClassTimetableDocx(artifact, fileBase('docx'), { attribution })
      toast.success('Timetable downloaded.')
    } catch (err) {
      console.error('[ClassTimetableStudio] docx export failed', err)
      toast.error('Could not build the Word file. Please try again.')
    }
  }
  async function onExportXlsx() {
    if (filled === 0) { toast.error('Fill the timetable first.'); return }
    try {
      await downloadClassTimetableXlsx(artifact, fileBase('xlsx'), { validation })
      toast.success('Excel workbook downloaded.')
    } catch (err) {
      console.error('[ClassTimetableStudio] xlsx export failed', err)
      toast.error('Could not build the Excel file. Please try again.')
    }
  }
  async function onExportPdf() {
    if (filled === 0) { toast.error('Fill the timetable first.'); return }
    try {
      await downloadClassTimetablePdf(artifact, { attribution, filename: fileBase('pdf') })
      toast.success('Timetable PDF downloaded.')
    } catch (err) {
      console.error('[ClassTimetableStudio] pdf export failed', err)
      toast.error(err?.message || 'Could not build the PDF. Please try again.')
    }
  }

  const overAllocated = allocated > capacity
  const subjectLabels = subjects.filter((s) => s.selected !== false || (Number(s.periodsPerWeek) || 0) > 0)
    .map((s) => s.label).filter(Boolean)
  const canUndo = historyRef.current.past.length > 0
  const canRedo = historyRef.current.future.length > 0
  const spareSlots = Math.max(0, capacity - allocated)
  const filteredDays = mobileDay === 'all' ? days : days.filter((d) => d === mobileDay)
  const visibleDays = filteredDays.length ? filteredDays : days
  const tints = useMemo(() => (gridModel ? subjectTintMap(gridModel) : {}), [gridModel])

  /* Palette pills for the workspace: each selected subject with its live
   * placed count against the weekly target. */
  const paletteSubjects = useMemo(() => subjects
    .filter((s) => s.selected !== false && (Number(s.periodsPerWeek) || 0) > 0 && s.label)
    .map((s) => {
      const report = validation.bySubject.find((r) => r.label === s.label)
      return { label: s.label, target: Number(s.periodsPerWeek) || 0, placed: report?.placed || 0 }
    }), [subjects, validation])

  const gradeLabelText = useMemo(() => {
    for (const stage of gradeStages) {
      const g = stage.grades.find((x) => x.value === header.grade)
      if (g) return g.label
    }
    return header.grade || 'Class'
  }, [gradeStages, header.grade])
  const classLabel = `${header.className || gradeLabelText}${header.year ? ` · ${header.year}` : ''} — Class timetable`

  /* Read-only preview of a recovered draft (G1): the recovered blocks are
   * rendered through the same artifact builder the live paper uses. */
  const recoveryPreviewArtifact = useMemo(() => {
    const p = draft.recovery?.payload
    if (!p || !showRecoveryPreview) return null
    try {
      const previewTiming = {
        ...DEFAULT_TIMING,
        breaks: DEFAULT_TIMING.breaks.map((b) => ({ ...b, enabled: true })),
        ...normalizeTimingBreaks(p.timing || {}),
      }
      const previewPeriods = buildPeriods(previewTiming)
      const previewDays = Array.isArray(p.days) && p.days.length ? p.days : DEFAULT_DAYS
      const previewBlocks = Array.isArray(p.blocks) && p.blocks.length
        ? p.blocks
        : slotsToBlocks(p.slots || {}, previewPeriods, previewDays)
      return buildTimetableArtifact({
        header: { ...(p.header || {}) },
        days: previewDays,
        periods: previewPeriods,
        blocks: previewBlocks,
        dayStructure: null,
        displayPreferences: p.displayPreferences || DEFAULT_DISPLAY_PREFERENCES,
        curriculumId: p.curriculumId || null,
        selectedOptions: p.selectedOptions || {},
        subjectAllocations: Array.isArray(p.subjects) ? p.subjects : [],
        calendarOverrides: [],
      })
    } catch (err) {
      console.error('[ClassTimetableStudio] draft preview failed', err)
      return null
    }
  }, [draft.recovery, showRecoveryPreview])

  /* ── validation panel (below the workspace grid) ── */
  // The curriculum check must NOT pass when an official learning area is absent
  // from the loaded allocation, even if every placed cell is internally sound.
  const effectiveStatus = allocationBlocked ? 'failed' : validation.status
  const statusStyle = effectiveStatus === 'passed'
    ? { borderColor: 'rgba(30,132,73,0.3)', background: 'rgba(30,132,73,0.06)' }
    : effectiveStatus === 'warning'
      ? { borderColor: 'rgba(212,160,23,0.35)', background: 'rgba(212,160,23,0.08)' }
      : { borderColor: 'rgba(190,49,68,0.35)', background: 'rgba(190,49,68,0.06)' }

  const validationPanel = filled > 0 ? (
    <div className="rounded-xl border p-3 text-xs space-y-1.5" style={statusStyle}>
      <div className="flex flex-wrap items-center gap-2">
        <span className="font-black uppercase tracking-wide"
          style={{ color: effectiveStatus === 'passed' ? '#1E8449' : effectiveStatus === 'warning' ? '#7a5800' : '#be3144' }}>
          {effectiveStatus === 'passed' ? 'Curriculum check passed'
            : effectiveStatus === 'warning' ? 'Curriculum check — warnings'
              : 'Curriculum check failed'}
        </span>
        {validation.customised && (
          <span className="rounded-full border px-2 py-0.5 text-[10px] font-black uppercase" style={{ borderColor: '#9a7000', color: 'var(--warning-fg)' }}>
            Customised from curriculum baseline
          </span>
        )}
      </div>

      {curriculum && (
        <div style={{ color: 'var(--zt-text-muted)' }}>
          {curriculum.curriculumName} · {curriculum.levelLabel} · {curriculum.periodMinutes}-min periods ·
          required {curriculum.totalPeriods} periods / {curriculum.contactLabel}
        </div>
      )}
      <div className="flex flex-wrap gap-x-4 gap-y-0.5 font-bold">
        <span>Curriculum periods: {validation.summary.curriculumPeriods} of {validation.summary.requiredPeriods}</span>
        <span>Contact time: {Math.floor(validation.summary.contactMinutes / 60)} h {validation.summary.contactMinutes % 60 ? `${validation.summary.contactMinutes % 60} min` : ''}{validation.summary.requiredContactMinutes ? ` of ${Math.floor(validation.summary.requiredContactMinutes / 60)} h` : ''}</span>
        <span>Valid double periods: {validation.summary.validDoubles}</span>
        <span>School-activity slots: {validation.summary.activityPeriods}</span>
        {validation.summary.emptySlots > 0 && <span>Empty slots: {validation.summary.emptySlots}</span>}
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-4">
        {validation.bySubject.filter((r) => r.selected || r.placed > 0).map((r) => (
          <div key={r.label} className="flex items-center justify-between gap-2">
            <span>{r.label}</span>
            <span className="font-black" style={{ color: r.status === 'ok' ? '#1E8449' : r.status === 'over' ? '#9a7000' : '#be3144' }}>
              {r.placed} of {r.target}
            </span>
          </div>
        ))}
      </div>
      {curriculum?.optionGroups?.map((g) => {
        const chosen = g.options.find((o) => o.id === g.selectedOptionId)
        const others = g.options.filter((o) => o.id !== g.selectedOptionId)
        return (
          <div key={g.id} style={{ color: 'var(--zt-text-muted)' }}>
            {chosen?.label} selected{others.length ? ` · ${others.map((o) => o.label).join(', ')} not selected` : ''}
          </div>
        )
      })}

      {allocationBlocked && readiness.missing.map((m) => (
        <div key={m.subjectId || m.label} className="font-bold text-rose-700">
          • {m.label} is missing from the curriculum allocation ({m.weeklyPeriods} periods) — reset the subjects from the curriculum.
        </div>
      ))}
      {validation.errors.map((m) => (
        <div key={m} className="font-bold text-rose-700">• {m}</div>
      ))}
      {validation.warnings.map((m) => (
        <div key={m} style={{ color: 'var(--warning-fg)' }}>• {m}</div>
      ))}
      {validation.notes.map((m) => (
        <div key={m} style={{ color: 'var(--zt-text-muted)' }}>• {m}</div>
      ))}
    </div>
  ) : null

  /* ── shared step / drawer content (built once, used by wizard AND
   * workspace drawers so an edit surface is never out of reach) ── */
  const schoolDayContent = (
    <WizardStepSchoolDay
      timing={timing}
      setT={setT}
      updateBreak={updateBreak}
      dayTemplate={dayTemplate}
      applyDayTemplate={applyDayTemplate}
      derivedPeriodMinutes={derivedPeriodMinutes}
      computedEnd={computedEnd}
      knockOffDelta={knockOffDelta}
      days={days}
      periods={periods}
      dayStructure={dayStructure}
      daySchedules={daySchedules}
      editingDayStructureFor={editingDayStructureFor}
      setEditingDayStructureFor={setEditingDayStructureFor}
      setDayType={setDayType}
      applyDayTemplateToDay={applyDayTemplateToDay}
      updateDayTiming={updateDayTiming}
      updateDayBreak={updateDayBreak}
      clearDaySchedule={clearDaySchedule}
      capacityFit={capacityFit}
      calendarOverrides={calendarOverrides}
      newOverrideDate={newOverrideDate}
      setNewOverrideDate={setNewOverrideDate}
      newOverrideDayType={newOverrideDayType}
      setNewOverrideDayType={setNewOverrideDayType}
      newOverrideReason={newOverrideReason}
      setNewOverrideReason={setNewOverrideReason}
      addCalendarOverride={addCalendarOverride}
      removeOverride={removeOverride}
    />
  )

  const subjectsPanel = (showAutoFill) => (
    <SubjectsPanel
      curriculum={curriculum}
      curriculumId={curriculumId}
      grade={header.grade}
      expectsAllocation={expectsAllocation}
      allocationBlocked={allocationBlocked}
      readiness={readiness}
      recoveredReview={recoveredReview}
      onResetSubjects={resetSubjectsFromCurriculum}
      onOptionSwitch={(groupId, optionId) => requestSwitch('option', optionId, groupId)}
      weekMode={weekMode}
      onWeekModeChange={changeWeekMode}
      dayCounts={dayCounts}
      setDayCounts={setDayCounts}
      days={days}
      timing={timing}
      activities={activities}
      setActivities={setActivities}
      subjects={subjects}
      validation={validation}
      capacity={capacity}
      allocated={allocated}
      overAllocated={overAllocated}
      spareSlots={spareSlots}
      onUpdateSubject={updateSubject}
      onAddSubject={addSubject}
      onRemoveSubject={requestRemoveSubject}
      showAutoFill={showAutoFill}
      onAutoFill={onAutoFill}
      onRequestClear={() => setConfirmClear(true)}
    />
  )

  const conflictsContent = (
    <TimetableConflictPanel
      conflicts={conflictResult.conflicts}
      coverage={conflictResult.coverage}
      status={siblingStatus}
      errorMessage={siblingError}
      lastCheckedAt={lastCheckedAt}
      offline={offline}
      staleSiblings={staleSiblings}
      currentTimetableId={generationId || ''}
      currentClassName={header.className || (header.grade ? `Grade ${String(header.grade).replace(/^G/i, '')}` : '')}
      days={days}
      selectedConflictId={selectedConflict?.conflictId || null}
      onRefresh={() => refreshConflicts()}
      onSelectConflict={onSelectConflict}
      onOpenTimetable={onOpenConflictingTimetable}
      onChangeTeacher={onEditBlockDetails}
      onChangeRoom={onEditBlockDetails}
      onMoveLesson={onMoveLessonAction}
    />
  )

  const previewContent = (
    <div className="space-y-3">
      {generationId && (
        <p className="text-xs" style={{ color: 'var(--zt-text-muted)' }}>
          In your library — <Link to={`/teacher/library/${generationId}`} className="font-bold underline">open the saved copy</Link>.
        </p>
      )}
      {filled > 0 ? (
        <ClassTimetableView timetable={artifact} />
      ) : (
        <div className="theme-border rounded-xl border border-dashed bg-white/60 py-14 text-center text-sm" style={{ color: 'var(--zt-text-muted)' }}>
          Auto-fill or place a few lessons — your printable timetable shows here.
        </div>
      )}
    </div>
  )

  /* Wizard CTA guards: never open the week on a state the generate path
   * would refuse anyway — the reason is spelled out on the button. */
  const wizardPrimaryDisabled = wizardStep === 0
    ? days.length === 0
    : wizardStep === 2 && entryMode === 'generate' && (allocationBlocked || days.length === 0)
  const wizardPrimaryDisabledReason = days.length === 0
    ? 'Pick at least one teaching day first.'
    : 'No complete curriculum allocation for this grade — see the diagnostic on this step, or switch to "Start blank".'

  const knockOffChip = knockOffDelta !== null && knockOffDelta > 0 ? (
    <Chip variant="amber" title={`The day runs to ${computedEnd} — ${knockOffDelta} min past your ${timing.endTime} knock-off. Adjust it on the School day step.`}>
      <AlertTriangle size={11} aria-hidden="true" /> {knockOffDelta} min past knock-off
    </Chip>
  ) : null

  return (
    <div className="studio-page">
      <SeoHelmet title="Class timetable" noIndex />
      <div className="w-full">
        {phase === 'wizard' ? (
          <>
            <StudioPageHeader
              eyebrow="Class administration"
              title="Class Timetable Studio"
              subtitle="Build your week from the curriculum — official subjects, weekly periods and double-period rules, ready to fine-tune, print or export."
              icon={Grid3x3}
            />
            <div className="mb-4">
              <DraftRecoveryPrompt {...draft} label="class timetable" onPreview={() => setShowRecoveryPreview(true)} />
            </div>
            <TimetableSetupWizard
              step={wizardStep}
              onStepChange={setWizardStep}
              entryMode={entryMode}
              onFinish={finishSetup}
              primaryDisabled={wizardPrimaryDisabled}
              primaryDisabledReason={wizardPrimaryDisabledReason}
            >
              {wizardStep === 0 && (
                <WizardStepClass
                  entryMode={entryMode}
                  onEntryModeChange={setEntryMode}
                  header={header}
                  setH={setH}
                  curriculumId={curriculumId}
                  requestSwitch={requestSwitch}
                  gradeStages={gradeStages}
                  days={days}
                  toggleDay={toggleDay}
                  onUploadExtracted={onUploadExtracted}
                />
              )}
              {wizardStep === 1 && schoolDayContent}
              {wizardStep === 2 && (
                <>
                  {knockOffChip && <div>{knockOffChip}</div>}
                  {subjectsPanel(false)}
                </>
              )}
            </TimetableSetupWizard>
          </>
        ) : (
          <>
            <div className="mb-3">
              <DraftRecoveryPrompt {...draft} label="class timetable" onPreview={() => setShowRecoveryPreview(true)} />
            </div>
            <TimetableWorkspace
              classLabel={classLabel}
              filled={filled}
              allocated={allocated}
              conflictsCount={conflictResult.conflicts.length}
              knockOffDelta={knockOffDelta}
              paletteSubjects={paletteSubjects}
              tints={tints}
              gridModel={gridModel}
              blocks={blocks}
              segments={segments}
              subjectLabels={subjectLabels}
              days={days}
              visibleDays={visibleDays}
              mobileDay={mobileDay}
              setMobileDay={setMobileDay}
              displayPreferences={displayPreferences}
              selectedConflict={selectedConflict}
              onSetCell={setCell}
              onJoinDown={onJoinDown}
              onSplit={onSplit}
              onToggleLock={onToggleLock}
              onEditDetails={setDetailsBlockId}
              undo={undo}
              redo={redo}
              canUndo={canUndo}
              canRedo={canRedo}
              onRequestClear={() => setConfirmClear(true)}
              draftStatus={{ status: draft.status, savedAt: draft.savedAt, online: draft.online }}
              onExportPdf={onExportPdf}
              onExportDocx={onExportDocx}
              onExportXlsx={onExportXlsx}
              onSaveDraft={() => onSaveToLibrary()}
              onFinalCheckAndSave={onFinalCheckAndSave}
              saving={saving}
              finalChecking={finalChecking}
              generationId={generationId}
              dirtySinceSave={dirtySinceSave}
              onEditSetup={() => { setPhase('wizard'); setWizardStep(0) }}
              validationPanel={validationPanel}
              schoolDayContent={schoolDayContent}
              subjectsContent={subjectsPanel(true)}
              layoutContent={<TimetableLayoutPanel displayPreferences={displayPreferences} setPref={setPref} />}
              conflictsContent={conflictsContent}
              previewContent={previewContent}
            />
          </>
        )}
      </div>

      {/* Read-only preview of a recovered draft (never auto-accepts it). */}
      <WorkspaceDrawer
        open={showRecoveryPreview}
        title="Draft preview (read-only)"
        wide
        onClose={() => setShowRecoveryPreview(false)}
      >
        {recoveryPreviewArtifact ? (
          <ClassTimetableView timetable={recoveryPreviewArtifact} />
        ) : (
          <p className="text-sm" style={{ color: 'var(--zt-text-muted)' }}>
            This draft could not be previewed — you can still choose Continue editing or Discard on the recovery strip.
          </p>
        )}
      </WorkspaceDrawer>

      <ConfirmDialog
        open={confirmClear}
        title="Clear the timetable grid?"
        message="Every placed lesson is removed. Your class details, days, periods and subjects are kept."
        confirmLabel="Clear grid"
        variant="danger"
        onConfirm={onClearGrid}
        onCancel={() => setConfirmClear(false)}
      />
      <ConfirmDialog
        open={pendingSwitch !== null}
        title={pendingSwitch?.kind === 'option' ? 'Change the optional subject?' : `Change ${pendingSwitch?.kind === 'curriculum' ? 'curriculum' : 'grade'} and reset the grid?`}
        message={pendingSwitch?.kind === 'option'
          ? 'The selected optional subject changes its weekly allocation. Lessons already on the grid are kept, but the timetable will need revalidation — the check below will flag anything that no longer complies.'
          : 'Switching reseeds the subject list from the curriculum and clears every placed lesson on the timetable. This can\'t be undone.'}
        confirmLabel={pendingSwitch?.kind === 'option' ? 'Change option' : 'Change and reset'}
        variant="danger"
        onConfirm={() => pendingSwitch && applySwitch(pendingSwitch)}
        onCancel={() => setPendingSwitch(null)}
      />
      <ConfirmDialog
        open={confirmRemoveDouble !== null}
        title="Remove the whole double period?"
        message="This is a double period — it clears as one block. To keep one of the two periods, cancel and use its Split button first."
        confirmLabel="Remove both periods"
        cancelLabel="Keep it"
        variant="danger"
        onConfirm={onRemoveWholeDouble}
        onCancel={() => setConfirmRemoveDouble(null)}
      />
      <ConfirmDialog
        open={confirmRemoveSubject !== null}
        title="Remove a compulsory subject?"
        message={`${subjects.find((s) => s.id === confirmRemoveSubject)?.label || 'This subject'} is a compulsory curriculum subject. Removing it means this timetable will no longer comply with the curriculum — the validation check will fail.`}
        confirmLabel="Remove anyway"
        variant="danger"
        onConfirm={() => { setSubjects((list) => list.filter((x) => x.id !== confirmRemoveSubject)); setConfirmRemoveSubject(null) }}
        onCancel={() => setConfirmRemoveSubject(null)}
      />
      <BlockDetailsModal
        open={detailsBlockId !== null}
        block={blocks.find((b) => b.blockId === detailsBlockId) || null}
        uid={uid}
        teacherDisplayName={header.teacherName || userProfile?.displayName || ''}
        assignments={assignments}
        onSave={onSaveBlockDetails}
        onClose={() => setDetailsBlockId(null)}
      />
    </div>
  )
}
