// Diagram fixup — closes the loop on AI-generated visual questions.
// Lists every figure a paper still needs — question stem/labelled figures AND
// per-option pictures on picture-based MCQs — suggests matching picture-bank
// figures (rankPicturesForBrief), and offers one-click AI generation from the
// brief (line art by default). Opens automatically when the automatic pass
// can't finish (hit the cap or errored); reachable any time from the AI panel.

import { useEffect, useMemo, useState } from 'react'
import { searchActivePictures, resolvePictureUrl } from '../../../utils/pictureBankService'
import { rankPicturesForBrief } from '../lib/diagramMatch'
import { generateDiagram } from '../../../utils/generateDiagram'
import { collectDiagramJobs, countDiagramJobs, autoGenerateDiagrams } from '../lib/autoGenerateDiagrams'

const AI_STYLES = [
  { provider: 'recraft', label: '🖋 Line art' },
  { provider: 'kie', label: '🎨 Colour' },
  { provider: 'openai', label: '📷 Photo' },
]

// Stable key for a job so React + busy state can tell stem from option briefs.
const jobKey = (job) => `${job.kind}-${job.sectionIndex}-${job.optionIndex ?? 'q'}`

export function countDiagramsNeeded(sections) {
  return countDiagramJobs(sections)
}

export default function DiagramFixupPanel({ sections, subject, questionNumbers, onAttach, onAttachOption, onClose }) {
  const [bank, setBank] = useState(null) // null = loading
  const [urls, setUrls] = useState({})
  const [busyKey, setBusyKey] = useState(null) // jobKey being generated
  const [batchRunning, setBatchRunning] = useState(false)
  const [errors, setErrors] = useState({}) // jobKey -> message
  const [provider, setProvider] = useState('recraft')

  const entries = useMemo(() => collectDiagramJobs(sections)
    .map((job) => ({ job, section: sections[job.sectionIndex] }))
    .filter(({ section }) => section?.kind === 'standalone'), [sections])

  useEffect(() => {
    let cancelled = false
    const load = async () => {
      const { rows } = await searchActivePictures({ subject: subject || 'all' })
      if (cancelled) return
      setBank(rows)
      for (const p of rows) {
        if (p.url) continue
        try {
          const u = await resolvePictureUrl(p)
          if (u && !cancelled) setUrls((m) => (m[p.id] ? m : { ...m, [p.id]: u }))
        } catch {
          // A single thumbnail failing to resolve shouldn't block the rest.
        }
      }
    }
    load().catch(() => {})
    return () => { cancelled = true }
  }, [subject])

  // Hand a finished image to the right place: question stem vs MCQ option.
  function attach(job, url) {
    if (job.kind === 'option') onAttachOption?.(job.sectionIndex, job.optionIndex, url)
    else onAttach?.(job.sectionIndex, url)
  }

  async function generateFor(job) {
    const key = jobKey(job)
    setBusyKey(key)
    setErrors((e) => ({ ...e, [key]: '' }))
    try {
      const { url } = await generateDiagram({ prompt: job.brief, provider })
      attach(job, url)
    } catch (err) {
      setErrors((e) => ({ ...e, [key]: err?.message || 'Generation failed.' }))
    } finally {
      setBusyKey(null)
    }
  }

  async function generateAllMissing() {
    setBatchRunning(true)
    try {
      const result = await autoGenerateDiagrams(sections, {
        provider,
        cap: entries.length,
        attachStem: (i, url) => onAttach?.(i, url),
        attachOption: (i, oi, url) => onAttachOption?.(i, oi, url),
        onProgress: ({ done }) => {
          // Mark the next pending job as the busy one for a little feedback.
          const pending = collectDiagramJobs(sections)[done]
          setBusyKey(pending ? jobKey(pending) : null)
        },
      })
      if (result.error) {
        // Surface the stop reason on the first still-pending job.
        const next = collectDiagramJobs(sections)[0]
        if (next) setErrors((e) => ({ ...e, [jobKey(next)]: result.error }))
      }
    } finally {
      setBusyKey(null)
      setBatchRunning(false)
    }
  }

  return (
    <div
      style={{
        position: 'fixed', inset: 0, zIndex: 92,
        background: 'rgba(14, 42, 50, 0.55)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        padding: 16,
      }}
      onClick={batchRunning ? undefined : onClose}
    >
      <div
        style={{
          background: 'var(--zt-card)', borderRadius: 16, width: 'min(760px, 100%)',
          maxHeight: '88vh', display: 'flex', flexDirection: 'column',
          padding: 16,
        }}
        onClick={(e) => e.stopPropagation()}
      >
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12 }}>
          <div>
            <h3 style={{ margin: 0, fontWeight: 900, fontSize: 18, color: 'var(--zt-text)' }}>
              🖼 Diagrams needed ({entries.length})
            </h3>
            <p style={{ margin: '4px 0 0', fontSize: 13, color: 'var(--zt-text-muted)' }}>
              These questions reference a figure. Attach a match from the
              picture bank, or generate one from the AI's description.
            </p>
          </div>
          <button type="button" onClick={onClose} disabled={batchRunning}
            style={{ fontSize: 22, lineHeight: 1, border: 'none', background: 'none', cursor: 'pointer' }}
            aria-label="Close">×</button>
        </div>

        {entries.length > 0 && (
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, margin: '10px 0' }}>
            <div style={{ display: 'flex', gap: 4 }}>
              {AI_STYLES.map((s) => (
                <button key={s.provider} type="button"
                  onClick={() => setProvider(s.provider)}
                  disabled={batchRunning || busyKey !== null}
                  style={{
                    padding: '5px 10px', borderRadius: 999, fontSize: 12, cursor: 'pointer',
                    border: `1.5px solid ${provider === s.provider ? '#d97757' : '#d9cfb8'}`,
                    background: provider === s.provider ? '#fff3e8' : '#fff', color: 'var(--zt-text)',
                  }}>
                  {s.label}
                </button>
              ))}
            </div>
            <div style={{ flex: 1 }} />
            <button type="button"
              onClick={generateAllMissing}
              disabled={batchRunning || busyKey !== null}
              style={{
                padding: '7px 14px', borderRadius: 10, fontSize: 13, fontWeight: 800,
                background: '#d97757', color: '#fff', border: 'none', cursor: 'pointer',
                opacity: batchRunning ? 0.6 : 1,
              }}>
              {batchRunning ? '✦ Generating…' : `✨ Generate all ${entries.length} with AI`}
            </button>
          </div>
        )}

        <div style={{ overflowY: 'auto', flex: 1, display: 'flex', flexDirection: 'column', gap: 10 }}>
          {entries.length === 0 && (
            <p style={{ fontSize: 14, color: 'var(--zt-text-muted)' }}>
              🎉 Every diagram question has its figure. Nothing to fix.
            </p>
          )}
          {entries.map(({ job, section }) => {
            const q = section.question
            const key = jobKey(job)
            const matches = bank ? rankPicturesForBrief(bank, job.brief) : []
            const busy = busyKey === key
            const label = job.kind === 'option'
              ? `Q${questionNumbers?.[q.localId] || '?'} · Option ${String.fromCharCode(65 + job.optionIndex)}`
              : `Q${questionNumbers?.[q.localId] || '?'} · ${String(q.text || '').slice(0, 90)}`
            return (
              <div key={key} style={{ border: '1px solid #d9cfb8', borderRadius: 12, padding: 12 }}>
                <div style={{ fontSize: 13, color: 'var(--zt-text-muted)' }}>
                  {label}
                </div>
                <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--zt-text)', margin: '4px 0 8px' }}>
                  {job.brief}
                </div>
                <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}>
                  {bank === null ? (
                    <span style={{ fontSize: 12, color: 'var(--zt-text-muted)' }}>Checking the picture bank…</span>
                  ) : matches.length > 0 ? (
                    matches.map((p) => {
                      const url = p.url || urls[p.id]
                      return (
                        <button key={p.id} type="button"
                          onClick={() => attach(job, url)}
                          disabled={!url || busy || batchRunning}
                          title={`Attach "${p.name}"`}
                          style={{
                            border: '1.5px solid #d9cfb8', borderRadius: 10, padding: 4,
                            background: 'var(--zt-card)', cursor: 'pointer', width: 92,
                          }}>
                          {url ? (
                            <img src={url} alt={p.name}
                              style={{ width: '100%', height: 60, objectFit: 'contain', background: 'var(--zt-surface)', borderRadius: 6 }} />
                          ) : (
                            <div style={{ width: '100%', height: 60, background: '#f1ede1', borderRadius: 6 }} />
                          )}
                          <div style={{ fontSize: 10, fontWeight: 700, color: 'var(--zt-text)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                            {p.name}
                          </div>
                        </button>
                      )
                    })
                  ) : (
                    <span style={{ fontSize: 12, color: 'var(--zt-text-muted)' }}>No bank match —</span>
                  )}
                  <button type="button"
                    onClick={() => generateFor(job)}
                    disabled={busy || batchRunning}
                    style={{
                      padding: '6px 12px', borderRadius: 10, fontSize: 13, fontWeight: 700,
                      border: '1.5px solid #d97757', background: '#fff3e8', color: 'var(--zt-text)',
                      cursor: 'pointer', opacity: busy ? 0.6 : 1,
                    }}>
                    {busy ? '✦ Generating…' : '✨ Generate it'}
                  </button>
                  {errors[key] && (
                    <span style={{ fontSize: 12, color: '#991b1b' }}>⚠️ {errors[key]}</span>
                  )}
                </div>
              </div>
            )
          })}
        </div>
      </div>
    </div>
  )
}
