// autoGenerateDiagrams — turns the figure briefs the AI left on a freshly
// created paper into real images, automatically. Walks the studio sections,
// collects every pending brief (stem/labelled question figures first, then
// per-option picture briefs), and generates them one at a time through the
// existing `generateDiagram` callable (Recraft B&W line art → Firebase
// Storage URL). Each finished image is handed back via attach callbacks so
// the studio can drop it onto the right question/option.
//
// Shared by two callers: the automatic pass after "Create paper with AI"
// (AssessmentStudio) and the manual "Generate all" button (DiagramFixupPanel).

import { generateDiagram } from '../../../utils/generateDiagram'

// Cap the automatic pass so one paper can't quietly burn a teacher's whole
// monthly diagram quota. Anything past the cap is left for the fixup panel.
export const DIAGRAM_AUTO_CAP = 15

/**
 * Collect pending image briefs from studio sections, in priority order:
 * question stem/labelled figures first, then per-option picture briefs.
 * A brief is "pending" when it has no imageUrl yet.
 *
 * @returns {Array<{kind:'stem'|'option', sectionIndex:number, optionIndex?:number, brief:string}>}
 */
export function collectDiagramJobs(sections) {
  const list = Array.isArray(sections) ? sections : []
  const stem = []
  const option = []
  list.forEach((section, sectionIndex) => {
    if (section?.kind !== 'standalone') return
    const q = section.question || {}
    if (q.diagramBrief && !q.imageUrl) {
      stem.push({ kind: 'stem', sectionIndex, brief: q.diagramBrief })
    }
    const media = Array.isArray(q.optionMedia) ? q.optionMedia : []
    media.forEach((slot, optionIndex) => {
      if (slot && slot.diagramBrief && !slot.imageUrl) {
        option.push({ kind: 'option', sectionIndex, optionIndex, brief: slot.diagramBrief })
      }
    })
  })
  return [...stem, ...option]
}

/** How many figures still need generating across the paper. */
export function countDiagramJobs(sections) {
  return collectDiagramJobs(sections).length
}

/**
 * Generate the pending figures sequentially and attach each as it lands.
 * Sequential on purpose: each image costs money and shares a rate limit, and
 * a hard failure (e.g. the monthly diagram meter is exhausted) stops the run
 * so errors don't cascade — whatever's left surfaces in the fixup panel.
 *
 * @param {Array} sections - studio sections snapshot to read briefs from
 * @param {object} opts
 * @param {string} [opts.provider='recraft']
 * @param {number} [opts.cap=DIAGRAM_AUTO_CAP]
 * @param {(sectionIndex:number, url:string)=>void} [opts.attachStem]
 * @param {(sectionIndex:number, optionIndex:number, url:string)=>void} [opts.attachOption]
 * @param {(p:{done:number,total:number})=>void} [opts.onProgress]
 * @param {()=>boolean} [opts.shouldCancel]
 * @returns {Promise<{done:number, total:number, remaining:number, error:string|null}>}
 */
export async function autoGenerateDiagrams(sections, {
  provider = 'recraft',
  cap = DIAGRAM_AUTO_CAP,
  attachStem,
  attachOption,
  onProgress,
  shouldCancel,
} = {}) {
  const all = collectDiagramJobs(sections)
  const jobs = all.slice(0, Math.max(0, cap))
  const total = jobs.length
  let done = 0
  let error = null

  for (const job of jobs) {
    if (typeof shouldCancel === 'function' && shouldCancel()) break
    try {
      const { url } = await generateDiagram({ prompt: job.brief, provider })
      if (job.kind === 'stem') {
        attachStem?.(job.sectionIndex, url)
      } else {
        attachOption?.(job.sectionIndex, job.optionIndex, url)
      }
      done += 1
      onProgress?.({ done, total })
    } catch (err) {
      error = err?.message || 'Diagram generation failed.'
      break
    }
  }

  return { done, total, remaining: all.length - done, error }
}
