/**
 * Static roster of ZedExams AI agents.
 *
 * The single source of truth for the /admin/agents UI. Server-side
 * dispatcher logic lives in functions/agents/ and reads this same shape
 * indirectly via the agentId field on agentJobs documents.
 *
 * Adding an agent? Update ORG.md too, then drop a .claude/agents/<id>.md
 * definition. See docs/AGENTS.md.
 */

export const DEPARTMENTS = {
  content: { id: 'content',  label: 'Content',         emoji: 'AC' },
  qaEng:   { id: 'qaEng',    label: 'QA / Engineering', emoji: 'QE' },
  revenue: { id: 'revenue',  label: 'Revenue',          emoji: 'RV' },
  support: { id: 'support',  label: 'Support',          emoji: 'SU' },
  growth:  { id: 'growth',   label: 'Growth',           emoji: 'GR' },
}

export const AGENTS = [
  {
    id: 'aria',
    name: 'Aria',
    role: 'Content Author',
    department: 'content',
    mission: 'Drafts CBC-aligned lesson plans, worksheets, schemes, rubrics, flashcards, and notes from a brief.',
    inputs: 'tool, grade, subject, topic, term, brief',
    outputs: 'agentJobs.output.draft (matches teacherTools schema)',
    wraps: 'functions/teacherTools/generate*.js runners',
    runtime: ['subagent', 'cloud-function'],
    invocation: 'Use the content-author subagent in Claude Code, or POST to agentJobs from a teacher brief form.',
  },
  {
    id: 'cala',
    name: 'Cala',
    role: 'CBC Alignment Officer',
    department: 'content',
    mission: 'Verifies a draft against the verified Zambian CBC knowledge base; flags drift, attaches citations.',
    inputs: 'Aria draft + grade, topic',
    outputs: '{ aligned, citations, gaps, drift }',
    wraps: 'functions/teacherTools/cbcKnowledge.js (resolveCbcContext)',
    runtime: ['subagent', 'cloud-function', 'github-action'],
    invocation: 'Use the cbc-alignment subagent after Aria produces a draft.',
  },
  {
    id: 'reva',
    name: 'Reva',
    role: 'Content Reviewer',
    department: 'content',
    mission: 'Pedagogy + tone + age-appropriateness review. Suggests edits, never auto-applies.',
    inputs: 'Aligned draft from Cala',
    outputs: '{ verdict, severity, edits, summary }',
    wraps: 'functions/aiService.js (callAnthropic)',
    runtime: ['subagent', 'cloud-function'],
    invocation: 'Use the content-reviewer subagent after Cala passes a draft.',
  },
  {
    id: 'qix',
    name: 'Qix',
    role: 'Question Bank Reviewer',
    department: 'content',
    mission: 'Reviews every captured question for the Central Question Bank — dedup, answer/curriculum/grade/quality checks — and gates it into the Master Bank.',
    inputs: 'A questionBank/{id} doc (status pending_review)',
    outputs: '{ reviewStatus, masterEligible, duplicateOf, aiReview }',
    wraps: 'functions/agents/questionReview.js + questionDedupCore.js (Haiku)',
    runtime: ['cloud-function'],
    invocation: 'Auto-runs in the background whenever a teacher creates/imports a question. Verdicts surface in /admin/question-review.',
  },
  {
    id: 'pubo',
    name: 'Pubo',
    role: 'Publisher',
    department: 'content',
    mission: 'Only agent allowed to publish. On admin approval, writes the final artifact to aiGenerations.',
    inputs: 'Approved agentJobs doc',
    outputs: 'New aiGenerations doc + publishedRefs',
    wraps: 'aiGenerations admin-SDK write path',
    runtime: ['subagent', 'cloud-function'],
    invocation: 'Auto-runs when an admin clicks Approve in /admin/agents.',
  },
  {
    id: 'gate',
    name: 'Gate',
    role: 'Content Auto-Publish Gate',
    department: 'content',
    mission: 'Auto-approves content jobs parked at awaiting_approval that clear a strict bar (Cala aligned + no gaps, Reva verdict approve), flipping them to approved so the existing dispatcher fires Pubo. OFF by default.',
    inputs: 'cron (every 30m) + content agentJobs at status awaiting_approval',
    outputs: 'status → approved on clean jobs (fires Pubo) + agentJobs rollup (output.gate)',
    wraps: 'functions/agents/runners/gate.js (deterministic, no LLM)',
    runtime: ['cloud-function'],
    invocation: 'Cron: every 30 minutes (contentAutoPublish). Only acts when agentControl/content.autoPublish === true. Reports to /admin/agents.',
  },
  {
    id: 'quill',
    name: 'Quill',
    role: 'QA Smoke Runner',
    department: 'qaEng',
    mission: 'Refreshes auth + authoring QA reports nightly; surfaces regressions as queued jobs.',
    inputs: 'cron schedule',
    outputs: '.auth-qa-report.json, .authoring-qa-report.json + summary job',
    wraps: 'scripts/check-file-integrity.mjs, scripts/test-question-schema.mjs, npm run smoke',
    runtime: ['subagent', 'cloud-function'],
    invocation: 'Cron: nightly 02:00 Africa/Lusaka. Manually: invoke the qa-smoke subagent.',
  },
  {
    id: 'rex',
    name: 'Rex',
    role: 'Code Reviewer',
    department: 'qaEng',
    mission: 'Reviews PR diffs for repo conventions, schema/rule changes, secrets, and Anthropic cost regressions.',
    inputs: 'PR diff (from gh pr diff)',
    outputs: 'PR review comment',
    wraps: 'Anthropic API via GitHub Action',
    runtime: ['subagent', 'github-action'],
    invocation: 'Auto on pull_request: opened, synchronize. Manually: invoke the code-reviewer subagent.',
  },
  {
    id: 'ledger',
    name: 'Ledger',
    role: 'Release Notes',
    department: 'qaEng',
    mission: 'On push to main, summarises merged PRs into a CHANGELOG PR.',
    inputs: 'git log since last changelog entry',
    outputs: 'Draft CHANGELOG PR',
    wraps: '@octokit/rest (already in functions/package.json)',
    runtime: ['subagent', 'github-action'],
    invocation: 'Auto on push to main. Manually: invoke the release-notes subagent.',
  },
  {
    id: 'mendi',
    name: 'Mendi',
    role: 'Bug Fixer',
    department: 'qaEng',
    mission: 'Reproduces a reported bug, fixes the root cause, adds a regression test, verifies lint/build/tests, and opens a draft PR. Never pushes to main.',
    inputs: 'A bug-labelled issue (or /mendi comment)',
    outputs: 'Draft PR with the fix + regression test',
    wraps: 'anthropics/claude-code-action via GitHub Action; .claude/agents/bug-fixer.md',
    runtime: ['subagent', 'github-action'],
    invocation: 'Auto when an issue gets the `bug` label, or a maintainer comments /mendi. Manually: invoke the bug-fixer subagent in Claude Code.',
  },
  {
    id: 'vigil',
    name: 'Vigil',
    role: 'Site Monitor',
    department: 'qaEng',
    mission: 'Every hour checks pages, Firebase, images, and quizzes; reports failures, suggests fixes, and escalates via email + a GitHub bug issue (which Mendi can pick up).',
    inputs: 'cron schedule (hourly)',
    outputs: 'agentJobs rollup (output.vigil) + alert email + bug issues',
    wraps: 'functions/agents/runners/monitor.js; Anthropic Haiku for fix suggestions',
    runtime: ['cloud-function'],
    invocation: 'Cron: every hour. Reports to /admin/agents; alerts OPS_ALERT_EMAILS and files bug issues on failure.',
  },
  {
    id: 'marshal',
    name: 'Marshal',
    role: 'Operations Supervisor',
    department: 'qaEng',
    mission: 'The watchdog-of-watchdogs. Every hour confirms each scheduled agent that writes a predictable rollup actually ran in its window, and surfaces stuck jobs, tripped breakers, and recent failures into a single company-health verdict.',
    inputs: 'cron (hourly) + agentJobs rollups, agentControl breakers, stuck jobs',
    outputs: 'company-health verdict for /admin/company + agentJobs rollup (output.marshal), filed as awaiting_approval when something is wrong',
    wraps: 'functions/agents/runners/marshal.js (deterministic, no LLM)',
    runtime: ['cloud-function'],
    invocation: 'Cron: every hour (hourlyAgentSupervisor). Surfaces to the /admin/company HQ and /admin/agents.',
  },
  {
    id: 'sift',
    name: 'Sift',
    role: 'Server Error Watch',
    department: 'qaEng',
    mission: 'Reads the last 75 minutes of ERROR-severity Cloud Logging entries for the project\'s Cloud Functions, groups them by function, and alerts when one is failing repeatedly. Exists because apiTrackVisit burned 80 errors in 2h — 100% of the server-side error volume — and nothing noticed: Sentry is frontend-only, and an OOM kill is a platform action no in-process reporter can observe. An unreadable log window is reported as unavailable, never as a healthy one.',
    inputs: 'cron (hourly) + Cloud Logging entries.list (ADC, roles/logging.viewer)',
    outputs: 'ops alert (email + webhook), de-duplicated per function+failure-class per 24h, plus an agentJobs rollup (output.sift)',
    wraps: 'functions/agents/runners/sift.js + siftCore.js (deterministic, no LLM)',
    runtime: ['cloud-function'],
    invocation: 'Cron: every hour (hourlyServerErrorWatch). Alerts OPS_ALERT_EMAILS + the ops webhook; reports to /admin/agents.',
  },
  {
    id: 'dawn',
    name: 'Dawn',
    role: 'Morning Briefing',
    department: 'qaEng',
    mission: 'On demand: reads the repo and researches the market, then writes a morning briefing — likely bugs to fix, polish to ship, competitive findings, and a ranked "Top 3 to do today" — and emails it.',
    inputs: 'admin "Run Dawn now" button (runDawnBriefing callable)',
    outputs: 'briefing email + agentJobs rollup (output.dawn)',
    wraps: 'functions/agents/runners/dawn.js (Claude Managed Agent via the Anthropic API)',
    runtime: ['cloud-function'],
    invocation: 'On-demand: "Run Dawn now" in /admin/agents (runDawnBriefing); a poller (deliverDawnBriefings, every 5m) delivers the finished briefing.',
  },
  {
    id: 'vex',
    name: 'Vex',
    role: 'Quiz Verifier',
    department: 'qaEng',
    mission: 'Synchronous pre-publish quality check on quizzes — answer accuracy, grade fit, clarity, grammar, options, and CBC alignment. Blocks publishing on critical errors, warns on minor issues.',
    inputs: 'quizId, questions[], meta { grade, subject, topic, subtopic, difficulty }',
    outputs: '{ verdict, overallScore, scores, summary, blockers[], warnings[] }',
    wraps: 'functions/agents/runners/vex.js (Anthropic Haiku, synchronous callable)',
    runtime: ['subagent', 'cloud-function'],
    invocation: 'Auto when an admin clicks Verify & publish in the quiz editor. Not queued — direct callable, no agentJobs writes.',
  },
  {
    id: 'till',
    name: 'Till',
    role: 'Revenue Reconciler',
    department: 'revenue',
    mission: 'Hourly: re-queries Lenco for stale pending payments and activates paid-but-stuck buyers a dropped webhook left behind. Idempotent — never double-grants.',
    inputs: 'cron (hourly) + payments stuck at status "pending"',
    outputs: 'agentJobs rollup (output.till) + activated subscriptions',
    wraps: 'functions/agents/runners/till.js; subscriptionActivation.js',
    runtime: ['cloud-function'],
    invocation: 'Cron: every hour (hourlyRevenueReconcile). Reports to /admin/agents.',
  },
  {
    id: 'echo',
    name: 'Echo',
    role: 'Support Triage',
    department: 'support',
    mission: 'Every 2h: sweeps new feedback + the public contact form, classifies and prioritises each, and drafts a reply. Drafts only — never sends.',
    inputs: 'cron (every 2h) + feedback/ and contactMessages/',
    outputs: 'echo* fields on each doc + agentJobs rollup (output.echo)',
    wraps: 'functions/agents/runners/echo.js; Anthropic Haiku for reply drafts',
    runtime: ['cloud-function'],
    invocation: 'Cron: every 2 hours (supportTriage). Reports to /admin/agents.',
  },
  {
    id: 'bonga',
    name: 'Bonga',
    role: 'WhatsApp Reply Agent',
    department: 'support',
    mission: 'The one agent that talks to people directly. Answers inbound WhatsApp messages on the ZedExams number — classifying each as study, support, or sales, drafting a reply, and auto-sending it inside WhatsApp\'s 24-hour customer-service window.',
    inputs: 'inbound WhatsApp messages (Meta webhook)',
    outputs: 'auto-sent WhatsApp reply + whatsappConversations/{phone} log',
    wraps: 'functions/index.js apiWhatsAppWebhook + functions/agents/runners/bonga.js (Anthropic Haiku)',
    runtime: ['cloud-function'],
    invocation: 'Auto on every inbound WhatsApp message; auto-sends within the 24h window. Kill-switch: agentControl/bonga.paused.',
  },
  {
    id: 'compass',
    name: 'Compass',
    role: 'Product Signal',
    department: 'content',
    mission: 'Weekly: aggregates recent quiz and exam attempts into a ranked "what to build next" backlog — grade/subject areas with demand but weak mastery.',
    inputs: 'cron (Mondays) + results/ and exam_attempts/',
    outputs: 'agentJobs rollup (output.compass) — ranked build backlog',
    wraps: 'functions/agents/runners/compass.js (deterministic, no LLM)',
    runtime: ['cloud-function'],
    invocation: 'Cron: Mondays 06:00 (weeklyProductSignal). Reports to /admin/agents.',
  },
  {
    id: 'anchor',
    name: 'Anchor',
    role: 'Retention Scout',
    department: 'growth',
    mission: 'Weekly: surfaces learners who were engaged then went quiet 14–45 days ago, ranked by win-back value, with a drafted nudge. Read-only — never messages learners.',
    inputs: 'cron (Mondays) + learnerStats/',
    outputs: 'agentJobs rollup (output.anchor) — at-risk cohort + draft nudges',
    wraps: 'functions/agents/runners/anchor.js (deterministic, no LLM)',
    runtime: ['cloud-function'],
    invocation: 'Cron: Mondays 07:00 (weeklyRetentionScan). Reports to /admin/agents.',
  },
]

export const AGENTS_BY_ID = Object.fromEntries(AGENTS.map(a => [a.id, a]))

export const JOB_STATUSES = [
  'queued',
  'running',
  'awaiting_approval',
  'approved',
  'rejected',
  'done',
  'failed',
]

export function agentsForDepartment(deptId) {
  return AGENTS.filter(a => a.department === deptId)
}
