/**
 * classes — Firestore data access for the teacher classroom roster
 * (audit A10).
 *
 * Reads + teacher-side writes are direct; the join-by-code flow goes
 * through a Cloud Function (`joinClassByCode`) so a learner can never
 * mutate someone else's class doc directly. Invite-code generation
 * also lives server-side so we can guarantee uniqueness across active
 * codes.
 */

import {
  addDoc,
  arrayRemove,
  collection,
  deleteDoc,
  doc,
  getDoc,
  getDocs,
  limit as fsLimit,
  orderBy,
  query,
  serverTimestamp,
  updateDoc,
  where,
} from 'firebase/firestore'
import { getFunctions, httpsCallable } from 'firebase/functions'
import app, { db } from '../firebase/config'

const COLLECTION = 'classes'
const fns = getFunctions(app, 'us-central1')

const generateClassInviteCallable = httpsCallable(fns, 'generateClassInvite')
const joinClassByCodeCallable = httpsCallable(fns, 'joinClassByCode')
const removeLearnerFromClassCallable = httpsCallable(fns, 'removeLearnerFromClass')
const leaveClassCallable = httpsCallable(fns, 'leaveClass')

/** List the classes a given teacher owns (active first, newest first). */
export async function listTeacherClasses(teacherUid, { includeArchived = false, limit = 100 } = {}) {
  const filters = [where('teacherUid', '==', teacherUid)]
  if (!includeArchived) filters.push(where('active', '==', true))
  const q = query(
    collection(db, COLLECTION),
    ...filters,
    orderBy('updatedAt', 'desc'),
    fsLimit(limit),
  )
  const snap = await getDocs(q)
  return snap.docs.map((d) => ({ id: d.id, ...d.data() }))
}

/** List the active classes a learner belongs to. */
export async function listLearnerClasses(learnerUid, { limit = 50 } = {}) {
  const q = query(
    collection(db, COLLECTION),
    where('learners', 'array-contains', learnerUid),
    where('active', '==', true),
    orderBy('updatedAt', 'desc'),
    fsLimit(limit),
  )
  const snap = await getDocs(q)
  return snap.docs.map((d) => ({ id: d.id, ...d.data() }))
}

export async function getClass(classId) {
  const snap = await getDoc(doc(db, COLLECTION, classId))
  return snap.exists() ? { id: snap.id, ...snap.data() } : null
}

/**
 * Teacher-side create. The teacherUid + empty learners[] are required
 * by Firestore rules. The invite code is generated by the Cloud
 * Function — clients never mint codes themselves.
 */
export async function createClass({ teacherUid, fields }) {
  const now = serverTimestamp()
  const ref = await addDoc(collection(db, COLLECTION), {
    name: fields.name,
    description: fields.description ?? null,
    grade: fields.grade,
    subject: fields.subject ?? null,
    school: fields.school ?? null,
    teacherUid,
    learners: [],
    active: true,
    createdAt: now,
    updatedAt: now,
  })
  return ref.id
}

export async function updateClass(classId, fields) {
  await updateDoc(doc(db, COLLECTION, classId), {
    ...fields,
    updatedAt: serverTimestamp(),
  })
}

/**
 * Soft-delete a class. The class doc is preserved (so historical
 * results / analytics keep their references) but `active: false`
 * removes it from learner lookups.
 */
export async function archiveClass(classId) {
  await updateClass(classId, { active: false })
}

export async function unarchiveClass(classId) {
  await updateClass(classId, { active: true })
}

export async function hardDeleteClass(classId) {
  await deleteDoc(doc(db, COLLECTION, classId))
}

/**
 * Server-issued invite code generation. Returns
 * `{ inviteCode, classId, expiresAt }`. The Cloud Function:
 *   - rotates the previous code (if any) so a single class never has
 *     two valid join codes simultaneously
 *   - guarantees code uniqueness across active classInvites/* docs
 *   - sets a 30-day TTL
 */
export async function generateClassInvite(classId) {
  const result = await generateClassInviteCallable({ classId })
  return result.data
}

/**
 * Learner submits an invite code. The Cloud Function:
 *   - resolves classInvites/{code} → classId (or rejects)
 *   - checks the class is active and under the 200-learner cap
 *   - adds the learner uid to classes/{classId}.learners via admin SDK
 * Returns `{ classId, name, teacherDisplayName }` on success.
 */
export async function joinClassByCode(code) {
  const result = await joinClassByCodeCallable({ code })
  return result.data
}

/**
 * Teacher removes a learner from a class. The Cloud Function checks
 * the caller is the class owner before applying the change — keeps
 * the rule simple (teachers can update their own class) without
 * letting them silently steal members from another teacher's class
 * via a doctored payload.
 */
export async function removeLearnerFromClass({ classId, learnerUid }) {
  const result = await removeLearnerFromClassCallable({ classId, learnerUid })
  return result.data
}

/**
 * Teacher self-removes a learner via direct write. This bypasses the
 * Cloud Function for cases where speed matters (large rosters) and
 * the rules already gate the call to the class owner. Falls back to
 * the callable on any rule-rejection.
 */
export async function removeLearnerFromClassFallback({ classId, learnerUid }) {
  try {
    await updateDoc(doc(db, COLLECTION, classId), {
      learners: arrayRemove(learnerUid),
      updatedAt: serverTimestamp(),
    })
  } catch (err) {
    console.warn('[classes] direct remove failed; trying callable', err)
    await removeLearnerFromClass({ classId, learnerUid })
  }
}

/**
 * Learner self-removes from a class. Goes through the leaveClass
 * Cloud Function because Firestore rules block any non-teacher
 * update of classes/{classId}. Returns { ok: true } on success.
 */
export async function leaveClass(classId) {
  const result = await leaveClassCallable({ classId })
  return result.data
}
