/**
 * Export a class timetable as a Word (.docx) file in landscape — the grid
 * teachers print and pin to the classroom wall. Mirrors
 * src/components/teacher/views/ClassTimetableView.jsx: a title block, then a
 * TIME × days grid with break/lunch rows spanning every day column.
 */

import { saveBlob } from './saveBlob.js'
import { sanitizeXmlText } from './xmlText.js'
import {
  AlignmentType,
  BorderStyle,
  Document,
  PageOrientation,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from 'docx'
import { attributionSection } from './docxAttribution.js'

const CELL_BORDER = {
  top:    { style: BorderStyle.SINGLE, size: 4, color: '000000' },
  bottom: { style: BorderStyle.SINGLE, size: 4, color: '000000' },
  left:   { style: BorderStyle.SINGLE, size: 4, color: '000000' },
  right:  { style: BorderStyle.SINGLE, size: 4, color: '000000' },
}

const text = (str, opts = {}) => new TextRun({ text: sanitizeXmlText(str), size: 18, ...opts })
const centred = (runs) => new Paragraph({
  children: Array.isArray(runs) ? runs : [runs],
  alignment: AlignmentType.CENTER,
  spacing: { after: 20 },
})

function cell(content, { bold = false, shade, colSpan, widthPct } = {}) {
  const runs = Array.isArray(content) ? content : [text(content, { bold })]
  return new TableCell({
    children: [centred(runs)],
    borders: CELL_BORDER,
    ...(shade ? { shading: { fill: shade } } : {}),
    ...(colSpan ? { columnSpan: colSpan } : {}),
    ...(widthPct ? { width: { size: widthPct, type: WidthType.PERCENTAGE } } : {}),
    verticalAlign: 'center',
  })
}

function titleBlock(h) {
  const gradeLabel = String(h.grade || '').replace(/^G/i, '')
  const lines = []
  if (h.school) {
    lines.push(new Paragraph({
      children: [text(h.school, { bold: true, size: 24 })],
      alignment: AlignmentType.CENTER, spacing: { after: 40 },
    }))
  }
  lines.push(new Paragraph({
    children: [text('CLASS TIMETABLE', { bold: true, size: 28 })],
    alignment: AlignmentType.CENTER, spacing: { after: 40 },
  }))
  const meta = [
    h.className && String(h.className).trim(),
    gradeLabel && `Grade ${gradeLabel}`,
    h.term && `Term ${h.term}`,
    h.year && String(h.year),
  ].filter(Boolean).join('   ·   ')
  if (meta) {
    lines.push(new Paragraph({
      children: [text(meta, { bold: true, size: 20 })],
      alignment: AlignmentType.CENTER, spacing: { after: 40 },
    }))
  }
  if (h.teacherName) {
    lines.push(new Paragraph({
      children: [text(`Class teacher: ${h.teacherName}`, { size: 18 })],
      alignment: AlignmentType.CENTER, spacing: { after: 160 },
    }))
  } else {
    lines.push(new Paragraph({ children: [text(' ', { size: 8 })], spacing: { after: 120 } }))
  }
  return lines
}

export function buildClassTimetableDocument(timetable, opts = {}) {
  const h = timetable.header || {}
  const days = Array.isArray(timetable.days) ? timetable.days : []
  const periods = Array.isArray(timetable.periods) ? timetable.periods : []
  const slots = timetable.slots || {}

  const dayWidth = days.length ? Math.floor(86 / days.length) : 86
  const headerRow = new TableRow({
    tableHeader: true,
    children: [
      cell('TIME', { bold: true, shade: 'E2E8F0', widthPct: 14 }),
      ...days.map((d) => cell(d.toUpperCase(), { bold: true, shade: 'E2E8F0', widthPct: dayWidth })),
    ],
  })

  const bodyRows = periods.map((p) => {
    if (p.kind === 'break') {
      return new TableRow({
        children: [
          cell(`${p.start}–${p.end}`, { bold: true }),
          cell(p.label, { bold: true, shade: 'F1ECE0', colSpan: days.length || 1 }),
        ],
      })
    }
    return new TableRow({
      children: [
        cell([
          text(`${p.start}–${p.end}`, { bold: true }),
        ], { bold: true }),
        ...days.map((d) => cell(slots?.[p.id]?.[d] || '', {})),
      ],
    })
  })

  const table = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [headerRow, ...bodyRows],
  })

  return new Document({
    creator: 'zedexams.com',
    title: sanitizeXmlText(`Class Timetable — ${h.className || h.grade || ''}`.trim()),
    description: 'Generated by ZedExams Teacher Tools',
    styles: { default: { document: { run: { font: 'Calibri', size: 20 } } } },
    sections: [{
      ...attributionSection(opts),
      properties: { page: { size: { orientation: PageOrientation.LANDSCAPE } } },
      children: [...titleBlock(h), table],
    }],
  })
}

export async function downloadClassTimetableDocx(timetable, filename = 'class-timetable.docx', opts = {}) {
  const doc = buildClassTimetableDocument(timetable, opts)
  const blob = await Packer.toBlob(doc)
  await saveBlob(blob, filename)
}
