/**
 * Export flashcards as a printable .docx — 2-column grid, cut-out-ready,
 * with the back of each card on the following line for easy folding.
 */

import {
  AlignmentType,
  BorderStyle,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from 'docx'

const DASH_BORDER = {
  top:    { style: BorderStyle.DASHED, size: 6, color: '9ca3af' },
  bottom: { style: BorderStyle.DASHED, size: 6, color: '9ca3af' },
  left:   { style: BorderStyle.DASHED, size: 6, color: '9ca3af' },
  right:  { style: BorderStyle.DASHED, size: 6, color: '9ca3af' },
}

function text(str, opts = {}) {
  return new TextRun({ text: str == null ? '' : String(str), ...opts })
}

function para(runs, opts = {}) {
  return new Paragraph({
    children: Array.isArray(runs) ? runs : [runs],
    spacing: { after: 80 },
    ...opts,
  })
}

function cardCell(content, {isFront}) {
  const children = [
    para(text(isFront ? 'QUESTION' : 'ANSWER', {
      bold: true, size: 16,
      color: isFront ? 'f59e0b' : '059669',
    })),
    para(text(content.front || '', { size: 22, bold: isFront })),
  ]
  if (!isFront) {
    children[1] = para(text(content.back || '', { size: 20 }))
    if (content.example) {
      children.push(para(text(`Example: ${content.example}`, {
        size: 18, italics: true, color: '6b7280',
      })))
    }
    if (content.hint) {
      children.push(para(text(`💡 ${content.hint}`, {
        size: 18, italics: true, color: '6b7280',
      })))
    }
  }
  return new TableCell({
    children,
    width: { size: 50, type: WidthType.PERCENTAGE },
    borders: DASH_BORDER,
    margins: { top: 200, bottom: 200, left: 200, right: 200 },
  })
}

export function buildFlashcardsDocument(flashcards, {mode = 'cutout'} = {}) {
  const cards = flashcards.cards || []
  const children = []

  children.push(new Paragraph({
    children: [text(flashcards.header?.title || 'Flashcards', {
      bold: true, size: 32,
    })],
    heading: HeadingLevel.HEADING_1,
    alignment: AlignmentType.CENTER,
    spacing: { after: 160 },
  }))
  children.push(new Paragraph({
    children: [text(
      `${flashcards.header?.grade || ''} · ${flashcards.header?.subject || ''} · ${flashcards.header?.topic || ''}`,
      { size: 20, color: '6b7280' },
    )],
    alignment: AlignmentType.CENTER,
    spacing: { after: 200 },
  }))
  children.push(new Paragraph({
    children: [text(
      mode === 'cutout' ?
        'Print double-sided. Cut along the dashed lines and fold each pair to make flashcards.' :
        'Pupil cards — print and fold.',
      { size: 18, italics: true, color: '6b7280' },
    )],
    alignment: AlignmentType.CENTER,
    spacing: { after: 300 },
  }))

  // Group cards in pairs; each row = [card1 front, card2 front] then a
  // following row with the matching backs. This lets a teacher print
  // duplex and cut cleanly.
  for (let i = 0; i < cards.length; i += 2) {
    const a = cards[i]
    const b = cards[i + 1] || null

    // Front row
    const frontRow = new TableRow({
      children: [
        cardCell(a, {isFront: true}),
        b ?
          cardCell(b, {isFront: true}) :
          new TableCell({
            children: [para(text('', {size: 22}))],
            width: {size: 50, type: WidthType.PERCENTAGE},
            borders: DASH_BORDER,
          }),
      ],
    })
    // Back row
    const backRow = new TableRow({
      children: [
        cardCell(a, {isFront: false}),
        b ?
          cardCell(b, {isFront: false}) :
          new TableCell({
            children: [para(text('', {size: 22}))],
            width: {size: 50, type: WidthType.PERCENTAGE},
            borders: DASH_BORDER,
          }),
      ],
    })

    children.push(new Table({
      width: {size: 100, type: WidthType.PERCENTAGE},
      rows: [frontRow, backRow],
    }))
    children.push(new Paragraph({
      children: [text(' ', {size: 18})],
      spacing: {after: 160},
    }))
  }

  return new Document({
    creator: 'zedexams.com',
    title: flashcards.header?.title || 'Flashcards',
    description: 'Flashcards generated by ZedExams Teacher Tools',
    styles: {
      default: { document: { run: { font: 'Calibri', size: 20 } } },
    },
    sections: [{ children }],
  })
}

export async function downloadFlashcardsDocx(flashcards, filename = 'flashcards.docx', opts = {}) {
  const doc = buildFlashcardsDocument(flashcards, opts)
  const blob = await Packer.toBlob(doc)
  try {
    const { saveAs } = await import('file-saver')
    saveAs(blob, filename)
    return
  } catch { /* fall through */ }
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
