export const grade4ModuleSeedQuizzes = [
  {
    id: 'grade4-english-term2-module-quiz',
    meta: {
      title: 'Grade 4 English - Term 2 Module Quiz',
      subject: 'English',
      grade: '4',
      term: '2',
      year: '2026',
      type: 'quiz',
      quizType: 'practice',
      duration: 20,
      totalMarks: 8,
      isPublished: true,
      questionCount: 8,
      topic: 'Calendar, prepositions, fiction and non-fiction, dictionary, verbs',
    },
    questions: [
      {
        text: 'What do we call the day after today?',
        options: ['Yesterday', 'Tomorrow', 'Weekend', 'Month'],
        correctAnswer: 1,
        topic: 'Calendar Vocabulary',
        marks: 1,
      },
      {
        text: 'How many months are in one year?',
        options: ['10', '11', '12', '13'],
        correctAnswer: 2,
        topic: 'Calendar Vocabulary',
        marks: 1,
      },
      {
        text: 'Choose the preposition in this sentence: The ball is under the chair.',
        options: ['ball', 'is', 'under', 'chair'],
        correctAnswer: 2,
        topic: 'Prepositions',
        marks: 1,
      },
      {
        text: 'Which sentence uses a preposition of place correctly?',
        options: ['The cat jumped happily.', 'The book is on the table.', 'She sings loudly.', 'We played yesterday.'],
        correctAnswer: 1,
        topic: 'Prepositions',
        marks: 1,
      },
      {
        text: 'A story made from imagination is called ________.',
        options: ['non-fiction', 'fiction', 'dictionary', 'summary'],
        correctAnswer: 1,
        topic: 'Fiction and Non-Fiction',
        marks: 1,
      },
      {
        text: 'What do we use a dictionary for?',
        options: ['To draw pictures', 'To find meanings and spellings of words', 'To measure time', 'To count money'],
        correctAnswer: 1,
        topic: 'The Dictionary',
        marks: 1,
      },
      {
        text: 'Which word is an action verb?',
        options: ['happy', 'jump', 'blue', 'slow'],
        correctAnswer: 1,
        topic: 'Action Verbs',
        marks: 1,
      },
      {
        text: 'Choose the linking verb in this sentence: The soup is hot.',
        options: ['soup', 'is', 'hot', 'the'],
        correctAnswer: 1,
        topic: 'Linking Verbs',
        marks: 1,
      },
    ],
  },
  {
    id: 'grade4-mathematics-module-quiz',
    meta: {
      title: 'Grade 4 Mathematics - Module Quiz',
      subject: 'Mathematics',
      grade: '4',
      term: '1',
      year: '2026',
      type: 'quiz',
      quizType: 'practice',
      duration: 20,
      totalMarks: 8,
      isPublished: true,
      questionCount: 8,
      topic: 'Sets, factors and multiples, fractions, money, angles, shapes',
    },
    questions: [
      {
        text: 'A collection of well-defined objects is called a ________.',
        options: ['fraction', 'set', 'shape', 'angle'],
        correctAnswer: 1,
        topic: 'Operations on Sets',
        marks: 1,
      },
      {
        text: 'Which symbol is used for intersection of sets?',
        options: ['+', 'x', '∩', '='],
        correctAnswer: 2,
        topic: 'Operations on Sets',
        marks: 1,
      },
      {
        text: 'Which of the following is a factor of 12?',
        options: ['5', '7', '3', '11'],
        correctAnswer: 2,
        topic: 'Factors and Multiples',
        marks: 1,
      },
      {
        text: 'Which list shows the first three multiples of 5?',
        options: ['5, 10, 15', '5, 6, 7', '10, 12, 14', '4, 8, 12'],
        correctAnswer: 0,
        topic: 'Factors and Multiples',
        marks: 1,
      },
      {
        text: 'What fraction shows one part out of four equal parts?',
        options: ['1/2', '1/3', '1/4', '4/1'],
        correctAnswer: 2,
        topic: 'Common Fractions',
        marks: 1,
      },
      {
        text: 'Write three-tenths as a decimal.',
        options: ['3.0', '0.3', '0.03', '3/10'],
        correctAnswer: 1,
        topic: 'Decimal Fractions',
        marks: 1,
      },
      {
        text: 'A learner buys a ruler for K4 and a book for K9. How much is spent altogether?',
        options: ['K12', 'K13', 'K14', 'K15'],
        correctAnswer: 1,
        topic: 'Money',
        marks: 1,
      },
      {
        text: 'Which angle is smaller than a right angle?',
        options: ['obtuse angle', 'acute angle', 'straight angle', 'reflex angle'],
        correctAnswer: 1,
        topic: 'Types of Angles',
        marks: 1,
      },
    ],
  },
  {
    id: 'grade4-integrated-science-module-quiz',
    meta: {
      title: 'Grade 4 Integrated Science - Module Quiz',
      subject: 'Integrated Science',
      grade: '4',
      term: '1',
      year: '2026',
      type: 'quiz',
      quizType: 'practice',
      duration: 20,
      totalMarks: 8,
      isPublished: true,
      questionCount: 8,
      topic: 'Respiratory system, food groups, healthy diets, environment, pests, soil',
    },
    questions: [
      {
        text: 'Which gas do we breathe in?',
        options: ['Carbon dioxide', 'Smoke', 'Oxygen', 'Nitrogen'],
        correctAnswer: 2,
        topic: 'Respiratory System',
        marks: 1,
      },
      {
        text: 'Which gas do we breathe out?',
        options: ['Oxygen', 'Carbon dioxide', 'Steam', 'Helium'],
        correctAnswer: 1,
        topic: 'Respiratory System',
        marks: 1,
      },
      {
        text: 'Which nutrient gives the body energy?',
        options: ['Carbohydrates', 'Proteins', 'Vitamins', 'Minerals'],
        correctAnswer: 0,
        topic: 'Classification of Food',
        marks: 1,
      },
      {
        text: 'Proteins help the body to ________.',
        options: ['stay cold', 'grow and repair itself', 'make noise', 'float in water'],
        correctAnswer: 1,
        topic: 'Healthy Diets',
        marks: 1,
      },
      {
        text: 'Which is a good way to prevent airborne diseases?',
        options: ['Closing all windows always', 'Sharing cups with sick people', 'Covering the mouth when coughing', 'Playing in dust'],
        correctAnswer: 2,
        topic: 'Air, Water, Foodborne Diseases',
        marks: 1,
      },
      {
        text: 'Environmental management means ________.',
        options: ['making the environment dirty', 'using and protecting resources responsibly', 'cutting all trees', 'burning all waste anywhere'],
        correctAnswer: 1,
        topic: 'Environmental Management',
        marks: 1,
      },
      {
        text: 'A pest is an organism that ________.',
        options: ['helps crops grow faster', 'damages crops or stored food', 'makes rain fall', 'changes sand into clay'],
        correctAnswer: 1,
        topic: 'Pests and Parasites',
        marks: 1,
      },
      {
        text: 'Which type of soil is best for farming?',
        options: ['Sand', 'Clay', 'Loam', 'Rock'],
        correctAnswer: 2,
        topic: 'Soil Structure',
        marks: 1,
      },
    ],
  },
  {
    id: 'grade4-social-studies-module-quiz',
    meta: {
      title: 'Grade 4 Social Studies - Module Quiz',
      subject: 'Social Studies',
      grade: '4',
      term: '1',
      year: '2026',
      type: 'quiz',
      quizType: 'practice',
      duration: 20,
      totalMarks: 8,
      isPublished: true,
      questionCount: 8,
      topic: 'Family, human rights, maps and directions, transport, weather and climate',
    },
    questions: [
      {
        text: 'A small family made up of parents and children is called a ________ family.',
        options: ['extended', 'community', 'nuclear', 'guardian'],
        correctAnswer: 2,
        topic: 'Members of the Family',
        marks: 1,
      },
      {
        text: 'Which of the following is a child right?',
        options: ['Right to education', 'Right to be rude', 'Right to fight', 'Right to damage property'],
        correctAnswer: 0,
        topic: 'Human Rights',
        marks: 1,
      },
      {
        text: 'Which list shows the four cardinal points?',
        options: ['North, South, East, West', 'Left, Right, Up, Down', 'Near, Far, Front, Back', 'Hot, Cold, Wet, Dry'],
        correctAnswer: 0,
        topic: 'Location of Places in the Community',
        marks: 1,
      },
      {
        text: 'What do we use a map for?',
        options: ['To cook food', 'To show location of places', 'To wash clothes', 'To count money'],
        correctAnswer: 1,
        topic: 'Location of Places in the Community',
        marks: 1,
      },
      {
        text: 'Which is one way of learning about the past?',
        options: ['Playing football', 'Listening to stories from elders', 'Sleeping in class', 'Buying sweets'],
        correctAnswer: 1,
        topic: 'Ways of Learning About the Past',
        marks: 1,
      },
      {
        text: 'Which of the following is a form of transport?',
        options: ['Radio', 'Bicycle', 'Television', 'Letter'],
        correctAnswer: 1,
        topic: 'Forms of Transport and Communication Services',
        marks: 1,
      },
      {
        text: 'Which of the following is a form of communication?',
        options: ['Bus', 'Scotch cart', 'Phone call', 'Wheelbarrow'],
        correctAnswer: 2,
        topic: 'Forms of Transport and Communication Services',
        marks: 1,
      },
      {
        text: 'Weather is the ________ condition of the atmosphere.',
        options: ['day-to-day', 'hundred-year', 'permanent', 'invisible'],
        correctAnswer: 0,
        topic: 'Elements of Weather and Climate',
        marks: 1,
      },
    ],
  },
  {
    id: 'grade4-technology-studies-module-quiz',
    meta: {
      title: 'Grade 4 Technology Studies - Module Quiz',
      subject: 'Technology Studies',
      grade: '4',
      term: '1',
      year: '2026',
      type: 'quiz',
      quizType: 'practice',
      duration: 20,
      totalMarks: 8,
      isPublished: true,
      questionCount: 8,
      topic: 'Safety, word processing, tools and equipment, graphic communication',
    },
    questions: [
      {
        text: 'Safety means taking care to prevent ________.',
        options: ['drawing', 'accidents and injuries', 'singing', 'measuring'],
        correctAnswer: 1,
        topic: 'Personal Safety',
        marks: 1,
      },
      {
        text: 'What does PPE stand for?',
        options: ['Personal Protective Equipment', 'Public Practice Exercise', 'Paper Pencil Eraser', 'Primary Practical Education'],
        correctAnswer: 0,
        topic: 'Personal Safety',
        marks: 1,
      },
      {
        text: 'Which of these is personal protective equipment?',
        options: ['Helmet', 'Plate', 'Notebook', 'Cup'],
        correctAnswer: 0,
        topic: 'Personal Safety',
        marks: 1,
      },
      {
        text: 'A word processor is used to ________.',
        options: ['cook meals', 'create and edit documents', 'wash tools', 'measure wood'],
        correctAnswer: 1,
        topic: 'Introduction to Word Processing',
        marks: 1,
      },
      {
        text: 'What does save mean on a computer?',
        options: ['Delete the document', 'Print the document', 'Store changes made to a document', 'Close the screen'],
        correctAnswer: 2,
        topic: 'Introduction to Word Processing',
        marks: 1,
      },
      {
        text: 'A work bench is ________.',
        options: ['a kind of shoe', 'a strong table used for working on materials', 'a drawing book', 'a safety sign'],
        correctAnswer: 1,
        topic: 'Work Bench',
        marks: 1,
      },
      {
        text: 'What is a vice used for on a work bench?',
        options: ['To hold materials firmly', 'To switch on a computer', 'To draw a map', 'To wash hands'],
        correctAnswer: 0,
        topic: 'Work Bench',
        marks: 1,
      },
      {
        text: 'Which is a type of line used in graphic communication?',
        options: ['hidden line', 'story line', 'music line', 'finish line'],
        correctAnswer: 0,
        topic: 'Types of Lines',
        marks: 1,
      },
    ],
  },
]
