/**
 * Export a curriculum-generated Quiz as a Word document. Mirrors
 * homeworkToDocx.js. One document: the quiz (questions + options) then a
 * teacher answer key (correct answer + explanation).
 */

import {
  AlignmentType,
  BorderStyle,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from 'docx'

const CELL_BORDER = {
  top:    { style: BorderStyle.SINGLE, size: 4, color: '888888' },
  bottom: { style: BorderStyle.SINGLE, size: 4, color: '888888' },
  left:   { style: BorderStyle.SINGLE, size: 4, color: '888888' },
  right:  { style: BorderStyle.SINGLE, size: 4, color: '888888' },
}

function text(str, opts = {}) {
  return new TextRun({ text: str == null ? '' : String(str), ...opts })
}
function para(runs, opts = {}) {
  return new Paragraph({
    children: Array.isArray(runs) ? runs : [runs],
    spacing: { after: 80 }, ...opts,
  })
}
function h1(str) {
  return new Paragraph({
    children: [text(str, { bold: true, size: 32 })],
    heading: HeadingLevel.HEADING_1,
    alignment: AlignmentType.CENTER, spacing: { after: 160 },
  })
}
function h2(str) {
  return new Paragraph({
    children: [text(str, { bold: true, size: 24 })],
    heading: HeadingLevel.HEADING_2, spacing: { before: 240, after: 120 },
  })
}
function bodyPara(str) {
  return new Paragraph({
    children: [text(str, { size: 20 })], spacing: { after: 60 },
  })
}
function cell(content, { width, shading } = {}) {
  return new TableCell({
    children: Array.isArray(content) ? content : [content],
    width: width ? { size: width, type: WidthType.PERCENTAGE } : undefined,
    borders: CELL_BORDER,
    ...(shading ? { shading: { fill: shading } } : {}),
  })
}
function metadataTable(header) {
  const rows = [
    ['Topic', header.topic],
    ['Sub-topic', header.subtopic],
    ['Grade', header.grade],
    ['Subject', header.subject],
    ['Term', header.term ? `Term ${header.term}` : ''],
    ['Time', header.durationMinutes ? `${header.durationMinutes} min` : ''],
  ].filter(([, v]) => v)
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: rows.map(([k, v]) => new TableRow({
      children: [
        cell(para(text(k, { bold: true, size: 18 })), { width: 30, shading: 'F3F4F6' }),
        cell(para(text(String(v), { size: 18 })), { width: 70 }),
      ],
    })),
  })
}

const LETTERS = ['A', 'B', 'C', 'D', 'E', 'F']

export function buildQuizDocument(quiz) {
  const children = []
  const header = quiz.header || {}
  children.push(h1(header.title || 'Quiz'))
  children.push(metadataTable(header))
  if (header.instructions) {
    children.push(para(text(header.instructions, { italics: true, size: 20 })))
  }
  children.push(para(text(' ', { size: 14 })))

  ;(quiz.questions || []).forEach((q) => {
    children.push(new Paragraph({
      children: [
        text(`${q.number}. `, { bold: true, size: 20 }),
        text(q.question, { size: 20 }),
      ],
      spacing: { before: 80, after: 40 },
    }))
    if (Array.isArray(q.options) && q.options.length) {
      q.options.forEach((opt, i) => {
        children.push(new Paragraph({
          children: [text(`${LETTERS[i] || '•'}. ${opt}`, { size: 20 })],
          indent: { left: 480 }, spacing: { after: 20 },
        }))
      })
    }
  })

  children.push(h2('Answer Key (teacher)'))
  ;(quiz.questions || []).forEach((q) => {
    children.push(new Paragraph({
      children: [
        text(`${q.number}. `, { bold: true, size: 20 }),
        text(q.correctAnswer || '—', { size: 20 }),
      ],
      spacing: { after: q.explanation ? 20 : 60 },
    }))
    if (q.explanation) {
      children.push(new Paragraph({
        children: [text(q.explanation, { italics: true, size: 18 })],
        indent: { left: 360 }, spacing: { after: 60 },
      }))
    }
  })
  if (quiz.answerKey?.notes) {
    children.push(bodyPara(quiz.answerKey.notes))
  }

  return new Document({
    creator: 'zedexams.com',
    title: header.title || 'Quiz',
    description: 'Generated by ZedExams Teacher Tools',
    styles: { default: { document: { run: { font: 'Calibri', size: 20 } } } },
    sections: [{ children }],
  })
}

export async function downloadQuizDocx(quiz, filename = 'quiz.docx') {
  const doc = buildQuizDocument(quiz)
  const blob = await Packer.toBlob(doc)
  try {
    const { saveAs } = await import('file-saver')
    saveAs(blob, filename)
    return
  } catch { /* fall through */ }
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
