/**
 * Same-origin download via the /api/download echo endpoint.
 *
 * On browsers that drop the filename for an in-page blob: download (DuckDuckGo,
 * in-app WebViews, older Android), the name has to arrive on an HTTP response
 * header. We POST the just-generated bytes (base64) to our own /api/download
 * Hosting rewrite, which echoes them back with a Content-Disposition attachment
 * header carrying the real name. The browser then:
 *   • names the file correctly (Content-Disposition), and
 *   • shows it downloading from zedexams.com — not firebasestorage.googleapis.com.
 *
 * We use a hidden <form> POST targeting a hidden <iframe> (not fetch) because
 * only a navigation response can drive the browser's download manager; the
 * attachment response downloads without navigating the page.
 *
 * Limit: form fields are text, so the file is base64'd into the body. We cap at
 * ~18 MB of file so we stay well under request-size limits; larger exports fall
 * back to the Storage-stamped path (saveViaStampedUrl).
 */

import { apiUrl } from './runtime.js'
import { blobToBase64 } from './nativeDownload.js'
import { reportClientError } from './clientErrorReporting.js'

// ~18 MB of source bytes → ~24 MB base64. Studio exports (lesson plans,
// worksheets, …) are far smaller; this only deflects pathological inputs.
const MAX_SOURCE_BYTES = 18 * 1024 * 1024

/**
 * @returns {Promise<boolean>} true when the download was triggered; false when
 *   we couldn't (no DOM, too large, build error) so the caller falls back.
 *   Never throws.
 */
export async function saveViaServerEcho(blob, filename) {
  if (typeof document === 'undefined' || typeof document.createElement !== 'function') {
    return false
  }
  if (blob && typeof blob.size === 'number' && blob.size > MAX_SOURCE_BYTES) {
    return false
  }

  try {
    const base64 = await blobToBase64(blob)
    if (!base64) return false

    const name = filename || 'download'
    const type = (blob && blob.type) || 'application/octet-stream'
    const action = apiUrl(
      `/api/download?name=${encodeURIComponent(name)}&type=${encodeURIComponent(type)}`,
    )

    // Hidden iframe target: the attachment response downloads without ever
    // navigating the visible page.
    const frameName = `dl_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`
    const iframe = document.createElement('iframe')
    iframe.name = frameName
    iframe.style.display = 'none'
    document.body.appendChild(iframe)

    const form = document.createElement('form')
    form.method = 'POST'
    form.action = action
    form.target = frameName
    form.style.display = 'none'

    const field = document.createElement('input')
    field.type = 'hidden'
    field.name = 'data'
    field.value = base64
    form.appendChild(field)

    document.body.appendChild(form)
    form.submit()

    // Tear down once the download has surely started.
    setTimeout(() => {
      try { form.remove() } catch { /* noop */ }
      try { iframe.remove() } catch { /* noop */ }
    }, 60_000)

    return true
  } catch (err) {
    reportClientError(err, 'server_echo_download')
    return false
  }
}
