/**
 * Regression spec: LOADING the Assessment Paper Studio must persist NOTHING.
 *
 * The bug: visiting /teacher/assessment-papers/new and doing nothing — no
 * typing, no clicks — filed a paper holding one blank question into the
 * teacher's library about two seconds later, plus a device/cloud draft. It
 * reproduced every time, and it polluted the library and the dashboard's Recent
 * Documents feed with junk.
 *
 * Root cause: the studio decided "the teacher has edited this paper" from paper
 * CONTENT — "one empty starter question AND no title AND no school name" — and
 * its OWN School-Profile seeding writes the teacher's school name onto an
 * untouched paper. Every teacher with a saved school name therefore had an
 * apparently-edited paper the moment the page finished loading. The autosave
 * gate then counted the blank starter question as content and filed it.
 *
 * So the school profile in this spec is not incidental colour: it is the
 * trigger. Without it the old code passes and this spec proves nothing.
 *
 * Covered here:
 *   • mount /new, run past both autosave debounces → zero writes of any kind;
 *   • the same after clicking "New paper" (startBlankPaper is a second route in);
 *   • the first real edit DOES persist — otherwise "no writes" would be
 *     satisfied by an autosave that never works at all.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { render, screen, fireEvent, act } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'

vi.mock('../../../firebase/config', () => ({ default: {}, auth: {}, db: {}, storage: {}, app: {} }))
vi.mock('firebase/storage', () => ({ ref: vi.fn(), uploadBytes: vi.fn(), getDownloadURL: vi.fn() }))
vi.mock('firebase/functions', () => ({ getFunctions: () => ({}), httpsCallable: () => vi.fn() }))

const mockCreateAssessment = vi.fn().mockResolvedValue('new-paper-1')
const mockSaveAssessmentQuestions = vi.fn().mockResolvedValue([])
const mockUpdateAssessmentWithQuestions = vi.fn().mockResolvedValue([])
vi.mock('../../../hooks/useFirestore', () => ({
  useFirestore: () => ({
    createAssessment: mockCreateAssessment,
    saveAssessmentQuestions: mockSaveAssessmentQuestions,
    getMyAssessments: vi.fn().mockResolvedValue([]),
    getAssessmentById: vi.fn(),
    getAssessmentQuestions: vi.fn().mockResolvedValue([]),
    updateAssessmentWithQuestions: mockUpdateAssessmentWithQuestions,
  }),
}))

// Every path out of the studio to durable storage, so "nothing was persisted"
// is a claim about all of them and not just the library doc.
const mockSaveDraft = vi.fn()
const mockSaveDraftRemote = vi.fn().mockResolvedValue(undefined)
vi.mock('../hooks/useAssessmentDraft', () => ({
  saveAssessmentDraft: (...args) => mockSaveDraft(...args),
  saveAssessmentDraftRemote: (...args) => mockSaveDraftRemote(...args),
  clearAssessmentDraft: vi.fn(),
  clearAssessmentDraftRemote: vi.fn(),
  loadAssessmentDraftMerged: vi.fn().mockResolvedValue({ draft: null, source: 'local' }),
}))

// THE TRIGGER: a teacher with a school name saved in their School Profile. The
// studio seeds it onto a fresh paper, which is what defeated the old
// "is this paper untouched?" test.
vi.mock('../../../utils/schoolProfileService', () => ({
  getSchoolProfile: vi.fn().mockResolvedValue({
    schoolName: 'Kabulonga Primary School',
    defaultDuration: 90,
    defaultCoverInstructions: 'Answer ALL questions in the spaces provided.',
    motto: 'Knowledge is power',
    address: 'Lusaka',
    emisNumber: '123456',
  }),
}))

const mockAuth = { currentUser: { uid: 'teacher-1' }, userProfile: { id: 'teacher-1' }, isAdmin: false }
vi.mock('../../../contexts/AuthContext', () => ({ useAuth: () => mockAuth }))

vi.mock('../../../services/quizImport/documentQuizImporter', () => ({
  importQuizDocument: vi.fn(), revokeImportedQuizAssets: vi.fn(), QUIZ_DOCUMENT_ACCEPT: '.pdf',
}))
vi.mock('../../../utils/aiAssistant', () => ({ generateAIQuizQuestions: vi.fn() }))
vi.mock('../../../utils/generateDiagram', () => ({ generateDiagram: vi.fn() }))
vi.mock('../../../utils/pictureBankService', () => ({ uploadBankPicture: vi.fn(), PICTURE_BANK_SUBJECTS_GENERIC: [] }))
vi.mock('../lib/autoGenerateDiagrams', () => ({
  autoGenerateDiagrams: vi.fn(), countDiagramJobs: () => 0, DIAGRAM_AUTO_CAP: 10,
}))
vi.mock('../../../utils/imageCompression', () => ({ compressImage: vi.fn() }))
vi.mock('../../../utils/questionBankService', () => ({
  saveQuestionToBank: vi.fn(), captureQuestionsToBank: vi.fn(), bumpQuestionUsage: vi.fn(),
  searchQuestionBank: vi.fn().mockResolvedValue({ rows: [] }),
}))

vi.mock('../components/AssessmentHomeView', () => ({
  HomeView: ({ onNewPaper }) => (
    <div data-testid="home-view">
      <button type="button" onClick={onNewPaper}>stub-new-paper</button>
    </div>
  ),
}))
// Surfaces the two mutators an edit goes through: a header field and a question.
vi.mock('../components/AssessmentBuilderView', () => ({
  BuilderView: ({ setF, onUpdateStandaloneQuestion, autoTitle }) => (
    <div data-testid="builder-view" data-auto-title={autoTitle}>
      <button type="button" onClick={() => setF('className', '4B')}>stub-type-class</button>
      <button
        type="button"
        onClick={() => onUpdateStandaloneQuestion(0, 'text', '<p>Name two mammals.</p>')}
      >
        stub-write-question
      </button>
    </div>
  ),
}))
vi.mock('../components/AssessmentSlideOvers', () => ({
  PaperRenderView: () => null, BlockPickerSlide: () => null, AiSlide: () => null,
  EditorSlide: () => null, PasteImportSlide: () => null,
}))
vi.mock('../components/AssessmentBars', () => ({ TopBar: () => null, BottomBar: () => null }))
vi.mock('../components/QuestionBankPanel', () => ({ default: () => null }))
vi.mock('../components/CreatePaperModal', () => ({ default: () => null }))
vi.mock('../components/DiagramFixupPanel', () => ({ default: () => null, countDiagramsNeeded: () => 0 }))
vi.mock('../components/DiagramScanner', () => ({ default: () => null }))
vi.mock('../../quizEditor', () => ({ QuizVerifyModal: () => null }))
vi.mock('../components/scan/ScanPaperModal', () => ({ default: () => null }))
vi.mock('../components/scan/ImportReviewScreen', () => ({ default: () => null }))
vi.mock('../components/PaperHealthModal', () => ({ default: () => null }))
vi.mock('../components/PaperTemplatePicker', () => ({ default: () => null }))
vi.mock('../../../shared/components/StudioOutputBoundary', () => ({ default: ({ children }) => children }))

vi.mock('react-router-dom', async (importOriginal) => {
  const actual = await importOriginal()
  return {
    ...actual,
    useNavigate: () => vi.fn(),
    useParams: () => ({}),            // /new — no :paperId
    useSearchParams: () => [new URLSearchParams(''), vi.fn()],
  }
})

import AssessmentStudio from './AssessmentStudio'

// Long enough to clear the 800ms device-draft debounce AND the 2s library
// autosave debounce, with room to spare.
const PAST_EVERY_AUTOSAVE_MS = 6000

function everyPersistenceCall() {
  return {
    papersCreated: mockCreateAssessment.mock.calls.length,
    questionsWritten: mockSaveAssessmentQuestions.mock.calls.length,
    papersUpdated: mockUpdateAssessmentWithQuestions.mock.calls.length,
    draftsSaved: mockSaveDraft.mock.calls.length,
    remoteDraftsSaved: mockSaveDraftRemote.mock.calls.length,
  }
}

// Let the mounted studio's async effects (school profile read, draft read)
// settle, then run every debounce out.
async function settleAndRunTimers(ms = PAST_EVERY_AUTOSAVE_MS) {
  await act(async () => { await Promise.resolve() })
  await act(async () => { vi.advanceTimersByTime(ms) })
  await act(async () => { await Promise.resolve() })
}

beforeEach(() => {
  vi.clearAllMocks()
  vi.useFakeTimers({ shouldAdvanceTime: true })
})

afterEach(() => {
  vi.useRealTimers()
})

describe('AssessmentStudio — an untouched new paper persists nothing', () => {
  it('THE BUG: mounting /new and doing nothing writes no paper, no question, no draft', async () => {
    render(<MemoryRouter><AssessmentStudio /></MemoryRouter>)
    await settleAndRunTimers()

    // The School Profile HAS been applied — otherwise this spec is testing a
    // studio the bug never affected.
    expect(screen.getByTestId('home-view')).toBeInTheDocument()
    expect(everyPersistenceCall()).toEqual({
      papersCreated: 0,
      questionsWritten: 0,
      papersUpdated: 0,
      draftsSaved: 0,
      remoteDraftsSaved: 0,
    })
  })

  it('clicking "New paper" and doing nothing also writes nothing', async () => {
    render(<MemoryRouter><AssessmentStudio /></MemoryRouter>)
    await settleAndRunTimers(0)

    fireEvent.click(screen.getByRole('button', { name: 'stub-new-paper' }))
    await settleAndRunTimers()

    expect(screen.getByTestId('builder-view')).toBeInTheDocument()
    expect(everyPersistenceCall()).toEqual({
      papersCreated: 0,
      questionsWritten: 0,
      papersUpdated: 0,
      draftsSaved: 0,
      remoteDraftsSaved: 0,
    })
  })

  it('typing into a header field drafts the paper but still does not file an empty one', async () => {
    render(<MemoryRouter><AssessmentStudio /></MemoryRouter>)
    await settleAndRunTimers(0)
    fireEvent.click(screen.getByRole('button', { name: 'stub-new-paper' }))
    await settleAndRunTimers(0)

    fireEvent.click(screen.getByRole('button', { name: 'stub-type-class' }))
    await settleAndRunTimers()

    // The edit is real, so the device draft captures it…
    expect(mockSaveDraft).toHaveBeenCalled()
    // …but a paper whose only question is blank is still not worth filing.
    expect(mockCreateAssessment).not.toHaveBeenCalled()
  })

  it('writing a question DOES file the paper — the autosave still works', async () => {
    render(<MemoryRouter><AssessmentStudio /></MemoryRouter>)
    await settleAndRunTimers(0)
    fireEvent.click(screen.getByRole('button', { name: 'stub-new-paper' }))
    await settleAndRunTimers(0)

    fireEvent.click(screen.getByRole('button', { name: 'stub-write-question' }))
    await settleAndRunTimers()

    expect(mockCreateAssessment).toHaveBeenCalledTimes(1)
    const [payload] = mockCreateAssessment.mock.calls[0]
    expect(payload.questionCount).toBe(1)
    // And the branding the studio seeded rides along on the real paper.
    expect(payload.schoolName).toBe('Kabulonga Primary School')
  })
})

describe('AssessmentStudio — the filed paper is named for its subject and term', () => {
  it('the generated title carries grade, subject, type, term and year', async () => {
    render(<MemoryRouter><AssessmentStudio /></MemoryRouter>)
    await settleAndRunTimers(0)
    fireEvent.click(screen.getByRole('button', { name: 'stub-new-paper' }))
    await settleAndRunTimers(0)
    fireEvent.click(screen.getByRole('button', { name: 'stub-write-question' }))
    await settleAndRunTimers()

    const [payload] = mockCreateAssessment.mock.calls[0]
    const year = new Date().getFullYear()
    // Defaults for a blank paper: Grade 4, Integrated Science, end-of-term, term 1.
    expect(payload.title).toBe(`GRADE 4 INTEGRATED SCIENCE - END OF TERM 1 TEST - ${year}`)
    expect(payload.titleSource).toBe('auto')
  })
})
