/**
 * The Question Bank insert, end to end inside the studio.
 *
 * The pieces are covered elsewhere — placement rules by
 * `test:question-bank-placement`, the picker's wording by
 * QuestionBankPlacementPicker.spec.jsx, the bank UI by
 * QuestionBankBrowser.spec.jsx, the write SHAPE by `test:bank-insert-writes`.
 * What is only observable HERE is the join between them:
 *
 *   - pressing Use opens the placement step and inserts NOTHING on its own;
 *   - confirming a position splices the paper's own copy in AT that position,
 *     so everything after it shifts down;
 *   - the copy carries provenance and lands unlocked and unedited;
 *   - the usage counter is bumped exactly once per insert, twice for two
 *     rapid inserts;
 *   - a question with nowhere to go gets a section added and inserted into it;
 *   - nothing in the flow writes to the bank.
 *
 * The drawer is stubbed down to two "use" buttons: what it renders is
 * QuestionBankBrowser's business, and mounting it here would make this a test
 * about the drawer instead of about the insert.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest'
import { render, screen, fireEvent, waitFor } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'

vi.mock('../../../firebase/config', () => ({ default: {}, auth: {}, db: {}, storage: {}, app: {} }))
vi.mock('firebase/storage', () => ({ ref: vi.fn(), uploadBytes: vi.fn(), getDownloadURL: vi.fn() }))
vi.mock('firebase/functions', () => ({ getFunctions: () => ({}), httpsCallable: () => vi.fn() }))

vi.mock('../../../hooks/useFirestore', () => ({
  useFirestore: () => ({
    createAssessment: vi.fn(),
    saveAssessmentQuestions: vi.fn(),
    getMyAssessments: vi.fn().mockResolvedValue([]),
    getAssessmentById: vi.fn(),
    getAssessmentQuestions: vi.fn().mockResolvedValue([]),
    updateAssessmentWithQuestions: vi.fn(),
  }),
}))

vi.mock('../../../contexts/AuthContext', () => ({
  useAuth: () => ({ currentUser: { uid: 'u1' }, userProfile: { id: 'u1' }, isAdmin: false }),
}))

vi.mock('../../../components/quiz/documentQuizImporter', () => ({
  importQuizDocument: vi.fn(), revokeImportedQuizAssets: vi.fn(),
}))
vi.mock('../../../utils/aiAssistant', () => ({ generateAIQuizQuestions: vi.fn() }))
vi.mock('../../../utils/generateDiagram', () => ({ generateDiagram: vi.fn() }))
vi.mock('../../../utils/pictureBankService', () => ({ uploadBankPicture: vi.fn(), PICTURE_BANK_SUBJECTS_GENERIC: [] }))
vi.mock('../../../utils/schoolProfileService', () => ({ getSchoolProfile: vi.fn().mockResolvedValue(null) }))
vi.mock('../lib/autoGenerateDiagrams', () => ({
  autoGenerateDiagrams: vi.fn(), countDiagramJobs: () => 0, DIAGRAM_AUTO_CAP: 10,
}))
vi.mock('../../../utils/imageCompression', () => ({ compressImage: vi.fn() }))

const bumpQuestionUsage = vi.fn()
const editMyBankQuestion = vi.fn()
const saveQuestionToBank = vi.fn()
const duplicateBankQuestion = vi.fn()
vi.mock('../../../utils/questionBankService', () => ({
  saveQuestionToBank: (...a) => saveQuestionToBank(...a),
  captureQuestionsToBank: vi.fn(),
  bumpQuestionUsage: (...a) => bumpQuestionUsage(...a),
  searchQuestionBank: vi.fn().mockResolvedValue({ rows: [] }),
  parseBankQuestion: (row) => { try { return JSON.parse(row?.data || 'null') } catch { return null } },
  duplicateBankQuestion: (...a) => duplicateBankQuestion(...a),
  editMyBankQuestion: (...a) => editMyBankQuestion(...a),
  toggleFavouriteQuestion: vi.fn(),
  listFavouriteIds: vi.fn().mockResolvedValue(new Set()),
  deleteBankQuestion: vi.fn(),
  getBankQuestion: vi.fn().mockResolvedValue(null),
}))

/** An MCQ carrying nested state, so the copy's isolation is observable. */
const MCQ_ROW = {
  id: 'row-mcq', ownerId: 'u1', type: 'mcq', grade: '4', subject: 'Mathematics',
  topic: 'Fractions', marks: 2, version: 3, usageCount: 3, preview: 'Add 1/2 and 1/4',
  data: JSON.stringify({
    text: 'Add 1/2 and 1/4', type: 'mcq', options: ['3/4', '1/2', '2/6', '1/8'],
    correctAnswer: 0, marks: 2, imageDiagram: { libraryKey: 'fraction_bar', params: { parts: 4 } },
    locked: true, teacherEdited: true,
  }),
}

/** A second MCQ, so ORDER is observable rather than inferred from a count. */
const MCQ_ROW_2 = {
  id: 'row-mcq-2', ownerId: 'u1', type: 'mcq', grade: '4', subject: 'Mathematics',
  topic: 'Fractions', marks: 1, version: 1, preview: 'Which is larger?',
  data: JSON.stringify({
    text: 'Which is larger?', type: 'mcq', options: ['1/2', '1/4', '1/8', '1/16'],
    correctAnswer: 0, marks: 1,
  }),
}

/** Somebody else's Master-Bank True/False question. */
const TF_ROW = {
  id: 'row-tf', ownerId: 'someone-else', masterEligible: true, type: 'tf', grade: '4',
  subject: 'Mathematics', marks: 1, preview: 'A half is bigger than a quarter.',
  data: JSON.stringify({
    text: 'A half is bigger than a quarter.', type: 'tf', options: ['True', 'False'],
    correctAnswer: 0, marks: 1,
  }),
}

vi.mock('../components/QuestionBankPanel', () => ({
  default: ({ open, onUse }) => (open ? (
    <div>
      <button type="button" onClick={() => onUse(MCQ_ROW, JSON.parse(MCQ_ROW.data))}>stub-use-mcq</button>
      <button type="button" onClick={() => onUse(MCQ_ROW_2, JSON.parse(MCQ_ROW_2.data))}>stub-use-mcq-2</button>
      <button type="button" onClick={() => onUse(TF_ROW, JSON.parse(TF_ROW.data))}>stub-use-tf</button>
    </div>
  ) : null),
}))

// The block picker is the real route to the drawer — the studio's
// handleBlockPick('question_bank') is what opens it.
vi.mock('../components/AssessmentSlideOvers', () => ({
  PaperRenderView: () => null,
  BlockPickerSlide: ({ open, onPick }) => (open
    ? <button type="button" onClick={() => onPick('question_bank')}>stub-pick-bank</button>
    : null),
  AiSlide: () => null,
  EditorSlide: ({ open }) => (open ? <div data-testid="editor-slide" /> : null),
  PasteImportSlide: () => null,
}))

// The builder, reduced to a readable dump of the paper's questions IN ORDER.
vi.mock('../components/AssessmentBuilderView', () => ({
  BuilderView: ({ sections = [], parts = [] }) => (
    <div
      data-testid="builder-view"
      data-part-count={parts.length}
      data-part-titles={parts.map(p => p.title).join('|')}
      data-questions={JSON.stringify(sections.map(s => ({
        text: s.question?.text ?? '',
        type: s.question?.type,
        locked: s.question?.locked ?? null,
        teacherEdited: s.question?.teacherEdited ?? null,
        sourceQuestionId: s.question?.sourceQuestionId ?? null,
        sourceBank: s.question?.sourceBank ?? null,
        sourceVersion: s.question?.sourceVersion ?? null,
        sourceBankId: s.question?.sourceBankId ?? null,
        hasInsertedAt: Boolean(s.question?.insertedAt),
        optionCount: (s.question?.options ?? []).filter(Boolean).length,
        partId: s.question?.partId ?? null,
      })))}
    />
  ),
}))

vi.mock('../components/AssessmentHomeView', () => ({ HomeView: () => <div data-testid="home-view" /> }))
// The dock exposes the "+" that opens the block picker.
vi.mock('../components/AssessmentBars', () => ({
  TopBar: () => null,
  BottomBar: ({ onAdd }) => <button type="button" onClick={onAdd}>stub-add-block</button>,
}))
vi.mock('../components/CreatePaperModal', () => ({ default: () => null }))
vi.mock('../components/DiagramFixupPanel', () => ({ default: () => null, countDiagramsNeeded: () => 0 }))
vi.mock('../components/DiagramScanner', () => ({ default: () => null }))
vi.mock('../../quizEditor', () => ({ QuizVerifyModal: () => null }))
vi.mock('../components/scan/ScanPaperModal', () => ({ default: () => null }))
vi.mock('../components/scan/ImportReviewScreen', () => ({ default: () => null }))
vi.mock('../components/PaperHealthModal', () => ({ default: () => null }))
vi.mock('../components/PaperTemplatePicker', () => ({ default: () => null }))
vi.mock('../../../shared/components/StudioOutputBoundary', () => ({ default: ({ children }) => children }))
vi.mock('../components/QuestionBankView', () => ({ default: () => <div data-testid="bank-view" /> }))

let searchParams = new URLSearchParams('view=builder')
vi.mock('react-router-dom', async (importOriginal) => {
  const actual = await importOriginal()
  return {
    ...actual,
    useNavigate: () => vi.fn(),
    useParams: () => ({}),
    useSearchParams: () => [searchParams, vi.fn()],
  }
})

import AssessmentStudio from './AssessmentStudio'

function questions() {
  return JSON.parse(screen.getByTestId('builder-view').getAttribute('data-questions'))
}
function builder() {
  return screen.getByTestId('builder-view')
}

async function openBank() {
  fireEvent.click(await screen.findByText('stub-add-block'))
  fireEvent.click(await screen.findByText('stub-pick-bank'))
}

/** Use → pick a labelled position → confirm. */
async function insertAt(useButton, positionLabel, { andEdit = false } = {}) {
  fireEvent.click(await screen.findByText(useButton))
  await screen.findByRole('dialog', { name: /Choose where this question goes/i })
  if (positionLabel) fireEvent.click(screen.getByRole('button', { name: positionLabel }))
  fireEvent.click(screen.getByRole('button', {
    name: andEdit ? /Insert and edit/ : /^Insert as Q\d+$/,
  }))
}

describe('AssessmentStudio — inserting from the Question Bank', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    searchParams = new URLSearchParams('view=builder')
    render(<MemoryRouter><AssessmentStudio /></MemoryRouter>)
  })

  it('Use opens the placement step and inserts nothing on its own', async () => {
    await openBank()
    expect(questions()).toHaveLength(1)
    expect(questions()[0].text).toBe('')

    fireEvent.click(await screen.findByText('stub-use-mcq'))
    expect(await screen.findByRole('dialog', { name: /Choose where this question goes/i })).toBeInTheDocument()

    // Still the blank starter — nothing has been placed.
    expect(questions()).toHaveLength(1)
    expect(questions()[0].text).toBe('')
    expect(bumpQuestionUsage).not.toHaveBeenCalled()
  })

  it('cancelling the placement step leaves the paper untouched', async () => {
    await openBank()
    fireEvent.click(await screen.findByText('stub-use-mcq'))
    await screen.findByRole('dialog', { name: /Choose where this question goes/i })
    fireEvent.click(screen.getByRole('button', { name: 'Cancel' }))

    await waitFor(() => expect(
      screen.queryByRole('dialog', { name: /Choose where this question goes/i }),
    ).not.toBeInTheDocument())
    expect(questions()).toHaveLength(1)
    expect(bumpQuestionUsage).not.toHaveBeenCalled()
  })

  it('the first insert replaces the blank starter and carries its provenance', async () => {
    await openBank()
    await insertAt('stub-use-mcq')

    await waitFor(() => expect(questions()).toHaveLength(1))
    const [q] = questions()
    expect(q.text).toBe('Add 1/2 and 1/4')
    expect(q.optionCount).toBe(4)
    expect(q.sourceQuestionId).toBe('row-mcq')
    expect(q.sourceBank).toBe('mine')
    expect(q.sourceVersion).toBe(3)
    expect(q.sourceBankId).toBe('row-mcq')
    expect(q.hasInsertedAt).toBe(true)
    // A copy is new work in THIS paper: never pre-locked, never pre-edited,
    // whatever the bank record happened to carry.
    expect(q.locked).toBe(false)
    expect(q.teacherEdited).toBe(false)
  })

  it('inserting at a chosen position shifts the questions after it down', async () => {
    await openBank()
    await insertAt('stub-use-mcq')
    await waitFor(() => expect(questions()).toHaveLength(1))

    // Placed AT Q1, not appended — so the question already there becomes Q2.
    // Two different questions, because "the paper grew" is not the claim;
    // "it grew in the right place" is, and identical rows cannot show that.
    await insertAt('stub-use-mcq-2', 'as Q1')
    await waitFor(() => expect(questions()).toHaveLength(2))
    expect(questions().map(q => q.text)).toEqual(['Which is larger?', 'Add 1/2 and 1/4'])

    // …and the end-of-section position lands after both, not at the front.
    await insertAt('stub-use-mcq', 'as Q3 (end of section)')
    await waitFor(() => expect(questions()).toHaveLength(3))
    expect(questions().map(q => q.text))
      .toEqual(['Which is larger?', 'Add 1/2 and 1/4', 'Add 1/2 and 1/4'])
  })

  it('a middle position lands in the middle, between the two named questions', async () => {
    await openBank()
    await insertAt('stub-use-mcq')
    await waitFor(() => expect(questions()).toHaveLength(1))
    await insertAt('stub-use-mcq-2', 'as Q2 (end of section)')
    await waitFor(() => expect(questions()).toHaveLength(2))
    expect(questions().map(q => q.text)).toEqual(['Add 1/2 and 1/4', 'Which is larger?'])

    // Q2 of three: the existing Q2 becomes Q3 and Q1 does not move.
    await insertAt('stub-use-mcq', 'as Q2')
    await waitFor(() => expect(questions()).toHaveLength(3))
    expect(questions().map(q => q.text))
      .toEqual(['Add 1/2 and 1/4', 'Add 1/2 and 1/4', 'Which is larger?'])
  })

  it('the usage counter is bumped once per insert — twice for two rapid inserts', async () => {
    await openBank()
    await insertAt('stub-use-mcq')
    await waitFor(() => expect(questions()).toHaveLength(1))
    await insertAt('stub-use-mcq', 'as Q1')
    await waitFor(() => expect(questions()).toHaveLength(2))

    expect(bumpQuestionUsage).toHaveBeenCalledTimes(2)
    expect(bumpQuestionUsage).toHaveBeenNthCalledWith(1, 'row-mcq')
    expect(bumpQuestionUsage).toHaveBeenNthCalledWith(2, 'row-mcq')
  })

  it('"Insert and edit" inserts and opens the editor on the new copy', async () => {
    await openBank()
    await insertAt('stub-use-mcq', null, { andEdit: true })
    await waitFor(() => expect(questions()).toHaveLength(1))
    expect(await screen.findByTestId('editor-slide')).toBeInTheDocument()
  })

  it('the drawer stays open, so several questions can be inserted in a row', async () => {
    await openBank()
    await insertAt('stub-use-mcq')
    await waitFor(() => expect(questions()).toHaveLength(1))
    expect(screen.getByText('stub-use-mcq')).toBeInTheDocument()
  })

  it('a question with nowhere to go gets a section added and is inserted into it', async () => {
    await openBank()
    await insertAt('stub-use-mcq')
    await waitFor(() => expect(questions()).toHaveLength(1))
    expect(builder().getAttribute('data-part-count')).toBe('0')

    // A True/False question cannot join an all-MCQ paper, and is never
    // converted so that it can.
    fireEvent.click(await screen.findByText('stub-use-tf'))
    await screen.findByRole('dialog', { name: /Choose where this question goes/i })
    expect(screen.getByText(/nowhere to put a true \/ false question/i)).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: /Add a True \/ False section/i }))

    await waitFor(() => expect(questions()).toHaveLength(2))
    expect(builder().getAttribute('data-part-count')).toBe('1')
    expect(builder().getAttribute('data-part-titles')).toBe('True / False')

    const inserted = questions()[1]
    expect(inserted.type).toBe('tf')
    expect(inserted.partId).toBeTruthy()
    // Provenance says master, because the row belongs to another teacher.
    expect(inserted.sourceBank).toBe('master')
    // No stored version on that row → null, never NaN (Firestore rejects it).
    expect(inserted.sourceVersion).toBeNull()
  })

  it('nothing in the insert flow writes to the bank', async () => {
    await openBank()
    await insertAt('stub-use-mcq')
    await waitFor(() => expect(questions()).toHaveLength(1))
    await insertAt('stub-use-mcq', 'as Q1')
    await waitFor(() => expect(questions()).toHaveLength(2))

    // Use creates ZERO bank documents and edits none: the usage counter is the
    // only thing an insert may touch.
    expect(saveQuestionToBank).not.toHaveBeenCalled()
    expect(duplicateBankQuestion).not.toHaveBeenCalled()
    expect(editMyBankQuestion).not.toHaveBeenCalled()
  })
})
