/**
 * Behaviour tests for AssessmentStudio.jsx — the (largest) teacher paper
 * builder for the Assessment Paper Studio (every assessment type — tests
 * AND examinations — is authored from this one studio; there's no
 * route-level variant any more).
 *
 * The full builder mounts an enormous view tree, so these focus on the
 * edit-mode gate that returns *before* that tree — and, most importantly,
 * on the ownership check, the file's highest-risk logic: a teacher opening
 * `/…/:id/edit` for a paper they do not own must be denied, never handed the
 * paper. Covered: the edit loading skeletons, "not found" for a missing
 * paper, and "Access denied" for a non-owner (no data leak).
 */
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { render, screen, fireEvent, waitFor } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'

vi.mock('../../../firebase/config', () => ({ default: {}, auth: {}, db: {}, storage: {}, app: {} }))
vi.mock('firebase/storage', () => ({ ref: vi.fn(), uploadBytes: vi.fn(), getDownloadURL: vi.fn() }))
// Many util services call getFunctions(app) at import time. Stubbing the
// low-level firebase/functions module neutralises that whole class of
// import-time init crashes without chasing each service transitively.
vi.mock('firebase/functions', () => ({ getFunctions: () => ({}), httpsCallable: () => vi.fn() }))

const mockGetAssessmentById = vi.fn()
const mockGetAssessmentQuestions = vi.fn()
const mockCreateAssessment = vi.fn()
const mockSaveAssessmentQuestions = vi.fn()
const mockUpdateAssessmentWithQuestions = vi.fn()
vi.mock('../../../hooks/useFirestore', () => ({
  useFirestore: () => ({
    createAssessment: mockCreateAssessment,
    saveAssessmentQuestions: mockSaveAssessmentQuestions,
    getMyAssessments: vi.fn().mockResolvedValue([]),
    getAssessmentById: mockGetAssessmentById,
    getAssessmentQuestions: mockGetAssessmentQuestions,
    updateAssessmentWithQuestions: mockUpdateAssessmentWithQuestions,
  }),
}))

let mockAuth = { currentUser: { uid: 'owner-1' }, userProfile: { id: 'owner-1' }, isAdmin: false }
vi.mock('../../../contexts/AuthContext', () => ({ useAuth: () => mockAuth }))

const mockImportQuizDocument = vi.fn()
vi.mock('../../../components/quiz/documentQuizImporter', () => ({
  importQuizDocument: (...args) => mockImportQuizDocument(...args),
  revokeImportedQuizAssets: vi.fn(),
}))

// Firebase-touching / network util leaves.
vi.mock('../../../utils/aiAssistant', () => ({ generateAIQuizQuestions: vi.fn() }))
vi.mock('../../../utils/generateDiagram', () => ({ generateDiagram: vi.fn() }))
vi.mock('../../../utils/pictureBankService', () => ({ uploadBankPicture: vi.fn(), PICTURE_BANK_SUBJECTS_GENERIC: [] }))
vi.mock('../../../utils/schoolProfileService', () => ({ getSchoolProfile: vi.fn().mockResolvedValue(null) }))
vi.mock('../lib/autoGenerateDiagrams', () => ({
  autoGenerateDiagrams: vi.fn(), countDiagramJobs: () => 0, DIAGRAM_AUTO_CAP: 10,
}))
vi.mock('../../../utils/imageCompression', () => ({ compressImage: vi.fn() }))

// Heavy child views / modals — mostly render nothing so only the studio shell
// mounts. HomeView + BuilderView are *lightweight* stubs (not null): the edit
// gate tests never render either (they return in the loading / error branch),
// but the interaction tests below drive the real home→builder view wiring, so
// these stubs surface the callbacks the studio passes down (onNewPaper /
// onCreateWithAi) as clickable buttons and mark which view is on screen.
vi.mock('../components/AssessmentHomeView', () => ({
  HomeView: ({ eyebrow, onNewPaper, onCreateWithAi }) => (
    <div data-testid="home-view">
      <span data-testid="home-eyebrow">{eyebrow}</span>
      <button type="button" onClick={onNewPaper}>stub-new-paper</button>
      <button type="button" onClick={onCreateWithAi}>stub-home-create-ai</button>
    </div>
  ),
}))
vi.mock('../components/AssessmentBuilderView', () => ({
  // Expose form.title and sections.length as data attributes. Also expose
  // onImportDocument so B1 tests can trigger an import without a real file UI.
  BuilderView: ({ form, sections = [], onImportDocument }) => (
    <div
      data-testid="builder-view"
      data-form-title={form?.title ?? ''}
      data-section-count={sections.length}
    >
      builder-view
      <button
        type="button"
        onClick={() =>
          onImportDocument?.([new File([''], 'stub.pdf', { type: 'application/pdf' })])
        }
      >
        stub-import-doc
      </button>
    </div>
  ),
}))
// Slide-overs live in AssessmentSlideOvers (not previously mocked because the
// edit-gate tests never reach the main return). The interaction tests DO reach
// it, so stub these to keep the non-edit render cheap — AiSlide surfaces its
// open state so we can assert onAi wiring.
vi.mock('../components/AssessmentSlideOvers', () => ({
  PaperRenderView: () => null,
  BlockPickerSlide: () => null,
  AiSlide: ({ open }) => (open ? <div data-testid="ai-slide">ai-slide</div> : null),
  EditorSlide: () => null,
  PasteImportSlide: () => null,
}))
// Read-only best-effort bank read fired by the builder-view effect. Keep it
// deterministic (no real callable) so the transition tests don't depend on it.
vi.mock('../../../utils/questionBankService', () => ({
  saveQuestionToBank: vi.fn(),
  captureQuestionsToBank: vi.fn(),
  bumpQuestionUsage: vi.fn(),
  searchQuestionBank: vi.fn().mockResolvedValue({ rows: [] }),
  parseBankQuestion: (row) => { try { return JSON.parse(row?.data || 'null') } catch { return null } },
  duplicateBankQuestion: vi.fn(),
  editMyBankQuestion: vi.fn(),
  toggleFavouriteQuestion: vi.fn(),
  listFavouriteIds: vi.fn().mockResolvedValue(new Set()),
  deleteBankQuestion: vi.fn(),
  getBankQuestion: vi.fn().mockResolvedValue(null),
}))
vi.mock('../components/AssessmentBars', () => ({ TopBar: () => null, BottomBar: () => null }))
vi.mock('../components/QuestionBankPanel', () => ({ default: () => null }))
vi.mock('../components/CreatePaperModal', () => ({ default: () => <div data-testid="create-paper-modal">create-paper-modal</div> }))
vi.mock('../components/DiagramFixupPanel', () => ({ default: () => null, countDiagramsNeeded: () => 0 }))
vi.mock('../components/DiagramScanner', () => ({ default: () => null }))
vi.mock('../../../components/quiz/QuizVerifyModal', () => ({ default: () => null }))
vi.mock('../components/scan/ScanPaperModal', () => ({ default: () => null }))
vi.mock('../components/scan/ImportReviewScreen', () => ({ default: () => null }))
vi.mock('../components/PaperHealthModal', () => ({ default: () => null }))
vi.mock('../components/PaperTemplatePicker', () => ({ default: () => null }))
vi.mock('../../../components/teacher/StudioOutputBoundary', () => ({ default: ({ children }) => children }))

const mockNavigate = vi.fn()
let mockParams = { paperId: 'paper-1' }
vi.mock('react-router-dom', async (importOriginal) => {
  const actual = await importOriginal()
  return {
    ...actual,
    useNavigate: () => mockNavigate,
    useParams: () => mockParams,
    useSearchParams: () => [new URLSearchParams(''), vi.fn()],
  }
})

import AssessmentStudio from './AssessmentStudio'

function renderStudio() {
  return render(<MemoryRouter><AssessmentStudio /></MemoryRouter>)
}

beforeEach(() => {
  vi.clearAllMocks()
  mockAuth = { currentUser: { uid: 'owner-1' }, userProfile: { id: 'owner-1' }, isAdmin: false }
  mockParams = { paperId: 'paper-1' }
  mockGetAssessmentQuestions.mockResolvedValue([])
})

describe('AssessmentStudio — edit gate', () => {
  it('shows loading skeletons while the paper is being fetched', () => {
    mockGetAssessmentById.mockReturnValue(new Promise(() => {}))
    mockGetAssessmentQuestions.mockReturnValue(new Promise(() => {}))
    const { container } = renderStudio()
    expect(container.querySelectorAll('.studio-v2').length).toBeGreaterThan(0)
    expect(screen.queryByText(/Access denied/)).not.toBeInTheDocument()
  })

  it('shows "not found" when the paper does not exist', async () => {
    mockGetAssessmentById.mockResolvedValue(null)
    renderStudio()
    expect(await screen.findByText(/not found/)).toBeInTheDocument()
  })

  it('denies a non-owner, non-admin without leaking the paper', async () => {
    mockAuth = { currentUser: { uid: 'intruder' }, userProfile: { id: 'intruder' }, isAdmin: false }
    mockGetAssessmentById.mockResolvedValue({
      id: 'paper-1', title: 'Confidential Exam', createdBy: 'owner-1',
    })
    renderStudio()
    expect(await screen.findByText('Access denied')).toBeInTheDocument()
    expect(screen.queryByText(/Confidential Exam/)).not.toBeInTheDocument()
  })
})

/*
 * Interaction coverage. AssessmentStudio delegates almost all of its UI to
 * child views (HomeView / BuilderView / TopBar / BottomBar) and slide-overs, so
 * the genuinely testable interactions are the ones AssessmentStudio owns
 * itself: the home→builder view switch it wires through `changeView`, the AI
 * slide-over it opens through `openSlide`, and the static Assessment Paper
 * Studio wording it emits directly in its OWN markup (the edit-gate error
 * screen). Everything that lives *inside* a stubbed child is deliberately
 * out of scope here.
 */
function renderStudioFresh() {
  return render(<MemoryRouter><AssessmentStudio /></MemoryRouter>)
}

describe('AssessmentStudio — interaction', () => {
  beforeEach(() => {
    // Non-edit mode: no :id → isEditing is false, so the studio renders the
    // home view instead of the edit gate.
    mockParams = {}
  })

  it('renders the home view fresh (no paperId) with the studio eyebrow', () => {
    renderStudioFresh()
    expect(screen.getByTestId('home-view')).toBeInTheDocument()
    expect(screen.queryByTestId('builder-view')).not.toBeInTheDocument()
    expect(screen.getByTestId('home-eyebrow')).toHaveTextContent('Assessment Paper Studio')
  })

  it('home → builder: "New paper" switches the studio view to the builder', async () => {
    renderStudioFresh()
    expect(screen.getByTestId('home-view')).toBeInTheDocument()

    fireEvent.click(screen.getByRole('button', { name: 'stub-new-paper' }))

    // changeView('builder') flips the studio's own `view` state → BuilderView
    // renders and HomeView unmounts.
    await waitFor(() => expect(screen.getByTestId('builder-view')).toBeInTheDocument())
    expect(screen.queryByTestId('home-view')).not.toBeInTheDocument()
  })

  it('home → Create with AI: opens the builder on the Create-paper-with-AI modal', async () => {
    renderStudioFresh()
    expect(screen.queryByTestId('create-paper-modal')).not.toBeInTheDocument()

    fireEvent.click(screen.getByRole('button', { name: 'stub-home-create-ai' }))

    // openCreatePaperFromHome() does a full startBlankPaper() reset (→ builder
    // view) AND opens CreatePaperModal — the same modal the builder toolbar's
    // "Create with AI" button opens — instead of the old AI slide-over.
    await waitFor(() => expect(screen.getByTestId('builder-view')).toBeInTheDocument())
    expect(screen.getByTestId('create-paper-modal')).toBeInTheDocument()
    expect(screen.queryByTestId('home-view')).not.toBeInTheDocument()
  })
})

describe('AssessmentStudio — edit gate copy', () => {
  // The edit-gate error screen is markup AssessmentStudio emits itself. There
  // is no more route-level variant — every assessment type shares the same
  // "assessment paper" wording regardless of whether the saved doc is a test
  // or an examination.
  it('renders "Assessment paper not found" + assessment-papers back link', async () => {
    mockParams = { paperId: 'missing' }
    mockGetAssessmentById.mockResolvedValue(null)
    render(<MemoryRouter><AssessmentStudio /></MemoryRouter>)
    expect(await screen.findByText('Assessment paper not found')).toBeInTheDocument()
    expect(screen.getByText(/Back to assessment papers/)).toBeInTheDocument()
  })

  it('"access denied" copy names assessment papers for any owner mismatch, test or examination', async () => {
    mockParams = { paperId: 'paper-1' }
    mockAuth = { currentUser: { uid: 'intruder' }, userProfile: { id: 'intruder' }, isAdmin: false }
    mockGetAssessmentById.mockResolvedValue({
      id: 'paper-1', title: 'Confidential', createdBy: 'owner-1', assessmentType: 'examination',
    })
    render(<MemoryRouter><AssessmentStudio /></MemoryRouter>)
    expect(await screen.findByText('Access denied')).toBeInTheDocument()
    expect(screen.getByText(/You can only edit assessment papers you created\./)).toBeInTheDocument()
  })
})

/*
 * B1 regression — zero-extraction import must not wipe the current paper.
 *
 * Root cause: runImportDocument mutated all state (setImportedAssets, setForm,
 * setSections([]), setParts, resetUndoBaseline) BEFORE checking whether the
 * parsed file produced any questions. A zero-extraction result wiped the paper
 * and reseeded the undo stack, making recovery via Ctrl+Z impossible.
 *
 * Fix: importHasQuestions(imported) guard fires immediately after the await,
 * before any state mutation. A zero-result returns false + toast and leaves
 * the current paper completely untouched.
 *
 * Observable: after triggering a zero-extraction import the sections count
 * (exposed via BuilderView's data-section-count) must remain at its pre-import
 * value (the single starter section).
 */
describe('AssessmentStudio — zero-extraction import guard (B1)', () => {
  beforeEach(() => {
    mockParams = {}
    mockImportQuizDocument.mockResolvedValue({
      sections: [],
      questions: [],
      imageAssets: [],
      quiz: {
        title: '',
        grade: '',
        subject: '',
        sourceFileName: 'stub.pdf',
        sourceContentType: 'application/pdf',
      },
      importStatus: 'ok',
      warnings: [],
      summary: {},
      scanned: false,
      smartApplied: false,
      pageImageUrls: {},
      parts: [],
    })
  })

  it('a zero-extraction import leaves the current paper sections untouched', async () => {
    renderStudioFresh('test')
    fireEvent.click(screen.getByRole('button', { name: 'stub-new-paper' }))
    await waitFor(() => expect(screen.getByTestId('builder-view')).toBeInTheDocument())

    // The studio starts with a single blank starter section.
    expect(screen.getByTestId('builder-view').dataset.sectionCount).toBe('1')

    fireEvent.click(screen.getByRole('button', { name: 'stub-import-doc' }))

    // Wait for the async import to resolve.
    await waitFor(() => expect(mockImportQuizDocument).toHaveBeenCalledTimes(1))

    // Guard fired before mutations: starter section is preserved (count stays 1).
    expect(screen.getByTestId('builder-view').dataset.sectionCount).toBe('1')
  })
})

/*
 * F6 regression — startBlankPaper() resets createdIdRef.current to null.
 *
 * Root cause: the old inline "New paper" handler forgot to null-out
 * createdIdRef.current. The 2-second library autosave then saw the stale
 * Firestore ID and overwrote the previously-saved paper with a blank form,
 * silently destroying the teacher's work. Fix: startBlankPaper() explicitly
 * sets createdIdRef.current = null before changing the view.
 *
 * The unit-level observable: clicking the "New paper" button in HomeView
 * resets the studio to builder mode with an empty form title — proving
 * startBlankPaper() (the function that contains the fix) was called rather
 * than the old partial-reset inline handler.
 */
describe('AssessmentStudio — startBlankPaper resets form (F6)', () => {
  beforeEach(() => {
    mockParams = {}  // fresh mode — no paperId, so HomeView is shown first
  })

  it('after onNewPaper fires, builder view renders with an empty form title', async () => {
    renderStudioFresh('test')
    expect(screen.getByTestId('home-view')).toBeInTheDocument()

    fireEvent.click(screen.getByRole('button', { name: 'stub-new-paper' }))

    // startBlankPaper() calls changeView('builder') — BuilderView mounts.
    await waitFor(() => expect(screen.getByTestId('builder-view')).toBeInTheDocument())

    // makeDefaultForm() seeds title as '' — prove the form was fully reset.
    const builderEl = screen.getByTestId('builder-view')
    expect(builderEl.dataset.formTitle).toBe('')
  })
})

/*
 * Runaway-duplicate regression — a failed question write must not mint a
 * second paper.
 *
 * Root cause: in persistAssessment's create branch, `createdIdRef.current` was
 * assigned AFTER `saveAssessmentQuestions`. That call rejects on a Zod failure
 * (questionWritePayload.js) or a validQuestionFields() rules rejection, which
 * left the ref null even though the parent doc already existed. Saving is a
 * 2-second debounced autosave rather than a button, so every subsequent edit
 * re-entered the create branch and filed another orphan paper — the four
 * identical "GRADE 4 END OF TERM 1 TEST" rows in the library.
 *
 * Fix: claim the id immediately after createAssessment(), before anything that
 * can throw, so the retry is an UPDATE to the paper that already exists.
 *
 * Observable: with saveAssessmentQuestions rejecting, a second autosave cycle
 * calls createAssessment exactly once in total and routes the retry through
 * updateAssessmentWithQuestions against the id from the first create.
 */
describe('AssessmentStudio — failed question write does not duplicate the paper', () => {
  const importedPaper = {
    sections: [],
    questions: [
      {
        type: 'mcq',
        question: 'What is 2 + 2?',
        options: ['3', '4', '5', '6'],
        correctAnswer: 1,
        marks: 1,
      },
    ],
    imageAssets: [],
    quiz: {
      title: 'Imported Paper',
      grade: '4',
      subject: 'Mathematics',
      sourceFileName: 'stub.pdf',
      sourceContentType: 'application/pdf',
    },
    importStatus: 'ok',
    warnings: [],
    summary: {},
    scanned: false,
    smartApplied: false,
    pageImageUrls: {},
    parts: [],
  }

  beforeEach(() => {
    mockParams = {}
    mockImportQuizDocument.mockResolvedValue(importedPaper)
    mockCreateAssessment.mockResolvedValue('created-paper-1')
    // The failure this whole regression is about: the parent doc is written,
    // the question batch is rejected.
    mockSaveAssessmentQuestions.mockRejectedValue(new Error('permission-denied'))
    mockUpdateAssessmentWithQuestions.mockResolvedValue([])
  })

  it('claims the created id before the question write, so a retry updates instead of re-creating', async () => {
    vi.useFakeTimers({ shouldAdvanceTime: true })
    try {
      renderStudioFresh('test')
      fireEvent.click(screen.getByRole('button', { name: 'stub-new-paper' }))
      await waitFor(() => expect(screen.getByTestId('builder-view')).toBeInTheDocument())

      // Seed a real question so the library autosave gate opens
      // (shouldAutosaveToLibrary requires authoredQuestionCount > 0 +
      // libraryDirty — a blank starter question is not enough).
      fireEvent.click(screen.getByRole('button', { name: 'stub-import-doc' }))
      await waitFor(() => expect(mockImportQuizDocument).toHaveBeenCalledTimes(1))

      // First autosave: creates the parent, then the question batch rejects.
      await vi.advanceTimersByTimeAsync(2500)
      await waitFor(() => expect(mockCreateAssessment).toHaveBeenCalledTimes(1))
      await waitFor(() => expect(mockSaveAssessmentQuestions).toHaveBeenCalledTimes(1))

      // A further edit re-arms the debounced autosave (this is the keystroke
      // that used to mint orphan #2). The paper now holds work, so the import
      // goes through the "Replace current questions?" confirmation first.
      fireEvent.click(screen.getByRole('button', { name: 'stub-import-doc' }))
      fireEvent.click(await screen.findByRole('button', { name: 'Replace questions' }))
      await waitFor(() => expect(mockImportQuizDocument).toHaveBeenCalledTimes(2))
      await vi.advanceTimersByTimeAsync(2500)

      // The retry is an UPDATE to the paper that already exists…
      await waitFor(() =>
        expect(mockUpdateAssessmentWithQuestions).toHaveBeenCalledWith(
          'created-paper-1',
          expect.any(Object),
          expect.any(Array),
          expect.any(Array),
        ),
      )
      // …and no second paper was ever created.
      expect(mockCreateAssessment).toHaveBeenCalledTimes(1)
    } finally {
      vi.useRealTimers()
    }
  })
})

/*
 * Load-failure regression — a dropped questions read must not present as an
 * empty (or deleted) paper.
 *
 * Root cause: getAssessmentQuestions (useFirestore.js) swallows read failures
 * and returns []. The edit-route effect hydrated that as a real paper, set
 * savedToLibrary(true), and the next autosave wrote questionCount: 0 and
 * totalMarks: 0 over the real values — a 40-question exam emptied on screen.
 *
 * Fix: a paper whose questionCount > 0 that yields zero questions is a failed
 * read, not an empty paper. It gets its own error state, with copy that says
 * the questions are safe and a way to retry.
 */
describe('AssessmentStudio — questions read failure (load-failed state)', () => {
  beforeEach(() => {
    mockParams = { paperId: 'paper-1' }
  })

  it('shows a retryable load-failed state instead of hydrating an empty paper', async () => {
    mockGetAssessmentById.mockResolvedValue({
      id: 'paper-1', title: 'Term 2 Exam', createdBy: 'owner-1', questionCount: 40,
    })
    mockGetAssessmentQuestions.mockResolvedValue([])   // swallowed read failure

    render(<MemoryRouter><AssessmentStudio /></MemoryRouter>)

    expect(await screen.findByText(/Couldn't open this assessment paper/)).toBeInTheDocument()
    expect(screen.getByText(/Your questions are safe/)).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Try again' })).toBeInTheDocument()
    // Never the "deleted" copy — a teacher told their exam is gone rebuilds it.
    expect(screen.queryByText(/has been deleted/)).not.toBeInTheDocument()
    // The builder must not mount, so no autosave can overwrite the counts.
    expect(screen.queryByTestId('builder-view')).not.toBeInTheDocument()
  })

  it('a genuinely empty paper (questionCount 0) still opens in the builder', async () => {
    mockGetAssessmentById.mockResolvedValue({
      id: 'paper-1', title: 'Fresh Paper', createdBy: 'owner-1', questionCount: 0,
    })
    mockGetAssessmentQuestions.mockResolvedValue([])

    render(<MemoryRouter><AssessmentStudio /></MemoryRouter>)

    await waitFor(() => expect(screen.getByTestId('builder-view')).toBeInTheDocument())
    expect(screen.queryByText(/Couldn't open this/)).not.toBeInTheDocument()
  })

  it('shows load-failed (not "not found") when the assessment doc read throws', async () => {
    // getAssessmentById now re-throws on a real error so a network blip does
    // not look like a deleted paper. The loader's .catch() must surface this as
    // a retryable 'loadfailed' state, not the misleading 'notfound' copy.
    mockGetAssessmentById.mockRejectedValue(new Error('network blip'))

    render(<MemoryRouter><AssessmentStudio /></MemoryRouter>)

    expect(await screen.findByText(/Couldn't open this assessment paper/)).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Try again' })).toBeInTheDocument()
    // Not the "does not exist or has been deleted" copy.
    expect(screen.queryByText(/not exist or has been deleted/)).not.toBeInTheDocument()
    expect(screen.queryByText(/not found/i)).not.toBeInTheDocument()
  })
})
