/**
 * Zambian CBC Knowledge Base — topic seed data.
 *
 * Covers Early Childhood Education (Nursery `ECE_N` 3–4 yrs, Reception
 * `ECE_R` 4–5 yrs) and Grades 1-9 across Mathematics, English, Literacy
 * (G1-4), Integrated Science, Social Studies, Religious Education, Creative &
 * Technology Studies (CTS), and Civic Education (G8-9). Based on the 2013 and
 * 2023 Zambia Education Curriculum Frameworks and the CDC syllabi used in
 * government and CDC-aligned private schools.
 *
 * ECE entries follow the 2023 ECE syllabus (the four learning-area sheets in
 * public/syllabi/curriculum-data.json) and use the same canonical subject
 * codes the ECE teacher studios pass: `english`, `zambian_language`,
 * `numeracy` (Pre-Maths & Science) and `expressive_arts` (Creative & Tech).
 * ECE is play-based and thematic, so `term` placements are a sensible
 * sequencing aid rather than a strict termly split.
 *
 * Structure per entry:
 *   { id, grade, subject, term, topic,
 *     subtopics: [...], specificOutcomes: [...],
 *     keyCompetencies: [...], values: [...], suggestedMaterials: [...],
 *     reviewStatus: "needs_check" | "approved" }
 *
 * To extend: add more entries to this array. Nothing else needs to change —
 * cbcKnowledge.js imports from here and handles lookup.
 *
 * `reviewStatus` tracks Zambian-teacher sign-off. Every seed entry starts at
 * "needs_check"; flip an entry to "approved" once a curriculum reviewer has
 * verified its grade/subject/term placement and outcome wording.
 * `npm run cbc:validate` reports counts by status and asserts schema invariants.
 */

const TOPICS = [
  // ═══════════════════════════════════════════════════════════════════
  // EARLY CHILDHOOD EDUCATION — NURSERY (ECE_N, ages 3–4)
  // Play-based, thematic. 2023 ECE syllabus, four learning areas.
  // ═══════════════════════════════════════════════════════════════════

  // ── Nursery · English Language ──────────────────────────────────────
  {
    id: "ece-n-eng-naming",
    grade: "ECE_N", subject: "english", term: 1,
    topic: "Naming",
    subtopics: ["Own name", "Names of family members", "Things at home", "Things at school", "Things in the environment"],
    specificOutcomes: [
      "Tell their own name and the names of family members",
      "Name common objects found at home, at school and in the environment",
    ],
    keyCompetencies: ["Communication and language", "Listening skills"],
    values: ["Confidence", "Attentiveness"],
    suggestedMaterials: ["Picture cards", "Real objects from home and class", "Name cards", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-n-eng-conversation",
    grade: "ECE_N", subject: "english", term: 1,
    topic: "Conversation and Greetings",
    subtopics: ["Greetings for different times of day", "Simple commands", "Asking and giving permission", "Likes and dislikes"],
    specificOutcomes: [
      "Use appropriate greetings at different times of the day",
      "Listen and respond to simple commands",
      "Use polite language to ask for and give permission, and to talk about likes and dislikes",
    ],
    keyCompetencies: ["Communication and language", "Social and emotional skills"],
    values: ["Respect", "Politeness"],
    suggestedMaterials: ["Picture cards", "Greeting role-play prompts", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-n-eng-stories-rhymes-songs",
    grade: "ECE_N", subject: "english", term: 2,
    topic: "Stories, Rhymes and Songs",
    subtopics: ["Simple stories", "Picture stories", "Rhymes", "Tongue twisters", "Simple songs", "Simple plays (drama)"],
    specificOutcomes: [
      "Listen and respond to simple stories and interpret picture stories",
      "Recite rhymes and tongue twisters and sing simple songs",
      "Dramatise simple stories and plays",
    ],
    keyCompetencies: ["Communication and language", "Creativity and imagination"],
    values: ["Confidence", "Cooperation"],
    suggestedMaterials: ["Big picture story books", "Rhyme and song charts", "Simple props for role play", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-n-eng-pre-reading",
    grade: "ECE_N", subject: "english", term: 2,
    topic: "Pre-Reading Skills",
    subtopics: ["Book handling", "Left-to-right eye movement", "Matching", "Odd one out", "Visual memory", "Picture reading", "Initial and end sounds"],
    specificOutcomes: [
      "Demonstrate correct book-handling habits and left-to-right eye movement",
      "Read pictures, recognise their own name and recall objects from memory",
      "Recognise initial and end sounds orally in simple words",
    ],
    keyCompetencies: ["Pre-literacy", "Observation"],
    values: ["Attentiveness", "Perseverance"],
    suggestedMaterials: ["Picture books", "Name cards", "Matching and sorting cards", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-n-eng-pre-writing",
    grade: "ECE_N", subject: "english", term: 3,
    topic: "Pre-Writing and Handwriting",
    subtopics: ["Eye-hand coordination", "Sitting posture", "Finger and hand manipulation", "Pencil grip (tripod)", "Scribbling", "Pattern work", "Copying own name"],
    specificOutcomes: [
      "Hold a pencil using the tripod grip and sit with correct posture",
      "Trace lines and patterns using templates",
      "Copy their own name from a name card",
    ],
    keyCompetencies: ["Pre-writing", "Fine motor skills"],
    values: ["Perseverance", "Neatness"],
    suggestedMaterials: ["Crayons and pencils", "Pattern tracing templates", "Clay or play dough", "Name cards", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },

  // ── Nursery · Zambian Languages ─────────────────────────────────────
  {
    id: "ece-n-zam-names-greetings",
    grade: "ECE_N", subject: "zambian_language", term: 1,
    topic: "Names and Greetings",
    subtopics: ["Own name", "Names of family members", "Family relationships", "Names of body parts", "Familiar objects and animals", "Common greetings"],
    specificOutcomes: [
      "Tell their own name and the names and relationships of immediate family members in a Zambian Language",
      "Name body parts, familiar objects and animals in the home environment",
      "Use appropriate greetings for different times of the day",
    ],
    keyCompetencies: ["Communication and language", "Cultural identity"],
    values: ["Respect", "Sense of belonging"],
    suggestedMaterials: ["Picture cards", "Family photo cards", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-n-zam-conversation",
    grade: "ECE_N", subject: "zambian_language", term: 1,
    topic: "Conversations and Permission",
    subtopics: ["Family experiences", "Likes and dislikes", "Home rules", "School rules", "Asking for permission", "Following instructions and directions"],
    specificOutcomes: [
      "Talk about family experiences, likes and dislikes in a Zambian Language",
      "Use appropriate language to ask for permission",
      "Follow simple instructions and directions",
    ],
    keyCompetencies: ["Communication and language", "Social and emotional skills"],
    values: ["Respect", "Obedience"],
    suggestedMaterials: ["Role-play prompts", "Picture cards", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-n-zam-stories-rhymes",
    grade: "ECE_N", subject: "zambian_language", term: 2,
    topic: "Stories, Rhymes and Prayer",
    subtopics: ["Simple stories", "Simple rhymes", "Simple prayer"],
    specificOutcomes: [
      "Listen to a simple story told in a Zambian Language",
      "Recite a simple rhyme and say a simple prayer",
    ],
    keyCompetencies: ["Communication and language", "Cultural identity"],
    values: ["Spirituality", "Attentiveness"],
    suggestedMaterials: ["Local folk-story collections", "Rhyme charts", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-n-zam-print-sounds",
    grade: "ECE_N", subject: "zambian_language", term: 2,
    topic: "Concept of Print and Sounds",
    subtopics: ["Book handling", "Directionality", "Identifying print", "Animal and object sounds", "Syllables", "Letter sounds", "Picture interpretation"],
    specificOutcomes: [
      "Handle a book and pretend to read from left to right",
      "Imitate animal and object sounds and interpret pictures",
      "Identify syllables and letter sounds in simple oral words",
    ],
    keyCompetencies: ["Pre-literacy", "Listening skills"],
    values: ["Curiosity", "Attentiveness"],
    suggestedMaterials: ["Picture books", "Sound and picture cards", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-n-zam-handwriting",
    grade: "ECE_N", subject: "zambian_language", term: 3,
    topic: "Handwriting",
    subtopics: ["Sitting posture", "Finger manipulation", "Tripod grip", "Pattern writing", "Tracing", "Colouring", "Drawing"],
    specificOutcomes: [
      "Demonstrate correct sitting posture and hold writing tools with a tripod grip",
      "Write simple patterns and trace lines",
      "Colour shapes and drawings and draw different objects",
    ],
    keyCompetencies: ["Pre-writing", "Fine motor skills"],
    values: ["Perseverance", "Neatness"],
    suggestedMaterials: ["Crayons and pencils", "Tracing templates", "Drawing paper", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },

  // ── Nursery · Pre-Maths & Science (numeracy) ────────────────────────
  {
    id: "ece-n-num-exploring-my-world",
    grade: "ECE_N", subject: "numeracy", term: 1,
    topic: "Exploring My World",
    subtopics: ["Grouping things by characteristics", "Recognising numbers", "Recognising money"],
    specificOutcomes: [
      "Group things according to their characteristics",
      "Recognise numbers and money used in everyday life",
    ],
    keyCompetencies: ["Pre-numeracy", "Classification"],
    values: ["Curiosity", "Accuracy"],
    suggestedMaterials: ["Counters (bottle tops, stones, seeds)", "Number cards", "Toy/real coins", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-n-num-understanding-my-body",
    grade: "ECE_N", subject: "numeracy", term: 1,
    topic: "Understanding My Body",
    subtopics: ["External body parts", "Caring for the body"],
    specificOutcomes: [
      "Name the external parts of the human body",
      "Describe how to care for external parts of the body",
    ],
    keyCompetencies: ["Scientific exploration", "Self-management"],
    values: ["Cleanliness", "Responsibility"],
    suggestedMaterials: ["Body chart", "Soap, water and cloth", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-n-num-sky-seasons",
    grade: "ECE_N", subject: "numeracy", term: 2,
    topic: "Exploring the Sky and Seasons",
    subtopics: ["Time and seasons", "Activities of the day"],
    specificOutcomes: [
      "Tell the time of day by linking it to daily activities",
    ],
    keyCompetencies: ["Scientific exploration", "Observation"],
    values: ["Curiosity", "Orderliness"],
    suggestedMaterials: ["Daily routine picture chart", "Weather chart", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-n-num-understanding-materials",
    grade: "ECE_N", subject: "numeracy", term: 2,
    topic: "Understanding Materials",
    subtopics: ["Shapes and patterns", "Light and shadows"],
    specificOutcomes: [
      "Create simple shapes and patterns",
      "Demonstrate how shadows are formed",
    ],
    keyCompetencies: ["Pre-numeracy", "Scientific exploration"],
    values: ["Curiosity", "Creativity"],
    suggestedMaterials: ["Shape cut-outs", "Torch and objects for shadow play", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-n-num-exploring-mixtures",
    grade: "ECE_N", subject: "numeracy", term: 3,
    topic: "Exploring Mixtures",
    subtopics: ["Adding things", "Subtracting things", "Everyday mathematical operations"],
    specificOutcomes: [
      "Use simple addition and subtraction with objects in everyday situations",
    ],
    keyCompetencies: ["Pre-numeracy", "Problem solving"],
    values: ["Accuracy", "Cooperation"],
    suggestedMaterials: ["Counters (bottle tops, stones)", "Everyday objects for grouping", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },

  // ── Nursery · Creative & Technology Studies (expressive_arts) ───────
  {
    id: "ece-n-art-safety-hygiene",
    grade: "ECE_N", subject: "expressive_arts", term: 1,
    topic: "Safety and Hygiene",
    subtopics: ["Safety in the environment", "Food hygiene", "Personal hygiene", "Environmental hygiene"],
    specificOutcomes: [
      "Practise safety in the environment",
      "Practise food, personal and environmental hygiene",
    ],
    keyCompetencies: ["Self-management", "Health and well-being"],
    values: ["Cleanliness", "Responsibility", "Care for the environment"],
    suggestedMaterials: ["Soap, water and towel", "Litter bin", "Picture cards on safety", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-n-art-tools-ict-light",
    grade: "ECE_N", subject: "expressive_arts", term: 1,
    topic: "Tools, ICT Devices and Light",
    subtopics: ["Hand tools", "ICT devices", "Sources of light"],
    specificOutcomes: [
      "Use simple hand tools found in the immediate environment",
      "Operate ICT devices found in the locality",
      "Use sources of light to solve simple problems",
    ],
    keyCompetencies: ["Technology and innovation", "Problem solving"],
    values: ["Curiosity", "Care for property"],
    suggestedMaterials: ["Safe child-sized hand tools", "A phone or radio (with supervision)", "Torch", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-n-art-food",
    grade: "ECE_N", subject: "expressive_arts", term: 2,
    topic: "Food",
    subtopics: ["Types of food", "Sorting food by characteristics"],
    specificOutcomes: [
      "Sort different types of food according to their characteristics",
    ],
    keyCompetencies: ["Classification", "Health and well-being"],
    values: ["Healthy living", "Curiosity"],
    suggestedMaterials: ["Real or plastic food samples", "Food picture cards", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-n-art-motor-development",
    grade: "ECE_N", subject: "expressive_arts", term: 2,
    topic: "Motor Development",
    subtopics: ["Gross (locomotor) skills", "Non-locomotor skills", "Eye-hand and eye-foot coordination", "Fine motor skills"],
    specificOutcomes: [
      "Develop gross (locomotor) and non-locomotor skills",
      "Develop eye-hand and eye-foot coordination and fine motor skills",
    ],
    keyCompetencies: ["Physical development", "Coordination"],
    values: ["Perseverance", "Cooperation"],
    suggestedMaterials: ["Balls and bean bags", "Skipping ropes", "Beads for threading", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-n-art-music-dance-drama",
    grade: "ECE_N", subject: "expressive_arts", term: 2,
    topic: "Music, Dance and Drama",
    subtopics: ["Music and dance", "Rhythm and movement", "Role play"],
    specificOutcomes: [
      "Explore different types of music and dance",
      "Perform rhythm and movement and act out various roles",
    ],
    keyCompetencies: ["Creativity and imagination", "Aesthetic appreciation"],
    values: ["Confidence", "Cultural identity"],
    suggestedMaterials: ["Drums and shakers", "Local songs", "Simple costumes", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-n-art-art-crafts",
    grade: "ECE_N", subject: "expressive_arts", term: 3,
    topic: "Art and Crafts",
    subtopics: ["Drawing and tracing", "Colouring", "Patterns", "Threading", "Weaving", "Modelling and moulding", "Paper crafts"],
    specificOutcomes: [
      "Draw lines, trace objects using templates and colour objects",
      "Make simple patterns and thread and weave different items",
      "Model and mould simple artifacts and make paper crafts",
    ],
    keyCompetencies: ["Creativity and imagination", "Fine motor skills"],
    values: ["Creativity", "Neatness"],
    suggestedMaterials: ["Crayons and paper", "String and beads", "Clay or play dough", "Old paper for craft", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-n-art-games",
    grade: "ECE_N", subject: "expressive_arts", term: 3,
    topic: "Games",
    subtopics: ["Traditional games"],
    specificOutcomes: [
      "Play traditional games with others",
    ],
    keyCompetencies: ["Physical development", "Social and emotional skills"],
    values: ["Cooperation", "Fair play", "Cultural identity"],
    suggestedMaterials: ["Open play space", "Locally made play materials", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },

  // ═══════════════════════════════════════════════════════════════════
  // EARLY CHILDHOOD EDUCATION — RECEPTION (ECE_R, ages 4–5)
  // School-readiness. 2023 ECE syllabus, four learning areas.
  // ═══════════════════════════════════════════════════════════════════

  // ── Reception · English Language ────────────────────────────────────
  {
    id: "ece-r-eng-conversation",
    grade: "ECE_R", subject: "english", term: 1,
    topic: "Conversation",
    subtopics: ["Greetings", "Simple instructions", "Classroom rules", "Making requests"],
    specificOutcomes: [
      "Use appropriate greetings and make polite requests",
      "Follow simple instructions and classroom rules",
    ],
    keyCompetencies: ["Communication and language", "Social and emotional skills"],
    values: ["Respect", "Politeness"],
    suggestedMaterials: ["Classroom rules chart", "Role-play prompts", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-r-eng-naming",
    grade: "ECE_R", subject: "english", term: 1,
    topic: "Naming",
    subtopics: ["Things at home", "Things at school", "Domestic animals", "Wild animals", "Occupations", "Modes of transport"],
    specificOutcomes: [
      "Name objects found at home and at school",
      "Name domestic and wild animals",
      "Name different occupations in the community and modes of transport",
    ],
    keyCompetencies: ["Communication and language", "General knowledge"],
    values: ["Curiosity", "Confidence"],
    suggestedMaterials: ["Picture cards of animals, jobs and transport", "Real classroom objects", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-r-eng-descriptions",
    grade: "ECE_R", subject: "english", term: 1,
    topic: "Descriptions",
    subtopics: ["Primary colours", "Describing things by attributes", "Home chores", "Positions of things", "Singular and plural forms"],
    specificOutcomes: [
      "Describe objects according to primary colours and their attributes",
      "Use appropriate language to show the position of things",
      "Use appropriate vocabulary to express singular and plural forms",
    ],
    keyCompetencies: ["Communication and language", "Pre-numeracy"],
    values: ["Accuracy", "Curiosity"],
    suggestedMaterials: ["Coloured objects and cards", "Positional play items (box, ball)", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-r-eng-songs-narration-stories",
    grade: "ECE_R", subject: "english", term: 2,
    topic: "Songs, Narration and Stories",
    subtopics: ["Days of the week", "Months of the year", "Road safety rules", "Weather", "Narrating simple events", "Caring for others", "Buying and selling"],
    specificOutcomes: [
      "Name the days of the week and months of the year",
      "Narrate simple events and talk about the weather and road safety rules",
      "Use appropriate language to talk about caring for others and about buying and selling",
    ],
    keyCompetencies: ["Communication and language", "Social and emotional skills"],
    values: ["Care for others", "Responsibility"],
    suggestedMaterials: ["Calendar chart", "Weather chart", "Picture stories", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-r-eng-pre-reading",
    grade: "ECE_R", subject: "english", term: 2,
    topic: "Pre-Reading Skills",
    subtopics: ["Matching and identification", "Reading picture stories", "Initial sounds", "Counting sounds", "Blending", "Substitution", "Rhyming", "Tongue twisters"],
    specificOutcomes: [
      "Read picture stories and identify objects according to their attributes",
      "Recognise, count, blend and substitute sounds in regular words",
      "Identify rhyming words and recite tongue twisters",
    ],
    keyCompetencies: ["Pre-literacy", "Phonological awareness"],
    values: ["Attentiveness", "Perseverance"],
    suggestedMaterials: ["Picture story cards", "Sound and letter cards", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-r-eng-pre-writing",
    grade: "ECE_R", subject: "english", term: 3,
    topic: "Pre-Writing and Handwriting",
    subtopics: ["Sitting posture", "Finger manipulation", "Book handling", "Parts of a book", "Making a picture book", "Pencil grip (tripod)", "Patterns", "Copying simple words"],
    specificOutcomes: [
      "Demonstrate correct posture, tripod grip and book handling",
      "Name the parts of a book and make a simple picture book",
      "Draw lines, patterns and shapes and copy simple words",
    ],
    keyCompetencies: ["Pre-writing", "Fine motor skills"],
    values: ["Neatness", "Perseverance"],
    suggestedMaterials: ["Pencils and crayons", "Tracing templates", "Stapled blank booklets", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },

  // ── Reception · Zambian Languages ───────────────────────────────────
  {
    id: "ece-r-zam-names-greetings",
    grade: "ECE_R", subject: "zambian_language", term: 1,
    topic: "Names and Greetings",
    subtopics: ["Extended family members", "Family relationships", "Objects in the school", "Occupations", "Classifying animals", "Common greetings"],
    specificOutcomes: [
      "Name members of the extended family and tell their relationships in a Zambian Language",
      "Name objects in the school and occupations in the community",
      "Classify domestic animals according to function and use greetings for different situations",
    ],
    keyCompetencies: ["Communication and language", "Cultural identity"],
    values: ["Respect", "Sense of belonging"],
    suggestedMaterials: ["Family and animal picture cards", "School-object cards", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-r-zam-conversation-messages",
    grade: "ECE_R", subject: "zambian_language", term: 1,
    topic: "Conversations and Messages",
    subtopics: ["Emotions", "Means of communication", "Family experiences", "Taking turns", "Home and school chores", "Modes of transport", "Buying and selling", "Common signposts", "Instructions and directions"],
    specificOutcomes: [
      "Talk about emotions, chores and means of communication and take turns when conversing",
      "Role play family experiences and buying and selling",
      "Interpret common signposts and give simple instructions and directions",
    ],
    keyCompetencies: ["Communication and language", "Social and emotional skills"],
    values: ["Respect", "Cooperation"],
    suggestedMaterials: ["Signpost picture cards", "Play money and market props", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-r-zam-oral-literature",
    grade: "ECE_R", subject: "zambian_language", term: 2,
    topic: "Oral Literature",
    subtopics: ["Simple stories", "Simple rhymes", "Tongue twisters", "Riddles", "Poems", "Simple prayer"],
    specificOutcomes: [
      "Listen to simple stories told in a Zambian Language",
      "Recite simple rhymes, tongue twisters and poems and respond to simple riddles",
      "Say a simple prayer",
    ],
    keyCompetencies: ["Communication and language", "Cultural identity"],
    values: ["Cultural identity", "Spirituality"],
    suggestedMaterials: ["Local folk-story and riddle collections", "Rhyme charts", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-r-zam-pre-reading",
    grade: "ECE_R", subject: "zambian_language", term: 2,
    topic: "Pre-Reading and Reading",
    subtopics: ["Parts of a book", "Picture interpretation", "Syllables", "Initial sounds", "Letter sounds", "Listening comprehension", "Reading simple words"],
    specificOutcomes: [
      "Identify parts of a book and interpret pictures",
      "Identify syllables, initial sounds and letter sounds in oral words",
      "Blend sounds to form syllables and read simple words",
    ],
    keyCompetencies: ["Pre-literacy", "Phonological awareness"],
    values: ["Attentiveness", "Perseverance"],
    suggestedMaterials: ["Picture books", "Syllable and letter cards", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-r-zam-handwriting",
    grade: "ECE_R", subject: "zambian_language", term: 3,
    topic: "Handwriting",
    subtopics: ["Pattern writing", "Tracing", "Copying", "Colouring", "Drawing"],
    specificOutcomes: [
      "Write simple patterns, trace lines and copy simple patterns",
      "Colour shapes and drawings and draw different objects",
    ],
    keyCompetencies: ["Pre-writing", "Fine motor skills"],
    values: ["Neatness", "Perseverance"],
    suggestedMaterials: ["Crayons and pencils", "Tracing templates", "Drawing paper", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },

  // ── Reception · Pre-Maths & Science (numeracy) ──────────────────────
  {
    id: "ece-r-num-exploring-my-world",
    grade: "ECE_R", subject: "numeracy", term: 1,
    topic: "Exploring My World",
    subtopics: ["Grouping things by characteristics", "Recognising numbers", "Recognising money"],
    specificOutcomes: [
      "Group things according to their characteristics",
      "Recognise numbers and money used in everyday life",
    ],
    keyCompetencies: ["Pre-numeracy", "Classification"],
    values: ["Curiosity", "Accuracy"],
    suggestedMaterials: ["Counters (bottle tops, stones, seeds)", "Number cards", "Toy/real coins", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-r-num-understanding-my-body",
    grade: "ECE_R", subject: "numeracy", term: 1,
    topic: "Understanding My Body",
    subtopics: ["The five senses", "Caring for the senses"],
    specificOutcomes: [
      "Name the parts of the body associated with the five senses",
      "Describe how to care for the parts of the body associated with the five senses",
    ],
    keyCompetencies: ["Scientific exploration", "Self-management"],
    values: ["Cleanliness", "Responsibility"],
    suggestedMaterials: ["Five-senses picture chart", "Objects to taste, smell, touch and hear", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-r-num-sky-seasons",
    grade: "ECE_R", subject: "numeracy", term: 2,
    topic: "Exploring the Sky and Seasons",
    subtopics: ["Time and seasons", "Activities of the day"],
    specificOutcomes: [
      "Tell the time of day by linking it to daily activities",
    ],
    keyCompetencies: ["Scientific exploration", "Observation"],
    values: ["Curiosity", "Orderliness"],
    suggestedMaterials: ["Daily routine picture chart", "Weather chart", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-r-num-understanding-materials",
    grade: "ECE_R", subject: "numeracy", term: 2,
    topic: "Understanding Materials",
    subtopics: ["Shapes and patterns", "Sinking and floating", "Light and shadows"],
    specificOutcomes: [
      "Create simple shapes and patterns",
      "Recognise sinking and floating objects in everyday life",
      "Demonstrate how shadows are formed",
    ],
    keyCompetencies: ["Pre-numeracy", "Scientific exploration"],
    values: ["Curiosity", "Creativity"],
    suggestedMaterials: ["Shape cut-outs", "Basin of water with objects", "Torch for shadow play", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-r-num-exploring-mixtures",
    grade: "ECE_R", subject: "numeracy", term: 3,
    topic: "Exploring Mixtures",
    subtopics: ["Adding things", "Subtracting things", "Everyday mathematical operations"],
    specificOutcomes: [
      "Use simple addition and subtraction with objects in everyday situations",
    ],
    keyCompetencies: ["Pre-numeracy", "Problem solving"],
    values: ["Accuracy", "Cooperation"],
    suggestedMaterials: ["Counters (bottle tops, stones)", "Everyday objects for grouping", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },

  // ── Reception · Creative & Technology Studies (expressive_arts) ─────
  {
    id: "ece-r-art-safety",
    grade: "ECE_R", subject: "expressive_arts", term: 1,
    topic: "Safety",
    subtopics: ["Safety in school", "Road safety", "Storage of tools", "Personal safety (strangers)"],
    specificOutcomes: [
      "Practise safety in the school environment and on the road",
      "Store tools in designated places",
      "Recognise the dangers of interacting with strangers",
    ],
    keyCompetencies: ["Self-management", "Health and well-being"],
    values: ["Responsibility", "Self-protection"],
    suggestedMaterials: ["Road safety picture cards", "Tool storage box", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-r-art-hygiene-hospitality",
    grade: "ECE_R", subject: "expressive_arts", term: 1,
    topic: "Hygiene and Hospitality",
    subtopics: ["Food hygiene and preservation", "Personal hygiene", "Environmental hygiene", "Good manners", "Eating habits"],
    specificOutcomes: [
      "Practise personal, food and environmental hygiene",
      "Practise good manners and good eating habits",
    ],
    keyCompetencies: ["Self-management", "Social and emotional skills"],
    values: ["Cleanliness", "Good manners", "Care for the environment"],
    suggestedMaterials: ["Soap, water and towel", "Place setting for table manners", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-r-art-heat-ict-materials",
    grade: "ECE_R", subject: "expressive_arts", term: 2,
    topic: "Heat, ICT and Materials",
    subtopics: ["Sources of heat", "ICT devices", "Types of materials"],
    specificOutcomes: [
      "Explore the various sources of heat",
      "Use ICT devices and utilise different materials",
    ],
    keyCompetencies: ["Technology and innovation", "Scientific exploration"],
    values: ["Curiosity", "Care for property"],
    suggestedMaterials: ["Pictures of heat sources", "A phone or radio (with supervision)", "Assorted craft materials", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-r-art-motor-development",
    grade: "ECE_R", subject: "expressive_arts", term: 2,
    topic: "Motor Development",
    subtopics: ["Gross (locomotor) skills", "Non-locomotor skills", "Eye-hand and eye-foot coordination", "Fine motor skills"],
    specificOutcomes: [
      "Develop locomotor and non-locomotor skills",
      "Develop eye-hand and eye-foot coordination and fine motor skills",
    ],
    keyCompetencies: ["Physical development", "Coordination"],
    values: ["Perseverance", "Cooperation"],
    suggestedMaterials: ["Balls and bean bags", "Skipping ropes", "Beads for threading", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-r-art-music-dance-drama-games",
    grade: "ECE_R", subject: "expressive_arts", term: 2,
    topic: "Music, Dance, Drama and Games",
    subtopics: ["Music and movement", "Rhythm and balance", "Musical instruments", "Drama", "Traditional and conventional games"],
    specificOutcomes: [
      "Practise music, movement and rhythm and control the body to balance",
      "Play different musical instruments and dramatise different scenarios",
      "Perform traditional and conventional games",
    ],
    keyCompetencies: ["Creativity and imagination", "Physical development"],
    values: ["Confidence", "Fair play", "Cultural identity"],
    suggestedMaterials: ["Drums, shakers and rattles", "Local songs", "Open play space", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "ece-r-art-art-crafts",
    grade: "ECE_R", subject: "expressive_arts", term: 3,
    topic: "Art and Crafts",
    subtopics: ["Drawing and colouring", "Patterns", "Weaving", "Modelling and moulding", "Mosaic and collage"],
    specificOutcomes: [
      "Draw and colour pictures",
      "Make patterns, weave items and model familiar artifacts",
      "Recognise materials for making collage and mosaic pictures",
    ],
    keyCompetencies: ["Creativity and imagination", "Fine motor skills"],
    values: ["Creativity", "Neatness"],
    suggestedMaterials: ["Crayons and paper", "String and weaving strips", "Clay or play dough", "Seeds and scraps for collage", "ECE Syllabus 3–5 Years (CDC)"],
    reviewStatus: "needs_check",
  },

  // ═══════════════════════════════════════════════════════════════════
  // GRADE 1 — Foundation phase
  // ═══════════════════════════════════════════════════════════════════

  {
    id: "g1-lit-letter-sounds",
    grade: "G1", subject: "literacy", term: 1,
    topic: "Letter Sounds",
    subtopics: ["Vowel sounds (a, e, i, o, u)", "Consonant sounds", "Blending two sounds", "Recognising letters in words"],
    specificOutcomes: [
      "Identify the sound made by each letter of the alphabet",
      "Blend two sounds to make a simple word (e.g. 'at', 'it')",
    ],
    keyCompetencies: ["Communication and literacy", "Listening skills"],
    values: ["Attentiveness", "Perseverance"],
    suggestedMaterials: ["Letter sound cards", "Alphabet chart", "Grade 1 Literacy Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g1-lit-sight-words",
    grade: "G1", subject: "literacy", term: 2,
    topic: "Sight Words",
    subtopics: ["Common sight words (the, and, is, it)", "Reading sight words in sentences", "Writing sight words"],
    specificOutcomes: [
      "Read 20 common sight words at first glance",
      "Use sight words in simple sentences",
    ],
    keyCompetencies: ["Literacy", "Communication"],
    values: ["Confidence", "Perseverance"],
    suggestedMaterials: ["Sight-word flashcards", "Grade 1 Literacy Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g1-math-numbers-20",
    grade: "G1", subject: "mathematics", term: 1,
    topic: "Numbers to 20",
    subtopics: ["Counting to 20", "Reading number names", "Writing numerals", "Comparing numbers"],
    specificOutcomes: [
      "Count forwards and backwards from 1 to 20",
      "Write numerals 1-20 correctly",
      "Compare two numbers using 'more than' and 'less than'",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Number cards", "Counters (bottle tops, stones)", "Grade 1 Maths Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g1-math-addition-10",
    grade: "G1", subject: "mathematics", term: 1,
    topic: "Addition within 10",
    subtopics: ["Counting on", "Using objects to add", "Number bonds to 10", "Writing addition sentences"],
    specificOutcomes: [
      "Add two numbers whose sum is up to 10",
      "Use counters to model simple addition",
    ],
    keyCompetencies: ["Numeracy", "Problem solving"],
    values: ["Accuracy", "Cooperation"],
    suggestedMaterials: ["Counters", "Number line", "Grade 1 Maths Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g1-math-shapes-2d",
    grade: "G1", subject: "mathematics", term: 2,
    topic: "2D Shapes",
    subtopics: ["Circle", "Square", "Triangle", "Rectangle", "Shapes around us"],
    specificOutcomes: [
      "Name the four basic 2D shapes",
      "Identify 2D shapes in their environment",
    ],
    keyCompetencies: ["Observation", "Numeracy"],
    values: ["Curiosity", "Accuracy"],
    suggestedMaterials: ["Shape cut-outs", "Objects from the classroom", "Grade 1 Maths Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g1-sci-my-body",
    grade: "G1", subject: "integrated_science", term: 1,
    topic: "My Body",
    subtopics: ["External body parts", "The five senses", "Keeping my body clean", "Healthy food"],
    specificOutcomes: [
      "Name the main external parts of the body",
      "Describe what each of the five senses does",
      "Explain why personal hygiene matters",
    ],
    keyCompetencies: ["Scientific literacy", "Self-management"],
    values: ["Cleanliness", "Responsibility"],
    suggestedMaterials: ["Body chart", "Soap, water, cloth", "Grade 1 Integrated Science Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g1-sci-living-things",
    grade: "G1", subject: "integrated_science", term: 2,
    topic: "Living and Non-living Things",
    subtopics: ["Characteristics of living things", "Plants around us", "Animals around us", "Non-living things"],
    specificOutcomes: [
      "Tell the difference between living and non-living things",
      "Name common plants and animals found in Zambia",
    ],
    keyCompetencies: ["Scientific literacy", "Observation"],
    values: ["Care for the environment", "Curiosity"],
    suggestedMaterials: ["Real plant samples", "Pictures of Zambian animals", "Grade 1 Integrated Science Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g1-soc-my-family",
    grade: "G1", subject: "social_studies", term: 1,
    topic: "My Family",
    subtopics: ["Family members", "Roles in the family", "Family tree", "Respect in the family"],
    specificOutcomes: [
      "Name members of their immediate and extended family",
      "Describe the role each family member plays at home",
    ],
    keyCompetencies: ["Communication", "Citizenship"],
    values: ["Love", "Respect", "Responsibility"],
    suggestedMaterials: ["Family photographs", "Drawing paper", "Grade 1 Social Studies Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g1-eng-listening-speaking",
    grade: "G1", subject: "english", term: 1,
    topic: "Listening and Speaking",
    subtopics: ["Following instructions", "Greetings", "Simple questions and answers", "Taking turns"],
    specificOutcomes: [
      "Follow one- and two-step classroom instructions",
      "Greet and respond appropriately in English",
    ],
    keyCompetencies: ["Communication", "Collaboration"],
    values: ["Respect", "Attentiveness"],
    suggestedMaterials: ["Grade 1 English Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g1-re-gods-creation",
    grade: "G1", subject: "religious_education", term: 1,
    topic: "God the Creator",
    subtopics: ["God made the world", "Things God created", "Thanking God", "Simple prayer"],
    specificOutcomes: [
      "State that God is the creator of all things",
      "Name five things God created",
      "Say a short prayer of thanks",
    ],
    keyCompetencies: ["Communication", "Spiritual awareness"],
    values: ["Gratitude", "Reverence"],
    suggestedMaterials: ["Bible (simplified/picture)", "Creation pictures", "Grade 1 RE Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },

  // ═══════════════════════════════════════════════════════════════════
  // GRADE 2
  // ═══════════════════════════════════════════════════════════════════

  {
    id: "g2-lit-reading-simple-texts",
    grade: "G2", subject: "literacy", term: 1,
    topic: "Reading Simple Texts",
    subtopics: ["Reading short passages", "Answering questions from text", "Reading aloud fluently"],
    specificOutcomes: [
      "Read a short (3-5 sentence) passage fluently",
      "Answer simple questions about what they have read",
    ],
    keyCompetencies: ["Literacy", "Comprehension"],
    values: ["Perseverance", "Confidence"],
    suggestedMaterials: ["Grade 2 Literacy Pupil's Book (CDC)", "Chalkboard"],
    reviewStatus: "needs_check",
  },
  {
    id: "g2-math-numbers-100",
    grade: "G2", subject: "mathematics", term: 1,
    topic: "Numbers to 100",
    subtopics: ["Counting in ones", "Counting in tens", "Place value (tens and ones)", "Comparing numbers"],
    specificOutcomes: [
      "Count, read and write numbers up to 100",
      "State the place value of a digit in a two-digit number",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Place value chart", "Bundled sticks (tens and ones)", "Grade 2 Maths Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g2-math-add-sub-20",
    grade: "G2", subject: "mathematics", term: 1,
    topic: "Addition and Subtraction within 20",
    subtopics: ["Adding two 1-digit numbers", "Subtracting within 20", "Word problems", "Number bonds"],
    specificOutcomes: [
      "Add and subtract numbers with answers up to 20",
      "Solve one-step word problems using addition or subtraction",
    ],
    keyCompetencies: ["Numeracy", "Problem solving"],
    values: ["Accuracy", "Cooperation"],
    suggestedMaterials: ["Counters", "Number line", "Grade 2 Maths Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g2-math-measurement-length",
    grade: "G2", subject: "mathematics", term: 2,
    topic: "Measuring Length",
    subtopics: ["Longer and shorter", "Non-standard units (hand, foot, pencil)", "Introducing the centimetre"],
    specificOutcomes: [
      "Compare the lengths of two or more objects",
      "Measure length using non-standard units",
    ],
    keyCompetencies: ["Numeracy", "Observation"],
    values: ["Accuracy", "Cooperation"],
    suggestedMaterials: ["Ruler", "String", "Everyday classroom objects", "Grade 2 Maths Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g2-sci-plants-around-us",
    grade: "G2", subject: "integrated_science", term: 1,
    topic: "Plants Around Us",
    subtopics: ["Common plants in Zambia", "Parts of a plant", "Plants we eat", "Caring for plants"],
    specificOutcomes: [
      "Name the main parts of a plant (root, stem, leaves, flower)",
      "Identify plants that we eat (e.g. maize, beans, rape)",
    ],
    keyCompetencies: ["Scientific literacy", "Observation"],
    values: ["Care for the environment", "Curiosity"],
    suggestedMaterials: ["Real plant samples", "Grade 2 Integrated Science Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g2-soc-community",
    grade: "G2", subject: "social_studies", term: 2,
    topic: "Our Community",
    subtopics: ["People who help us", "Places in our community", "Being a good community member"],
    specificOutcomes: [
      "Name people who serve the community (teacher, nurse, police)",
      "Describe how to behave as a good community member",
    ],
    keyCompetencies: ["Citizenship", "Communication"],
    values: ["Respect", "Responsibility", "Cooperation"],
    suggestedMaterials: ["Community pictures", "Grade 2 Social Studies Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g2-eng-simple-sentences",
    grade: "G2", subject: "english", term: 1,
    topic: "Building Simple Sentences",
    subtopics: ["Subject and verb", "Using full stops", "Using capital letters", "Writing about myself"],
    specificOutcomes: [
      "Write a complete simple sentence with capital letter and full stop",
      "Produce 3-4 sentences about themselves",
    ],
    keyCompetencies: ["Communication", "Literacy"],
    values: ["Accuracy", "Confidence"],
    suggestedMaterials: ["Grade 2 English Pupil's Book (CDC)", "Exercise book"],
    reviewStatus: "needs_check",
  },

  // ═══════════════════════════════════════════════════════════════════
  // GRADE 3
  // ═══════════════════════════════════════════════════════════════════

  {
    id: "g3-math-numbers-1000",
    grade: "G3", subject: "mathematics", term: 1,
    topic: "Numbers to 1000",
    subtopics: ["Counting, reading, writing", "Place value (hundreds, tens, ones)", "Ordering numbers", "Rounding to nearest 10"],
    specificOutcomes: [
      "Read, write and order numbers up to 1000",
      "State the place value of digits in a three-digit number",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Place value chart", "Number cards", "Grade 3 Maths Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g3-math-multiplication-intro",
    grade: "G3", subject: "mathematics", term: 2,
    topic: "Introduction to Multiplication",
    subtopics: ["Multiplication as repeated addition", "Times tables 2, 5, 10", "Multiplying by 1 and 0", "Word problems"],
    specificOutcomes: [
      "Explain multiplication as repeated addition",
      "Recall multiplication facts for 2, 5 and 10 times tables",
    ],
    keyCompetencies: ["Numeracy", "Problem solving"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Counters", "Multiplication chart", "Grade 3 Maths Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g3-math-fractions-intro",
    grade: "G3", subject: "mathematics", term: 3,
    topic: "Introduction to Fractions",
    subtopics: ["Halves", "Quarters", "Thirds", "Writing fractions (1/2, 1/4)"],
    specificOutcomes: [
      "Identify halves, quarters and thirds of simple shapes",
      "Write the fraction for a shaded part",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Cooperation"],
    suggestedMaterials: ["Fraction strips", "Paper shapes", "Grade 3 Maths Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g3-math-time",
    grade: "G3", subject: "mathematics", term: 3,
    topic: "Telling Time",
    subtopics: ["O'clock", "Half past", "Quarter past and quarter to", "Days, weeks, months"],
    specificOutcomes: [
      "Read time on an analogue clock to the nearest quarter hour",
      "State how many days are in a week and months in a year",
    ],
    keyCompetencies: ["Numeracy", "Self-management"],
    values: ["Punctuality", "Accuracy"],
    suggestedMaterials: ["Analogue clock", "Calendar", "Grade 3 Maths Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g3-sci-human-body",
    grade: "G3", subject: "integrated_science", term: 1,
    topic: "The Human Body",
    subtopics: ["Main body parts", "Skeleton (simple)", "Teeth and their care", "Keeping the body clean"],
    specificOutcomes: [
      "Name the main external and internal body parts",
      "Describe how to care for teeth",
    ],
    keyCompetencies: ["Scientific literacy", "Self-management"],
    values: ["Cleanliness", "Responsibility"],
    suggestedMaterials: ["Body chart", "Toothbrush", "Grade 3 Integrated Science Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g3-sci-weather",
    grade: "G3", subject: "integrated_science", term: 2,
    topic: "Weather",
    subtopics: ["Types of weather", "Seasons in Zambia (cool, hot, rainy)", "Weather and our clothes", "Recording the weather"],
    specificOutcomes: [
      "Describe the three seasons in Zambia",
      "Record daily weather using simple symbols",
    ],
    keyCompetencies: ["Observation", "Scientific literacy"],
    values: ["Curiosity", "Responsibility"],
    suggestedMaterials: ["Weather chart", "Grade 3 Integrated Science Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g3-soc-zambia-my-country",
    grade: "G3", subject: "social_studies", term: 1,
    topic: "Zambia My Country",
    subtopics: ["Our national symbols (flag, anthem, coat of arms)", "Provinces of Zambia", "Capital city", "Zambian currency"],
    specificOutcomes: [
      "Identify the Zambian flag, coat of arms and national anthem",
      "Name the 10 provinces of Zambia and their capitals",
    ],
    keyCompetencies: ["Citizenship", "Communication"],
    values: ["Patriotism", "Respect"],
    suggestedMaterials: ["Map of Zambia", "Picture of flag and coat of arms", "Grade 3 Social Studies Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g3-eng-comprehension",
    grade: "G3", subject: "english", term: 1,
    topic: "Reading Comprehension",
    subtopics: ["Reading a short story", "Answering who / what / where / when", "New vocabulary", "Retelling the story"],
    specificOutcomes: [
      "Read a short passage and answer literal comprehension questions",
      "Retell a story in 3-4 sentences",
    ],
    keyCompetencies: ["Literacy", "Communication"],
    values: ["Attentiveness", "Perseverance"],
    suggestedMaterials: ["Grade 3 English Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g3-eng-grammar-nouns",
    grade: "G3", subject: "english", term: 2,
    topic: "Nouns",
    subtopics: ["Common nouns", "Proper nouns", "Singular and plural", "Using nouns in sentences"],
    specificOutcomes: [
      "Identify common and proper nouns in a sentence",
      "Form the plural of regular nouns",
    ],
    keyCompetencies: ["Literacy", "Communication"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Grade 3 English Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },

  // ═══════════════════════════════════════════════════════════════════
  // GRADE 4
  // ═══════════════════════════════════════════════════════════════════

  {
    id: "g4-math-numbers-10000",
    grade: "G4", subject: "mathematics", term: 1,
    topic: "Numbers to 10 000",
    subtopics: ["Place value (thousands)", "Reading and writing large numbers", "Rounding", "Ordering"],
    specificOutcomes: [
      "Read, write and order numbers up to 10 000",
      "Round a 4-digit number to the nearest 10, 100 or 1000",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Place value chart", "Grade 4 Maths Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g4-math-multiplication-tables",
    grade: "G4", subject: "mathematics", term: 1,
    topic: "Multiplication Tables and Division",
    subtopics: ["Tables 2-10", "Division as sharing", "Division as grouping", "Word problems"],
    specificOutcomes: [
      "Recall multiplication facts from 2× to 10×",
      "Solve division problems using the multiplication tables",
    ],
    keyCompetencies: ["Numeracy", "Problem solving"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Multiplication chart", "Counters", "Grade 4 Maths Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g4-math-fractions",
    grade: "G4", subject: "mathematics", term: 2,
    topic: "Fractions",
    subtopics: ["Proper and improper fractions", "Equivalent fractions (simple)", "Adding fractions with like denominators", "Comparing fractions"],
    specificOutcomes: [
      "Identify proper and improper fractions",
      "Add two fractions with the same denominator",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Cooperation"],
    suggestedMaterials: ["Fraction strips", "Grade 4 Maths Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g4-math-area-perimeter",
    grade: "G4", subject: "mathematics", term: 3,
    topic: "Area and Perimeter",
    subtopics: ["Perimeter of squares and rectangles", "Area by counting squares", "Units (cm, m)"],
    specificOutcomes: [
      "Calculate the perimeter of a rectangle given its length and width",
      "Find the area of a rectangle by counting unit squares",
    ],
    keyCompetencies: ["Numeracy", "Problem solving"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Ruler", "Grid paper", "Grade 4 Maths Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g4-sci-plant-parts",
    grade: "G4", subject: "integrated_science", term: 1,
    topic: "Parts of a Plant",
    subtopics: ["Roots and their functions", "Stem and its functions", "Leaves and photosynthesis (simple)", "Flowers and fruits"],
    specificOutcomes: [
      "Name the main parts of a plant and state each part's function",
      "Identify parts on a real plant sample",
    ],
    keyCompetencies: ["Scientific literacy", "Observation", "Collaboration"],
    values: ["Curiosity", "Care for the environment", "Cooperation"],
    suggestedMaterials: ["Real plant samples (maize, bean)", "Plant parts chart", "Grade 4 Integrated Science Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g4-sci-states-of-matter",
    grade: "G4", subject: "integrated_science", term: 2,
    topic: "States of Matter",
    subtopics: ["Solids", "Liquids", "Gases", "Changes between states (melting, freezing, evaporation)"],
    specificOutcomes: [
      "Describe the properties of solids, liquids and gases",
      "Give examples of changes of state in everyday life",
    ],
    keyCompetencies: ["Scientific literacy", "Observation"],
    values: ["Curiosity", "Accuracy"],
    suggestedMaterials: ["Ice, water, kettle demonstration", "Grade 4 Integrated Science Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g4-soc-zambia-geography",
    grade: "G4", subject: "social_studies", term: 1,
    topic: "Physical Features of Zambia",
    subtopics: ["Rivers (Zambezi, Kafue, Luangwa)", "Lakes (Kariba, Tanganyika, Bangweulu)", "Mountains and plateaus", "Using a simple map"],
    specificOutcomes: [
      "Locate major rivers and lakes of Zambia on a map",
      "Describe the main physical features of their province",
    ],
    keyCompetencies: ["Map literacy", "Citizenship"],
    values: ["Patriotism", "Care for the environment"],
    suggestedMaterials: ["Map of Zambia", "Grade 4 Social Studies Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  // Grade 4 Social Studies — official CDC "Social Studies Teaching Module,
  // Grade 4, Term 1 & 2" (Ministry of Education / Curriculum Development
  // Centre, Lusaka, 2026). The six topics (4.1–4.6) are transcribed directly
  // from that module. Term split below (Term 1: Family, Maps & Directions,
  // Governance · Term 2: Learning About the Past, Transport & Communication,
  // Weather & Climate) follows the module ordering and awaits reviewer
  // confirmation, hence reviewStatus: "needs_check".
  {
    id: "g4-soc-family",
    grade: "G4", subject: "social_studies", term: 1,
    topic: "Family",
    subtopics: ["Members of the Family", "Roles of Family Members", "Family in Different Religions"],
    specificOutcomes: [
      "Demonstrate understanding of relationships in families",
      "Express sympathy and empathy to others",
      "Show understanding of family values",
      "Perform one's roles in a family",
      "Examine teachings about family in different religions (Christianity, Islam, Hinduism and Zambian Traditional)",
    ],
    keyCompetencies: ["Analytical thinking", "Collaboration", "Emotional intelligence", "Citizenship", "Critical thinking", "Communication"],
    values: ["Love", "Respect", "Responsibility", "Kindness", "Care for others"],
    suggestedMaterials: ["Scenario cards", "Pictures showing family members", "Charts showing family values", "Role play cards", "Family roles flashcards", "Social Studies Teaching Module Grade 4 Term 1 & 2 (CDC, 2026)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g4-soc-maps-directions",
    grade: "G4", subject: "social_studies", term: 1,
    topic: "Maps and Directions",
    subtopics: ["Location of Places in the Community", "Cardinal points (North, South, East, West)", "Inter-cardinal points (NE, NW, SE, SW)"],
    specificOutcomes: [
      "Draw simple maps of the local community",
      "Use the knowledge of cardinal and inter-cardinal points to locate places in the community",
    ],
    keyCompetencies: ["Problem solving", "Collaboration", "Communication"],
    values: ["Cooperation", "Accuracy", "Teamwork"],
    suggestedMaterials: ["Maps of the school, classroom and local community", "Compass", "Charts showing cardinal and inter-cardinal points", "Social Studies Teaching Module Grade 4 Term 1 & 2 (CDC, 2026)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g4-soc-governance",
    grade: "G4", subject: "social_studies", term: 1,
    topic: "Governance",
    subtopics: ["Human Rights", "Obligations and Duties of Citizens", "Child Abuse"],
    specificOutcomes: [
      "Recognise one's rights",
      "Demonstrate patriotism for one's country",
      "Report child abuse",
    ],
    keyCompetencies: ["Communication", "Collaboration", "Critical thinking", "Problem solving", "Citizenship"],
    values: ["Responsibility", "Respect", "Patriotism", "Fairness", "Justice"],
    suggestedMaterials: ["Story cards", "Pictures of children eating, going to school and playing", "Charts illustrating types of abuse (physical, emotional, neglect)", "Flashcards of community helpers (teacher, police officer, social worker)", "Social Studies Teaching Module Grade 4 Term 1 & 2 (CDC, 2026)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g4-soc-learning-about-the-past",
    grade: "G4", subject: "social_studies", term: 2,
    topic: "Learning About the Past",
    subtopics: ["Importance of Learning About the Past", "Ways of Learning About the Past"],
    specificOutcomes: [
      "Show respect for cultural and historical identities",
      "Gather information about the past",
    ],
    keyCompetencies: ["Citizenship", "Critical thinking", "Collaboration", "Analytical thinking"],
    values: ["Respect", "Appreciation of heritage", "Cooperation"],
    suggestedMaterials: ["Pictures depicting old and new ways of life", "A resource person from the community (elder)", "Map showing where different ethnic groups live in Zambia", "Traditional objects and artefacts", "Social Studies Teaching Module Grade 4 Term 1 & 2 (CDC, 2026)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g4-soc-transport-communication",
    grade: "G4", subject: "social_studies", term: 2,
    topic: "Transport and Communication",
    subtopics: ["Forms of Transport and Communication Services", "Digital Communication Tools"],
    specificOutcomes: [
      "Recognise different forms of transport and communication services",
      "Use digital communication tools responsibly",
    ],
    keyCompetencies: ["Critical thinking", "Collaboration", "Communication", "Digital literacy"],
    values: ["Responsibility", "Safety", "Cooperation"],
    suggestedMaterials: ["Pictures showing different forms of transport and communication", "Paper and envelopes for writing letters", "Simple 'telephone' made from cups and string", "Flashcards of digital communication tools", "Social Studies Teaching Module Grade 4 Term 1 & 2 (CDC, 2026)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g4-soc-weather-climate",
    grade: "G4", subject: "social_studies", term: 2,
    topic: "Weather and Climate",
    subtopics: ["Elements of Weather and Climate (temperature, sunshine, wind, rain, cloud cover, humidity, pressure)"],
    specificOutcomes: [
      "Use appropriate instruments to measure weather and climate",
    ],
    keyCompetencies: ["Communication", "Collaboration", "Citizenship", "Digital literacy", "Environmental sustainability", "Problem solving"],
    values: ["Curiosity", "Responsibility", "Care for the environment"],
    suggestedMaterials: ["Improvised instruments (rain gauge, wind vane)", "Thermometer", "Charts showing weather elements", "Flashcards (sunny, rainy, windy, cloud)", "Social Studies Teaching Module Grade 4 Term 1 & 2 (CDC, 2026)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g4-eng-composition-narrative",
    grade: "G4", subject: "english", term: 2,
    topic: "Narrative Composition",
    subtopics: ["Beginning, middle and end", "Using descriptive words", "Writing in sequence", "Proof-reading"],
    specificOutcomes: [
      "Write a short story of 8-10 sentences with a clear beginning, middle and end",
      "Use at least three descriptive words in a piece of writing",
    ],
    keyCompetencies: ["Literacy", "Creativity", "Communication"],
    values: ["Creativity", "Perseverance"],
    suggestedMaterials: ["Grade 4 English Pupil's Book (CDC)", "Exercise book"],
    reviewStatus: "needs_check",
  },

  // ═══════════════════════════════════════════════════════════════════
  // GRADE 5
  // ═══════════════════════════════════════════════════════════════════

  {
    id: "g5-math-fractions",
    grade: "G5", subject: "mathematics", term: 2,
    topic: "Fractions",
    subtopics: ["Equivalent Fractions", "Comparing Fractions", "Adding Fractions with Like Denominators", "Adding Fractions with Unlike Denominators", "Subtracting Fractions", "Multiplying Fractions by Whole Numbers", "Word Problems with Fractions"],
    specificOutcomes: [
      "Identify the LCD of two unlike denominators",
      "Add and subtract fractions with unlike denominators",
      "Apply fraction operations to real-life word problems",
    ],
    keyCompetencies: ["Critical thinking and problem solving", "Numeracy", "Communication and collaboration"],
    values: ["Accuracy", "Perseverance", "Cooperation"],
    suggestedMaterials: ["Fraction strips (paper)", "Chalkboard and chalk", "Pupils' exercise books", "Grade 5 Mathematics Pupil's Book (CDC), pages 48-62"],
    reviewStatus: "needs_check",
  },
  {
    id: "g5-math-decimals",
    grade: "G5", subject: "mathematics", term: 2,
    topic: "Decimals",
    subtopics: ["Place Value in Decimals", "Comparing Decimals", "Adding Decimals", "Subtracting Decimals", "Converting Fractions to Decimals"],
    specificOutcomes: [
      "State the place value of digits in a decimal number",
      "Add and subtract decimals to two decimal places",
      "Convert simple fractions to decimals",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking and problem solving"],
    values: ["Accuracy", "Responsibility"],
    suggestedMaterials: ["Place value chart", "Chalkboard", "Grade 5 Mathematics Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g5-math-percentages",
    grade: "G5", subject: "mathematics", term: 3,
    topic: "Percentages",
    subtopics: ["Meaning of percent", "Converting fractions to percentages", "Finding a percentage of a quantity", "Percentages in daily life"],
    specificOutcomes: [
      "Express a fraction as a percentage",
      "Calculate a percentage of a given quantity",
    ],
    keyCompetencies: ["Numeracy", "Problem solving"],
    values: ["Accuracy", "Responsibility"],
    suggestedMaterials: ["100-square grid", "Grade 5 Mathematics Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g5-math-geometry-angles",
    grade: "G5", subject: "mathematics", term: 3,
    topic: "Angles",
    subtopics: ["Types of angles (acute, right, obtuse)", "Measuring angles with a protractor", "Angles on a straight line"],
    specificOutcomes: [
      "Classify angles as acute, right or obtuse",
      "Measure and draw angles using a protractor",
    ],
    keyCompetencies: ["Numeracy", "Observation"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Protractor", "Ruler", "Grade 5 Mathematics Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g5-math-measurement",
    grade: "G5", subject: "mathematics", term: 1,
    topic: "Measurement — Length, Mass and Capacity",
    subtopics: ["Units of length (mm, cm, m, km)", "Units of mass (g, kg)", "Units of capacity (ml, l)", "Converting between units"],
    specificOutcomes: [
      "Convert between units of length, mass and capacity",
      "Solve word problems involving measurement",
    ],
    keyCompetencies: ["Numeracy", "Problem solving"],
    values: ["Accuracy", "Cooperation"],
    suggestedMaterials: ["Ruler, weighing scale, measuring cylinder", "Grade 5 Mathematics Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g5-eng-comprehension",
    grade: "G5", subject: "english", term: 1,
    topic: "Reading Comprehension",
    subtopics: ["Main idea", "Supporting details", "Inferring meaning from context", "Summarising"],
    specificOutcomes: [
      "Identify the main idea and supporting details of a passage",
      "Infer word meanings from context",
      "Write a short summary of a passage",
    ],
    keyCompetencies: ["Literacy", "Critical thinking"],
    values: ["Attentiveness", "Perseverance"],
    suggestedMaterials: ["Grade 5 English Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g5-eng-tenses",
    grade: "G5", subject: "english", term: 2,
    topic: "Verb Tenses",
    subtopics: ["Present simple", "Past simple", "Future simple", "Using tenses in writing"],
    specificOutcomes: [
      "Form and use the simple present, simple past and simple future tenses correctly",
      "Identify the tense used in a given sentence",
    ],
    keyCompetencies: ["Literacy", "Communication"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Grade 5 English Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g5-eng-letter-writing",
    grade: "G5", subject: "english", term: 3,
    topic: "Informal Letter Writing",
    subtopics: ["Parts of an informal letter", "Writing to a friend or relative", "Layout and punctuation"],
    specificOutcomes: [
      "Write an informal letter with the correct layout",
      "Use appropriate tone and punctuation",
    ],
    keyCompetencies: ["Literacy", "Communication"],
    values: ["Respect", "Creativity"],
    suggestedMaterials: ["Sample letters", "Grade 5 English Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g5-sci-plants-photosynthesis",
    grade: "G5", subject: "integrated_science", term: 1,
    topic: "Photosynthesis",
    subtopics: ["Requirements (sunlight, water, carbon dioxide, chlorophyll)", "Products (glucose and oxygen)", "Why leaves are green", "Testing a leaf for starch (demo)"],
    specificOutcomes: [
      "State the four requirements for photosynthesis",
      "Write the simple word equation for photosynthesis",
    ],
    keyCompetencies: ["Scientific literacy", "Critical thinking"],
    values: ["Curiosity", "Care for the environment"],
    suggestedMaterials: ["Real green leaves", "Chart of photosynthesis", "Grade 5 Integrated Science Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g5-sci-digestive-system",
    grade: "G5", subject: "integrated_science", term: 2,
    topic: "The Human Digestive System",
    subtopics: ["Mouth and teeth", "Oesophagus and stomach", "Small and large intestines", "Healthy eating"],
    specificOutcomes: [
      "Name the main parts of the digestive system in order",
      "Explain what happens to food at each stage",
    ],
    keyCompetencies: ["Scientific literacy", "Self-management"],
    values: ["Responsibility", "Cleanliness"],
    suggestedMaterials: ["Digestive system chart", "Grade 5 Integrated Science Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g5-soc-zambia-history",
    grade: "G5", subject: "social_studies", term: 2,
    topic: "Pre-colonial Zambia",
    subtopics: ["Early inhabitants", "Bantu migration", "Traditional kingdoms (Lunda, Luba, Lozi, Bemba)", "Trade and culture"],
    specificOutcomes: [
      "Describe the movement of the Bantu people into what is now Zambia",
      "Name three traditional kingdoms that existed before colonial rule",
    ],
    keyCompetencies: ["Citizenship", "Critical thinking"],
    values: ["Patriotism", "Respect for heritage"],
    suggestedMaterials: ["Map of Zambia", "Grade 5 Social Studies Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g5-re-bible-stories",
    grade: "G5", subject: "religious_education", term: 1,
    topic: "Old Testament Heroes",
    subtopics: ["Abraham", "Moses", "David", "Lessons for today"],
    specificOutcomes: [
      "Retell the story of Moses leading the Israelites out of Egypt",
      "Identify one value we can learn from each Bible hero",
    ],
    keyCompetencies: ["Spiritual awareness", "Communication"],
    values: ["Faith", "Courage", "Obedience"],
    suggestedMaterials: ["Bible", "Grade 5 RE Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },

  // ═══════════════════════════════════════════════════════════════════
  // GRADE 6
  // ═══════════════════════════════════════════════════════════════════

  {
    id: "g6-math-ratio-proportion",
    grade: "G6", subject: "mathematics", term: 1,
    topic: "Ratio and Proportion",
    subtopics: ["Writing ratios", "Simplifying ratios", "Sharing in a given ratio", "Direct proportion"],
    specificOutcomes: [
      "Express a ratio in its simplest form",
      "Share a quantity in a given ratio",
      "Solve simple direct proportion problems",
    ],
    keyCompetencies: ["Numeracy", "Problem solving"],
    values: ["Accuracy", "Fairness"],
    suggestedMaterials: ["Grade 6 Mathematics Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g6-math-percentages",
    grade: "G6", subject: "mathematics", term: 1,
    topic: "Percentages and their Applications",
    subtopics: ["Percentage increase and decrease", "Discount", "Simple interest", "Profit and loss"],
    specificOutcomes: [
      "Calculate percentage increase and decrease",
      "Solve problems involving simple interest and discount",
    ],
    keyCompetencies: ["Numeracy", "Problem solving", "Entrepreneurship"],
    values: ["Accuracy", "Responsibility"],
    suggestedMaterials: ["Calculator", "Grade 6 Mathematics Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g6-math-algebra-intro",
    grade: "G6", subject: "mathematics", term: 2,
    topic: "Introduction to Algebra",
    subtopics: ["Letters as variables", "Writing simple expressions", "Evaluating expressions", "Simple linear equations"],
    specificOutcomes: [
      "Write a simple algebraic expression for a given situation",
      "Evaluate an expression when the value of the variable is given",
      "Solve one-step linear equations",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Grade 6 Mathematics Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g6-math-data-handling",
    grade: "G6", subject: "mathematics", term: 3,
    topic: "Data Handling",
    subtopics: ["Bar graphs", "Pictographs", "Mean (average)", "Mode"],
    specificOutcomes: [
      "Draw a bar graph from given data",
      "Calculate the mean and identify the mode of a set of numbers",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Cooperation"],
    suggestedMaterials: ["Graph paper", "Grade 6 Mathematics Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g6-eng-summary",
    grade: "G6", subject: "english", term: 2,
    topic: "Summary Writing",
    subtopics: ["Identifying key points", "Writing concisely", "Using own words", "Counting words"],
    specificOutcomes: [
      "Identify the key points of a passage",
      "Write a summary of a given passage in a stated number of words",
    ],
    keyCompetencies: ["Literacy", "Critical thinking"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Grade 6 English Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g6-eng-poetry",
    grade: "G6", subject: "english", term: 3,
    topic: "Poetry",
    subtopics: ["Rhyme", "Rhythm", "Simile and metaphor", "Reading a poem aloud"],
    specificOutcomes: [
      "Identify rhyme and simple similes in a poem",
      "Read a poem aloud with appropriate rhythm",
    ],
    keyCompetencies: ["Literacy", "Creativity", "Communication"],
    values: ["Creativity", "Appreciation"],
    suggestedMaterials: ["Zambian and English poetry samples", "Grade 6 English Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g6-sci-circulatory-system",
    grade: "G6", subject: "integrated_science", term: 1,
    topic: "The Circulatory System",
    subtopics: ["The heart", "Blood vessels (arteries, veins, capillaries)", "Blood composition", "Keeping the heart healthy"],
    specificOutcomes: [
      "Describe the path of blood through the heart",
      "State the function of arteries, veins and capillaries",
    ],
    keyCompetencies: ["Scientific literacy", "Self-management"],
    values: ["Responsibility", "Care for one's health"],
    suggestedMaterials: ["Circulatory system chart", "Grade 6 Integrated Science Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g6-sci-forces",
    grade: "G6", subject: "integrated_science", term: 2,
    topic: "Forces",
    subtopics: ["Push and pull", "Gravity", "Friction", "Measuring force with a spring balance"],
    specificOutcomes: [
      "Define force and give examples of pushes and pulls",
      "Explain the effect of friction on moving objects",
    ],
    keyCompetencies: ["Scientific literacy", "Observation"],
    values: ["Curiosity", "Accuracy"],
    suggestedMaterials: ["Spring balance", "Toy car", "Grade 6 Integrated Science Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g6-soc-zambia-independence",
    grade: "G6", subject: "social_studies", term: 2,
    topic: "The Road to Zambia's Independence",
    subtopics: ["Colonial rule in Northern Rhodesia", "The rise of political parties", "Kenneth Kaunda and UNIP", "24 October 1964"],
    specificOutcomes: [
      "Describe the main events leading to Zambia's independence",
      "Identify key figures in the independence movement",
    ],
    keyCompetencies: ["Citizenship", "Communication"],
    values: ["Patriotism", "Unity", "Respect for heritage"],
    suggestedMaterials: ["Historical pictures", "Grade 6 Social Studies Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },

  // ═══════════════════════════════════════════════════════════════════
  // GRADE 7 — ECZ Composite Exam preparation
  // ═══════════════════════════════════════════════════════════════════

  {
    id: "g7-math-algebra",
    grade: "G7", subject: "mathematics", term: 1,
    topic: "Algebra",
    subtopics: ["Simplifying expressions", "Expanding brackets", "Linear equations in one variable", "Word problems"],
    specificOutcomes: [
      "Simplify algebraic expressions by collecting like terms",
      "Solve linear equations of the form ax + b = c",
      "Form and solve equations from word problems",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking", "Problem solving"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Grade 7 Mathematics Pupil's Book (CDC)", "ECZ past-paper samples"],
    reviewStatus: "needs_check",
  },
  {
    id: "g7-math-geometry-triangles",
    grade: "G7", subject: "mathematics", term: 2,
    topic: "Triangles",
    subtopics: ["Types of triangles", "Angle sum of a triangle", "Isosceles and equilateral properties", "Pythagoras theorem (simple)"],
    specificOutcomes: [
      "Classify triangles by sides and by angles",
      "Use the angle sum of a triangle to find an unknown angle",
    ],
    keyCompetencies: ["Numeracy", "Observation"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Protractor, ruler, set square", "Grade 7 Mathematics Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g7-math-statistics",
    grade: "G7", subject: "mathematics", term: 3,
    topic: "Statistics",
    subtopics: ["Collecting and organising data", "Frequency tables", "Bar and line graphs", "Mean, median, mode"],
    specificOutcomes: [
      "Collect data and organise it into a frequency table",
      "Calculate mean, median and mode of a data set",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Honesty"],
    suggestedMaterials: ["Graph paper", "Grade 7 Mathematics Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g7-math-probability",
    grade: "G7", subject: "mathematics", term: 3,
    topic: "Introduction to Probability",
    subtopics: ["Certain, likely, unlikely, impossible", "Simple probability as a fraction", "Experimental probability"],
    specificOutcomes: [
      "Describe the likelihood of everyday events",
      "Calculate simple theoretical probability as a fraction",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Fairness"],
    suggestedMaterials: ["Coins, dice", "Grade 7 Mathematics Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g7-eng-composition",
    grade: "G7", subject: "english", term: 2,
    topic: "Composition Writing",
    subtopics: ["Narrative composition", "Descriptive composition", "Argumentative composition", "Planning an essay"],
    specificOutcomes: [
      "Plan and write a composition of 150-200 words",
      "Use paragraphs to organise ideas clearly",
    ],
    keyCompetencies: ["Literacy", "Creativity", "Communication"],
    values: ["Creativity", "Perseverance"],
    suggestedMaterials: ["Grade 7 English Pupil's Book (CDC)", "Exercise book"],
    reviewStatus: "needs_check",
  },
  {
    id: "g7-eng-formal-letter",
    grade: "G7", subject: "english", term: 3,
    topic: "Formal Letter Writing",
    subtopics: ["Layout of a formal letter", "Addressing", "Opening and closing formulas", "Writing a letter of complaint or enquiry"],
    specificOutcomes: [
      "Write a formal letter with correct layout and tone",
      "Use appropriate opening and closing formulas",
    ],
    keyCompetencies: ["Literacy", "Communication"],
    values: ["Respect", "Responsibility"],
    suggestedMaterials: ["Sample formal letters", "Grade 7 English Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g7-sci-electricity",
    grade: "G7", subject: "integrated_science", term: 2,
    topic: "Electricity",
    subtopics: ["Simple circuits", "Conductors and insulators", "Series and parallel circuits", "Safety with electricity"],
    specificOutcomes: [
      "Draw and build a simple electric circuit",
      "Classify common materials as conductors or insulators",
    ],
    keyCompetencies: ["Scientific literacy", "Innovation"],
    values: ["Safety", "Curiosity"],
    suggestedMaterials: ["Battery, wires, bulb, switch", "Grade 7 Integrated Science Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g7-sci-reproduction",
    grade: "G7", subject: "integrated_science", term: 3,
    topic: "Reproduction in Plants and Animals",
    subtopics: ["Parts of a flower", "Pollination and fertilisation", "Seed dispersal", "Life cycles of familiar animals"],
    specificOutcomes: [
      "Name the parts of a flower and their functions",
      "Describe pollination and seed dispersal",
    ],
    keyCompetencies: ["Scientific literacy", "Observation"],
    values: ["Curiosity", "Care for the environment"],
    suggestedMaterials: ["Real flowers (hibiscus)", "Grade 7 Integrated Science Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g7-soc-government",
    grade: "G7", subject: "social_studies", term: 1,
    topic: "Government of Zambia",
    subtopics: ["Three arms of government (Executive, Legislature, Judiciary)", "The President", "Parliament", "Elections"],
    specificOutcomes: [
      "Name the three arms of government and their roles",
      "Describe how the President is elected",
    ],
    keyCompetencies: ["Citizenship", "Critical thinking"],
    values: ["Patriotism", "Responsibility"],
    suggestedMaterials: ["Zambian constitution (simplified)", "Grade 7 Social Studies Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g7-soc-economy",
    grade: "G7", subject: "social_studies", term: 2,
    topic: "The Zambian Economy",
    subtopics: ["Copper mining", "Agriculture", "Tourism", "Small and medium-sized enterprises"],
    specificOutcomes: [
      "Name the main sectors of the Zambian economy",
      "Explain the importance of copper mining to Zambia",
    ],
    keyCompetencies: ["Citizenship", "Entrepreneurship", "Critical thinking"],
    values: ["Patriotism", "Responsibility"],
    suggestedMaterials: ["Map of Zambian mines", "Grade 7 Social Studies Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },

  // ═══════════════════════════════════════════════════════════════════
  // GRADE 8 — Junior Secondary
  // ═══════════════════════════════════════════════════════════════════

  {
    id: "g8-math-integers",
    grade: "G8", subject: "mathematics", term: 1,
    topic: "Integers",
    subtopics: ["Positive and negative numbers", "The number line", "Adding and subtracting integers", "Multiplying and dividing integers"],
    specificOutcomes: [
      "Perform the four operations on integers",
      "Apply integers to real-life contexts (temperature, profit/loss)",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Number line", "Grade 8 Mathematics Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g8-math-linear-equations",
    grade: "G8", subject: "mathematics", term: 1,
    topic: "Linear Equations",
    subtopics: ["Solving equations with one unknown", "Equations with brackets", "Equations with fractions", "Word problems"],
    specificOutcomes: [
      "Solve linear equations involving brackets and fractions",
      "Translate a word problem into a linear equation and solve it",
    ],
    keyCompetencies: ["Numeracy", "Problem solving", "Critical thinking"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Grade 8 Mathematics Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g8-math-sets",
    grade: "G8", subject: "mathematics", term: 2,
    topic: "Sets",
    subtopics: ["Set notation", "Types of sets (empty, finite, infinite, equal)", "Union and intersection", "Venn diagrams"],
    specificOutcomes: [
      "Use set notation to describe a set",
      "Find the union and intersection of two sets",
      "Use a Venn diagram to solve a two-set problem",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Grade 8 Mathematics Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g8-math-geometry-polygons",
    grade: "G8", subject: "mathematics", term: 3,
    topic: "Polygons",
    subtopics: ["Types of polygons", "Sum of interior angles", "Sum of exterior angles", "Regular polygons"],
    specificOutcomes: [
      "Calculate the sum of interior angles of any polygon",
      "Find the size of an interior angle of a regular polygon",
    ],
    keyCompetencies: ["Numeracy", "Observation"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Protractor, ruler", "Grade 8 Mathematics Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g8-eng-comprehension",
    grade: "G8", subject: "english", term: 1,
    topic: "Advanced Comprehension",
    subtopics: ["Literal questions", "Inferential questions", "Vocabulary in context", "Tone and attitude"],
    specificOutcomes: [
      "Answer literal and inferential questions on a passage",
      "Explain the meaning of words as used in a passage",
    ],
    keyCompetencies: ["Literacy", "Critical thinking"],
    values: ["Attentiveness", "Accuracy"],
    suggestedMaterials: ["Grade 8 English Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g8-eng-argumentative",
    grade: "G8", subject: "english", term: 2,
    topic: "Argumentative Composition",
    subtopics: ["Stating a position", "Supporting with reasons and evidence", "Considering the opposite view", "Concluding"],
    specificOutcomes: [
      "Write an argumentative composition of 250-300 words",
      "Support a position with at least three reasons",
    ],
    keyCompetencies: ["Literacy", "Critical thinking", "Communication"],
    values: ["Honesty", "Respect", "Integrity"],
    suggestedMaterials: ["Grade 8 English Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g8-sci-cells",
    grade: "G8", subject: "integrated_science", term: 1,
    topic: "Cells and Tissues",
    subtopics: ["Plant and animal cells (structure)", "Functions of cell parts", "Specialised cells", "Tissues"],
    specificOutcomes: [
      "Draw and label plant and animal cells",
      "State the function of the nucleus, cytoplasm, cell membrane and cell wall",
    ],
    keyCompetencies: ["Scientific literacy", "Observation"],
    values: ["Curiosity", "Accuracy"],
    suggestedMaterials: ["Microscope (if available)", "Cell diagram charts", "Grade 8 Integrated Science Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g8-sci-chemistry-atoms",
    grade: "G8", subject: "integrated_science", term: 2,
    topic: "Atoms and Elements",
    subtopics: ["Atoms and molecules", "Elements and compounds", "The periodic table (introduction)", "Chemical symbols"],
    specificOutcomes: [
      "Define atom, element, compound and molecule",
      "Write the chemical symbols of the first 20 elements",
    ],
    keyCompetencies: ["Scientific literacy", "Critical thinking"],
    values: ["Curiosity", "Accuracy"],
    suggestedMaterials: ["Periodic table", "Grade 8 Integrated Science Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g8-sci-motion",
    grade: "G8", subject: "integrated_science", term: 3,
    topic: "Motion",
    subtopics: ["Distance and displacement", "Speed, velocity, acceleration", "Distance-time graphs", "Everyday examples"],
    specificOutcomes: [
      "Distinguish between distance and displacement, speed and velocity",
      "Calculate speed using speed = distance / time",
      "Draw and interpret a simple distance-time graph",
    ],
    keyCompetencies: ["Numeracy", "Scientific literacy"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Stopwatch, measuring tape", "Grade 8 Integrated Science Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g8-civ-constitution",
    grade: "G8", subject: "civic_education", term: 1,
    topic: "The Constitution of Zambia",
    subtopics: ["What a constitution is", "The Bill of Rights", "Duties of citizens", "Amending the constitution"],
    specificOutcomes: [
      "Define a constitution",
      "List at least five fundamental rights in the Bill of Rights",
      "Describe the duties of a Zambian citizen",
    ],
    keyCompetencies: ["Citizenship", "Critical thinking", "Communication"],
    values: ["Patriotism", "Responsibility", "Justice"],
    suggestedMaterials: ["Simplified Zambian constitution", "Grade 8 Civic Education Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g8-civ-human-rights",
    grade: "G8", subject: "civic_education", term: 2,
    topic: "Human Rights",
    subtopics: ["Categories of human rights", "Child rights", "Women's rights", "Human rights institutions in Zambia (HRC)"],
    specificOutcomes: [
      "List major categories of human rights",
      "Explain three specific rights of the Zambian child",
    ],
    keyCompetencies: ["Citizenship", "Communication"],
    values: ["Respect", "Justice", "Equality"],
    suggestedMaterials: ["Child Rights booklet", "Grade 8 Civic Education Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g8-soc-zambia-history-colonial",
    grade: "G8", subject: "social_studies", term: 2,
    topic: "Colonial Rule in Northern Rhodesia",
    subtopics: ["Arrival of Europeans", "The BSA Company", "Establishment of colonial rule", "African resistance"],
    specificOutcomes: [
      "Describe how the British South Africa Company came to rule Northern Rhodesia",
      "Identify major forms of African resistance during the colonial period",
    ],
    keyCompetencies: ["Citizenship", "Critical thinking"],
    values: ["Patriotism", "Unity"],
    suggestedMaterials: ["Historical maps", "Grade 8 Social Studies Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g8-re-world-religions",
    grade: "G8", subject: "religious_education", term: 2,
    topic: "World Religions — Introduction",
    subtopics: ["Christianity", "Islam", "Hinduism", "African Traditional Religion"],
    specificOutcomes: [
      "State the main beliefs of Christianity, Islam, Hinduism and African Traditional Religion",
      "Identify one value that is common to all of them",
    ],
    keyCompetencies: ["Spiritual awareness", "Critical thinking", "Communication"],
    values: ["Respect", "Tolerance"],
    suggestedMaterials: ["Religious texts (where available)", "Grade 8 RE Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },

  // ═══════════════════════════════════════════════════════════════════
  // GRADE 9 — Junior Secondary Certificate (JSC) preparation
  // ═══════════════════════════════════════════════════════════════════

  {
    id: "g9-math-quadratic-intro",
    grade: "G9", subject: "mathematics", term: 2,
    topic: "Introduction to Quadratic Expressions",
    subtopics: ["Expanding (a+b)(c+d)", "Factorising ax + ay", "Factorising quadratic expressions of the form x² + bx + c"],
    specificOutcomes: [
      "Expand products of two binomials",
      "Factorise quadratic expressions of the form x² + bx + c",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking", "Problem solving"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Grade 9 Mathematics Pupil's Book (CDC)", "ECZ JSC past papers"],
    reviewStatus: "needs_check",
  },
  {
    id: "g9-math-simultaneous-equations",
    grade: "G9", subject: "mathematics", term: 2,
    topic: "Simultaneous Linear Equations",
    subtopics: ["Elimination method", "Substitution method", "Graphical method", "Word problems"],
    specificOutcomes: [
      "Solve a pair of simultaneous linear equations by elimination and by substitution",
      "Form and solve simultaneous equations from a word problem",
    ],
    keyCompetencies: ["Numeracy", "Problem solving"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Grade 9 Mathematics Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g9-math-trigonometry",
    grade: "G9", subject: "mathematics", term: 3,
    topic: "Introduction to Trigonometry",
    subtopics: ["Sine, cosine, tangent in a right-angled triangle", "Using trig tables or calculator", "Finding unknown sides", "Finding unknown angles"],
    specificOutcomes: [
      "State the sine, cosine and tangent ratios in a right-angled triangle",
      "Use trig ratios to find an unknown side or angle",
    ],
    keyCompetencies: ["Numeracy", "Problem solving"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Scientific calculator or trig tables", "Grade 9 Mathematics Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g9-math-mensuration",
    grade: "G9", subject: "mathematics", term: 3,
    topic: "Mensuration",
    subtopics: ["Area of triangles, circles, trapeziums", "Volume of cuboids, cylinders", "Surface area of cuboids and cylinders", "Applications"],
    specificOutcomes: [
      "Calculate the area of composite shapes",
      "Calculate the volume and surface area of cuboids and cylinders",
    ],
    keyCompetencies: ["Numeracy", "Problem solving"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Formula sheet", "Grade 9 Mathematics Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g9-eng-literature-prose",
    grade: "G9", subject: "english", term: 2,
    topic: "Prose — Setting, Plot and Character",
    subtopics: ["Setting", "Plot stages (exposition, rising action, climax, falling action, resolution)", "Characterisation", "Theme"],
    specificOutcomes: [
      "Describe the setting and plot of a prescribed short story or novel",
      "Analyse the main character using evidence from the text",
    ],
    keyCompetencies: ["Literacy", "Critical thinking", "Communication"],
    values: ["Empathy", "Integrity"],
    suggestedMaterials: ["Prescribed Zambian/African literature text", "Grade 9 English Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g9-eng-poetry-devices",
    grade: "G9", subject: "english", term: 3,
    topic: "Poetic Devices",
    subtopics: ["Simile and metaphor", "Personification", "Alliteration", "Tone and mood"],
    specificOutcomes: [
      "Identify simile, metaphor, personification and alliteration in a poem",
      "Describe the tone and mood of a poem using evidence",
    ],
    keyCompetencies: ["Literacy", "Creativity"],
    values: ["Appreciation", "Creativity"],
    suggestedMaterials: ["Zambian and African poetry anthology", "Grade 9 English Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g9-sci-genetics",
    grade: "G9", subject: "integrated_science", term: 2,
    topic: "Introduction to Genetics",
    subtopics: ["Chromosomes and genes (simple)", "Inherited and acquired traits", "Variation in humans", "Ethical issues (brief)"],
    specificOutcomes: [
      "Distinguish between inherited and acquired characteristics",
      "Give examples of variation in humans",
    ],
    keyCompetencies: ["Scientific literacy", "Critical thinking"],
    values: ["Curiosity", "Respect for diversity"],
    suggestedMaterials: ["Chart of inheritance", "Grade 9 Integrated Science Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g9-sci-acids-bases",
    grade: "G9", subject: "integrated_science", term: 2,
    topic: "Acids, Bases and Salts",
    subtopics: ["Properties of acids and bases", "Indicators and pH scale", "Neutralisation", "Common salts in daily life"],
    specificOutcomes: [
      "Classify substances as acids, bases or neutral using indicators",
      "Explain neutralisation with a word equation",
    ],
    keyCompetencies: ["Scientific literacy", "Observation"],
    values: ["Safety", "Curiosity"],
    suggestedMaterials: ["Litmus paper, lemon juice, bicarbonate of soda", "Grade 9 Integrated Science Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g9-sci-energy-transformations",
    grade: "G9", subject: "integrated_science", term: 3,
    topic: "Energy and its Transformations",
    subtopics: ["Forms of energy", "Energy conversions (e.g. chemical → electrical)", "Conservation of energy", "Renewable energy in Zambia"],
    specificOutcomes: [
      "List at least six forms of energy",
      "Describe energy conversions in common devices",
      "Discuss renewable energy sources relevant to Zambia",
    ],
    keyCompetencies: ["Scientific literacy", "Innovation", "Citizenship"],
    values: ["Responsibility", "Care for the environment"],
    suggestedMaterials: ["Pictures of solar panels, hydro plants (Kariba)", "Grade 9 Integrated Science Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g9-civ-democracy",
    grade: "G9", subject: "civic_education", term: 1,
    topic: "Democracy and Governance",
    subtopics: ["Features of a democracy", "Elections in Zambia", "Role of political parties", "Role of the citizen"],
    specificOutcomes: [
      "Describe the main features of a democracy",
      "Explain the role of elections in a democracy",
    ],
    keyCompetencies: ["Citizenship", "Communication", "Critical thinking"],
    values: ["Patriotism", "Responsibility", "Integrity"],
    suggestedMaterials: ["ECZ Voter Education pamphlets", "Grade 9 Civic Education Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g9-civ-corruption",
    grade: "G9", subject: "civic_education", term: 2,
    topic: "Corruption and Integrity",
    subtopics: ["What corruption is", "Effects on society", "Anti-Corruption Commission (ACC) of Zambia", "Promoting integrity"],
    specificOutcomes: [
      "Define corruption and give examples",
      "Describe how corruption harms society and how citizens can fight it",
    ],
    keyCompetencies: ["Citizenship", "Critical thinking"],
    values: ["Integrity", "Honesty", "Responsibility"],
    suggestedMaterials: ["ACC awareness materials", "Grade 9 Civic Education Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
  {
    id: "g9-soc-climate-change",
    grade: "G9", subject: "social_studies", term: 3,
    topic: "Climate Change and Zambia",
    subtopics: ["Causes of climate change", "Effects on Zambia (droughts, floods, agriculture)", "Mitigation and adaptation", "Role of youth"],
    specificOutcomes: [
      "Explain human causes of climate change",
      "Describe two climate-change impacts already being seen in Zambia",
      "Suggest actions that young people can take",
    ],
    keyCompetencies: ["Citizenship", "Critical thinking", "Innovation"],
    values: ["Responsibility", "Care for the environment"],
    suggestedMaterials: ["News articles on Zambian climate impacts", "Grade 9 Social Studies Pupil's Book (CDC)"],
    reviewStatus: "needs_check",
  },
]

module.exports = {TOPICS}
