/**
 * Zambian CBC Knowledge Base — topic seed data.
 *
 * Covers Grades 1-9 across Mathematics, English, Literacy (G1-4), Integrated
 * Science, Social Studies, Religious Education, Creative & Technology Studies
 * (CTS), and Civic Education (G8-9). Based on the 2013 Zambia Education
 * Curriculum Framework and the CDC syllabi used in government and CDC-aligned
 * private schools.
 *
 * Structure per entry:
 *   { id, grade, subject, term, topic,
 *     subtopics: [...], specificOutcomes: [...],
 *     keyCompetencies: [...], values: [...], suggestedMaterials: [...] }
 *
 * To extend: add more entries to this array. Nothing else needs to change —
 * cbcKnowledge.js imports from here and handles lookup.
 *
 * Review status: initial seed. Recommend a Zambian teacher collaborator
 * review this file before public launch; flag uncertain entries with a
 * `review: "needs_check"` field so we can track them.
 */

const TOPICS = [
  // ═══════════════════════════════════════════════════════════════════
  // GRADE 1 — Foundation phase
  // ═══════════════════════════════════════════════════════════════════

  {
    id: "g1-lit-letter-sounds",
    grade: "G1", subject: "literacy", term: 1,
    topic: "Letter Sounds",
    subtopics: ["Vowel sounds (a, e, i, o, u)", "Consonant sounds", "Blending two sounds", "Recognising letters in words"],
    specificOutcomes: [
      "Identify the sound made by each letter of the alphabet",
      "Blend two sounds to make a simple word (e.g. 'at', 'it')",
    ],
    keyCompetencies: ["Communication and literacy", "Listening skills"],
    values: ["Attentiveness", "Perseverance"],
    suggestedMaterials: ["Letter sound cards", "Alphabet chart", "Grade 1 Literacy Pupil's Book (CDC)"],
  },
  {
    id: "g1-lit-sight-words",
    grade: "G1", subject: "literacy", term: 2,
    topic: "Sight Words",
    subtopics: ["Common sight words (the, and, is, it)", "Reading sight words in sentences", "Writing sight words"],
    specificOutcomes: [
      "Read 20 common sight words at first glance",
      "Use sight words in simple sentences",
    ],
    keyCompetencies: ["Literacy", "Communication"],
    values: ["Confidence", "Perseverance"],
    suggestedMaterials: ["Sight-word flashcards", "Grade 1 Literacy Pupil's Book (CDC)"],
  },
  {
    id: "g1-math-numbers-20",
    grade: "G1", subject: "mathematics", term: 1,
    topic: "Numbers to 20",
    subtopics: ["Counting to 20", "Reading number names", "Writing numerals", "Comparing numbers"],
    specificOutcomes: [
      "Count forwards and backwards from 1 to 20",
      "Write numerals 1-20 correctly",
      "Compare two numbers using 'more than' and 'less than'",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Number cards", "Counters (bottle tops, stones)", "Grade 1 Maths Pupil's Book (CDC)"],
  },
  {
    id: "g1-math-addition-10",
    grade: "G1", subject: "mathematics", term: 1,
    topic: "Addition within 10",
    subtopics: ["Counting on", "Using objects to add", "Number bonds to 10", "Writing addition sentences"],
    specificOutcomes: [
      "Add two numbers whose sum is up to 10",
      "Use counters to model simple addition",
    ],
    keyCompetencies: ["Numeracy", "Problem solving"],
    values: ["Accuracy", "Cooperation"],
    suggestedMaterials: ["Counters", "Number line", "Grade 1 Maths Pupil's Book (CDC)"],
  },
  {
    id: "g1-math-shapes-2d",
    grade: "G1", subject: "mathematics", term: 2,
    topic: "2D Shapes",
    subtopics: ["Circle", "Square", "Triangle", "Rectangle", "Shapes around us"],
    specificOutcomes: [
      "Name the four basic 2D shapes",
      "Identify 2D shapes in their environment",
    ],
    keyCompetencies: ["Observation", "Numeracy"],
    values: ["Curiosity", "Accuracy"],
    suggestedMaterials: ["Shape cut-outs", "Objects from the classroom", "Grade 1 Maths Pupil's Book (CDC)"],
  },
  {
    id: "g1-sci-my-body",
    grade: "G1", subject: "integrated_science", term: 1,
    topic: "My Body",
    subtopics: ["External body parts", "The five senses", "Keeping my body clean", "Healthy food"],
    specificOutcomes: [
      "Name the main external parts of the body",
      "Describe what each of the five senses does",
      "Explain why personal hygiene matters",
    ],
    keyCompetencies: ["Scientific literacy", "Self-management"],
    values: ["Cleanliness", "Responsibility"],
    suggestedMaterials: ["Body chart", "Soap, water, cloth", "Grade 1 Integrated Science Pupil's Book (CDC)"],
  },
  {
    id: "g1-sci-living-things",
    grade: "G1", subject: "integrated_science", term: 2,
    topic: "Living and Non-living Things",
    subtopics: ["Characteristics of living things", "Plants around us", "Animals around us", "Non-living things"],
    specificOutcomes: [
      "Tell the difference between living and non-living things",
      "Name common plants and animals found in Zambia",
    ],
    keyCompetencies: ["Scientific literacy", "Observation"],
    values: ["Care for the environment", "Curiosity"],
    suggestedMaterials: ["Real plant samples", "Pictures of Zambian animals", "Grade 1 Integrated Science Pupil's Book (CDC)"],
  },
  {
    id: "g1-soc-my-family",
    grade: "G1", subject: "social_studies", term: 1,
    topic: "My Family",
    subtopics: ["Family members", "Roles in the family", "Family tree", "Respect in the family"],
    specificOutcomes: [
      "Name members of their immediate and extended family",
      "Describe the role each family member plays at home",
    ],
    keyCompetencies: ["Communication", "Citizenship"],
    values: ["Love", "Respect", "Responsibility"],
    suggestedMaterials: ["Family photographs", "Drawing paper", "Grade 1 Social Studies Pupil's Book (CDC)"],
  },
  {
    id: "g1-eng-listening-speaking",
    grade: "G1", subject: "english", term: 1,
    topic: "Listening and Speaking",
    subtopics: ["Following instructions", "Greetings", "Simple questions and answers", "Taking turns"],
    specificOutcomes: [
      "Follow one- and two-step classroom instructions",
      "Greet and respond appropriately in English",
    ],
    keyCompetencies: ["Communication", "Collaboration"],
    values: ["Respect", "Attentiveness"],
    suggestedMaterials: ["Grade 1 English Pupil's Book (CDC)"],
  },
  {
    id: "g1-re-gods-creation",
    grade: "G1", subject: "religious_education", term: 1,
    topic: "God the Creator",
    subtopics: ["God made the world", "Things God created", "Thanking God", "Simple prayer"],
    specificOutcomes: [
      "State that God is the creator of all things",
      "Name five things God created",
      "Say a short prayer of thanks",
    ],
    keyCompetencies: ["Communication", "Spiritual awareness"],
    values: ["Gratitude", "Reverence"],
    suggestedMaterials: ["Bible (simplified/picture)", "Creation pictures", "Grade 1 RE Pupil's Book (CDC)"],
  },

  // ═══════════════════════════════════════════════════════════════════
  // GRADE 2
  // ═══════════════════════════════════════════════════════════════════

  {
    id: "g2-lit-reading-simple-texts",
    grade: "G2", subject: "literacy", term: 1,
    topic: "Reading Simple Texts",
    subtopics: ["Reading short passages", "Answering questions from text", "Reading aloud fluently"],
    specificOutcomes: [
      "Read a short (3-5 sentence) passage fluently",
      "Answer simple questions about what they have read",
    ],
    keyCompetencies: ["Literacy", "Comprehension"],
    values: ["Perseverance", "Confidence"],
    suggestedMaterials: ["Grade 2 Literacy Pupil's Book (CDC)", "Chalkboard"],
  },
  {
    id: "g2-math-numbers-100",
    grade: "G2", subject: "mathematics", term: 1,
    topic: "Numbers to 100",
    subtopics: ["Counting in ones", "Counting in tens", "Place value (tens and ones)", "Comparing numbers"],
    specificOutcomes: [
      "Count, read and write numbers up to 100",
      "State the place value of a digit in a two-digit number",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Place value chart", "Bundled sticks (tens and ones)", "Grade 2 Maths Pupil's Book (CDC)"],
  },
  {
    id: "g2-math-add-sub-20",
    grade: "G2", subject: "mathematics", term: 1,
    topic: "Addition and Subtraction within 20",
    subtopics: ["Adding two 1-digit numbers", "Subtracting within 20", "Word problems", "Number bonds"],
    specificOutcomes: [
      "Add and subtract numbers with answers up to 20",
      "Solve one-step word problems using addition or subtraction",
    ],
    keyCompetencies: ["Numeracy", "Problem solving"],
    values: ["Accuracy", "Cooperation"],
    suggestedMaterials: ["Counters", "Number line", "Grade 2 Maths Pupil's Book (CDC)"],
  },
  {
    id: "g2-math-measurement-length",
    grade: "G2", subject: "mathematics", term: 2,
    topic: "Measuring Length",
    subtopics: ["Longer and shorter", "Non-standard units (hand, foot, pencil)", "Introducing the centimetre"],
    specificOutcomes: [
      "Compare the lengths of two or more objects",
      "Measure length using non-standard units",
    ],
    keyCompetencies: ["Numeracy", "Observation"],
    values: ["Accuracy", "Cooperation"],
    suggestedMaterials: ["Ruler", "String", "Everyday classroom objects", "Grade 2 Maths Pupil's Book (CDC)"],
  },
  {
    id: "g2-sci-plants-around-us",
    grade: "G2", subject: "integrated_science", term: 1,
    topic: "Plants Around Us",
    subtopics: ["Common plants in Zambia", "Parts of a plant", "Plants we eat", "Caring for plants"],
    specificOutcomes: [
      "Name the main parts of a plant (root, stem, leaves, flower)",
      "Identify plants that we eat (e.g. maize, beans, rape)",
    ],
    keyCompetencies: ["Scientific literacy", "Observation"],
    values: ["Care for the environment", "Curiosity"],
    suggestedMaterials: ["Real plant samples", "Grade 2 Integrated Science Pupil's Book (CDC)"],
  },
  {
    id: "g2-soc-community",
    grade: "G2", subject: "social_studies", term: 2,
    topic: "Our Community",
    subtopics: ["People who help us", "Places in our community", "Being a good community member"],
    specificOutcomes: [
      "Name people who serve the community (teacher, nurse, police)",
      "Describe how to behave as a good community member",
    ],
    keyCompetencies: ["Citizenship", "Communication"],
    values: ["Respect", "Responsibility", "Cooperation"],
    suggestedMaterials: ["Community pictures", "Grade 2 Social Studies Pupil's Book (CDC)"],
  },
  {
    id: "g2-eng-simple-sentences",
    grade: "G2", subject: "english", term: 1,
    topic: "Building Simple Sentences",
    subtopics: ["Subject and verb", "Using full stops", "Using capital letters", "Writing about myself"],
    specificOutcomes: [
      "Write a complete simple sentence with capital letter and full stop",
      "Produce 3-4 sentences about themselves",
    ],
    keyCompetencies: ["Communication", "Literacy"],
    values: ["Accuracy", "Confidence"],
    suggestedMaterials: ["Grade 2 English Pupil's Book (CDC)", "Exercise book"],
  },

  // ═══════════════════════════════════════════════════════════════════
  // GRADE 3
  // ═══════════════════════════════════════════════════════════════════

  {
    id: "g3-math-numbers-1000",
    grade: "G3", subject: "mathematics", term: 1,
    topic: "Numbers to 1000",
    subtopics: ["Counting, reading, writing", "Place value (hundreds, tens, ones)", "Ordering numbers", "Rounding to nearest 10"],
    specificOutcomes: [
      "Read, write and order numbers up to 1000",
      "State the place value of digits in a three-digit number",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Place value chart", "Number cards", "Grade 3 Maths Pupil's Book (CDC)"],
  },
  {
    id: "g3-math-multiplication-intro",
    grade: "G3", subject: "mathematics", term: 2,
    topic: "Introduction to Multiplication",
    subtopics: ["Multiplication as repeated addition", "Times tables 2, 5, 10", "Multiplying by 1 and 0", "Word problems"],
    specificOutcomes: [
      "Explain multiplication as repeated addition",
      "Recall multiplication facts for 2, 5 and 10 times tables",
    ],
    keyCompetencies: ["Numeracy", "Problem solving"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Counters", "Multiplication chart", "Grade 3 Maths Pupil's Book (CDC)"],
  },
  {
    id: "g3-math-fractions-intro",
    grade: "G3", subject: "mathematics", term: 3,
    topic: "Introduction to Fractions",
    subtopics: ["Halves", "Quarters", "Thirds", "Writing fractions (1/2, 1/4)"],
    specificOutcomes: [
      "Identify halves, quarters and thirds of simple shapes",
      "Write the fraction for a shaded part",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Cooperation"],
    suggestedMaterials: ["Fraction strips", "Paper shapes", "Grade 3 Maths Pupil's Book (CDC)"],
  },
  {
    id: "g3-math-time",
    grade: "G3", subject: "mathematics", term: 3,
    topic: "Telling Time",
    subtopics: ["O'clock", "Half past", "Quarter past and quarter to", "Days, weeks, months"],
    specificOutcomes: [
      "Read time on an analogue clock to the nearest quarter hour",
      "State how many days are in a week and months in a year",
    ],
    keyCompetencies: ["Numeracy", "Self-management"],
    values: ["Punctuality", "Accuracy"],
    suggestedMaterials: ["Analogue clock", "Calendar", "Grade 3 Maths Pupil's Book (CDC)"],
  },
  {
    id: "g3-sci-human-body",
    grade: "G3", subject: "integrated_science", term: 1,
    topic: "The Human Body",
    subtopics: ["Main body parts", "Skeleton (simple)", "Teeth and their care", "Keeping the body clean"],
    specificOutcomes: [
      "Name the main external and internal body parts",
      "Describe how to care for teeth",
    ],
    keyCompetencies: ["Scientific literacy", "Self-management"],
    values: ["Cleanliness", "Responsibility"],
    suggestedMaterials: ["Body chart", "Toothbrush", "Grade 3 Integrated Science Pupil's Book (CDC)"],
  },
  {
    id: "g3-sci-weather",
    grade: "G3", subject: "integrated_science", term: 2,
    topic: "Weather",
    subtopics: ["Types of weather", "Seasons in Zambia (cool, hot, rainy)", "Weather and our clothes", "Recording the weather"],
    specificOutcomes: [
      "Describe the three seasons in Zambia",
      "Record daily weather using simple symbols",
    ],
    keyCompetencies: ["Observation", "Scientific literacy"],
    values: ["Curiosity", "Responsibility"],
    suggestedMaterials: ["Weather chart", "Grade 3 Integrated Science Pupil's Book (CDC)"],
  },
  {
    id: "g3-soc-zambia-my-country",
    grade: "G3", subject: "social_studies", term: 1,
    topic: "Zambia My Country",
    subtopics: ["Our national symbols (flag, anthem, coat of arms)", "Provinces of Zambia", "Capital city", "Zambian currency"],
    specificOutcomes: [
      "Identify the Zambian flag, coat of arms and national anthem",
      "Name the 10 provinces of Zambia and their capitals",
    ],
    keyCompetencies: ["Citizenship", "Communication"],
    values: ["Patriotism", "Respect"],
    suggestedMaterials: ["Map of Zambia", "Picture of flag and coat of arms", "Grade 3 Social Studies Pupil's Book (CDC)"],
  },
  {
    id: "g3-eng-comprehension",
    grade: "G3", subject: "english", term: 1,
    topic: "Reading Comprehension",
    subtopics: ["Reading a short story", "Answering who / what / where / when", "New vocabulary", "Retelling the story"],
    specificOutcomes: [
      "Read a short passage and answer literal comprehension questions",
      "Retell a story in 3-4 sentences",
    ],
    keyCompetencies: ["Literacy", "Communication"],
    values: ["Attentiveness", "Perseverance"],
    suggestedMaterials: ["Grade 3 English Pupil's Book (CDC)"],
  },
  {
    id: "g3-eng-grammar-nouns",
    grade: "G3", subject: "english", term: 2,
    topic: "Nouns",
    subtopics: ["Common nouns", "Proper nouns", "Singular and plural", "Using nouns in sentences"],
    specificOutcomes: [
      "Identify common and proper nouns in a sentence",
      "Form the plural of regular nouns",
    ],
    keyCompetencies: ["Literacy", "Communication"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Grade 3 English Pupil's Book (CDC)"],
  },

  // ═══════════════════════════════════════════════════════════════════
  // GRADE 4
  // ═══════════════════════════════════════════════════════════════════

  {
    id: "g4-math-numbers-10000",
    grade: "G4", subject: "mathematics", term: 1,
    topic: "Numbers to 10 000",
    subtopics: ["Place value (thousands)", "Reading and writing large numbers", "Rounding", "Ordering"],
    specificOutcomes: [
      "Read, write and order numbers up to 10 000",
      "Round a 4-digit number to the nearest 10, 100 or 1000",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Place value chart", "Grade 4 Maths Pupil's Book (CDC)"],
  },
  {
    id: "g4-math-multiplication-tables",
    grade: "G4", subject: "mathematics", term: 1,
    topic: "Multiplication Tables and Division",
    subtopics: ["Tables 2-10", "Division as sharing", "Division as grouping", "Word problems"],
    specificOutcomes: [
      "Recall multiplication facts from 2× to 10×",
      "Solve division problems using the multiplication tables",
    ],
    keyCompetencies: ["Numeracy", "Problem solving"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Multiplication chart", "Counters", "Grade 4 Maths Pupil's Book (CDC)"],
  },
  {
    id: "g4-math-fractions",
    grade: "G4", subject: "mathematics", term: 2,
    topic: "Fractions",
    subtopics: ["Proper and improper fractions", "Equivalent fractions (simple)", "Adding fractions with like denominators", "Comparing fractions"],
    specificOutcomes: [
      "Identify proper and improper fractions",
      "Add two fractions with the same denominator",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Cooperation"],
    suggestedMaterials: ["Fraction strips", "Grade 4 Maths Pupil's Book (CDC)"],
  },
  {
    id: "g4-math-area-perimeter",
    grade: "G4", subject: "mathematics", term: 3,
    topic: "Area and Perimeter",
    subtopics: ["Perimeter of squares and rectangles", "Area by counting squares", "Units (cm, m)"],
    specificOutcomes: [
      "Calculate the perimeter of a rectangle given its length and width",
      "Find the area of a rectangle by counting unit squares",
    ],
    keyCompetencies: ["Numeracy", "Problem solving"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Ruler", "Grid paper", "Grade 4 Maths Pupil's Book (CDC)"],
  },
  {
    id: "g4-sci-plant-parts",
    grade: "G4", subject: "integrated_science", term: 1,
    topic: "Parts of a Plant",
    subtopics: ["Roots and their functions", "Stem and its functions", "Leaves and photosynthesis (simple)", "Flowers and fruits"],
    specificOutcomes: [
      "Name the main parts of a plant and state each part's function",
      "Identify parts on a real plant sample",
    ],
    keyCompetencies: ["Scientific literacy", "Observation", "Collaboration"],
    values: ["Curiosity", "Care for the environment", "Cooperation"],
    suggestedMaterials: ["Real plant samples (maize, bean)", "Plant parts chart", "Grade 4 Integrated Science Pupil's Book (CDC)"],
  },
  {
    id: "g4-sci-states-of-matter",
    grade: "G4", subject: "integrated_science", term: 2,
    topic: "States of Matter",
    subtopics: ["Solids", "Liquids", "Gases", "Changes between states (melting, freezing, evaporation)"],
    specificOutcomes: [
      "Describe the properties of solids, liquids and gases",
      "Give examples of changes of state in everyday life",
    ],
    keyCompetencies: ["Scientific literacy", "Observation"],
    values: ["Curiosity", "Accuracy"],
    suggestedMaterials: ["Ice, water, kettle demonstration", "Grade 4 Integrated Science Pupil's Book (CDC)"],
  },
  {
    id: "g4-soc-zambia-geography",
    grade: "G4", subject: "social_studies", term: 1,
    topic: "Physical Features of Zambia",
    subtopics: ["Rivers (Zambezi, Kafue, Luangwa)", "Lakes (Kariba, Tanganyika, Bangweulu)", "Mountains and plateaus", "Using a simple map"],
    specificOutcomes: [
      "Locate major rivers and lakes of Zambia on a map",
      "Describe the main physical features of their province",
    ],
    keyCompetencies: ["Map literacy", "Citizenship"],
    values: ["Patriotism", "Care for the environment"],
    suggestedMaterials: ["Map of Zambia", "Grade 4 Social Studies Pupil's Book (CDC)"],
  },
  {
    id: "g4-eng-composition-narrative",
    grade: "G4", subject: "english", term: 2,
    topic: "Narrative Composition",
    subtopics: ["Beginning, middle and end", "Using descriptive words", "Writing in sequence", "Proof-reading"],
    specificOutcomes: [
      "Write a short story of 8-10 sentences with a clear beginning, middle and end",
      "Use at least three descriptive words in a piece of writing",
    ],
    keyCompetencies: ["Literacy", "Creativity", "Communication"],
    values: ["Creativity", "Perseverance"],
    suggestedMaterials: ["Grade 4 English Pupil's Book (CDC)", "Exercise book"],
  },

  // ═══════════════════════════════════════════════════════════════════
  // GRADE 5
  // ═══════════════════════════════════════════════════════════════════

  {
    id: "g5-math-fractions",
    grade: "G5", subject: "mathematics", term: 2,
    topic: "Fractions",
    subtopics: ["Equivalent Fractions", "Comparing Fractions", "Adding Fractions with Like Denominators", "Adding Fractions with Unlike Denominators", "Subtracting Fractions", "Multiplying Fractions by Whole Numbers", "Word Problems with Fractions"],
    specificOutcomes: [
      "Identify the LCD of two unlike denominators",
      "Add and subtract fractions with unlike denominators",
      "Apply fraction operations to real-life word problems",
    ],
    keyCompetencies: ["Critical thinking and problem solving", "Numeracy", "Communication and collaboration"],
    values: ["Accuracy", "Perseverance", "Cooperation"],
    suggestedMaterials: ["Fraction strips (paper)", "Chalkboard and chalk", "Pupils' exercise books", "Grade 5 Mathematics Pupil's Book (CDC), pages 48-62"],
  },
  {
    id: "g5-math-decimals",
    grade: "G5", subject: "mathematics", term: 2,
    topic: "Decimals",
    subtopics: ["Place Value in Decimals", "Comparing Decimals", "Adding Decimals", "Subtracting Decimals", "Converting Fractions to Decimals"],
    specificOutcomes: [
      "State the place value of digits in a decimal number",
      "Add and subtract decimals to two decimal places",
      "Convert simple fractions to decimals",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking and problem solving"],
    values: ["Accuracy", "Responsibility"],
    suggestedMaterials: ["Place value chart", "Chalkboard", "Grade 5 Mathematics Pupil's Book (CDC)"],
  },
  {
    id: "g5-math-percentages",
    grade: "G5", subject: "mathematics", term: 3,
    topic: "Percentages",
    subtopics: ["Meaning of percent", "Converting fractions to percentages", "Finding a percentage of a quantity", "Percentages in daily life"],
    specificOutcomes: [
      "Express a fraction as a percentage",
      "Calculate a percentage of a given quantity",
    ],
    keyCompetencies: ["Numeracy", "Problem solving"],
    values: ["Accuracy", "Responsibility"],
    suggestedMaterials: ["100-square grid", "Grade 5 Mathematics Pupil's Book (CDC)"],
  },
  {
    id: "g5-math-geometry-angles",
    grade: "G5", subject: "mathematics", term: 3,
    topic: "Angles",
    subtopics: ["Types of angles (acute, right, obtuse)", "Measuring angles with a protractor", "Angles on a straight line"],
    specificOutcomes: [
      "Classify angles as acute, right or obtuse",
      "Measure and draw angles using a protractor",
    ],
    keyCompetencies: ["Numeracy", "Observation"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Protractor", "Ruler", "Grade 5 Mathematics Pupil's Book (CDC)"],
  },
  {
    id: "g5-math-measurement",
    grade: "G5", subject: "mathematics", term: 1,
    topic: "Measurement — Length, Mass and Capacity",
    subtopics: ["Units of length (mm, cm, m, km)", "Units of mass (g, kg)", "Units of capacity (ml, l)", "Converting between units"],
    specificOutcomes: [
      "Convert between units of length, mass and capacity",
      "Solve word problems involving measurement",
    ],
    keyCompetencies: ["Numeracy", "Problem solving"],
    values: ["Accuracy", "Cooperation"],
    suggestedMaterials: ["Ruler, weighing scale, measuring cylinder", "Grade 5 Mathematics Pupil's Book (CDC)"],
  },
  {
    id: "g5-eng-comprehension",
    grade: "G5", subject: "english", term: 1,
    topic: "Reading Comprehension",
    subtopics: ["Main idea", "Supporting details", "Inferring meaning from context", "Summarising"],
    specificOutcomes: [
      "Identify the main idea and supporting details of a passage",
      "Infer word meanings from context",
      "Write a short summary of a passage",
    ],
    keyCompetencies: ["Literacy", "Critical thinking"],
    values: ["Attentiveness", "Perseverance"],
    suggestedMaterials: ["Grade 5 English Pupil's Book (CDC)"],
  },
  {
    id: "g5-eng-tenses",
    grade: "G5", subject: "english", term: 2,
    topic: "Verb Tenses",
    subtopics: ["Present simple", "Past simple", "Future simple", "Using tenses in writing"],
    specificOutcomes: [
      "Form and use the simple present, simple past and simple future tenses correctly",
      "Identify the tense used in a given sentence",
    ],
    keyCompetencies: ["Literacy", "Communication"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Grade 5 English Pupil's Book (CDC)"],
  },
  {
    id: "g5-eng-letter-writing",
    grade: "G5", subject: "english", term: 3,
    topic: "Informal Letter Writing",
    subtopics: ["Parts of an informal letter", "Writing to a friend or relative", "Layout and punctuation"],
    specificOutcomes: [
      "Write an informal letter with the correct layout",
      "Use appropriate tone and punctuation",
    ],
    keyCompetencies: ["Literacy", "Communication"],
    values: ["Respect", "Creativity"],
    suggestedMaterials: ["Sample letters", "Grade 5 English Pupil's Book (CDC)"],
  },
  {
    id: "g5-sci-plants-photosynthesis",
    grade: "G5", subject: "integrated_science", term: 1,
    topic: "Photosynthesis",
    subtopics: ["Requirements (sunlight, water, carbon dioxide, chlorophyll)", "Products (glucose and oxygen)", "Why leaves are green", "Testing a leaf for starch (demo)"],
    specificOutcomes: [
      "State the four requirements for photosynthesis",
      "Write the simple word equation for photosynthesis",
    ],
    keyCompetencies: ["Scientific literacy", "Critical thinking"],
    values: ["Curiosity", "Care for the environment"],
    suggestedMaterials: ["Real green leaves", "Chart of photosynthesis", "Grade 5 Integrated Science Pupil's Book (CDC)"],
  },
  {
    id: "g5-sci-digestive-system",
    grade: "G5", subject: "integrated_science", term: 2,
    topic: "The Human Digestive System",
    subtopics: ["Mouth and teeth", "Oesophagus and stomach", "Small and large intestines", "Healthy eating"],
    specificOutcomes: [
      "Name the main parts of the digestive system in order",
      "Explain what happens to food at each stage",
    ],
    keyCompetencies: ["Scientific literacy", "Self-management"],
    values: ["Responsibility", "Cleanliness"],
    suggestedMaterials: ["Digestive system chart", "Grade 5 Integrated Science Pupil's Book (CDC)"],
  },
  {
    id: "g5-soc-zambia-history",
    grade: "G5", subject: "social_studies", term: 2,
    topic: "Pre-colonial Zambia",
    subtopics: ["Early inhabitants", "Bantu migration", "Traditional kingdoms (Lunda, Luba, Lozi, Bemba)", "Trade and culture"],
    specificOutcomes: [
      "Describe the movement of the Bantu people into what is now Zambia",
      "Name three traditional kingdoms that existed before colonial rule",
    ],
    keyCompetencies: ["Citizenship", "Critical thinking"],
    values: ["Patriotism", "Respect for heritage"],
    suggestedMaterials: ["Map of Zambia", "Grade 5 Social Studies Pupil's Book (CDC)"],
  },
  {
    id: "g5-re-bible-stories",
    grade: "G5", subject: "religious_education", term: 1,
    topic: "Old Testament Heroes",
    subtopics: ["Abraham", "Moses", "David", "Lessons for today"],
    specificOutcomes: [
      "Retell the story of Moses leading the Israelites out of Egypt",
      "Identify one value we can learn from each Bible hero",
    ],
    keyCompetencies: ["Spiritual awareness", "Communication"],
    values: ["Faith", "Courage", "Obedience"],
    suggestedMaterials: ["Bible", "Grade 5 RE Pupil's Book (CDC)"],
  },

  // ═══════════════════════════════════════════════════════════════════
  // GRADE 6
  // ═══════════════════════════════════════════════════════════════════

  {
    id: "g6-math-ratio-proportion",
    grade: "G6", subject: "mathematics", term: 1,
    topic: "Ratio and Proportion",
    subtopics: ["Writing ratios", "Simplifying ratios", "Sharing in a given ratio", "Direct proportion"],
    specificOutcomes: [
      "Express a ratio in its simplest form",
      "Share a quantity in a given ratio",
      "Solve simple direct proportion problems",
    ],
    keyCompetencies: ["Numeracy", "Problem solving"],
    values: ["Accuracy", "Fairness"],
    suggestedMaterials: ["Grade 6 Mathematics Pupil's Book (CDC)"],
  },
  {
    id: "g6-math-percentages",
    grade: "G6", subject: "mathematics", term: 1,
    topic: "Percentages and their Applications",
    subtopics: ["Percentage increase and decrease", "Discount", "Simple interest", "Profit and loss"],
    specificOutcomes: [
      "Calculate percentage increase and decrease",
      "Solve problems involving simple interest and discount",
    ],
    keyCompetencies: ["Numeracy", "Problem solving", "Entrepreneurship"],
    values: ["Accuracy", "Responsibility"],
    suggestedMaterials: ["Calculator", "Grade 6 Mathematics Pupil's Book (CDC)"],
  },
  {
    id: "g6-math-algebra-intro",
    grade: "G6", subject: "mathematics", term: 2,
    topic: "Introduction to Algebra",
    subtopics: ["Letters as variables", "Writing simple expressions", "Evaluating expressions", "Simple linear equations"],
    specificOutcomes: [
      "Write a simple algebraic expression for a given situation",
      "Evaluate an expression when the value of the variable is given",
      "Solve one-step linear equations",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Grade 6 Mathematics Pupil's Book (CDC)"],
  },
  {
    id: "g6-math-data-handling",
    grade: "G6", subject: "mathematics", term: 3,
    topic: "Data Handling",
    subtopics: ["Bar graphs", "Pictographs", "Mean (average)", "Mode"],
    specificOutcomes: [
      "Draw a bar graph from given data",
      "Calculate the mean and identify the mode of a set of numbers",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Cooperation"],
    suggestedMaterials: ["Graph paper", "Grade 6 Mathematics Pupil's Book (CDC)"],
  },
  {
    id: "g6-eng-summary",
    grade: "G6", subject: "english", term: 2,
    topic: "Summary Writing",
    subtopics: ["Identifying key points", "Writing concisely", "Using own words", "Counting words"],
    specificOutcomes: [
      "Identify the key points of a passage",
      "Write a summary of a given passage in a stated number of words",
    ],
    keyCompetencies: ["Literacy", "Critical thinking"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Grade 6 English Pupil's Book (CDC)"],
  },
  {
    id: "g6-eng-poetry",
    grade: "G6", subject: "english", term: 3,
    topic: "Poetry",
    subtopics: ["Rhyme", "Rhythm", "Simile and metaphor", "Reading a poem aloud"],
    specificOutcomes: [
      "Identify rhyme and simple similes in a poem",
      "Read a poem aloud with appropriate rhythm",
    ],
    keyCompetencies: ["Literacy", "Creativity", "Communication"],
    values: ["Creativity", "Appreciation"],
    suggestedMaterials: ["Zambian and English poetry samples", "Grade 6 English Pupil's Book (CDC)"],
  },
  {
    id: "g6-sci-circulatory-system",
    grade: "G6", subject: "integrated_science", term: 1,
    topic: "The Circulatory System",
    subtopics: ["The heart", "Blood vessels (arteries, veins, capillaries)", "Blood composition", "Keeping the heart healthy"],
    specificOutcomes: [
      "Describe the path of blood through the heart",
      "State the function of arteries, veins and capillaries",
    ],
    keyCompetencies: ["Scientific literacy", "Self-management"],
    values: ["Responsibility", "Care for one's health"],
    suggestedMaterials: ["Circulatory system chart", "Grade 6 Integrated Science Pupil's Book (CDC)"],
  },
  {
    id: "g6-sci-forces",
    grade: "G6", subject: "integrated_science", term: 2,
    topic: "Forces",
    subtopics: ["Push and pull", "Gravity", "Friction", "Measuring force with a spring balance"],
    specificOutcomes: [
      "Define force and give examples of pushes and pulls",
      "Explain the effect of friction on moving objects",
    ],
    keyCompetencies: ["Scientific literacy", "Observation"],
    values: ["Curiosity", "Accuracy"],
    suggestedMaterials: ["Spring balance", "Toy car", "Grade 6 Integrated Science Pupil's Book (CDC)"],
  },
  {
    id: "g6-soc-zambia-independence",
    grade: "G6", subject: "social_studies", term: 2,
    topic: "The Road to Zambia's Independence",
    subtopics: ["Colonial rule in Northern Rhodesia", "The rise of political parties", "Kenneth Kaunda and UNIP", "24 October 1964"],
    specificOutcomes: [
      "Describe the main events leading to Zambia's independence",
      "Identify key figures in the independence movement",
    ],
    keyCompetencies: ["Citizenship", "Communication"],
    values: ["Patriotism", "Unity", "Respect for heritage"],
    suggestedMaterials: ["Historical pictures", "Grade 6 Social Studies Pupil's Book (CDC)"],
  },

  // ═══════════════════════════════════════════════════════════════════
  // GRADE 7 — ECZ Composite Exam preparation
  // ═══════════════════════════════════════════════════════════════════

  {
    id: "g7-math-algebra",
    grade: "G7", subject: "mathematics", term: 1,
    topic: "Algebra",
    subtopics: ["Simplifying expressions", "Expanding brackets", "Linear equations in one variable", "Word problems"],
    specificOutcomes: [
      "Simplify algebraic expressions by collecting like terms",
      "Solve linear equations of the form ax + b = c",
      "Form and solve equations from word problems",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking", "Problem solving"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Grade 7 Mathematics Pupil's Book (CDC)", "ECZ past-paper samples"],
  },
  {
    id: "g7-math-geometry-triangles",
    grade: "G7", subject: "mathematics", term: 2,
    topic: "Triangles",
    subtopics: ["Types of triangles", "Angle sum of a triangle", "Isosceles and equilateral properties", "Pythagoras theorem (simple)"],
    specificOutcomes: [
      "Classify triangles by sides and by angles",
      "Use the angle sum of a triangle to find an unknown angle",
    ],
    keyCompetencies: ["Numeracy", "Observation"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Protractor, ruler, set square", "Grade 7 Mathematics Pupil's Book (CDC)"],
  },
  {
    id: "g7-math-statistics",
    grade: "G7", subject: "mathematics", term: 3,
    topic: "Statistics",
    subtopics: ["Collecting and organising data", "Frequency tables", "Bar and line graphs", "Mean, median, mode"],
    specificOutcomes: [
      "Collect data and organise it into a frequency table",
      "Calculate mean, median and mode of a data set",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Honesty"],
    suggestedMaterials: ["Graph paper", "Grade 7 Mathematics Pupil's Book (CDC)"],
  },
  {
    id: "g7-math-probability",
    grade: "G7", subject: "mathematics", term: 3,
    topic: "Introduction to Probability",
    subtopics: ["Certain, likely, unlikely, impossible", "Simple probability as a fraction", "Experimental probability"],
    specificOutcomes: [
      "Describe the likelihood of everyday events",
      "Calculate simple theoretical probability as a fraction",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Fairness"],
    suggestedMaterials: ["Coins, dice", "Grade 7 Mathematics Pupil's Book (CDC)"],
  },
  {
    id: "g7-eng-composition",
    grade: "G7", subject: "english", term: 2,
    topic: "Composition Writing",
    subtopics: ["Narrative composition", "Descriptive composition", "Argumentative composition", "Planning an essay"],
    specificOutcomes: [
      "Plan and write a composition of 150-200 words",
      "Use paragraphs to organise ideas clearly",
    ],
    keyCompetencies: ["Literacy", "Creativity", "Communication"],
    values: ["Creativity", "Perseverance"],
    suggestedMaterials: ["Grade 7 English Pupil's Book (CDC)", "Exercise book"],
  },
  {
    id: "g7-eng-formal-letter",
    grade: "G7", subject: "english", term: 3,
    topic: "Formal Letter Writing",
    subtopics: ["Layout of a formal letter", "Addressing", "Opening and closing formulas", "Writing a letter of complaint or enquiry"],
    specificOutcomes: [
      "Write a formal letter with correct layout and tone",
      "Use appropriate opening and closing formulas",
    ],
    keyCompetencies: ["Literacy", "Communication"],
    values: ["Respect", "Responsibility"],
    suggestedMaterials: ["Sample formal letters", "Grade 7 English Pupil's Book (CDC)"],
  },
  {
    id: "g7-sci-electricity",
    grade: "G7", subject: "integrated_science", term: 2,
    topic: "Electricity",
    subtopics: ["Simple circuits", "Conductors and insulators", "Series and parallel circuits", "Safety with electricity"],
    specificOutcomes: [
      "Draw and build a simple electric circuit",
      "Classify common materials as conductors or insulators",
    ],
    keyCompetencies: ["Scientific literacy", "Innovation"],
    values: ["Safety", "Curiosity"],
    suggestedMaterials: ["Battery, wires, bulb, switch", "Grade 7 Integrated Science Pupil's Book (CDC)"],
  },
  {
    id: "g7-sci-reproduction",
    grade: "G7", subject: "integrated_science", term: 3,
    topic: "Reproduction in Plants and Animals",
    subtopics: ["Parts of a flower", "Pollination and fertilisation", "Seed dispersal", "Life cycles of familiar animals"],
    specificOutcomes: [
      "Name the parts of a flower and their functions",
      "Describe pollination and seed dispersal",
    ],
    keyCompetencies: ["Scientific literacy", "Observation"],
    values: ["Curiosity", "Care for the environment"],
    suggestedMaterials: ["Real flowers (hibiscus)", "Grade 7 Integrated Science Pupil's Book (CDC)"],
  },
  {
    id: "g7-soc-government",
    grade: "G7", subject: "social_studies", term: 1,
    topic: "Government of Zambia",
    subtopics: ["Three arms of government (Executive, Legislature, Judiciary)", "The President", "Parliament", "Elections"],
    specificOutcomes: [
      "Name the three arms of government and their roles",
      "Describe how the President is elected",
    ],
    keyCompetencies: ["Citizenship", "Critical thinking"],
    values: ["Patriotism", "Responsibility"],
    suggestedMaterials: ["Zambian constitution (simplified)", "Grade 7 Social Studies Pupil's Book (CDC)"],
  },
  {
    id: "g7-soc-economy",
    grade: "G7", subject: "social_studies", term: 2,
    topic: "The Zambian Economy",
    subtopics: ["Copper mining", "Agriculture", "Tourism", "Small and medium-sized enterprises"],
    specificOutcomes: [
      "Name the main sectors of the Zambian economy",
      "Explain the importance of copper mining to Zambia",
    ],
    keyCompetencies: ["Citizenship", "Entrepreneurship", "Critical thinking"],
    values: ["Patriotism", "Responsibility"],
    suggestedMaterials: ["Map of Zambian mines", "Grade 7 Social Studies Pupil's Book (CDC)"],
  },

  // ═══════════════════════════════════════════════════════════════════
  // GRADE 8 — Junior Secondary
  // ═══════════════════════════════════════════════════════════════════

  {
    id: "g8-math-integers",
    grade: "G8", subject: "mathematics", term: 1,
    topic: "Integers",
    subtopics: ["Positive and negative numbers", "The number line", "Adding and subtracting integers", "Multiplying and dividing integers"],
    specificOutcomes: [
      "Perform the four operations on integers",
      "Apply integers to real-life contexts (temperature, profit/loss)",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Number line", "Grade 8 Mathematics Pupil's Book (CDC)"],
  },
  {
    id: "g8-math-linear-equations",
    grade: "G8", subject: "mathematics", term: 1,
    topic: "Linear Equations",
    subtopics: ["Solving equations with one unknown", "Equations with brackets", "Equations with fractions", "Word problems"],
    specificOutcomes: [
      "Solve linear equations involving brackets and fractions",
      "Translate a word problem into a linear equation and solve it",
    ],
    keyCompetencies: ["Numeracy", "Problem solving", "Critical thinking"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Grade 8 Mathematics Pupil's Book (CDC)"],
  },
  {
    id: "g8-math-sets",
    grade: "G8", subject: "mathematics", term: 2,
    topic: "Sets",
    subtopics: ["Set notation", "Types of sets (empty, finite, infinite, equal)", "Union and intersection", "Venn diagrams"],
    specificOutcomes: [
      "Use set notation to describe a set",
      "Find the union and intersection of two sets",
      "Use a Venn diagram to solve a two-set problem",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Grade 8 Mathematics Pupil's Book (CDC)"],
  },
  {
    id: "g8-math-geometry-polygons",
    grade: "G8", subject: "mathematics", term: 3,
    topic: "Polygons",
    subtopics: ["Types of polygons", "Sum of interior angles", "Sum of exterior angles", "Regular polygons"],
    specificOutcomes: [
      "Calculate the sum of interior angles of any polygon",
      "Find the size of an interior angle of a regular polygon",
    ],
    keyCompetencies: ["Numeracy", "Observation"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Protractor, ruler", "Grade 8 Mathematics Pupil's Book (CDC)"],
  },
  {
    id: "g8-eng-comprehension",
    grade: "G8", subject: "english", term: 1,
    topic: "Advanced Comprehension",
    subtopics: ["Literal questions", "Inferential questions", "Vocabulary in context", "Tone and attitude"],
    specificOutcomes: [
      "Answer literal and inferential questions on a passage",
      "Explain the meaning of words as used in a passage",
    ],
    keyCompetencies: ["Literacy", "Critical thinking"],
    values: ["Attentiveness", "Accuracy"],
    suggestedMaterials: ["Grade 8 English Pupil's Book (CDC)"],
  },
  {
    id: "g8-eng-argumentative",
    grade: "G8", subject: "english", term: 2,
    topic: "Argumentative Composition",
    subtopics: ["Stating a position", "Supporting with reasons and evidence", "Considering the opposite view", "Concluding"],
    specificOutcomes: [
      "Write an argumentative composition of 250-300 words",
      "Support a position with at least three reasons",
    ],
    keyCompetencies: ["Literacy", "Critical thinking", "Communication"],
    values: ["Honesty", "Respect", "Integrity"],
    suggestedMaterials: ["Grade 8 English Pupil's Book (CDC)"],
  },
  {
    id: "g8-sci-cells",
    grade: "G8", subject: "integrated_science", term: 1,
    topic: "Cells and Tissues",
    subtopics: ["Plant and animal cells (structure)", "Functions of cell parts", "Specialised cells", "Tissues"],
    specificOutcomes: [
      "Draw and label plant and animal cells",
      "State the function of the nucleus, cytoplasm, cell membrane and cell wall",
    ],
    keyCompetencies: ["Scientific literacy", "Observation"],
    values: ["Curiosity", "Accuracy"],
    suggestedMaterials: ["Microscope (if available)", "Cell diagram charts", "Grade 8 Integrated Science Pupil's Book (CDC)"],
  },
  {
    id: "g8-sci-chemistry-atoms",
    grade: "G8", subject: "integrated_science", term: 2,
    topic: "Atoms and Elements",
    subtopics: ["Atoms and molecules", "Elements and compounds", "The periodic table (introduction)", "Chemical symbols"],
    specificOutcomes: [
      "Define atom, element, compound and molecule",
      "Write the chemical symbols of the first 20 elements",
    ],
    keyCompetencies: ["Scientific literacy", "Critical thinking"],
    values: ["Curiosity", "Accuracy"],
    suggestedMaterials: ["Periodic table", "Grade 8 Integrated Science Pupil's Book (CDC)"],
  },
  {
    id: "g8-sci-motion",
    grade: "G8", subject: "integrated_science", term: 3,
    topic: "Motion",
    subtopics: ["Distance and displacement", "Speed, velocity, acceleration", "Distance-time graphs", "Everyday examples"],
    specificOutcomes: [
      "Distinguish between distance and displacement, speed and velocity",
      "Calculate speed using speed = distance / time",
      "Draw and interpret a simple distance-time graph",
    ],
    keyCompetencies: ["Numeracy", "Scientific literacy"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Stopwatch, measuring tape", "Grade 8 Integrated Science Pupil's Book (CDC)"],
  },
  {
    id: "g8-civ-constitution",
    grade: "G8", subject: "civic_education", term: 1,
    topic: "The Constitution of Zambia",
    subtopics: ["What a constitution is", "The Bill of Rights", "Duties of citizens", "Amending the constitution"],
    specificOutcomes: [
      "Define a constitution",
      "List at least five fundamental rights in the Bill of Rights",
      "Describe the duties of a Zambian citizen",
    ],
    keyCompetencies: ["Citizenship", "Critical thinking", "Communication"],
    values: ["Patriotism", "Responsibility", "Justice"],
    suggestedMaterials: ["Simplified Zambian constitution", "Grade 8 Civic Education Pupil's Book (CDC)"],
  },
  {
    id: "g8-civ-human-rights",
    grade: "G8", subject: "civic_education", term: 2,
    topic: "Human Rights",
    subtopics: ["Categories of human rights", "Child rights", "Women's rights", "Human rights institutions in Zambia (HRC)"],
    specificOutcomes: [
      "List major categories of human rights",
      "Explain three specific rights of the Zambian child",
    ],
    keyCompetencies: ["Citizenship", "Communication"],
    values: ["Respect", "Justice", "Equality"],
    suggestedMaterials: ["Child Rights booklet", "Grade 8 Civic Education Pupil's Book (CDC)"],
  },
  {
    id: "g8-soc-zambia-history-colonial",
    grade: "G8", subject: "social_studies", term: 2,
    topic: "Colonial Rule in Northern Rhodesia",
    subtopics: ["Arrival of Europeans", "The BSA Company", "Establishment of colonial rule", "African resistance"],
    specificOutcomes: [
      "Describe how the British South Africa Company came to rule Northern Rhodesia",
      "Identify major forms of African resistance during the colonial period",
    ],
    keyCompetencies: ["Citizenship", "Critical thinking"],
    values: ["Patriotism", "Unity"],
    suggestedMaterials: ["Historical maps", "Grade 8 Social Studies Pupil's Book (CDC)"],
  },
  {
    id: "g8-re-world-religions",
    grade: "G8", subject: "religious_education", term: 2,
    topic: "World Religions — Introduction",
    subtopics: ["Christianity", "Islam", "Hinduism", "African Traditional Religion"],
    specificOutcomes: [
      "State the main beliefs of Christianity, Islam, Hinduism and African Traditional Religion",
      "Identify one value that is common to all of them",
    ],
    keyCompetencies: ["Spiritual awareness", "Critical thinking", "Communication"],
    values: ["Respect", "Tolerance"],
    suggestedMaterials: ["Religious texts (where available)", "Grade 8 RE Pupil's Book (CDC)"],
  },

  // ═══════════════════════════════════════════════════════════════════
  // GRADE 9 — Junior Secondary Certificate (JSC) preparation
  // ═══════════════════════════════════════════════════════════════════

  {
    id: "g9-math-quadratic-intro",
    grade: "G9", subject: "mathematics", term: 2,
    topic: "Introduction to Quadratic Expressions",
    subtopics: ["Expanding (a+b)(c+d)", "Factorising ax + ay", "Factorising quadratic expressions of the form x² + bx + c"],
    specificOutcomes: [
      "Expand products of two binomials",
      "Factorise quadratic expressions of the form x² + bx + c",
    ],
    keyCompetencies: ["Numeracy", "Critical thinking", "Problem solving"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Grade 9 Mathematics Pupil's Book (CDC)", "ECZ JSC past papers"],
  },
  {
    id: "g9-math-simultaneous-equations",
    grade: "G9", subject: "mathematics", term: 2,
    topic: "Simultaneous Linear Equations",
    subtopics: ["Elimination method", "Substitution method", "Graphical method", "Word problems"],
    specificOutcomes: [
      "Solve a pair of simultaneous linear equations by elimination and by substitution",
      "Form and solve simultaneous equations from a word problem",
    ],
    keyCompetencies: ["Numeracy", "Problem solving"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Grade 9 Mathematics Pupil's Book (CDC)"],
  },
  {
    id: "g9-math-trigonometry",
    grade: "G9", subject: "mathematics", term: 3,
    topic: "Introduction to Trigonometry",
    subtopics: ["Sine, cosine, tangent in a right-angled triangle", "Using trig tables or calculator", "Finding unknown sides", "Finding unknown angles"],
    specificOutcomes: [
      "State the sine, cosine and tangent ratios in a right-angled triangle",
      "Use trig ratios to find an unknown side or angle",
    ],
    keyCompetencies: ["Numeracy", "Problem solving"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Scientific calculator or trig tables", "Grade 9 Mathematics Pupil's Book (CDC)"],
  },
  {
    id: "g9-math-mensuration",
    grade: "G9", subject: "mathematics", term: 3,
    topic: "Mensuration",
    subtopics: ["Area of triangles, circles, trapeziums", "Volume of cuboids, cylinders", "Surface area of cuboids and cylinders", "Applications"],
    specificOutcomes: [
      "Calculate the area of composite shapes",
      "Calculate the volume and surface area of cuboids and cylinders",
    ],
    keyCompetencies: ["Numeracy", "Problem solving"],
    values: ["Accuracy", "Perseverance"],
    suggestedMaterials: ["Formula sheet", "Grade 9 Mathematics Pupil's Book (CDC)"],
  },
  {
    id: "g9-eng-literature-prose",
    grade: "G9", subject: "english", term: 2,
    topic: "Prose — Setting, Plot and Character",
    subtopics: ["Setting", "Plot stages (exposition, rising action, climax, falling action, resolution)", "Characterisation", "Theme"],
    specificOutcomes: [
      "Describe the setting and plot of a prescribed short story or novel",
      "Analyse the main character using evidence from the text",
    ],
    keyCompetencies: ["Literacy", "Critical thinking", "Communication"],
    values: ["Empathy", "Integrity"],
    suggestedMaterials: ["Prescribed Zambian/African literature text", "Grade 9 English Pupil's Book (CDC)"],
  },
  {
    id: "g9-eng-poetry-devices",
    grade: "G9", subject: "english", term: 3,
    topic: "Poetic Devices",
    subtopics: ["Simile and metaphor", "Personification", "Alliteration", "Tone and mood"],
    specificOutcomes: [
      "Identify simile, metaphor, personification and alliteration in a poem",
      "Describe the tone and mood of a poem using evidence",
    ],
    keyCompetencies: ["Literacy", "Creativity"],
    values: ["Appreciation", "Creativity"],
    suggestedMaterials: ["Zambian and African poetry anthology", "Grade 9 English Pupil's Book (CDC)"],
  },
  {
    id: "g9-sci-genetics",
    grade: "G9", subject: "integrated_science", term: 2,
    topic: "Introduction to Genetics",
    subtopics: ["Chromosomes and genes (simple)", "Inherited and acquired traits", "Variation in humans", "Ethical issues (brief)"],
    specificOutcomes: [
      "Distinguish between inherited and acquired characteristics",
      "Give examples of variation in humans",
    ],
    keyCompetencies: ["Scientific literacy", "Critical thinking"],
    values: ["Curiosity", "Respect for diversity"],
    suggestedMaterials: ["Chart of inheritance", "Grade 9 Integrated Science Pupil's Book (CDC)"],
  },
  {
    id: "g9-sci-acids-bases",
    grade: "G9", subject: "integrated_science", term: 2,
    topic: "Acids, Bases and Salts",
    subtopics: ["Properties of acids and bases", "Indicators and pH scale", "Neutralisation", "Common salts in daily life"],
    specificOutcomes: [
      "Classify substances as acids, bases or neutral using indicators",
      "Explain neutralisation with a word equation",
    ],
    keyCompetencies: ["Scientific literacy", "Observation"],
    values: ["Safety", "Curiosity"],
    suggestedMaterials: ["Litmus paper, lemon juice, bicarbonate of soda", "Grade 9 Integrated Science Pupil's Book (CDC)"],
  },
  {
    id: "g9-sci-energy-transformations",
    grade: "G9", subject: "integrated_science", term: 3,
    topic: "Energy and its Transformations",
    subtopics: ["Forms of energy", "Energy conversions (e.g. chemical → electrical)", "Conservation of energy", "Renewable energy in Zambia"],
    specificOutcomes: [
      "List at least six forms of energy",
      "Describe energy conversions in common devices",
      "Discuss renewable energy sources relevant to Zambia",
    ],
    keyCompetencies: ["Scientific literacy", "Innovation", "Citizenship"],
    values: ["Responsibility", "Care for the environment"],
    suggestedMaterials: ["Pictures of solar panels, hydro plants (Kariba)", "Grade 9 Integrated Science Pupil's Book (CDC)"],
  },
  {
    id: "g9-civ-democracy",
    grade: "G9", subject: "civic_education", term: 1,
    topic: "Democracy and Governance",
    subtopics: ["Features of a democracy", "Elections in Zambia", "Role of political parties", "Role of the citizen"],
    specificOutcomes: [
      "Describe the main features of a democracy",
      "Explain the role of elections in a democracy",
    ],
    keyCompetencies: ["Citizenship", "Communication", "Critical thinking"],
    values: ["Patriotism", "Responsibility", "Integrity"],
    suggestedMaterials: ["ECZ Voter Education pamphlets", "Grade 9 Civic Education Pupil's Book (CDC)"],
  },
  {
    id: "g9-civ-corruption",
    grade: "G9", subject: "civic_education", term: 2,
    topic: "Corruption and Integrity",
    subtopics: ["What corruption is", "Effects on society", "Anti-Corruption Commission (ACC) of Zambia", "Promoting integrity"],
    specificOutcomes: [
      "Define corruption and give examples",
      "Describe how corruption harms society and how citizens can fight it",
    ],
    keyCompetencies: ["Citizenship", "Critical thinking"],
    values: ["Integrity", "Honesty", "Responsibility"],
    suggestedMaterials: ["ACC awareness materials", "Grade 9 Civic Education Pupil's Book (CDC)"],
  },
  {
    id: "g9-soc-climate-change",
    grade: "G9", subject: "social_studies", term: 3,
    topic: "Climate Change and Zambia",
    subtopics: ["Causes of climate change", "Effects on Zambia (droughts, floods, agriculture)", "Mitigation and adaptation", "Role of youth"],
    specificOutcomes: [
      "Explain human causes of climate change",
      "Describe two climate-change impacts already being seen in Zambia",
      "Suggest actions that young people can take",
    ],
    keyCompetencies: ["Citizenship", "Critical thinking", "Innovation"],
    values: ["Responsibility", "Care for the environment"],
    suggestedMaterials: ["News articles on Zambian climate impacts", "Grade 9 Social Studies Pupil's Book (CDC)"],
  },
]

module.exports = {TOPICS}
