import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest'
import { render, screen, fireEvent, act } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import NotesStudio from './NotesStudio.jsx'

// The audience split (§1, §5, §7). What is under test is the studio's IDENTITY:
// which document it opens on, which controls belong to which audience, and
// whether the teacher's choices actually leave the browser. The last one is the
// one worth having — a Format control that changes a piece of local state and
// never reaches the payload looks correct in every screenshot and produces the
// same document every time.
//
// Mocks mirror NotesStudio.spec.jsx (the idempotency-lock suite); the two are
// deliberately separate files because they are about different things.

vi.mock('../../../utils/teacherTools', () => ({
  generateNotes: vi.fn(),
  TEACHER_LANGUAGES: [{ value: 'english', label: 'English' }],
  DURATION_PRESETS: [{ value: 40, label: '40 min' }],
}))

vi.mock('../../../contexts/AuthContext', () => {
  const currentUser = { uid: 'test-uid' }
  const userProfile = {}
  return { useAuth: () => ({ currentUser, userProfile, isAdmin: false }) }
})
vi.mock('../../../hooks/useGenerationGate', () => ({
  useGenerationGate: () => ({ ensureCanGenerate: () => true }),
}))
vi.mock('../../../contexts/PlatformSettingsContext', () => ({
  usePlatformSettings: () => ({ settings: { featureFlags: {} } }),
}))
vi.mock('../../../utils/useFormDefaultsFromUrl', () => ({
  useFormDefaultsFromUrl: () => ({}),
}))
vi.mock('../../../utils/teacherLibraryService', () => ({
  listMyGenerations: vi.fn(() => Promise.resolve([])),
  titleForGeneration: () => 'plan',
  formatDate: () => '',
  attachLibraryToGeneration: vi.fn(() => Promise.resolve()),
  updateGenerationOutput: vi.fn(() => Promise.resolve()),
  isFreePlanTeacher: () => false,
}))
vi.mock('../../../utils/notesAutoGenerateDiagrams', () => ({
  collectNotesDiagramJobs: () => [],
  autoGenerateNotesDiagrams: vi.fn(() => Promise.resolve({})),
  NOTES_DIAGRAM_CAP: 6,
}))
vi.mock('../../../engines/export-engine/notesToDocx', () => ({ downloadNotesDocx: vi.fn() }))
vi.mock('../../../engines/export-engine/notesToPdf', () => ({
  downloadNotesPdf: vi.fn(),
  downloadAnswerPagePdf: vi.fn(),
}))
vi.mock('../../../utils/learnerNotesToDocx', () => ({
  downloadLearnerNotesDocx: vi.fn(),
  downloadAnswerPageDocx: vi.fn(),
}))
vi.mock('../../../hooks/draft/useDraftManager', () => ({
  useDraftManager: () => ({
    status: 'idle', savedAt: null, online: true,
    flush: vi.fn(), clear: vi.fn(() => Promise.resolve()),
  }),
}))
vi.mock('../../../shared/components/DraftStatusIndicator', () => ({ default: () => null }))
vi.mock('../../../shared/components/DraftRecoveryPrompt', () => ({ default: () => null }))
vi.mock('../../../components/seo/SeoHelmet', () => ({ default: () => null }))
vi.mock('../../../components/ui/LiveGenerationCanvas', () => ({ default: () => null }))
vi.mock('../components/NotesView', () => ({ default: () => null }))
vi.mock('../components/NotesPagesPreview', () => ({
  default: ({ paper, boardPreview }) => (
    <div data-testid="pages-preview" data-paper={paper} data-board={String(boardPreview)} />
  ),
}))
vi.mock('../../../shared/components/StudioPageHeader', () => ({
  default: ({ eyebrow, title }) => <div><span>{eyebrow}</span><h1>{title}</h1></div>,
}))
vi.mock('../../../shared/components/StudioOutputBoundary', () => ({ default: ({ children }) => children }))
vi.mock('../../../components/teacher/generate/StudioAssignmentChangeNotice', () => ({ default: () => null }))

const VALID_CURR = {
  curriculumMode: 'cbc',
  grade: 'G4',
  subject: 'integrated_science',
  subjectLabel: 'Integrated Science',
  topic: 'The Digestive System',
  subtopic: '',
  curriculum: 'cbc',
  framework: '2023',
}
vi.mock('../../../components/teacher/curriculum/StudioCurriculumSelector', () => ({
  default: ({ onChange }) => (
    <button type="button" onClick={() => onChange(VALID_CURR)}>seed-curriculum</button>
  ),
}))

function renderStudio() {
  return render(<MemoryRouter><NotesStudio /></MemoryRouter>)
}

const seedCurriculum = () =>
  fireEvent.click(screen.getByRole('button', { name: /seed-curriculum/i }))

const generateButton = () => screen.getByRole('button', { name: /Generate Notes/i })

async function generateAndReadPayload() {
  const { generateNotes } = await import('../../../utils/teacherTools')
  generateNotes.mockResolvedValue({
    ok: true,
    data: { notes: { header: {}, audience: 'learner' }, generationId: 'gen-1', usage: null, warning: '' },
  })
  seedCurriculum()
  await act(async () => { fireEvent.click(generateButton()) })
  return generateNotes.mock.calls[0][0]
}

beforeEach(() => { vi.clearAllMocks() })
afterEach(() => { sessionStorage.clear() })

describe('Notes Studio — identity', () => {
  it('opens as "Notes Studio" under the Teaching Materials category', () => {
    renderStudio()
    expect(screen.getByRole('heading', { name: 'Notes Studio' })).toBeInTheDocument()
    expect(screen.getByText('TEACHING MATERIALS')).toBeInTheDocument()
  })

  it('pre-selects Learner notes', () => {
    renderStudio()
    expect(screen.getByRole('radio', { name: /Learner notes/i })).toHaveAttribute('aria-checked', 'true')
    expect(screen.getByRole('radio', { name: /Teaching notes/i })).toHaveAttribute('aria-checked', 'false')
  })

  it('keeps the From a plan / Standalone toggle in both modes', () => {
    renderStudio()
    expect(screen.getByRole('tab', { name: /From a plan/i })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('radio', { name: /Teaching notes/i }))
    expect(screen.getByRole('tab', { name: /From a plan/i })).toBeInTheDocument()
  })
})

describe('Notes Studio — which controls belong to which audience', () => {
  it('hides Lesson duration in learner mode and shows it in teaching mode', () => {
    renderStudio()
    // A study note is read and kept; it is not delivered in forty minutes.
    expect(screen.queryByLabelText(/Lesson duration/i)).toBeNull()
    fireEvent.click(screen.getByRole('radio', { name: /Teaching notes/i }))
    expect(screen.getByLabelText(/Lesson duration/i)).toBeInTheDocument()
  })

  it('shows the learner presentation controls only in learner mode', () => {
    renderStudio()
    expect(screen.getByRole('radio', { name: /Handout/i })).toBeInTheDocument()
    expect(screen.getByLabelText(/^Detail$/i)).toBeInTheDocument()
    expect(screen.getByLabelText(/^Length$/i)).toBeInTheDocument()
    expect(screen.getByLabelText(/English level/i)).toBeInTheDocument()
    expect(screen.getByLabelText(/Paper size/i)).toBeInTheDocument()

    fireEvent.click(screen.getByRole('radio', { name: /Teaching notes/i }))
    expect(screen.queryByRole('radio', { name: /Handout/i })).toBeNull()
    expect(screen.queryByLabelText(/English level/i)).toBeNull()
  })
})

describe('Notes Studio — the choices reach the server', () => {
  it('sends the learner audience and every presentation option', async () => {
    renderStudio()
    const payload = await generateAndReadPayload()
    expect(payload.audience).toBe('learner')
    expect(payload.format).toBe('handout')
    expect(payload.detail).toBe('detailed')
    expect(payload.length).toBe('one')
    expect(payload.englishLevel).toBe('standard')
    expect(payload.paperSize).toBe('a4')
  })

  it('sends the teacher’s edited choices, not the defaults', async () => {
    renderStudio()
    fireEvent.click(screen.getByRole('radio', { name: /Board notes/i }))
    fireEvent.change(screen.getByLabelText(/^Length$/i), { target: { value: 'half' } })
    fireEvent.change(screen.getByLabelText(/^Detail$/i), { target: { value: 'summarised' } })
    fireEvent.change(screen.getByLabelText(/English level/i), { target: { value: 'simple' } })
    fireEvent.change(screen.getByLabelText(/Paper size/i), { target: { value: 'a5' } })

    const payload = await generateAndReadPayload()
    expect(payload.format).toBe('board')
    expect(payload.length).toBe('half')
    expect(payload.detail).toBe('summarised')
    expect(payload.englishLevel).toBe('simple')
    expect(payload.paperSize).toBe('a5')
  })

  it('sends the teaching audience when the teacher asks for delivery notes', async () => {
    renderStudio()
    fireEvent.click(screen.getByRole('radio', { name: /Teaching notes/i }))
    const payload = await generateAndReadPayload()
    expect(payload.audience).toBe('teaching')
    // The learner presentation options are not sent for a document that has no
    // use for them — a payload carrying a paper size for delivery notes invites
    // a server to act on it.
    expect(payload.format).toBeUndefined()
    expect(payload.englishLevel).toBeUndefined()
  })

  it('stamps the audience and format on the library entry', async () => {
    const { attachLibraryToGeneration } = await import('../../../utils/teacherLibraryService')
    renderStudio()
    await generateAndReadPayload()
    const meta = attachLibraryToGeneration.mock.calls[0][1]
    expect(meta.audience).toBe('learner')
    expect(meta.noteFormat).toBe('handout')
  })
})
