import { useEffect, useMemo, useState, useRef } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../../../contexts/AuthContext'
import { useGenerationGate } from '../../../hooks/useGenerationGate'
import { useIsMounted } from '../../../hooks/useIsMounted'
import {
  generateNotes,
  TEACHER_LANGUAGES,
  DURATION_PRESETS,
} from '../../../utils/teacherTools'
import { downloadNotesDocx } from '../../../engines/export-engine/notesToDocx'
import { downloadNotesPdf, downloadAnswerPagePdf } from '../../../engines/export-engine/notesToPdf'
import {
  downloadAnswerPageDocx,
  downloadLearnerNotesDocx,
} from '../../../utils/learnerNotesToDocx'
import {
  AUDIENCE_LABELS,
  DEFAULT_AUDIENCE,
  DETAIL_LABELS,
  ENGLISH_LEVEL_LABELS,
  FORMAT_LABELS,
  LENGTH_LABELS,
  NOTE_AUDIENCES,
  NOTE_DETAIL,
  NOTE_FORMATS,
  NOTE_LENGTHS,
  PAPER_SIZE_LABELS,
  ENGLISH_LEVELS,
  PAPER_SIZES,
} from '../../../utils/notesOptions'
import { buildDownloadName } from '../../../utils/downloadFilename'
import { useFormDefaultsFromUrl } from '../../../utils/useFormDefaultsFromUrl'
import SeoHelmet from '../../../shared/components/SeoHelmet'
import {
  listMyGenerations,
  titleForGeneration,
  formatDate,
  attachLibraryToGeneration,
  updateGenerationOutput,
  isFreePlanTeacher,
} from '../../../utils/teacherLibraryService'
import {
  collectNotesDiagramJobs,
  autoGenerateNotesDiagrams,
  NOTES_DIAGRAM_CAP,
} from '../../../utils/notesAutoGenerateDiagrams'
import { LIBRARY_TYPES } from '../../../config/library'
import NotesView from '../components/NotesView'
import NotesPagesPreview from '../components/NotesPagesPreview'
import GroundingChip from '../components/GroundingChip'
import { buildAnswerPageBlocks } from '../../../utils/learnerNotesPrintable'
import StudioPageHeader from '../../../shared/components/StudioPageHeader'
import LiveGenerationCanvas from '../../../shared/components/LiveGenerationCanvas'
import StudioCurriculumSelector from '../../../components/teacher/curriculum/StudioCurriculumSelector'
import { curriculumSeedFromProfile } from '../../../utils/teacherDefaults'
import { readActiveAssignmentSeed, resolveStudioSeed } from '../../../utils/activeAssignmentSeed'
import StudioAssignmentChangeNotice from '../../../components/teacher/generate/StudioAssignmentChangeNotice'
import {
  FieldLabel,
  FieldText,
  FieldTextarea,
  FieldSelect,
  FieldDate,
  FieldGrid,
  AdvancedOptions,
  GenerateButton,
  StudioEmptyState,
} from '../../../shared/components/studioFields'
import Icon from '../../../shared/components/Icon'
import { Download, ImageIcon, RefreshCw } from '../../../shared/components/icons'
import { NotebookText } from 'lucide-react'
import StudioOutputBoundary from '../../../shared/components/StudioOutputBoundary'
import { useDraftManager } from '../../../hooks/draft/useDraftManager'
import { useAiOperationLock } from '../../../hooks/useAiOperationLock'
import { stableFingerprint } from '../../../hooks/aiOperationLockCore'
import { notesInputDescriptor } from '../../../hooks/draft/descriptors'
import { usePlatformSettings } from '../../../contexts/PlatformSettingsContext'
import DraftStatusIndicator from '../../../shared/components/DraftStatusIndicator'
import DraftRecoveryPrompt from '../../../shared/components/DraftRecoveryPrompt'

const MODE_FROM_PLAN = 'from_plan'
const MODE_STANDALONE = 'standalone'

// A plan can only seed notes if it carries a structured body. The Cloud
// Functions pipeline stores it under `output`; the legacy studio editor
// under `data`. Plans still generating (or failed) have neither.
function planHasBody(plan) {
  if (!plan) return false
  if (plan.output && typeof plan.output === 'object') return true
  if (plan.data && typeof plan.data === 'object') return true
  return false
}

export default function NotesStudio() {
  const navigate = useNavigate()
  const { currentUser, userProfile, isAdmin } = useAuth()
  const { ensureCanGenerate } = useGenerationGate(currentUser?.uid)
  const urlDefaults = useFormDefaultsFromUrl()
  // Selector seed: a deep-link handoff (?grade=…) wins; then the active
  // Teaching Profile assignment (persisted by the dashboard); then the
  // teacher's saved curriculum defaults (Teacher Settings → My Teaching).
  // Read once on mount by the selector — never re-seeds reactively.
  const [selectorSeed, setSelectorSeed] = useState(() =>
    resolveStudioSeed({
      urlSeed: urlDefaults,
      activeSeed: readActiveAssignmentSeed(currentUser?.uid),
      profileSeed: curriculumSeedFromProfile(userProfile),
    }),
  )
  const [selectorKey, setSelectorKey] = useState(0)

  // If a lessonPlanId is in the URL, default to the from-plan tab.
  const initialMode = urlDefaults.lessonPlanId ? MODE_FROM_PLAN : MODE_STANDALONE
  const [mode, setMode] = useState(initialMode)

  // Audience is the studio's identity, so it is the first thing on the form and
  // the first thing in state. `learner` is the default because learner notes
  // ARE the product; teaching notes are the second mode, kept whole.
  //
  // A SAVED document defaults the other way — see `readAudience` in
  // notesOptions — so every note written before this existed reopens as what it
  // is. The two defaults are different on purpose.
  const [audience, setAudience] = useState(DEFAULT_AUDIENCE)
  const isLearnerMode = audience === NOTE_AUDIENCES.LEARNER

  const [form, setForm] = useState(() => ({
    date: '',
    term: '',
    lessonNumber: '',
    totalLessons: '',
    learningEnvironment: '',
    durationMinutes: 40,
    // Learner-mode presentation. Additive with defaults: a payload without them
    // is a valid payload, which is what keeps this a non-breaking change.
    format: NOTE_FORMATS.HANDOUT,
    detail: NOTE_DETAIL.DETAILED,
    length: NOTE_LENGTHS.ONE,
    englishLevel: ENGLISH_LEVELS.STANDARD,
    paperSize: PAPER_SIZES.A4,
    language: 'english',
    teacherName: userProfile?.displayName || userProfile?.fullName || '',
    school: userProfile?.school || userProfile?.schoolName || '',
    instructions: '',
    lessonPlanId: '',
    ...urlDefaults,
  }))
  // Standardized curriculum selection (CBC/Previous → grade → subject → topic →
  // subtopic) — drives the Standalone tab. `curr` holds the latest payload,
  // including the server-ready grade/subject/curriculum/framework fields.
  const [curr, setCurr] = useState({})

  const [plans, setPlans] = useState([])
  const [plansLoading, setPlansLoading] = useState(true)
  const [plansError, setPlansError] = useState(false)
  const [status, setStatus] = useState('idle')
  const [errorMessage, setErrorMessage] = useState('')
  const isMounted = useIsMounted()
  const [notes, setNotes] = useState(null)
  const [generationId, setGenerationId] = useState(null)
  const [usage, setUsage] = useState(null)
  const [warning, setWarning] = useState('')
  // Live Generation Canvas hand-off (see WorksheetGenerator for the pattern).
  const [handedOff, setHandedOff] = useState(false)
  // Per-run token: stops a resolved callable from hijacking the UI if Stop was
  // clicked before the response landed.
  const runRef = useRef(0)

  // Idempotency lock: one logical generation → one provider call + one saved
  // doc + one usage charge, even across a double-click / rapid tap / refresh /
  // a second tab. generateNotes.js's server-side reservation enforces this;
  // this is the client-side belt (mints + persists the key). Separate lock keys
  // for the full generate vs a per-section regenerate so they never collide.
  const { run: runGenerateLocked } = useAiOperationLock('notes-studio:generate')
  const { run: runRegenerateLocked } = useAiOperationLock('notes-studio:regenerate')

  // Universal Draft Manager: auto-save the notes inputs (incl. the mode tab).
  const { featureFlags } = usePlatformSettings().settings
  const draft = useDraftManager({
    studioId: 'notes',
    uid: currentUser?.uid,
    draftId: 'notes-current',
    descriptor: notesInputDescriptor,
    state: { form, curr, mode, audience },
    enabled: Boolean(currentUser?.uid && featureFlags?.universalDrafts !== false),
    onRestore: (payload) => {
      if (payload?.form) setForm((f) => ({ ...f, ...payload.form }))
      if (payload?.mode) setMode(payload.mode)
      if (payload?.audience) setAudience(payload.audience)
      if (payload?.curr) {
        setCurr(payload.curr)
        setSelectorSeed(payload.curr)
        setSelectorKey((k) => k + 1)
      }
    },
  })

  // Diagram generation state (post-generation optional pass)
  const [diagramStatus, setDiagramStatus] = useState('idle') // idle | generating | done | error
  const [diagramProgress, setDiagramProgress] = useState({ done: 0, total: 0 })
  const [diagramError, setDiagramError] = useState('')

  // Back-fill teacher name + school once the profile resolves. The lazy
  // initializer above runs before the async profile loads, so on a cold load
  // these stay blank; fill them in when the profile arrives, but only if the
  // teacher hasn't already typed something (never clobber an edit or a URL
  // default).
  useEffect(() => {
    if (!userProfile) return
    setForm((f) => {
      const teacherName = f.teacherName || userProfile.displayName || userProfile.fullName || ''
      const school = f.school || userProfile.school || userProfile.schoolName || ''
      if (teacherName === f.teacherName && school === f.school) return f
      return { ...f, teacherName, school }
    })
  }, [userProfile])

  // Load the user's lesson plans for the from-plan picker.
  useEffect(() => {
    if (!currentUser) return
    let cancelled = false
    setPlansLoading(true)
    setPlansError(false)
    listMyGenerations({ uid: currentUser.uid, tool: 'lesson_plan' })
      // Only offer plans that actually have a body to build notes from —
      // a plan still generating (or one whose generation failed) has no
      // `output`/`data` and the server would reject it with a confusing
      // "isn't a lesson plan we can build notes from" error.
      .then((rows) => { if (!cancelled) setPlans(rows.filter(planHasBody)) })
      .catch(() => { if (!cancelled) { setPlans([]); setPlansError(true) } })
      .finally(() => { if (!cancelled) setPlansLoading(false) })
    return () => { cancelled = true }
  }, [currentUser])

  function updateField(key, value) {
    setForm((f) => ({ ...f, [key]: value }))
  }

  // What the RESULT is, not what the form currently says. The two can differ
  // for as long as it takes a teacher to flip the toggle after generating, and
  // every renderer and exporter below has to follow the document.
  const isLearnerDocument = notes?.audience === NOTE_AUDIENCES.LEARNER
  const answerPageBlocks = useMemo(
    () => (isLearnerDocument ? buildAnswerPageBlocks(notes) : []),
    [isLearnerDocument, notes],
  )

  const selectedPlan = useMemo(
    () => plans.find((p) => p.id === form.lessonPlanId) || null,
    [plans, form.lessonPlanId],
  )

  // Reproduce whichever payload the current mode uses (from-plan vs standalone),
  // so onGenerate and regenerateSection stay in lock-step.
  function buildInputs() {
    // The presentation options travel in BOTH modes. A note built from a lesson
    // plan is still a handout or a board sheet, still half a page or two, and
    // still written at the level the teacher chose — the plan supplies the
    // subject matter, not the format.
    const presentation = {
      audience,
      ...(isLearnerMode ? {
        format: form.format,
        detail: form.detail,
        length: form.length,
        englishLevel: form.englishLevel,
        paperSize: form.paperSize,
      } : {}),
    }
    // The learner presentation lives in `form` so the draft manager persists it
    // with everything else, which means a TEACHING payload has to have it taken
    // back out. Spreading the form wholesale would send a paper size with a set
    // of delivery notes — a field the server has no use for and every reason to
    // ignore, which is exactly the kind of thing that stops being ignored.
    const { format: _f, detail: _d, length: _l, englishLevel: _e, paperSize: _p, ...plainForm } = form
    return mode === MODE_FROM_PLAN
      ? {
          lessonPlanId: form.lessonPlanId,
          instructions: form.instructions,
          date: form.date,
          ...presentation,
        }
      : {
          ...plainForm,
          lessonPlanId: '',
          grade: curr.grade,
          subject: curr.subject,
          topic: curr.topic,
          subtopic: curr.subtopic,
          curriculum: curr.curriculum,
          framework: curr.framework,
          ...presentation,
        }
  }

  async function regenerateSection(sectionId) {
    if (!ensureCanGenerate('notes')) return null
    const payload = buildInputs()
    const lockResult = await runRegenerateLocked({
      // Section-scoped fingerprint so a regenerate mints its own key rather
      // than resuming the full-generate result.
      fingerprint: stableFingerprint({ ...payload, __regenerateSection: sectionId }),
      action: async (idempotencyKey) => {
        const outcome = await generateNotes({ ...payload, idempotencyKey })
        if (!outcome.ok) {
          const err = new Error(outcome.error || 'Generation failed')
          err.response = outcome
          throw err
        }
        return outcome
      },
    })
    if (lockResult.reason === 'locked') return null
    const res = lockResult.ok ? lockResult.data : (lockResult.error?.response || { ok: false })
    if (res.ok && res.data?.notes) {
      const fresh = res.data.notes
      setNotes((prev) => (prev ? { ...prev, [sectionId]: fresh[sectionId] } : fresh))
      return fresh
    }
    return null
  }

  function saveToLibrary() {
    if (!generationId) return
    const sourcePlan = mode === MODE_FROM_PLAN ? selectedPlan : null
    const grade   = notes?.header?.grade   || curr.grade   || sourcePlan?.inputs?.grade
    const subject = notes?.header?.subject || curr.subject || sourcePlan?.inputs?.subject
    const term    = sourcePlan?.inputs?.term || sourcePlan?.library?.term
    // From a plan → inherit that plan's saved curriculum; otherwise use the
    // curriculum the teacher picked in the selector. Keeps notes in the same
    // CBC/OBC folder as their source.
    const syllabusHint = sourcePlan?.library?.syllabus ||
      (curr.curriculum === 'previous' ? 'OBC' : 'CBC')
    attachLibraryToGeneration(generationId, {
      libraryType: LIBRARY_TYPES.NOTES,
      syllabusHint,
      grade,
      term,
      subject,
      // So My Library can tell "Learner notes — handout" from "Teaching notes"
      // without opening the document (§6).
      audience,
      noteFormat: isLearnerMode ? form.format : null,
    }).catch((err) => console.error('[library attach]', err))
  }

  async function onGenerate(e) {
    e?.preventDefault?.()

    if (mode === MODE_FROM_PLAN) {
      if (!form.lessonPlanId) {
        setErrorMessage('Pick a lesson plan to generate notes from.')
        setStatus('error')
        return
      }
    } else {
      if (!curr.curriculumMode) {
        setErrorMessage('Please choose a curriculum.')
        setStatus('error')
        return
      }
      if (!curr.grade || !curr.subject) {
        setErrorMessage('Please select a class and subject.')
        setStatus('error')
        return
      }
      if (!curr.topic || !curr.topic.trim()) {
        setErrorMessage('Please enter a topic.')
        setStatus('error')
        return
      }
    }

    if (!ensureCanGenerate('notes')) return
    const run = ++runRef.current
    setHandedOff(false)
    setStatus('generating')
    setErrorMessage('')
    setWarning('')
    setNotes(null)

    const payload = buildInputs()
    const lockResult = await runGenerateLocked({
      fingerprint: stableFingerprint(payload),
      action: async (idempotencyKey) => {
        const outcome = await generateNotes({ ...payload, idempotencyKey })
        if (!outcome.ok) {
          // generateNotes() resolves rather than throws; a genuine failure must
          // be THROWN so the lock keeps the key reserved for a same-input retry
          // (never re-billed) instead of minting a fresh key.
          const err = new Error(outcome.error || 'Generation failed')
          err.response = outcome
          throw err
        }
        return outcome
      },
    })
    if (run !== runRef.current) return
    if (!isMounted.current) return
    if (lockResult.reason === 'locked') return // a duplicate click slipped past the disabled button
    const res = lockResult.ok ? lockResult.data : (lockResult.error?.response || {
      ok: false, error: lockResult.error?.message || 'Generation failed. Please try again.',
    })
    if (res.ok && res.data?.status === 'processing') {
      // The server already has this exact request in flight (a retried network
      // call or another tab) — leave "Generating…" showing; the owning call
      // completes it.
      return
    }
    if (!res.ok) {
      setStatus('error')
      setErrorMessage(res.error)
      return
    }
    setNotes(res.data.notes)
    setGenerationId(res.data.generationId)
    setUsage(res.data.usage)
    setWarning(res.data.warning || '')
    setStatus('success')
    draft.clear().catch(() => {})

    if (res.data.generationId) {
      // For from-plan mode, the term hint may not be in the form — fall
      // back to the source plan's term (best-effort).
      const sourcePlan = mode === MODE_FROM_PLAN ? selectedPlan : null
      const grade   = res.data.notes?.header?.grade   || curr.grade   || sourcePlan?.inputs?.grade
      const subject = res.data.notes?.header?.subject || curr.subject || sourcePlan?.inputs?.subject
      const term    = sourcePlan?.inputs?.term || sourcePlan?.library?.term
      const syllabusHint = sourcePlan?.library?.syllabus ||
        (curr.curriculum === 'previous' ? 'OBC' : 'CBC')
      attachLibraryToGeneration(res.data.generationId, {
        libraryType: LIBRARY_TYPES.NOTES,
        syllabusHint,
        grade,
        term,
        subject,
        audience,
        noteFormat: isLearnerMode ? form.format : null,
      }).catch((err) => console.error('[library attach]', err))
    }
  }

  async function onGenerateDiagrams() {
    if (!notes || diagramStatus === 'generating') return
    const jobs = collectNotesDiagramJobs(notes)
    if (!jobs.length) return
    setDiagramStatus('generating')
    setDiagramError('')
    setDiagramProgress({ done: 0, total: jobs.length })

    let updated = notes
    const { error } = await autoGenerateNotesDiagrams(notes, {
      onAttach: (index, url) => {
        updated = {
          ...updated,
          keyConcepts: updated.keyConcepts.map((c, i) =>
            i === index ? { ...c, diagramUrl: url } : c,
          ),
        }
        setNotes(updated)
        setDiagramProgress((p) => ({ ...p, done: p.done + 1 }))
      },
    })

    if (error) {
      setDiagramStatus('error')
      setDiagramError(error)
    } else {
      setDiagramStatus('done')
      if (generationId) {
        updateGenerationOutput(generationId, updated).catch(() => {})
      }
    }
  }

  // One filename builder for every download, so the answer page is recognisably
  // the same document's answer page in a teacher's Downloads folder.
  function downloadName({ variant, ext } = {}) {
    return buildDownloadName({
      docType: 'Notes',
      grade: notes?.header?.grade || curr.grade,
      subject: notes?.header?.subject || curr.subjectLabel || curr.subject,
      topic: notes?.header?.topic || curr.topic,
      ...(variant ? { variant } : {}),
      ...(ext ? { ext } : {}),
    })
  }

  const attribution = () => isFreePlanTeacher({ userProfile, isAdmin })

  function onExportDocx() {
    if (!notes) return
    // The audience is read from the DOCUMENT, not from the form. A teacher who
    // generated learner notes and then flipped the toggle before downloading
    // must still get the document they are looking at.
    if (isLearnerDocument) {
      downloadLearnerNotesDocx(notes, downloadName(), { attribution: attribution() })
      return
    }
    downloadNotesDocx(notes, downloadName(), { attribution: attribution() })
  }

  function onExportPdf() {
    if (!notes) return
    downloadNotesPdf(notes, downloadName({ ext: 'pdf' }), { attribution: attribution() })
  }

  // The answer page is its own FILE, in both formats. Never appended to the
  // learner's pages — see learnerNotesToDocx's docblock for why that is a rule
  // rather than a preference.
  function onExportAnswersDocx() {
    if (!notes) return
    downloadAnswerPageDocx(notes, downloadName({ variant: 'Answers' }), { attribution: attribution() })
  }

  function onExportAnswersPdf() {
    if (!notes) return
    downloadAnswerPagePdf(notes, downloadName({ variant: 'Answers', ext: 'pdf' }), {
      attribution: attribution(),
    })
  }

  return (
    <div className="studio-page">
      <SeoHelmet title="Teaching Notes Studio" noIndex />
      <div className="w-full">
        <StudioPageHeader
          eyebrow="TEACHING MATERIALS"
          title="Notes Studio"
          subtitle="Clear study notes for your learners — board-ready or as a printable handout, grounded in the curriculum."
          icon={NotebookText}
        />

        {mode === MODE_STANDALONE && (
          <StudioAssignmentChangeNotice
            uid={currentUser?.uid}
            currentSeed={{ grade: curr.grade || selectorSeed?.grade || '', subject: curr.subject || selectorSeed?.subject || '', curriculum: curr.curriculum || selectorSeed?.curriculum || '' }}
            onApply={(seed) => { setSelectorSeed(seed); setSelectorKey((k) => k + 1); setCurr({}) }}
          hasUnsavedChanges={draft.status !== 'idle'}
          saveDraft={draft.flush}
          />
        )}
        <div className="mb-4">
          <DraftRecoveryPrompt {...draft} label="notes" />
        </div>
        <div className="grid grid-cols-1 lg:grid-cols-[400px_1fr] gap-6">
          {/* ── Input panel ─────────────────────────────────────── */}
          <form
            onSubmit={onGenerate}
            className="studio-card p-5 space-y-4 h-fit"
          >
            <div className="flex justify-end">
              <DraftStatusIndicator status={draft.status} savedAt={draft.savedAt} online={draft.online} />
            </div>
            {/* Audience — the first decision, because it decides the document.
                Above the curriculum picker per §1. */}
            <SegmentedControl
              label="Audience"
              value={audience}
              onChange={setAudience}
              options={[
                {
                  value: NOTE_AUDIENCES.LEARNER,
                  label: AUDIENCE_LABELS[NOTE_AUDIENCES.LEARNER],
                  hint: 'Study notes written to your class',
                },
                {
                  value: NOTE_AUDIENCES.TEACHING,
                  label: AUDIENCE_LABELS[NOTE_AUDIENCES.TEACHING],
                  hint: 'Delivery notes for you',
                },
              ]}
            />

            {/* Mode tabs */}
            <div
              role="tablist"
              className="flex rounded-xl overflow-hidden"
              style={{ border: '2px solid #0e2a32' }}
            >
              <ModeTab
                active={mode === MODE_FROM_PLAN}
                onClick={() => setMode(MODE_FROM_PLAN)}
              >
                📘 From a plan
              </ModeTab>
              <ModeTab
                active={mode === MODE_STANDALONE}
                onClick={() => setMode(MODE_STANDALONE)}
              >
                ✨ Standalone
              </ModeTab>
            </div>

            {mode === MODE_FROM_PLAN && (
              <PlanPicker
                plans={plans}
                loading={plansLoading}
                error={plansError}
                selectedId={form.lessonPlanId}
                onSelect={(id) => updateField('lessonPlanId', id)}
                onBrowseLibrary={() => navigate('/teacher/library?tool=lesson_plan')}
              />
            )}

            {mode === MODE_FROM_PLAN && selectedPlan && (
              <SelectedPlanSummary plan={selectedPlan} />
            )}

            {mode === MODE_STANDALONE && (
              <>
                <StudioCurriculumSelector
                  key={selectorKey}
                  value={selectorSeed}
                  onChange={setCurr}
                />
                <FieldGrid>
                  {/* Lesson duration is a property of a LESSON. Study notes are
                      not delivered in forty minutes; they are read and kept. It
                      stays in teaching mode, where it means something. */}
                  {!isLearnerMode && (
                    <FieldSelect
                      label="Lesson duration"
                      value={String(form.durationMinutes)}
                      options={DURATION_PRESETS.map((p) => ({
                        value: String(p.value),
                        label: p.label,
                      }))}
                      onChange={(v) => updateField('durationMinutes', Number(v))}
                    />
                  )}
                  <FieldSelect
                    label="Medium of instruction"
                    value={form.language}
                    options={TEACHER_LANGUAGES}
                    onChange={(v) => updateField('language', v)}
                  />
                </FieldGrid>
                <AdvancedOptions label="Document details" hint="School, teacher name, lesson date">
                  <FieldText
                    label="School"
                    placeholder="School name"
                    value={form.school}
                    onChange={(v) => updateField('school', v)}
                    maxLength={120}
                  />
                  <FieldText
                    label="Teacher name"
                    placeholder="Mr / Mrs ..."
                    value={form.teacherName}
                    onChange={(v) => updateField('teacherName', v)}
                    maxLength={80}
                  />
                  <FieldDate
                    label="Lesson date (optional)"
                    value={form.date}
                    onChange={(v) => updateField('date', v)}
                  />
                </AdvancedOptions>
              </>
            )}

            {mode === MODE_FROM_PLAN && (
              <FieldDate
                label="Lesson date (optional)"
                value={form.date}
                onChange={(v) => updateField('date', v)}
              />
            )}

            {/* Learner presentation (§5). Shown in BOTH tabs: a note built from a
                lesson plan is still a handout or a board sheet. */}
            {isLearnerMode && (
              <div className="space-y-4 rounded-xl p-3" style={{ background: '#faf6ee', border: '1.5px solid var(--zt-line)' }}>
                <SegmentedControl
                  label="Format"
                  value={form.format}
                  onChange={(v) => updateField('format', v)}
                  options={[
                    { value: NOTE_FORMATS.HANDOUT, label: FORMAT_LABELS[NOTE_FORMATS.HANDOUT], hint: 'Photocopiable sheet' },
                    { value: NOTE_FORMATS.BOARD, label: FORMAT_LABELS[NOTE_FORMATS.BOARD], hint: 'For copying off the board' },
                  ]}
                />
                <FieldGrid>
                  <FieldSelect
                    label="Detail"
                    value={form.detail}
                    options={Object.entries(DETAIL_LABELS).map(([value, label]) => ({ value, label }))}
                    onChange={(v) => updateField('detail', v)}
                  />
                  <FieldSelect
                    label="Length"
                    value={form.length}
                    options={Object.entries(LENGTH_LABELS).map(([value, label]) => ({ value, label }))}
                    onChange={(v) => updateField('length', v)}
                  />
                </FieldGrid>
                <FieldGrid>
                  <FieldSelect
                    label="English level"
                    value={form.englishLevel}
                    options={Object.entries(ENGLISH_LEVEL_LABELS).map(([value, label]) => ({ value, label }))}
                    onChange={(v) => updateField('englishLevel', v)}
                  />
                  <FieldSelect
                    label="Paper size"
                    value={form.paperSize}
                    options={Object.entries(PAPER_SIZE_LABELS).map(([value, label]) => ({ value, label }))}
                    onChange={(v) => updateField('paperSize', v)}
                  />
                </FieldGrid>
                <p className="text-[11px]" style={{ color: 'var(--zt-text-muted)' }}>
                  Length and detail change what gets WRITTEN, not just how it is laid
                  out — a half page is a shorter document, not a longer one squeezed.
                  All three English levels keep the textbook's technical terms.
                </p>
              </div>
            )}

            <FieldTextarea
              label="Extra instructions (optional)"
              placeholder={
                isLearnerMode
                  ? 'e.g. Use examples from a village market. Keep sentences short.'
                  : mode === MODE_FROM_PLAN
                    ? 'e.g. Keep examples short. Use Bemba for the hook only.'
                    : 'e.g. Include a real-life Lusaka example for the hook.'
              }
              value={form.instructions}
              onChange={(v) => updateField('instructions', v)}
              maxLength={500}
            />

            <GenerateButton
              generating={status === 'generating'}
              generatingLabel={isLearnerMode ? 'Writing to your learners…' : 'Writing notes…'}
            >
              Generate Notes
            </GenerateButton>

            {usage && (
              <div className="text-xs theme-text-secondary text-center">
                {usage.used}/{usage.limit} used on the{' '}
                <span className="font-bold capitalize">{usage.plan}</span> plan this month
              </div>
            )}
          </form>

          {/* ── Output panel ────────────────────────────────────── */}
          <StudioOutputBoundary onRetry={() => setStatus('idle')}>
          {handedOff && status === 'success' && notes ? (
          <section className="studio-card p-5 min-h-[400px]">
              <>
                <div className="flex flex-wrap items-center justify-between gap-3 mb-5">
                  <div>
                    <h2 className="studio-display" style={{ fontSize: 22, margin: '0 0 2px' }}>
                      {isLearnerDocument ? 'Your Learner Notes' : 'Your Teacher Notes'}
                    </h2>
                    <p className="text-xs" style={{ color: 'var(--zt-text-muted)' }}>
                      {isLearnerDocument
                        ? 'This is the sheet your class will hold. The answer page is a separate file.'
                        : 'Skim before class — or print and tuck into your lesson plan.'}
                    </p>
                  </div>
                  <div className="flex gap-2 flex-wrap">
                    <button onClick={saveToLibrary} className="studio-btn-primary">
                      Save to library
                    </button>
                    <button onClick={onExportDocx} className="studio-btn-ghost">
                      <Icon as={Download} size="sm" /> Word
                    </button>
                    <button onClick={onExportPdf} className="studio-btn-ghost">
                      <Icon as={Download} size="sm" /> PDF
                    </button>
                    {isLearnerDocument && (
                      <>
                        <button onClick={onExportAnswersDocx} className="studio-btn-ghost">
                          <Icon as={Download} size="sm" /> Answer page (Word)
                        </button>
                        <button onClick={onExportAnswersPdf} className="studio-btn-ghost">
                          <Icon as={Download} size="sm" /> Answer page (PDF)
                        </button>
                      </>
                    )}
                    <button onClick={() => setStatus('idle')} className="studio-btn-ghost">
                      <Icon as={RefreshCw} size="sm" /> Generate Another
                    </button>
                  </div>
                </div>
                {isLearnerDocument && (
                  <div className="mb-4">
                    <GroundingChip grounding={notes.grounding} checks={notes.checks} />
                  </div>
                )}
                {warning && (
                  <div className="mb-4 rounded-xl border border-amber-300 bg-amber-50 text-amber-900 px-4 py-3 text-sm">
                    ⚠️ {warning}
                  </div>
                )}
                {isLearnerDocument ? (
                  <NotesPagesPreview
                    notes={notes}
                    paper={notes.paperSize}
                    // The board look is a PREVIEW of what the class copies down.
                    // Every export path renders plain black on white.
                    boardPreview={notes.format === NOTE_FORMATS.BOARD}
                    answerPageBlocks={answerPageBlocks}
                  />
                ) : (
                  <NotesView notes={notes} />
                )}

                {/* Diagram generation CTA — teaching notes only. A learner
                    document's figures come from the curriculum diagram library
                    (§4b), which is deterministic, labelled, printable and free;
                    offering an image generator beside it would be offering a
                    worse picture at a cost. */}
                {!isLearnerDocument && notes.keyConcepts?.length > 0 && diagramStatus !== 'done' && (
                  <div className="mt-6 rounded-2xl border-2 border-dashed p-4 flex flex-wrap items-center justify-between gap-3"
                    style={{ borderColor: 'var(--zt-line)', background: '#faf6ee' }}>
                    <div>
                      <p className="text-sm font-black" style={{ color: 'var(--zt-text)' }}>
                        🎨 Add AI diagrams to key concepts
                      </p>
                      <p className="text-xs mt-0.5" style={{ color: 'var(--zt-text-muted)' }}>
                        Generates up to {NOTES_DIAGRAM_CAP} labelled illustrations — one per concept.
                      </p>
                      {diagramStatus === 'error' && (
                        <p className="text-xs mt-1 text-red-600">{diagramError}</p>
                      )}
                    </div>
                    <button
                      onClick={onGenerateDiagrams}
                      disabled={diagramStatus === 'generating'}
                      className="studio-btn-ghost disabled:opacity-50 disabled:cursor-not-allowed whitespace-nowrap"
                    >
                      {diagramStatus === 'generating' ? (
                        `Drawing… ${diagramProgress.done}/${diagramProgress.total}`
                      ) : (
                        <><Icon as={ImageIcon} size="sm" /> Generate diagrams</>
                      )}
                    </button>
                  </div>
                )}
                {diagramStatus === 'done' && (
                  <div className="mt-4 text-sm text-emerald-700 font-semibold">
                    ✓ {diagramProgress.total} diagram{diagramProgress.total === 1 ? '' : 's'} added to key concepts
                  </div>
                )}

                {generationId && (
                  <div className="mt-6 text-xs theme-text-secondary">
                    Saved as generation <code>{generationId}</code>. Visit your Library to find it again.
                  </div>
                )}
              </>
          </section>
          ) : (
            <LiveGenerationCanvas
              tool={isLearnerMode ? 'learnerNotes' : 'notes'}
              status={status}
              result={notes}
              docTitle={notes?.header?.title}
              title={isLearnerMode ? 'Writing to your learners…' : 'Writing your notes…'}
              emptyState={<EmptyState mode={mode} learner={isLearnerMode} />}
              errorMessage={errorMessage}
              savedToLibrary={Boolean(generationId)}
              onStop={() => { runRef.current += 1; setStatus('idle') }}
              onRegenerate={() => onGenerate()}
              onRegenerateSection={regenerateSection}
              onSaveToLibrary={saveToLibrary}
              onContinueEditing={() => setHandedOff(true)}
              onRetry={() => setStatus('idle')}
              continueLabel="Continue to editing & export"
            />
          )}
          </StudioOutputBoundary>
        </div>
      </div>
    </div>
  )
}

/* ── Subcomponents ─────────────────────────────────────────────── */

function ModeTab({ active, onClick, children }) {
  return (
    <button
      type="button"
      role="tab"
      aria-selected={active}
      onClick={onClick}
      className="flex-1 px-3 py-2 text-sm font-black transition"
      style={
        active
          ? { background: '#d97757', color: '#fff' }
          : { background: 'transparent', color: 'var(--zt-text)' }
      }
    >
      {children}
    </button>
  )
}

function PlanPicker({ plans, loading, error, selectedId, onSelect, onBrowseLibrary }) {
  if (loading) {
    return (
      <div className="rounded-xl border-2 border-dashed p-4 text-center text-sm" style={{ borderColor: 'var(--zt-line)', color: 'var(--zt-text-muted)' }}>
        Loading your lesson plans…
      </div>
    )
  }
  if (error) {
    return (
      <div className="rounded-xl border-2 border-dashed p-4 text-center" style={{ borderColor: '#e6b8b8' }}>
        <p className="text-sm mb-2" style={{ color: 'var(--zt-text)' }}>
          Couldn't load your lesson plans.
        </p>
        <p className="text-xs" style={{ color: 'var(--zt-text-muted)' }}>
          Check your connection and try again, or switch to <strong>Standalone</strong> to write notes without a plan.
        </p>
      </div>
    )
  }
  if (plans.length === 0) {
    return (
      <div className="rounded-xl border-2 border-dashed p-4 text-center" style={{ borderColor: 'var(--zt-line)' }}>
        <p className="text-sm mb-2" style={{ color: 'var(--zt-text)' }}>
          You don't have any saved lesson plans yet.
        </p>
        <p className="text-xs" style={{ color: 'var(--zt-text-muted)' }}>
          Switch to <strong>Standalone</strong> for now, or generate a plan in
          the Lesson Plan Studio first.
        </p>
      </div>
    )
  }
  return (
    <div>
      <FieldLabel>Lesson plan *</FieldLabel>
      <select
        value={selectedId || ''}
        onChange={(e) => onSelect(e.target.value)}
        className="studio-input"
      >
        <option value="">— Choose a saved plan —</option>
        {plans.map((p) => (
          <option key={p.id} value={p.id}>
            {titleForGeneration(p)} · {p.inputs?.grade || ''} · {formatDate(p.createdAt)}
          </option>
        ))}
      </select>
      <button
        type="button"
        onClick={onBrowseLibrary}
        className="mt-1.5 text-xs font-bold hover:underline"
        style={{ color: '#d97757' }}
      >
        Browse in library →
      </button>
    </div>
  )
}

function SelectedPlanSummary({ plan }) {
  const h = plan.output?.header || {}
  return (
    <div className="rounded-xl p-3" style={{ background: '#fff5e6', border: '1.5px solid #d97757' }}>
      <p className="text-[10px] font-black uppercase tracking-wide mb-1" style={{ color: '#d97757' }}>
        Source plan
      </p>
      <p className="text-sm font-bold" style={{ color: 'var(--zt-text)' }}>
        {titleForGeneration(plan)}
      </p>
      <p className="text-xs mt-0.5" style={{ color: 'var(--zt-text-muted)' }}>
        {[h.class || plan.inputs?.grade, h.subject || plan.inputs?.subject]
          .filter(Boolean).join(' · ')}
      </p>
    </div>
  )
}

/* ── Form fields ──────────────────────────────────────────────── */

/* ── State views ──────────────────────────────────────────────── */

function EmptyState({ mode, learner }) {
  return (
    <StudioEmptyState icon={NotebookText} tone="#dbe7f4" title="Notes ready when you are">
      {learner
        ? (mode === MODE_FROM_PLAN
          ? 'Pick one of your saved lesson plans on the left and we\'ll write study notes your class can read and keep.'
          : 'Tell us the grade, subject and topic on the left and we\'ll write study notes for your learners, grounded in their syllabus.')
        : (mode === MODE_FROM_PLAN
          ? 'Pick one of your saved lesson plans on the left and we\'ll write delivery notes that match it.'
          : 'Tell us the grade, subject and topic on the left and we\'ll write teacher notes you can skim before class.')}
    </StudioEmptyState>
  )
}

/**
 * A two- or three-way choice rendered as one control.
 *
 * Used for the two decisions that change the DOCUMENT rather than a detail of
 * it — the audience and the format. Both are the kind of choice a teacher
 * should be able to see the alternatives to without opening anything, which is
 * what a segmented control does and a select does not.
 */
function SegmentedControl({ label, value, onChange, options }) {
  return (
    <div>
      <FieldLabel>{label}</FieldLabel>
      <div role="radiogroup" aria-label={label} className="grid gap-1.5"
        style={{ gridTemplateColumns: `repeat(${options.length}, minmax(0, 1fr))` }}>
        {options.map((option) => {
          const active = option.value === value
          return (
            <button
              key={option.value}
              type="button"
              role="radio"
              aria-checked={active}
              onClick={() => onChange(option.value)}
              className="rounded-xl px-3 py-2 text-left transition"
              style={active
                ? { background: '#d97757', color: '#fff', border: '2px solid #d97757' }
                : { background: 'transparent', color: 'var(--zt-text)', border: '2px solid var(--zt-line)' }}
            >
              <span className="block text-sm font-black leading-tight">{option.label}</span>
              {option.hint && (
                <span className="block text-[10px] mt-0.5 leading-tight"
                  style={{ opacity: active ? 0.85 : 0.65 }}>
                  {option.hint}
                </span>
              )}
            </button>
          )
        })}
      </div>
    </div>
  )
}
