import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest'
import { render, screen, fireEvent, act } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import NotesStudio from './NotesStudio.jsx'

// Request-locking / idempotency initiative — this suite is the UI-level
// guarantee for the Notes studio: (1) a real generation sends a payload
// carrying a client-minted idempotencyKey, and (2) a synchronous double-submit
// (two clicks before the first resolves) produces exactly ONE generateNotes
// call. useAiOperationLock + aiOperationLockCore run for real here — that's the
// wiring under test — everything else the component pulls in is mocked so the
// studio renders in jsdom and its Generate path can be driven. Mirrors
// HomeworkStudio.spec.jsx (standalone mode, seeded curriculum).

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

// The generator + the constant exports NotesStudio reads for its selects.
vi.mock('../../../utils/teacherTools', () => ({
  generateNotes: vi.fn(),
  TEACHER_LANGUAGES: [{ value: 'english', label: 'English' }],
  DURATION_PRESETS: [{ value: 40, label: '40 min' }],
}))

// Stable references — NotesStudio has a mount effect keyed on [currentUser]
// that toggles plansLoading. A fresh object each render would re-fire it every
// render, whose async chain flips the loading state back, re-rendering forever
// (an act() that never settles → test timeout). Closing over one object each
// keeps the effect from re-running.
vi.mock('../../../contexts/AuthContext', () => {
  const currentUser = { uid: 'test-uid' }
  const userProfile = {}
  return { useAuth: () => ({ currentUser, userProfile, isAdmin: false }) }
})
vi.mock('../../../hooks/useGenerationGate', () => ({
  useGenerationGate: () => ({ ensureCanGenerate: () => true }),
}))
vi.mock('../../../contexts/PlatformSettingsContext', () => ({
  usePlatformSettings: () => ({ settings: { featureFlags: {} } }),
}))
vi.mock('../../../utils/useFormDefaultsFromUrl', () => ({
  useFormDefaultsFromUrl: () => ({}),
}))

// Firebase-backed library service — the initial plans fetch + success side
// effects — stubbed to no-ops.
vi.mock('../../../utils/teacherLibraryService', () => ({
  listMyGenerations: vi.fn(() => Promise.resolve([])),
  titleForGeneration: () => 'plan',
  formatDate: () => '',
  attachLibraryToGeneration: vi.fn(() => Promise.resolve()),
  updateGenerationOutput: vi.fn(() => Promise.resolve()),
  isFreePlanTeacher: () => false,
}))
vi.mock('../../../utils/notesAutoGenerateDiagrams', () => ({
  collectNotesDiagramJobs: () => [],
  autoGenerateNotesDiagrams: vi.fn(() => Promise.resolve({})),
  NOTES_DIAGRAM_CAP: 6,
}))
vi.mock('../../../engines/export-engine/notesToDocx', () => ({ downloadNotesDocx: vi.fn() }))
vi.mock('../../../engines/export-engine/notesToPdf', () => ({ downloadNotesPdf: vi.fn() }))

// Draft manager (PlatformSettingsContext + Firestore) — stubbed idle.
vi.mock('../../../hooks/draft/useDraftManager', () => ({
  useDraftManager: () => ({
    status: 'idle',
    savedAt: null,
    online: true,
    flush: vi.fn(),
    clear: vi.fn(() => Promise.resolve()),
  }),
}))
vi.mock('../../../components/draft/DraftStatusIndicator', () => ({ default: () => null }))
vi.mock('../../../components/draft/DraftRecoveryPrompt', () => ({ default: () => null }))

// Helmet needs a provider we don't want to stand up here.
vi.mock('../../../components/seo/SeoHelmet', () => ({ default: () => null }))

// Presentational bits with no bearing on the generate path.
vi.mock('../../../components/ui/LiveGenerationCanvas', () => ({ default: () => null }))
vi.mock('../components/NotesView', () => ({ default: () => null }))
vi.mock('../../../shared/components/StudioPageHeader', () => ({ default: () => null }))
vi.mock('../../../shared/components/StudioOutputBoundary', () => ({ default: ({ children }) => children }))
vi.mock('../../../components/teacher/generate/StudioAssignmentChangeNotice', () => ({ default: () => null }))

// The curriculum selector is mocked to a single button that, when clicked,
// hands the studio a fully-satisfied curriculum payload via its onChange — so
// onGenerate's standalone-mode guards pass without driving the real selector.
const VALID_CURR = {
  curriculumMode: 'cbc',
  grade: '4',
  subject: 'mathematics',
  subjectLabel: 'Mathematics',
  topic: 'Fractions',
  subtopic: 'Adding fractions',
  curriculum: 'cbc',
  framework: '2023',
}
vi.mock('../../../components/teacher/curriculum/StudioCurriculumSelector', () => ({
  default: ({ onChange }) => (
    <button type="button" onClick={() => onChange(VALID_CURR)}>
      seed-curriculum
    </button>
  ),
}))

function renderStudio() {
  return render(
    <MemoryRouter>
      <NotesStudio />
    </MemoryRouter>,
  )
}

// Satisfy the curriculum guards, then return the Generate button.
function seedCurriculumAndGetGenerate() {
  fireEvent.click(screen.getByRole('button', { name: /seed-curriculum/i }))
  return screen.getByRole('button', { name: /Generate Notes/i })
}

beforeEach(() => {
  vi.clearAllMocks()
})

afterEach(() => {
  // The lock persists its pending record to sessionStorage keyed by lockKey;
  // clear it so idempotency-key state never leaks across tests.
  sessionStorage.clear()
})

describe('NotesStudio — AI idempotency lock wiring', () => {
  it('sends a payload carrying a client-minted idempotencyKey when generating', async () => {
    const { generateNotes } = await import('../../../utils/teacherTools')
    generateNotes.mockResolvedValue({
      ok: true,
      data: { notes: { header: {} }, generationId: 'gen-1', usage: null, warning: '' },
    })

    renderStudio()
    const generateBtn = seedCurriculumAndGetGenerate()

    await act(async () => {
      fireEvent.click(generateBtn)
    })

    expect(generateNotes).toHaveBeenCalledTimes(1)
    const payload = generateNotes.mock.calls[0][0]
    expect(typeof payload.idempotencyKey).toBe('string')
    expect(payload.idempotencyKey).toBeTruthy()
    expect(payload.idempotencyKey).toMatch(UUID_RE)
    // Sanity: the seeded curriculum rode along in the payload.
    expect(payload.topic).toBe('Fractions')
  })

  it('a synchronous double-submit results in exactly one generateNotes call', async () => {
    const { generateNotes } = await import('../../../utils/teacherTools')
    // A deferred that stays pending, so BOTH clicks land while the first
    // request is still in flight — exactly when the lock has to hold.
    let resolveGenerate
    generateNotes.mockImplementation(
      () => new Promise((res) => { resolveGenerate = res }),
    )

    renderStudio()
    const generateBtn = seedCurriculumAndGetGenerate()

    // Two rapid clicks in the same synchronous burst — like a real double-click
    // firing before React re-renders the disabled state.
    fireEvent.click(generateBtn)
    fireEvent.click(generateBtn)

    expect(generateNotes).toHaveBeenCalledTimes(1)

    // Release the in-flight request so nothing dangles.
    await act(async () => {
      resolveGenerate({
        ok: true,
        data: { notes: { header: {} }, generationId: 'gen-1', usage: null, warning: '' },
      })
    })
    expect(generateNotes).toHaveBeenCalledTimes(1)
  })
})
