import { createElement } from 'react'
import {
  AcademicCapIcon,
  ArrowDownTrayIcon,
  ArrowLeftIcon,
  ArrowPathIcon,
  ArrowRightStartOnRectangleIcon,
  ArrowTrendingUpIcon,
  ArrowsPointingOutIcon,
  ArrowUpTrayIcon,
  ArrowUturnLeftIcon,
  ArrowUturnRightIcon,
  Bars3BottomLeftIcon,
  Bars3BottomRightIcon,
  Bars3CenterLeftIcon,
  Bars3Icon,
  Battery100Icon,
  BeakerIcon,
  BellAlertIcon,
  BellIcon,
  BoldIcon,
  BoltIcon,
  BookOpenIcon,
  BookmarkSquareIcon,
  CalendarDaysIcon,
  ChartBarIcon,
  CheckBadgeIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleStackIcon,
  ClockIcon,
  ClipboardDocumentCheckIcon,
  ClipboardDocumentIcon,
  ClipboardDocumentListIcon,
  Cog6ToothIcon,
  CreditCardIcon,
  CursorArrowRaysIcon,
  DocumentDuplicateIcon,
  DocumentTextIcon,
  EnvelopeIcon,
  EyeDropperIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  EyeSlashIcon,
  FireIcon,
  FolderOpenIcon,
  H1Icon,
  H2Icon,
  HomeIcon,
  ItalicIcon,
  LightBulbIcon,
  ListBulletIcon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  MicrophoneIcon,
  NoSymbolIcon,
  NumberedListIcon,
  PaintBrushIcon,
  PaperAirplaneIcon,
  PencilSquareIcon,
  PlayIcon,
  PlusIcon,
  PresentationChartBarIcon,
  PrinterIcon,
  PuzzlePieceIcon,
  QueueListIcon,
  RectangleStackIcon,
  ShieldCheckIcon,
  SignalIcon,
  SparklesIcon,
  SpeakerWaveIcon,
  SpeakerXMarkIcon,
  StarIcon,
  Squares2X2Icon,
  StopIcon,
  StrikethroughIcon,
  SwatchIcon,
  TableCellsIcon,
  TrophyIcon,
  UnderlineIcon,
  UserIcon,
  UserGroupIcon,
  VariableIcon,
  XMarkIcon,
} from '@heroicons/react/24/outline'

export function RobotIcon(props) {
  return createElement(
    'svg',
    {
      viewBox: '0 0 24 24',
      fill: 'none',
      stroke: 'currentColor',
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
      ...props,
    },
    createElement('path', { d: 'M12 4v2' }),
    createElement('path', { d: 'M8.5 4h7' }),
    createElement('path', { d: 'M7 8h10a3 3 0 0 1 3 3v5a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4v-5a3 3 0 0 1 3-3Z' }),
    createElement('path', { d: 'M8.5 13h.01' }),
    createElement('path', { d: 'M15.5 13h.01' }),
    createElement('path', { d: 'M9.5 16.5c1.4.9 3.6.9 5 0' }),
    createElement('path', { d: 'M4 13H2.75' }),
    createElement('path', { d: 'M21.25 13H20' }),
  )
}

export {
  AcademicCapIcon as GraduationCap,
  AcademicCapIcon,
  ArrowDownTrayIcon as Download,
  ArrowDownTrayIcon,
  ArrowLeftIcon,
  ArrowLeftIcon as ArrowLeft,
  ArrowPathIcon as RefreshCw,
  ArrowPathIcon as RotateCcw,
  ArrowRightStartOnRectangleIcon as LogOut,
  ArrowTrendingUpIcon as TrendingUp,
  ArrowsPointingOutIcon as Maximize2,
  ArrowUpTrayIcon as Upload,
  ArrowUturnLeftIcon as Undo2,
  ArrowUturnRightIcon as Redo2,
  Bars3BottomLeftIcon as AlignLeft,
  Bars3BottomRightIcon as AlignRight,
  Bars3CenterLeftIcon as AlignCenter,
  Bars3Icon as Menu,
  Battery100Icon as Battery,
  BeakerIcon,
  BellAlertIcon as BellRing,
  BellIcon as Bell,
  BoldIcon as Bold,
  BoltIcon as Zap,
  BookOpenIcon as BookMarked,
  BookOpenIcon,
  BookOpenIcon as BookOpen,
  BookmarkSquareIcon,
  CalendarDaysIcon as CalendarDays,
  ChartBarIcon,
  ChartBarIcon as BarChart3,
  CheckBadgeIcon as Award,
  CheckBadgeIcon as CheckSquare,
  CheckCircleIcon,
  CheckIcon as Check,
  ChevronDownIcon as ChevronDown,
  ChevronLeftIcon as ChevronLeft,
  ChevronRightIcon as ChevronRight,
  ChevronUpIcon as ChevronUp,
  CircleStackIcon as Sprout,
  ClockIcon as Clock,
  ClipboardDocumentCheckIcon as ListChecks,
  ClipboardDocumentIcon as Copy,
  ClipboardDocumentListIcon as ClipboardList,
  Cog6ToothIcon as Settings,
  CreditCardIcon as CreditCard,
  CursorArrowRaysIcon as Target,
  DocumentDuplicateIcon as Files,
  DocumentTextIcon,
  DocumentTextIcon as FileText,
  EnvelopeIcon,
  EnvelopeIcon as Mail,
  EyeDropperIcon as Highlighter,
  ExclamationCircleIcon as AlertCircle,
  ExclamationTriangleIcon as AlertTriangle,
  EyeIcon as Eye,
  EyeSlashIcon as EyeOff,
  FireIcon,
  FolderOpenIcon,
  FolderOpenIcon as FolderOpen,
  H1Icon as Superscript,
  H2Icon as Subscript,
  HomeIcon as Home,
  ItalicIcon as Italic,
  LightBulbIcon as Lightbulb,
  ListBulletIcon as List,
  LockClosedIcon as Lock,
  LockClosedIcon,
  MagnifyingGlassIcon as Search,
  MicrophoneIcon as Mic,
  NoSymbolIcon as MicOff,
  NumberedListIcon as ListOrdered,
  PaintBrushIcon,
  PaintBrushIcon as Palette,
  PaperAirplaneIcon as Send,
  PencilSquareIcon as PencilLine,
  PencilSquareIcon as PenLine,
  PencilSquareIcon,
  PlayIcon as Play,
  PlusIcon as Plus,
  PresentationChartBarIcon as Presentation,
  PrinterIcon as Printer,
  PuzzlePieceIcon,
  PuzzlePieceIcon as Gamepad2,
  QueueListIcon as ClipboardCheckList,
  RectangleStackIcon as Layers,
  ShieldCheckIcon as ShieldCheck,
  SignalIcon as Signal,
  SparklesIcon as Sparkles,
  SpeakerWaveIcon as Volume2,
  SpeakerXMarkIcon as VolumeX,
  Squares2X2Icon as LayoutDashboard,
  Squares2X2Icon as LayoutGrid,
  StarIcon,
  StopIcon as Square,
  StrikethroughIcon as Strikethrough,
  SwatchIcon,
  TableCellsIcon as Table,
  TableCellsIcon as TableIcon,
  TrophyIcon,
  UnderlineIcon as Underline,
  UserIcon as User,
  UserGroupIcon as Users,
  VariableIcon as Sigma,
  RobotIcon as Bot,
  XMarkIcon as X,
  XMarkIcon,
}
