/**
 * Behaviour tests for AssessmentStudio.jsx — the (largest) teacher paper
 * builder that backs both the Test Paper Studio and the Exam Studio.
 *
 * The full builder mounts an enormous view tree, so these focus on the
 * edit-mode gate that returns *before* that tree — and, most importantly,
 * on the ownership check, the file's highest-risk logic: a teacher opening
 * `/…/:id/edit` for a paper they do not own must be denied, never handed the
 * paper. Covered: the edit loading skeletons, "not found" for a missing
 * paper, and "Access denied" for a non-owner (no data leak).
 */
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { render, screen } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'

vi.mock('../../firebase/config', () => ({ default: {}, auth: {}, db: {}, storage: {}, app: {} }))
vi.mock('firebase/storage', () => ({ ref: vi.fn(), uploadBytes: vi.fn(), getDownloadURL: vi.fn() }))
// Many util services call getFunctions(app) at import time. Stubbing the
// low-level firebase/functions module neutralises that whole class of
// import-time init crashes without chasing each service transitively.
vi.mock('firebase/functions', () => ({ getFunctions: () => ({}), httpsCallable: () => vi.fn() }))

const mockGetAssessmentById = vi.fn()
const mockGetAssessmentQuestions = vi.fn()
vi.mock('../../hooks/useFirestore', () => ({
  useFirestore: () => ({
    createAssessment: vi.fn(),
    saveAssessmentQuestions: vi.fn(),
    getMyAssessments: vi.fn().mockResolvedValue([]),
    getAssessmentById: mockGetAssessmentById,
    getAssessmentQuestions: mockGetAssessmentQuestions,
    updateAssessmentWithQuestions: vi.fn(),
  }),
}))

let mockAuth = { currentUser: { uid: 'owner-1' }, userProfile: { id: 'owner-1' }, isAdmin: false }
vi.mock('../../contexts/AuthContext', () => ({ useAuth: () => mockAuth }))

// Firebase-touching / network util leaves.
vi.mock('../../utils/aiAssistant', () => ({ generateAIQuizQuestions: vi.fn() }))
vi.mock('../../utils/generateDiagram', () => ({ generateDiagram: vi.fn() }))
vi.mock('../../utils/pictureBankService', () => ({ uploadBankPicture: vi.fn(), PICTURE_BANK_SUBJECTS_GENERIC: [] }))
vi.mock('../../utils/schoolProfileService', () => ({ getSchoolProfile: vi.fn().mockResolvedValue(null) }))
vi.mock('../../utils/autoGenerateDiagrams', () => ({
  autoGenerateDiagrams: vi.fn(), countDiagramJobs: () => 0, DIAGRAM_AUTO_CAP: 10,
}))
vi.mock('../../utils/imageCompression', () => ({ compressImage: vi.fn() }))

// Heavy child views / modals — render nothing so only the studio shell mounts.
vi.mock('./studio/AssessmentHomeView', () => ({ HomeView: () => null }))
vi.mock('./studio/AssessmentBuilderView', () => ({ BuilderView: () => null }))
vi.mock('./studio/AssessmentBars', () => ({ TopBar: () => null, BottomBar: () => null }))
vi.mock('./QuestionBankPanel', () => ({ default: () => null }))
vi.mock('./CreatePaperModal', () => ({ default: () => null }))
vi.mock('./DiagramFixupPanel', () => ({ default: () => null, countDiagramsNeeded: () => 0 }))
vi.mock('./DiagramScanner', () => ({ default: () => null }))
vi.mock('../quiz/QuizVerifyModal', () => ({ default: () => null }))
vi.mock('./scan/ScanPaperModal', () => ({ default: () => null }))
vi.mock('./scan/ImportReviewScreen', () => ({ default: () => null }))
vi.mock('./PaperHealthModal', () => ({ default: () => null }))
vi.mock('./PaperTemplatePicker', () => ({ default: () => null }))
vi.mock('./StudioOutputBoundary', () => ({ default: ({ children }) => children }))

const mockNavigate = vi.fn()
let mockParams = { paperId: 'paper-1' }
vi.mock('react-router-dom', async (importOriginal) => {
  const actual = await importOriginal()
  return {
    ...actual,
    useNavigate: () => mockNavigate,
    useParams: () => mockParams,
    useSearchParams: () => [new URLSearchParams(''), vi.fn()],
  }
})

import AssessmentStudio from './AssessmentStudio'

function renderStudio() {
  return render(<MemoryRouter><AssessmentStudio variant="test" /></MemoryRouter>)
}

beforeEach(() => {
  vi.clearAllMocks()
  mockAuth = { currentUser: { uid: 'owner-1' }, userProfile: { id: 'owner-1' }, isAdmin: false }
  mockParams = { paperId: 'paper-1' }
  mockGetAssessmentQuestions.mockResolvedValue([])
})

describe('AssessmentStudio — edit gate', () => {
  it('shows loading skeletons while the paper is being fetched', () => {
    mockGetAssessmentById.mockReturnValue(new Promise(() => {}))
    mockGetAssessmentQuestions.mockReturnValue(new Promise(() => {}))
    const { container } = renderStudio()
    expect(container.querySelectorAll('.studio-v2').length).toBeGreaterThan(0)
    expect(screen.queryByText(/Access denied/)).not.toBeInTheDocument()
  })

  it('shows "not found" when the paper does not exist', async () => {
    mockGetAssessmentById.mockResolvedValue(null)
    renderStudio()
    expect(await screen.findByText(/not found/)).toBeInTheDocument()
  })

  it('denies a non-owner, non-admin without leaking the paper', async () => {
    mockAuth = { currentUser: { uid: 'intruder' }, userProfile: { id: 'intruder' }, isAdmin: false }
    mockGetAssessmentById.mockResolvedValue({
      id: 'paper-1', title: 'Confidential Exam', createdBy: 'owner-1',
    })
    renderStudio()
    expect(await screen.findByText('Access denied')).toBeInTheDocument()
    expect(screen.queryByText(/Confidential Exam/)).not.toBeInTheDocument()
  })
})
