/**
 * Behaviour tests for AssessmentStudio.jsx — the (largest) teacher paper
 * builder that backs both the Test Paper Studio and the Exam Studio.
 *
 * The full builder mounts an enormous view tree, so these focus on the
 * edit-mode gate that returns *before* that tree — and, most importantly,
 * on the ownership check, the file's highest-risk logic: a teacher opening
 * `/…/:id/edit` for a paper they do not own must be denied, never handed the
 * paper. Covered: the edit loading skeletons, "not found" for a missing
 * paper, and "Access denied" for a non-owner (no data leak).
 */
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { render, screen, fireEvent, waitFor } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'

vi.mock('../../firebase/config', () => ({ default: {}, auth: {}, db: {}, storage: {}, app: {} }))
vi.mock('firebase/storage', () => ({ ref: vi.fn(), uploadBytes: vi.fn(), getDownloadURL: vi.fn() }))
// Many util services call getFunctions(app) at import time. Stubbing the
// low-level firebase/functions module neutralises that whole class of
// import-time init crashes without chasing each service transitively.
vi.mock('firebase/functions', () => ({ getFunctions: () => ({}), httpsCallable: () => vi.fn() }))

const mockGetAssessmentById = vi.fn()
const mockGetAssessmentQuestions = vi.fn()
vi.mock('../../hooks/useFirestore', () => ({
  useFirestore: () => ({
    createAssessment: vi.fn(),
    saveAssessmentQuestions: vi.fn(),
    getMyAssessments: vi.fn().mockResolvedValue([]),
    getAssessmentById: mockGetAssessmentById,
    getAssessmentQuestions: mockGetAssessmentQuestions,
    updateAssessmentWithQuestions: vi.fn(),
  }),
}))

let mockAuth = { currentUser: { uid: 'owner-1' }, userProfile: { id: 'owner-1' }, isAdmin: false }
vi.mock('../../contexts/AuthContext', () => ({ useAuth: () => mockAuth }))

const mockImportQuizDocument = vi.fn()
vi.mock('../quiz/documentQuizImporter', () => ({
  importQuizDocument: (...args) => mockImportQuizDocument(...args),
  revokeImportedQuizAssets: vi.fn(),
}))

// Firebase-touching / network util leaves.
vi.mock('../../utils/aiAssistant', () => ({ generateAIQuizQuestions: vi.fn() }))
vi.mock('../../utils/generateDiagram', () => ({ generateDiagram: vi.fn() }))
vi.mock('../../utils/pictureBankService', () => ({ uploadBankPicture: vi.fn(), PICTURE_BANK_SUBJECTS_GENERIC: [] }))
vi.mock('../../utils/schoolProfileService', () => ({ getSchoolProfile: vi.fn().mockResolvedValue(null) }))
vi.mock('../../utils/autoGenerateDiagrams', () => ({
  autoGenerateDiagrams: vi.fn(), countDiagramJobs: () => 0, DIAGRAM_AUTO_CAP: 10,
}))
vi.mock('../../utils/imageCompression', () => ({ compressImage: vi.fn() }))

// Heavy child views / modals — mostly render nothing so only the studio shell
// mounts. HomeView + BuilderView are *lightweight* stubs (not null): the edit
// gate tests never render either (they return in the loading / error branch),
// but the interaction tests below drive the real home→builder view wiring, so
// these stubs surface the callbacks the studio passes down (onNewPaper / onAi)
// as clickable buttons and mark which view is on screen.
vi.mock('./studio/AssessmentHomeView', () => ({
  HomeView: ({ eyebrow, onNewPaper, onAi }) => (
    <div data-testid="home-view">
      <span data-testid="home-eyebrow">{eyebrow}</span>
      <button type="button" onClick={onNewPaper}>stub-new-paper</button>
      <button type="button" onClick={onAi}>stub-home-ai</button>
    </div>
  ),
}))
vi.mock('./studio/AssessmentBuilderView', () => ({
  // Expose form.title and sections.length as data attributes. Also expose
  // onImportDocument so B1 tests can trigger an import without a real file UI.
  BuilderView: ({ form, sections = [], onImportDocument }) => (
    <div
      data-testid="builder-view"
      data-form-title={form?.title ?? ''}
      data-section-count={sections.length}
    >
      builder-view
      <button
        type="button"
        onClick={() =>
          onImportDocument?.([new File([''], 'stub.pdf', { type: 'application/pdf' })])
        }
      >
        stub-import-doc
      </button>
    </div>
  ),
}))
// Slide-overs live in AssessmentSlideOvers (not previously mocked because the
// edit-gate tests never reach the main return). The interaction tests DO reach
// it, so stub these to keep the non-edit render cheap — AiSlide surfaces its
// open state so we can assert onAi wiring.
vi.mock('./AssessmentSlideOvers', () => ({
  PaperRenderView: () => null,
  BlockPickerSlide: () => null,
  AiSlide: ({ open }) => (open ? <div data-testid="ai-slide">ai-slide</div> : null),
  EditorSlide: () => null,
  PasteImportSlide: () => null,
}))
// Read-only best-effort bank read fired by the builder-view effect. Keep it
// deterministic (no real callable) so the transition tests don't depend on it.
vi.mock('../../utils/questionBankService', () => ({
  saveQuestionToBank: vi.fn(),
  captureQuestionsToBank: vi.fn(),
  bumpQuestionUsage: vi.fn(),
  searchQuestionBank: vi.fn().mockResolvedValue({ rows: [] }),
}))
vi.mock('./studio/AssessmentBars', () => ({ TopBar: () => null, BottomBar: () => null }))
vi.mock('./QuestionBankPanel', () => ({ default: () => null }))
vi.mock('./CreatePaperModal', () => ({ default: () => null }))
vi.mock('./DiagramFixupPanel', () => ({ default: () => null, countDiagramsNeeded: () => 0 }))
vi.mock('./DiagramScanner', () => ({ default: () => null }))
vi.mock('../quiz/QuizVerifyModal', () => ({ default: () => null }))
vi.mock('./scan/ScanPaperModal', () => ({ default: () => null }))
vi.mock('./scan/ImportReviewScreen', () => ({ default: () => null }))
vi.mock('./PaperHealthModal', () => ({ default: () => null }))
vi.mock('./PaperTemplatePicker', () => ({ default: () => null }))
vi.mock('./StudioOutputBoundary', () => ({ default: ({ children }) => children }))

const mockNavigate = vi.fn()
let mockParams = { paperId: 'paper-1' }
vi.mock('react-router-dom', async (importOriginal) => {
  const actual = await importOriginal()
  return {
    ...actual,
    useNavigate: () => mockNavigate,
    useParams: () => mockParams,
    useSearchParams: () => [new URLSearchParams(''), vi.fn()],
  }
})

import AssessmentStudio from './AssessmentStudio'

function renderStudio() {
  return render(<MemoryRouter><AssessmentStudio variant="test" /></MemoryRouter>)
}

beforeEach(() => {
  vi.clearAllMocks()
  mockAuth = { currentUser: { uid: 'owner-1' }, userProfile: { id: 'owner-1' }, isAdmin: false }
  mockParams = { paperId: 'paper-1' }
  mockGetAssessmentQuestions.mockResolvedValue([])
})

describe('AssessmentStudio — edit gate', () => {
  it('shows loading skeletons while the paper is being fetched', () => {
    mockGetAssessmentById.mockReturnValue(new Promise(() => {}))
    mockGetAssessmentQuestions.mockReturnValue(new Promise(() => {}))
    const { container } = renderStudio()
    expect(container.querySelectorAll('.studio-v2').length).toBeGreaterThan(0)
    expect(screen.queryByText(/Access denied/)).not.toBeInTheDocument()
  })

  it('shows "not found" when the paper does not exist', async () => {
    mockGetAssessmentById.mockResolvedValue(null)
    renderStudio()
    expect(await screen.findByText(/not found/)).toBeInTheDocument()
  })

  it('denies a non-owner, non-admin without leaking the paper', async () => {
    mockAuth = { currentUser: { uid: 'intruder' }, userProfile: { id: 'intruder' }, isAdmin: false }
    mockGetAssessmentById.mockResolvedValue({
      id: 'paper-1', title: 'Confidential Exam', createdBy: 'owner-1',
    })
    renderStudio()
    expect(await screen.findByText('Access denied')).toBeInTheDocument()
    expect(screen.queryByText(/Confidential Exam/)).not.toBeInTheDocument()
  })
})

/*
 * Interaction coverage. AssessmentStudio delegates almost all of its UI to
 * child views (HomeView / BuilderView / TopBar / BottomBar) and slide-overs, so
 * the genuinely testable interactions are the ones AssessmentStudio owns
 * itself: the home→builder view switch it wires through `changeView`, the AI
 * slide-over it opens through `openSlide`, and the variant-driven wording it
 * emits directly in its OWN markup (the edit-gate error screen). Everything
 * that lives *inside* a stubbed child is deliberately out of scope here.
 */
function renderStudioFresh(variant = 'test') {
  return render(<MemoryRouter><AssessmentStudio variant={variant} /></MemoryRouter>)
}

describe('AssessmentStudio — interaction', () => {
  beforeEach(() => {
    // Non-edit mode: no :id → isEditing is false, so the studio renders the
    // home view instead of the edit gate.
    mockParams = {}
  })

  it('renders the home view fresh (no paperId) with the variant eyebrow', () => {
    renderStudioFresh('test')
    expect(screen.getByTestId('home-view')).toBeInTheDocument()
    expect(screen.queryByTestId('builder-view')).not.toBeInTheDocument()
    // cfg.eyebrow for the test variant is passed straight into HomeView.
    expect(screen.getByTestId('home-eyebrow')).toHaveTextContent('Test Paper Studio')
  })

  it('home → builder: "New paper" switches the studio view to the builder', async () => {
    renderStudioFresh('test')
    expect(screen.getByTestId('home-view')).toBeInTheDocument()

    fireEvent.click(screen.getByRole('button', { name: 'stub-new-paper' }))

    // changeView('builder') flips the studio's own `view` state → BuilderView
    // renders and HomeView unmounts.
    await waitFor(() => expect(screen.getByTestId('builder-view')).toBeInTheDocument())
    expect(screen.queryByTestId('home-view')).not.toBeInTheDocument()
  })

  it('home → AI slide-over: onAi opens the AI slide via openSlide', async () => {
    renderStudioFresh('test')
    expect(screen.queryByTestId('ai-slide')).not.toBeInTheDocument()

    fireEvent.click(screen.getByRole('button', { name: 'stub-home-ai' }))

    await waitFor(() => expect(screen.getByTestId('ai-slide')).toBeInTheDocument())
    // The AI slide is a slide-over, not a view switch — home stays mounted.
    expect(screen.getByTestId('home-view')).toBeInTheDocument()
  })

  it('exam variant surfaces exam-flavoured eyebrow wording on the home view', () => {
    renderStudioFresh('exam')
    expect(screen.getByTestId('home-eyebrow')).toHaveTextContent('Exam Studio')
  })
})

describe('AssessmentStudio — variant wording (edit gate)', () => {
  // The edit-gate error screen is markup AssessmentStudio emits itself, so it's
  // the cleanest place to prove getStudioVariant(...) drives the copy. `test`
  // and `exam` must produce distinct noun wording for the same failure.
  it('test variant renders "Test paper not found" + test-paper back link', async () => {
    mockParams = { paperId: 'missing' }
    mockGetAssessmentById.mockResolvedValue(null)
    render(<MemoryRouter><AssessmentStudio variant="test" /></MemoryRouter>)
    expect(await screen.findByText('Test paper not found')).toBeInTheDocument()
    expect(screen.getByText(/Back to test papers/)).toBeInTheDocument()
    expect(screen.queryByText('Exam paper not found')).not.toBeInTheDocument()
  })

  it('exam variant renders "Exam paper not found" + exam-paper back link', async () => {
    mockParams = { paperId: 'missing' }
    mockGetAssessmentById.mockResolvedValue(null)
    render(<MemoryRouter><AssessmentStudio variant="exam" /></MemoryRouter>)
    expect(await screen.findByText('Exam paper not found')).toBeInTheDocument()
    expect(screen.getByText(/Back to exam papers/)).toBeInTheDocument()
  })

  it('exam variant "access denied" copy names exam papers, not test papers', async () => {
    mockParams = { paperId: 'paper-1' }
    mockAuth = { currentUser: { uid: 'intruder' }, userProfile: { id: 'intruder' }, isAdmin: false }
    mockGetAssessmentById.mockResolvedValue({
      id: 'paper-1', title: 'Confidential', createdBy: 'owner-1',
    })
    render(<MemoryRouter><AssessmentStudio variant="exam" /></MemoryRouter>)
    expect(await screen.findByText('Access denied')).toBeInTheDocument()
    expect(screen.getByText(/You can only edit exam papers you created\./)).toBeInTheDocument()
  })
})

/*
 * B1 regression — zero-extraction import must not wipe the current paper.
 *
 * Root cause: runImportDocument mutated all state (setImportedAssets, setForm,
 * setSections([]), setParts, resetUndoBaseline) BEFORE checking whether the
 * parsed file produced any questions. A zero-extraction result wiped the paper
 * and reseeded the undo stack, making recovery via Ctrl+Z impossible.
 *
 * Fix: importHasQuestions(imported) guard fires immediately after the await,
 * before any state mutation. A zero-result returns false + toast and leaves
 * the current paper completely untouched.
 *
 * Observable: after triggering a zero-extraction import the sections count
 * (exposed via BuilderView's data-section-count) must remain at its pre-import
 * value (the single starter section).
 */
describe('AssessmentStudio — zero-extraction import guard (B1)', () => {
  beforeEach(() => {
    mockParams = {}
    mockImportQuizDocument.mockResolvedValue({
      sections: [],
      questions: [],
      imageAssets: [],
      quiz: {
        title: '',
        grade: '',
        subject: '',
        sourceFileName: 'stub.pdf',
        sourceContentType: 'application/pdf',
      },
      importStatus: 'ok',
      warnings: [],
      summary: {},
      scanned: false,
      smartApplied: false,
      pageImageUrls: {},
      parts: [],
    })
  })

  it('a zero-extraction import leaves the current paper sections untouched', async () => {
    renderStudioFresh('test')
    fireEvent.click(screen.getByRole('button', { name: 'stub-new-paper' }))
    await waitFor(() => expect(screen.getByTestId('builder-view')).toBeInTheDocument())

    // The studio starts with a single blank starter section.
    expect(screen.getByTestId('builder-view').dataset.sectionCount).toBe('1')

    fireEvent.click(screen.getByRole('button', { name: 'stub-import-doc' }))

    // Wait for the async import to resolve.
    await waitFor(() => expect(mockImportQuizDocument).toHaveBeenCalledTimes(1))

    // Guard fired before mutations: starter section is preserved (count stays 1).
    expect(screen.getByTestId('builder-view').dataset.sectionCount).toBe('1')
  })
})

/*
 * F6 regression — startBlankPaper() resets createdIdRef.current to null.
 *
 * Root cause: the old inline "New paper" handler forgot to null-out
 * createdIdRef.current. The 2-second library autosave then saw the stale
 * Firestore ID and overwrote the previously-saved paper with a blank form,
 * silently destroying the teacher's work. Fix: startBlankPaper() explicitly
 * sets createdIdRef.current = null before changing the view.
 *
 * The unit-level observable: clicking the "New paper" button in HomeView
 * resets the studio to builder mode with an empty form title — proving
 * startBlankPaper() (the function that contains the fix) was called rather
 * than the old partial-reset inline handler.
 */
describe('AssessmentStudio — startBlankPaper resets form (F6)', () => {
  beforeEach(() => {
    mockParams = {}  // fresh mode — no paperId, so HomeView is shown first
  })

  it('after onNewPaper fires, builder view renders with an empty form title', async () => {
    renderStudioFresh('test')
    expect(screen.getByTestId('home-view')).toBeInTheDocument()

    fireEvent.click(screen.getByRole('button', { name: 'stub-new-paper' }))

    // startBlankPaper() calls changeView('builder') — BuilderView mounts.
    await waitFor(() => expect(screen.getByTestId('builder-view')).toBeInTheDocument())

    // makeDefaultForm() seeds title as '' — prove the form was fully reset.
    const builderEl = screen.getByTestId('builder-view')
    expect(builderEl.dataset.formTitle).toBe('')
  })
})
