/**
 * Pure logic for the `number_target` game engine (Countdown-style maths).
 *
 * Lives in a plain .js module (no React, no imports) so it can be
 * unit-tested from plain Node scripts — same pattern as subjectMascots.js.
 * The React engine in NumberTargetGame.jsx consumes these helpers.
 *
 * A round is { tiles: number[], target: number, recipe: step[] } where each
 * recipe step is { a, op, b, result }. Rounds are generated BY CONSTRUCTION:
 * we draw tiles, then combine random pairs with allowed operators until we
 * land on a target — so every round is guaranteed solvable, and the recipe
 * doubles as the "one way to make it" reveal when a player skips.
 */

export const OPS = ['+', '−', '×', '÷']

export const DIFFICULTY_CONFIGS = {
  easy: {
    tileCount: 4,
    bigs: [],
    ops: ['+', '−'],
    steps: 2,
    minTarget: 5,
    maxTarget: 30,
    rounds: 6,
  },
  medium: {
    tileCount: 5,
    bigs: [10, 12, 15, 20],
    ops: ['+', '−', '×'],
    steps: 2,
    minTarget: 10,
    maxTarget: 150,
    rounds: 8,
  },
  hard: {
    tileCount: 6,
    bigs: [15, 20, 25, 50],
    ops: ['+', '−', '×', '÷'],
    steps: 3,
    minTarget: 20,
    maxTarget: 500,
    rounds: 8,
  },
}

/**
 * Resolve the difficulty config for a game doc: explicit `difficulty`
 * field wins, otherwise fall back by grade band.
 */
export function configForGame(game) {
  const byDifficulty = DIFFICULTY_CONFIGS[String(game?.difficulty || '').toLowerCase()]
  if (byDifficulty) return byDifficulty
  const grade = Number(game?.grade) || 0
  if (grade <= 3) return DIFFICULTY_CONFIGS.easy
  if (grade <= 5) return DIFFICULTY_CONFIGS.medium
  return DIFFICULTY_CONFIGS.hard
}

/**
 * Apply `a <op> b`. Returns the whole-number result, or null when the move
 * is not allowed (negative subtraction, inexact division, divide by zero).
 * These are the same rules the player plays under.
 */
export function applyOp(a, b, op) {
  if (!Number.isFinite(a) || !Number.isFinite(b)) return null
  if (op === '+') return a + b
  if (op === '−') return a - b > 0 ? a - b : null
  if (op === '×') return a * b
  if (op === '÷') return b !== 0 && a % b === 0 ? a / b : null
  return null
}

/** Friendly explanation for why a move was rejected, keyed by operator. */
export function invalidMoveHint(op) {
  if (op === '−') return 'Subtraction must leave a number bigger than zero. Try the other way round!'
  if (op === '÷') return 'Division must come out exactly — no remainders allowed.'
  return 'That move is not allowed here.'
}

function defaultRandom() {
  return Math.random()
}

function randInt(rand, min, max) {
  return min + Math.floor(rand() * (max - min + 1))
}

function drawTiles(cfg, rand) {
  const tiles = []
  const smallCount = cfg.bigs.length ? cfg.tileCount - 1 : cfg.tileCount
  const counts = {}
  for (let guard = 0; tiles.length < smallCount && guard < 200; guard++) {
    const n = randInt(rand, 1, 9)
    // Allow each small number at most twice so boards stay varied.
    if ((counts[n] || 0) >= 2) continue
    counts[n] = (counts[n] || 0) + 1
    tiles.push(n)
  }
  // Top up deterministically if the RNG was degenerate (never in production,
  // but keeps the function total for any injected `rand`).
  for (let n = 1; tiles.length < smallCount; n = (n % 9) + 1) {
    if ((counts[n] || 0) >= 2) continue
    counts[n] = (counts[n] || 0) + 1
    tiles.push(n)
  }
  if (cfg.bigs.length) {
    tiles.push(cfg.bigs[randInt(rand, 0, cfg.bigs.length - 1)])
  }
  return tiles
}

/**
 * Build one solvable round. `rand` is injectable for deterministic tests.
 * Falls back to a hand-checked round if random construction fails — that
 * should be vanishingly rare, but the game must never fail to start.
 */
export function generateRound(cfg, rand = defaultRandom) {
  for (let attempt = 0; attempt < 80; attempt++) {
    const tiles = drawTiles(cfg, rand)
    const round = buildRecipe(tiles, cfg, rand)
    if (!round) continue
    if (round.target < cfg.minTarget || round.target > cfg.maxTarget) continue
    if (tiles.includes(round.target)) continue
    return { tiles, target: round.target, recipe: round.recipe }
  }
  return fallbackRound(cfg)
}

function buildRecipe(tiles, cfg, rand) {
  let pool = tiles.slice()
  const recipe = []
  let result = null

  for (let step = 0; step < cfg.steps; step++) {
    let found = null
    for (let tries = 0; tries < 40; tries++) {
      const i = randInt(rand, 0, pool.length - 1)
      const j = randInt(rand, 0, pool.length - 1)
      if (i === j) continue
      const op = cfg.ops[randInt(rand, 0, cfg.ops.length - 1)]
      let a = pool[i]
      let b = pool[j]
      // Canonical order: bigger number first so − and ÷ have a chance.
      if ((op === '−' || op === '÷') && b > a) [a, b] = [b, a]
      // Skip trivial moves that teach nothing.
      if (op === '×' && (a === 1 || b === 1)) continue
      if (op === '÷' && b === 1) continue
      const r = applyOp(a, b, op)
      if (r === null || r === 0 || r > cfg.maxTarget) continue
      found = { a, b, op, result: r, i, j }
      break
    }
    if (!found) return null
    recipe.push({ a: found.a, op: found.op, b: found.b, result: found.result })
    pool = pool.filter((_, idx) => idx !== found.i && idx !== found.j)
    pool.push(found.result)
    result = found.result
  }

  return { target: result, recipe }
}

function fallbackRound(cfg) {
  if (cfg.steps >= 3) {
    return {
      tiles: [2, 4, 5, 8, 9, 25].slice(0, cfg.tileCount),
      target: 99,
      recipe: [
        { a: 25, op: '×', b: 4, result: 100 },
        { a: 100, op: '−', b: 9, result: 91 },
        { a: 91, op: '+', b: 8, result: 99 },
      ],
    }
  }
  if (cfg.ops.includes('×')) {
    return {
      tiles: [2, 3, 5, 7, 10].slice(0, cfg.tileCount),
      target: 31,
      recipe: [
        { a: 7, op: '×', b: 3, result: 21 },
        { a: 21, op: '+', b: 10, result: 31 },
      ],
    }
  }
  return {
    tiles: [3, 4, 6, 9].slice(0, cfg.tileCount),
    target: 13,
    recipe: [
      { a: 3, op: '+', b: 4, result: 7 },
      { a: 7, op: '+', b: 6, result: 13 },
    ],
  }
}

/** Format a recipe step as a readable equation, e.g. "7 × 3 = 21". */
export function formatStep(step) {
  return `${step.a} ${step.op} ${step.b} = ${step.result}`
}
